### ISSUE TITLE
Problema con instalación de Python 3.6

### ISSUE THREAD

**Issue by cmescobar** [IIC2233/syllabus-2018-2#1]
- **Sistema Operativo:** Windows 7
- **Programa a instalar:** Python 3.6

- Foto del error:
![image](https://user-images.githubusercontent.com/37762994/43754687-14e86d28-99da-11e8-8dad-bc1f7aa705b2.png)

- Descripción del problema: Tal como se puede apreciar en la imagen, tengo instalado la versión 3.6 de  Python. Sin embargo, al corroborar la versión en la ventana de comandos aparece que mi versión vigente es 2.7. Considerar, además, que tengo Anaconda instalado (ver imagen). ¿Será que también hay que eliminar Anaconda? Saludos!

**Comment by entamburini** [comment]
Hola! :)

Dado que es windows, la única forma de que tengas Python 2.7 instalado es con anaconda, te recomiendo fuertemente que desinstales ambos, tanto anaconda como python, y vuelvas a instalar sólo este último. Así no deberías tener problemas :D

Ojo, en la instalación de Python te aparecerá algo como esto (**Ignora el hecho de que es la instalación de Python 3.5**, es igual para Python 3.6.x):
![image003](https://user-images.githubusercontent.com/20786198/43808946-6a27c4ac-9a7d-11e8-9657-5e752bdd77d7.jpg)

Tienes que dejar marcada esa opción, tal cual aparece en la imagen! porque sino tendrás que configurarlo manualmente (y es un cacho xd)

Espero que te haya ayudado :)

**Comment by Cadagan** [comment]
Como extra: si no marcaste esa casilla, aca hay un link que explica como hacerlo manualmente :)

http://www.scielo.org.mx/avaliacao/manual_marcacion/instalacion_markup_paths.html

Saludos! 👍
