### ISSUE TITLE
Repositorio inicial vacío

### ISSUE THREAD

**Issue by ghost** [IIC2233/syllabus-2018-2#10]
Hola,

Cuando se creó mi repositorio privado y seguí el link para verlo, Github me mostró un mensaje de error y después me apareció el repositorio vacío, es decir, sin ninguna de las carpetas como "Actividades", "Tareas" o el README. Mi duda es, entonces, qué tengo que hacer para crear el template de nuevo?

Gracias de antemano.

**Comment by Hernan4444** [comment]
Hola, voy a clonar tu repositorio y hacer push con el template.

**Comment by Hernan4444** [comment]
@zrhftc listo, ahora tienes que hacer `pull`

**Comment by ghost** [comment]
Perfecto, gracias!
