### ISSUE TITLE
Usuarios con igual nombre

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#100]
El enunciado dice que se permiten dos correos con igual nombre siempre y cuando tengan servicio distinto. 

Esto se refiere tambien a que no podrian crearse por ejemplo tres usuarios como "martin@uc.cl", "martin@ing.puc.cl" y "martin@hotmail.com", o solo se refiere a que no pueden ser textualmente iguales? (pudiendose dar el caso que dije arriba)

**Comment by cilopez** [comment]
Obviamente se pueden crear  "martin@uc.cl", "martin@ing.puc.cl" y "martin@hotmail.com", ya son servicios distintos: uc, ingpuc y hotmail. Creo no comprender tu duda si no es esto.

**Comment by Cadagan** [comment]
Gracias! es que el enunciado dice: 
"el sistema **solo** va a permitir que existan **dos** usuarios con igual nombre de correo, siempre y cuando el servicio que provee ese correo sea diferente" 

En lugar de decir "varios usuarios con igual nombre", era una duda chica pero muchas gracias!
