### ISSUE TITLE
Buscar eventos por fecha

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#101]
Cuando busco eventos por fecha, los busco por fecha de inicio, fecha de termino o ambos al mismo tiempo?

**Comment by PPDZ** [comment]
Yo lo interprete como que restringías a que se muestren solo eventos en un rango de fecha determinadas, así que consulto para filtrar por año, mes y día. Puede que lo haya interpretado mal pero me parece coherente hacerlo así. (y de paso comento para saber si esta bien)

**Comment by Fenho** [comment]
Creo que es fecha de inicio, eso entendí de esta issue #62

**Comment by prod-bysilva** [comment]
Hola, 

- Para el orden de las fechas de eventos debes hacerlo como sale en la issue #62 
- Las consultas por fechas deben ser en intervalos.

Éxito!

**Comment by Marialuisaclaro** [comment]
¿que significa consultar por intervalo? ¿Consultar por fecha de inicio y fecha de termino (exactas)? ¿O por una fecha y que esta se encuentre entre cualquier fecha de inicio y termino?
