### ISSUE TITLE
encripcion /  binario

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#102]
Hola! Una duda, en el enunciado hablan de pasar los dígitos a binario con 8 dígitos pero transformando los números de mi lista, los últimos 3 usan 9 dígitos. Esta bien trabajarlos así o tengo algún problema yo? :( 
Gracias!

**Comment by lily416** [comment]
Hola :)

Se refiere a que cada número de la lista al ser transformado a binario tiene que tener 8 dígitos.
Por el ejemplo el 4 en binario puede escribirse como:
- 100
- 0100
- 00100
- ...
- **00000100**

Esta última sería la forma correcta de transformar el número para después concatenarlo con los otros.

Ojalá con esto quede claro, saludos 👋
