### ISSUE TITLE
Id de Correos, y opciones  en general

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#103]
Hola! Tengo 4 dudas:

1. En la bandeja de entrada se muestran 70 correos, por ejemplo. ¿Puedo asumir que el usuario escribirá un número entre el 0 y 70 o tengo que ponerme en el caso que ponga una 's' por ejemplo?
2. ¿Debo siempre ponerme en el caso de que el usuario se va a equivocar, aunque le explicite las instrucciones a seguir (cuando no es tan necesario, obvio que debo restringir cuando pone ',' en la contraseña y cosas así)?
3. Al enviar correos, ¿tenemos que asegurarnos también que sean válidos, es decir, x@uc?
4. ¿Los asuntos pueden tener ','?

Gracias de antemano

**Comment by cilopez** [comment]
Respondiendote ordenadamente:
- Si quieres tener el puntaje completo en consola, sí.
-  Si quieres tener el puntaje completo en consola, sí.
-  No, pueden ser cualquier cosa enverdad.
- No te preocupes por este caso

Si tienes problemas recuerda que la consola son sólo 4 puntos de 100

**Comment by Gorgola22** [comment]
Vale, gracias!
