### ISSUE TITLE
Uso de try/except en la tarea

### ISSUE THREAD

**Issue by rhanuch** [IIC2233/syllabus-2018-2#104]
Debido a que nos han llegado un número considerable de casos de uso de `try` y `except` y `error handlers`, aceptaremos, **sólo por esta tarea**, el uso de ellos. Eso si, el utilizar estos métodos va quedar sujeto a las siguiente restricción ☝🏼:

> El uso indebido (inadecuado acorde a lo que se pasa en el curso y a lo que el ayudante que corrija considere) de estos hará que se obtengan 0 puntos en el item de consola a prueba de inputs erróneos y, **sumado** a lo anterior, un descuento de 5 décimas en la tarea.

Para las otras tareas estos `handlers` quedaran **restringidos** a menos que se diga lo contrario

¡Ánimo en lo que les va quedando de la tarea! 🍀

----
P.S.: Para las siguientes tareas no se aceptará **ningún** uso de materia que no se haya pasado en el curso hasta ese minuto ❌.

**Comment by Kitaps** [comment]
Que opinarían de dar puntos extra para los que lo hicieron bien (sin `try`  y `except`) ?

**Comment by PPDZ** [comment]
Hola, para una función use try/except para descartar el caso de que el input dado no se le pueda aplicar int(), ¿se considera esto un uso indebido o esta bien y puedo dejarlo?

**Comment by Kitaps** [comment]
@PPDZ las string tienen un metodo q se llama [isnumeric](https://www.tutorialspoint.com/python/string_isnumeric.htm). Con eso puedes revisar antes de meter el string en int().
