### ISSUE TITLE
Bandeja correos, orden.

### ISSUE THREAD

**Issue by SergioGazali** [IIC2233/syllabus-2018-2#108]
En el enunciado se pide mostrar correos en orden desde más reciente a más antiguo, aunque en el spreadsheet no se menciona este punto. Efectivamente es así? y en ese caso cómo se sabe? porque no es un dato entregado en el archivo db_emails.
Muchas gracias!

**Comment by nachocontreras** [comment]
Hola!

Se habló de esto en la issue #36.

Saludos!
