### ISSUE TITLE
Tipo de base de datos

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#109]
Me di cuenta de que las bases de datos entregadas a pesar de ser csv (separadas por ";") en realidad tienen sus datos relevantes separados por ",", ¿Podemos confiar en que los datos con los que se pruebe nuestro programa tendrán este mismo tipo de separación? ¿o puede que los separen por ";"?

**Comment by ptflores1** [comment]
Hola !
La estructura de las bases de datos y la manera en que viene la información no cambiaran.
Saludos !
