### ISSUE TITLE
Abrir apuntes desde JupyterNotebook

### ISSUE THREAD

**Issue by cdlanas** [IIC2233/syllabus-2018-2#11]
Hola! ya descargué el programa Jupyter Notebook, y descargué los archivos de los apuntes como .ipynb guardándolo desde sus versiones Raw, pero al abrirlos desde Jupyter no se ejecuta y se ve lo mismo que en su versión Raw. ¿Cómo se deben descargar para hacer que los archivos sean interactivos en Jupyter?

Gracias!

**Comment by rhanuch** [comment]
¡Hola @cdlanas !

Para poder hacer ejecutable el archivo debes abrirlo con la aplicación en tu navegador web. Otra forma de hacerlo es como sale en [este link](http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html) 💻

**Comment by cdlanas** [comment]
Muchas Gracias!
