### ISSUE TITLE
Problema con algoritmo de desencriptación del mensaje

### ISSUE THREAD

**Issue by dberezin** [IIC2233/syllabus-2018-2#110]
Para desencriptar los mensajes estoy haciendo lo siguiente, sin embargo tengo problemas.

1.- construyo una cadena de largo 256 que es una concatenación de la clave (2233) y los diez primeros digitos del mensaje codificado.

2.- una lista que contiene los numeros del 0 al 255

3.- intercambio en esta lista el elemento lista[k] con el elemento lista[k] + cadena de inicio[k], tal como se ejemplifica en las instrucciones.

Sucede que en las instrucciones solo ponen el caso de intercambiar o no elementos adyacentes. Sin embargo, el algoritmo me indica que estoy ingresando indices no válidos. Es decir, llega un punto en que el elemento i-esimo de la cadena, más i, es mayor a 255 (esto sucede antes del 255 que es el único caso que se da en la guía). Qué se hace en este caso? O no debería suceder nunca y estoy haciendo algo mal?

**Comment by bgsamilla** [comment]
En el enunciado sale en el párrafo 3.5.5.d
Tienes que darle la vuelta, por ejemplo la posición 256 seria la posición 0, la 257 la 1 ..... etc.

Si aun tienes la duda podrías esperar a que te lo confirme un ayudante :P

**Comment by IchottMano** [comment]
@dberezin Tal como dicen, esto aparece en el enunciado y fue preguntado en la issue #48 

Saludos
