### ISSUE TITLE
Uso de Python 3.6

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus-2018-2#111]
Hola, estoy usando la version de python 3.6.6 y queria saber si era valido, ya que en las restricciones especifica que usemos 3.6 y me queda la duda si es estrictamente 3.6.0 o todos los 3.6.

**Comment by naquiroz** [comment]
Hola! Las instrucciones para el curso indican que debes usar **python 3.6.X**! Por lo que cualquier versión de python 3.6 debiera bastar.

Saludos! :v:
