### ISSUE TITLE
Fecha de eventos en el pasado

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#112]
Hola, en el enunciado solo se nos pide que la fecha de termino de los eventos sea después de la de inicio (por razones obvias), pero no se dice nada sobre si debe ser después de la fecha actual.

Se podría por ejemplo crear un evento que comenzara el 5/3/2017 y acabara el 6/3/2017?, o también debemos restringir eso?

**Comment by nachocontreras** [comment]
Hola!

Tendría sentido que sea a partir de la fecha actual debido a que crear un evento que ya ocurrió no es necesario.

Saludos!
