### ISSUE TITLE
\n al final de la ultima linea de la base de datos

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#113]
Podemos asumir que las bases de datos datos que nos entregarán tendrán  un \n al final de la ultima linea?

**Comment by meceledon** [comment]
Si te fijas no todas la bases de datos lo tienen actualmente :(  iba a preguntar lo mismo... La pregunta es si trabajamos con eso o asumimos que ellos lo van a "arreglar".

**Comment by rhanuch** [comment]
¡Hola @BSamilla , @meceledon !

Acabo de arreglar el error de la última línea, pueden asumir que no va a haber un `\n` al final de la última línea. ¡Hagan un `git pull` para actualizar sus archivos ⬇️!

¡Saludos y suerte en lo que queda de tarea! 🍀

**Comment by Cadagan** [comment]
En mi caso que ya hice mi programa considerando que una base de datos se terminaba con \n y en otra no, lo que afecta a mis funciones de guardar datos nuevos, si lo pongo en el read.me estara bien? porque obviamente mi porgrama **no funcionara** con las nuevas bases de datos
