### ISSUE TITLE
Base de datos db_emails.csv

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#114]
En la base de datos db_emails.csv, ¿los correos que aparecen están ordenados (de arriba hacia abajo) de mas reciente a mas antiguo o al reves?

**Comment by nachocontreras** [comment]
Hola!

Se habló de esto en la issue #36.

Saludos!

**Comment by mericci** [comment]
Entiendo que queda a mi elección y tengo que dejarlo como supuesto, ¿Esta bien eso?

Muchas gracias!

**Comment by nachocontreras** [comment]
Sí, está bien!
