### ISSUE TITLE
Error al leer coding (Non-ASCII)

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus-2018-2#118]
Hola, me aparece el siguiente error cuando trato de correr el código:
SyntaxError: Non-ASCII character '\xc3' in file
A que se debe?
Gracias

**Comment by bimartinez** [comment]
Hola @cristozille !

Ese error es porque probablemente en tu codigo tienes un caracter no [ASCII](https://en.wikipedia.org/wiki/ASCII) (con una ñ basta para destruir :boom: tu código). Para próximos errores de este tipo puedes buscar en [Google](https://www.google.com/) el error, acompañado de la versión de Python :snake:. Siempre a alguien le pasó lo mismo que a uno ~~aunque creamos que no~~.

Saludos! :smile: 

PD: [Esto](https://stackoverflow.com/questions/10589620/syntaxerror-non-ascii-character-xa3-in-file-when-function-returns-%C2%A3) encontré con tu error, lo bueno es que generalmente las respuestas son bien completas :computer:
