### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#121]
Hola, ¿Como hago uso del .gitignore? y en caso de ya haber subido archivos que no quería subir (data por ejemplo) ¿como hago para eliminarlos?

**Comment by ptflores1** [comment]
Hola !
El `.gitignore` te sirve para no subir los archivos, pero debes haberlo creado antes de subirlos. Googlee "git remove file from repository" y encontré [esto](https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo/2047477), espero que te sirva. 
Saludos !
