### ISSUE TITLE
Bandeja de entrada (¿cuando mostrarla ?)

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/syllabus-2018-2#124]
Tengo una duda, la bandeja de entrada debería mostrarse inmediatamente luego de que el usuario inicio sesión o puede existir una opción llamada "bandeja de entrada" y que cuando el usuario la seleccione esta se despliegue, muchas gracias

**Comment by FJavierOss** [comment]
Queda a criterio, trata de diseñarlo según te parezca más intuitivo y organizado de acuerdo a lo que es una bandeja de entrada en un sistema de correos. :smile:
