### ISSUE TITLE
consulta de eventos

### ISSUE THREAD

**Issue by chocopiano** [IIC2233/syllabus-2018-2#126]
Hola! No logro entender lo de consultar eventos según fecha, etiquetas y nombre. Osea si consulto segun etiquetas y/o nombre se que me debe mostrar los eventos con dichas etiquetas y/o nombres pero como se debe consultar segun fecha??(Me refiero el usuario debe preguntar por  los eventos en un mes o entre ciertas fechas o en cierto día o puede ser cualquiera de las anteriores??) Gracias y perdonen el enredó

**Comment by prod-bysilva** [comment]
Hola,

El formato para fechas aparece en la issue #101 

Éxito en la tarea!
