### ISSUE TITLE
Encriptación y comillas en db_emails.csv

### ISSUE THREAD

**Issue by rafafdz** [IIC2233/syllabus-2018-2#128]
Al intentar desencriptar los mensajes de db_emails.csv y compararlos con old_db_mails.csv, me di cuenta que **el mensaje encriptado incluye las comillas simples** (Si se intenta desencriptar sin incluirlas no se llega al mensaje original), siendo que en la sección 4.1 del enunciado dice claramente que estas **no deberían contar** para los 256 caracteres de la encriptación. Dicho esto, como implementamos la lectura / guardado de archivos en la tarea? Incluimos o no las comillas en el cuerpo encriptado del correo? Hacemos que se soporten ambas formas?

Muchas gracias!

**Comment by FernandoPieressa** [comment]
Hola! 

Fue error de la base de datos! Acabo de actualizarla para no incluir las comillas simples!

Saludos!

**Comment by viantirreau** [comment]
Estimado Fernando, 
La versión actualizada de la base de datos de correos db_emails.csv trae un \n al final. ¿Adaptamos nuestro código a este cambio o aplicamos lo del #113?

Muchas gracias!

**Comment by BenjaminRubio** [comment]
@FernandoPieressa

**Comment by FernandoPieressa** [comment]
Apliquen lo del 113, ya lo arregle.

Saludos!

**Comment by ararojas** [comment]
Hola! 
Ahora que el mensaje viene sin comillas, cuando alguien envía un email, ya no le agregamos las comillas simples tampoco?
Lo dejamos siempre sin comillas? O al desencriptar se las agregamos para cuando mostramos el mensaje?
