### ISSUE TITLE
Formato separación de destinatarios

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#130]
En el apartado 3.2.1, dice que los destinatarios deben estar separados por "," , pero el archivo de emails.csv tiene los destinatarios separados por ";" lo que hace mucho más sentido para facilitar el manejo de datos.
¿Cual le pedimos al usuario?

**Comment by ptflores1** [comment]
Hola !
El como se pide por consola es independiente a como deben ser escritos los archivos, los destinatarios deben ser ingresados por consola usando `,`'s  como se pide en el enunciado y las bases de datos quedan a tu criterio como manejarlas. **Ojo que tu programa debe ser capaz de partir solo con los archivos que les dimos**
Saludos !
