### ISSUE TITLE
Importar los datos de la base de datos creada

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#132]
No me queda muy claro si cuando se crear la base de datos respaldando los usuarios, correos enviados y eventos, esta debe persistir con el tiempo, es decir, cuando ejecute nuevamente el programa tendré que llamar a esta base de datos además de la que se nos esta dando. Ya que pasa , por ejemplo, si modifique los invitados a un evento, pasara que al importar esta base de datos, mas la que se nos da, existirán dos eventos iguales, donde solo tienen distinto los invitados.

No se si queda tan claro mi duda 😥

**Comment by cilopez** [comment]
Hola @NicolasCabello  , los datos si deben persistir en el tiempo.  No estoy seguro de comprender al 100% tu duda pero al editar un evento deberias modificar su intancia en la base de datos para que no pase eso.

**Comment by NicolasCabello** [comment]
@cilopez Si!, me quedo claro, mucha gracias!

**Comment by Cadagan** [comment]
No podemos **usar los archivos que ya estan** como base de datos para guardar la informacion nueva? (guardar usuarios nuevos en db_users.csv, guardar los correos en db_mails.csv, etc) 
o si o si tenemos que crear **un solo archivo** como base de datos que guarde **toda** la info?(usuarios, mails enviados, etc)

**Comment by NickCastillo** [comment]
@Cadagan Anda a ver el Issue #43 !
