### ISSUE TITLE
formato base de datos "db_emails.csv"

### ISSUE THREAD

**Issue by PaoloFabia** [IIC2233/syllabus-2018-2#137]
Hola!
Estoy teniendo muchos problemas para leer el archivo de emails, pues si bien el formato debería ser from,to,title,body,classifications (entiendo que todo en una celda separado por comas o bien cada elemento en una celda distinta, siendo que si el "to" son varias personas, deberían estar todas en la misma celda). Sin embargo, el archivo tiene en la primera celda "from, to (solo un mail)", de la segunda celda en adelante los otros mails pertenecientes a "to", cuando se hace el cambio a title es una celda con el formato: "ultmo_mail_de_to, title", etc... Está bien eso? debo trabajar con el archivo así? o no se me abre en forma correcta?
gracias! (ayuda)

**Comment by ptflores1** [comment]
Hola !
Te recomiendo no interpretar los datos como que están dentro de celdas. Piensa que todo lo que esta desde el inicio de cada fila (que no sea la fila del *header*) hasta la primera `,` corresponde a lo equivalente en el *header*, que en este caso es la columna `from`. Luego desde esta `,` hasta la siguiente todo lo que hay es lo que corresponde a `to` y así sucesivamente. Espero quede mas claro.
Saludos !

**Comment by tatanpoker09** [comment]
Con respecto a esto, puedo modificar la primera linea del csv? De esta manera crear namedtuples a través de `
    emails = namedtuple("Emails", firstline.replace(",", " "))`
sale muy conveniente, pero sin modificar, me genera errores al tener el `from` como nombre registrado.
