### ISSUE TITLE
Duda Feedback Tarea 0

### ISSUE THREAD

**Issue by dgfluxa** [IIC2233/syllabus-2018-2#139]
En el feedback no entendí a lo que se refiere el punto que dice:
Se puede crear un nuevo evento con los atributos que haya implementado: Por Ej: Si no alcanzó a implementar descripción y se puede crear un nuevo evento con el resto de los atributos, entonces tiene todo el ptje.

¿Se refiere a que se puede crear un evento aún cuando no se haya ingresado descripción, invitados, y/o etiquetas (tengo entendido que esos son los únicos que se pueden dejar en blanco)?

**Comment by jeschuwirth** [comment]
Saludos,
en ese punto podrás obtener 3 puntajes,  todo,  la mitad, o nada (redondeando hacia abajo), entonces tener el 68% significa la mitad del puntaje.

**Comment by dgfluxa** [comment]
Gracias, pero mi duda no era sobre el puntaje, si no de lo que nos están pidiendo que nuestro programa sea capaz de realizar en este punto, ya que no lo entendí.

**Comment by jeschuwirth** [comment]
Esa parte del feedback es en caso de que te falte tiempo o algún otra razón, si lograste crear los eventos, sin embargo nunca pudiste hacer que la fecha funcione (tu programa corre todo perfecto excepto las fechas que no funcionan). Entonces debes escribir en el ReadMe ese problema y evaluaremos la tarea sin eso, sin embargo probablemente recibas la mitad del puntaje en varios items como sería el caso de este.

Si te refieres a que se puede crear un evento sin fecha o descripción, aún cuando tienes todo eso puesto en tu código (el usuario simplemente no le quiso agregar), te diría que no se puede, para crear un evento este debe poseer todos los puntos de la parte 3.4.1 del enunciado.

Espero que eso aclare un poco tu duda

**Comment by dgfluxa** [comment]
Ahora si me quedo claro.
Muchas Gracias @jeschuwirth
