### ISSUE TITLE
Compilado dudas enunciado

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#14]
### Aqui dejo varias dudas que me surgieron al leer el enunciado:

1.- **[pag 4, 3.4 Calendario]**: dice que "en todo momento(...) puede ver los eventos que creo o a los que fue invitado". esto incluye cuando esta editando o creando eventos? o solo se refiere a desplegar una lista en una especie de "menu principal" al cual siempre se puede acceder independiente de lo que este haciendo? (no me quedo muy claro que cosas incluye lo de "en todo momento" y que no)

2.-**[pag 5, 3.4.2 acciones disponibles]**: cuando dice "consultar eventos segun fecha, nombre y etiquetas" se refiere a que se puede consultar solo usando una de las tres opciones a la vez, o podria buscar diciendo solo fecha y etiquetas, dejando en blanco la opcion "nombre"? o acaso se refiere a solo hacer consultas con los 3 campos al mismo tiempo?

3.- **[pag 6, 3.5 encriptación]**: En el paso 4, cuando dice "copiar la parte necesaria" se refiere a repetir clave + cadena aleatoria hasta llegar a los 256 caracteres y ahi cortar?

Gracias de antemano por contestar las dudas :)
Saludos!

**Comment by rhanuch** [comment]
¡Hola @cadagan !

Por favor haz issues separadas para así poder ayudar a la búsqueda de dudas más adelante! 😬😬

Saludos!
