### ISSUE TITLE
Fecha término de eventos

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#140]
Hola! De la parte 3.4.1. del enunciado de la tarea, sección de fecha y horas de inicio y término: se dice que la fecha de término no puede ser anterior a la de inicio. Por otra parte, el usuario puede no dar una hora de término, y en tal caso la hora de término será una hora después de la de inicio.

En una instancia, el usuario ingresa fecha de inicio = `08/11/2018` y la de término = `09/11/2019`. Pero luego, al tener que poner la hora de término para fecha de término, no lo da.

Entonces, ¿qué se respeta al final? Que la fecha de término sea el 09/11/2019 a las 00:00 horas, o que sea el 08/11/2018 una hora después de la hora de inicio?

O simplemente deberíamos hacer que, en lugar de no decidir hora de término, decida no poner fecha de término y que ahí se aplicara la regla de que la hora de término será `hora de inicio + 1` en el mismo día de inicio?

Saludos.

**Comment by ptflores1** [comment]
Hola !
Lo ultimo que dijiste es lo correcto

> O simplemente deberíamos hacer que, en lugar de no decidir hora de término, decida no poner fecha de término y que ahí se aplicara la regla de que la hora de término será hora de inicio + 1 en el mismo día de inicio?

Saludos !
