### ISSUE TITLE
Descuentos en modularización

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#142]
En el archivo _Descuentos.md_ habla sobre descuentos de modularización.
Solo para confirmar, cuando dice

> - >  3 décimas si 3 o más archivos exceden 600 líneas y es posible haberlo segmentado en otros archivos

¿Es posible tener tener uno de _+600, -800_ líneas y los demás bien?
Gracias! :disappointed_relieved:

**Comment by Arcoirisky** [comment]
La idea del descuento es cuando tienes un archivo grande cuando puedes separarlo en otros más pequeños o: si es que te salió relativamente grande pero estás seguro que todas esas líneas tienen sentido sólo en ese archivo, puede funcionar :D 

Oh! Y recuerda que si notas partes repetidas, puedes remplazarlas por una función que haga el mismo trabajo :D Así restas líneas :DD
