### ISSUE TITLE
Duda 4.1 archivos entregados 

### ISSUE THREAD

**Issue by BenjaCastillo** [IIC2233/syllabus-2018-2#144]
Im sorry pero no entiendo que debo hacer con esos archivos.
Tengo que meterlos a la base de datos de mi programa, cosa de que cuando corra el programa ya venga con toda esa informacion?

**Comment by BFFV** [comment]
Según entiendo lo mejor es simplemente usar esos mismos archivos como bases de datos iniciales e ir agregándoles los mails, eventos, etc.. nuevos que se vayan creando con el programa (excepto por el old_db_emails que es para probar la encriptación)

**Comment by prod-bysilva** [comment]
Hola, 

Revisa la issue #43 !
