### ISSUE TITLE
Numero cientifico al escribir archivo .csv

### ISSUE THREAD

**Issue by gejohow** [IIC2233/syllabus-2018-2#146]
Al momento de escribir en el archivo .csv el encriptado, se me guarda como numero cientifico. Por ejemplo se me escribe "5.6821102103011E+90" en vez del conjunto de numeros que son el encriptado. Busqué en internet soluciones pero ninguna funciona, estoy usando encoding utf-8.
Queria saber si alguno sabe como solucionarlo.

**Comment by pnheinsohn** [comment]
Hola! ¿Puede ser de que estás abriendo tu archivo CSV desde Excel o algún similar para verificar la conversión? En ese caso, trata de abrirlo desde un editor de texto ya que Excel (y similares) tienden a "parsear" sus celdas.
Revisa este link: https://support.3dcart.com/knowledgebase/article/View/619/7/why-does-my-exported-csv-data-get-converted-to-weird-formats
