### ISSUE TITLE
Encriptacion y Contenidos

### ISSUE THREAD

**Issue by csolguin** [IIC2233/syllabus-2018-2#147]
1- Es necesario pasar las palabras a ASCII y de ASCII a binario (así aparece en el feedback), si se puede pasar directamente de palabras a binario (el resultado es el mismo y así es mucho más directo)
2- Con respecto a la materia, ¿Cual es la diferencia entre **kwargs y*args?

**Comment by fringlesinthestreet** [comment]
Hola @csolguin :)

Te responderé la segunda duda. Algo importante es que las sintaxis importantes son `*` y `**`. Los nombres `args` y `kwargs` son convención solamente.

PS: Por favor para próximas _Issues_, separa tus dudas en 2 _Issues_ independientes (a menos que sigan el mismo tema).

---

Puedes utilizar `*` cuando no sabes cuantos argumentos **posicionales** ("normales") recibe tu función, es decir, que te permite tener flexibilidad con respecto a la cantidad de argumentos posicionales recibidos. ¿A qué me refiero con esto? Te mostraré un ejemplo:

```
def funcion_posicional(*numeros):
    print("Recibí {} argumentos".format(len(numeros)))
    print("Veamos cómo se imprimen: {}".format(numeros))

>>> funcion_posicional(7, 9, 3, 5, 1)
Recibí 5 argumentos
Veamos cómo se imprimen: (7, 9, 3, 5, 1) 
```

Con la sentencia `*` preparas a la función para recibir varios argumentos posicionales, es decir, ¡que importa el orden!

```
>>> funcion_posicional(1, 5, 3, 9, 7)
Recibí 5 argumentos
Veamos cómo se imprimen: (1, 5, 3, 9, 7)
```

Te puedes fijar que la variable `numeros` empaqueta todos los argumentos recibidos en una tupla :), por lo que podrías incluso iterar sobre ésta.

---

Por el otro lado, la sentencia `**` hace referencia a _keyword arguments_ (por eso kwargs), esto quiere decir que son argumentos que están asociados a una _key_ (o llave) al pasarse a la función. Un ejemplo:

```
def funcion_keyword(**frutas):
    print("Veamos cómo se imprime: {}".format(frutas))

>>> funcion_keyword(manzana = "Deliciosa", pera = "No tan deliciosa")
Veamos cómo se imprime: {'manzana': 'Deliciosa', 'pera': 'No tan deliciosa'}
```

Con la sentencia `**` preparas a la función para recibir varios argumentos asociados a llaves. te puedes fijar también que la variable `frutas` empaqueta todos los argumentos _keyword_ en un diccionario (por lo que **no importa el orden**).  

---


Obviamente, puedes crear funciones que utilicen `*` y `**`. Un ejemplo:

```
def funcion_flexible(*posicionales, **con_llave):
    print("Los argumentos posicionales son: {}".format(posicionales))
    print("Los argumentos keyword son: {}".format(con_llave))

>>> funcion_flexible(12, 33, 7, 43, a = 17, b = 97)
Los argumentos posicionales son: (12, 33, 7, 43)
Los argumentos keyword son: {'a': 17, 'b': 97}
```
La restricción es que al pasar argumentos a cualquier función/clase, debes pasar primeros los posicionales (normales) y luego los _keyword_.

Tu función también puede recibir argumentos específicos antes de utilizar `*` o `**`. Un ejemplo:

```
def funcion_ejemplo(departamento, *alumnos, **profes_asignados):
    print("El departamento es: {}".format(departamento))
    print("Los alumnos son: {}".format(alumnos))
    print("Los profes son: {}".format(profes_asignados))

>>> funcion_ejemplo("DCC", "Fernando", "Rodrigo", cruz = "IIC2333")
El departamento es: DCC
Los alumnos son: ('Fernando', 'Rodrigo')
Los profes son: {'cruz': 'IIC2333'}
```

La función va a priorizar los argumentos con nombre (en este caso `departamento`) por sobre los `*args` y los `**kwargs`.

```
>>> funcion_ejemplo(departamento = "DCC")
El departamento es: DCC
Los alumnos son: ()
Los profes son: {}
```

Ojo con hacer esto:

```
>>> funcion_ejemplo("DCC", departamento = "DCC")
TypeError: funcion_ejemplo() got multiple values for argument 'departamento'
```

---

La sentencia `*` y `**` también se pueden utilizar al entregar argumentos a una función. En este caso en vez de empaquetarlos (juntarlos), los desempaqueta. Un ejemplo:

```
def funcion_posicional(*numeros):
    print("Recibí {} argumentos".format(len(numeros)))
    print("Veamos cómo se imprimen: {}".format(numeros))

lista_numeros = [7, 9, 3, 5, 1]

>>> funcion_posicional(lista_numeros)
Recibí 1 argumentos
Veamos cómo se imprimen: ([7, 9, 3, 5, 1],)

>>> funcion_posicional(*lista_numeros)
Recibí 5 argumentos
Veamos cómo se imprimen: (7, 9, 3, 5, 1)
```

Otro ejemplo:

```
def funcion_keyword(**frutas):
    print("Veamos cómo se imprime: {}".format(frutas))

dic_frutas = {"manzana": "Deliciosa", "pera": "No tan deliciosa"}

>>> funcion_keyword(dic_frutas)
TypeError: funcion_keyword() takes 0 positional arguments but 1 was given

# Tira error porque le pasamos el diccionario como  argumento posicional 
# (i. e. no asociado a una llave), y la función sólo recibe argumentos keyword


>>> funcion_keyword(**dic_frutas)
Veamos cómo se imprime: {'manzana': 'Deliciosa', 'pera': 'No tan deliciosa'}
```

Espero te haya ayudado :). Si quedaste con más dudas, investiga (jeje) y si continúan pregunta por acá nomás :).
