### ISSUE TITLE
Visibilidad eventos creados, "en todo momento"

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#15]
Dice que "en todo momento(...) puede ver los eventos que creó o a los que fue invitado". esto incluye cuando esta editando o creando eventos? o solo se refiere a desplegar una lista en una especie de "menu principal" al cual siempre se puede acceder independiente de lo que este haciendo? (no me quedo muy claro qué cosas incluye lo de "en todo momento" y que no)

**Comment by nachocontreras** [comment]
Hola!

Esto se refiere a que el usuario **no** puede ver los eventos de los demás, sino que solo sus eventos o los eventos a los que fue invitado. Por lo tanto, **no** significa que siempre se tenga que ver el calendario, solo cuando sea necesario.

Éxito con la tarea! 😄
