### ISSUE TITLE
Parte 5 encriptación

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#151]
En el enunciado, en la parte 5.c dice que "Esto se repite para todos los elementos de la lista.". Entonces significa que debemos repetir el procedimiento hasta abarcar todos los elementos de la lista? o se refiere a que la posición j debe pasar por todos los numero desde el 0 hasta el final de la lista? o si no es ni una de las dos opciones hasta cuando hay que repetir el procedimiento?
Gracias!

**Comment by ncasassas** [comment]
Al menos yo lo hice repitiendo el procedimiento hasta que el "i" del enunciado pasa por los 255 elementos ya que el "j" del enunciado varia respecto del "i".
Saludos!
