### ISSUE TITLE
Duda comillas 

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#152]
Hola, en el enunciado mencionan lo siguiente: 

> Como podrias haber notado, pueden existir comas (“,”) dentro de las descripciones, nombres, titulos y
cuerpo, por lo que estos textos est´an entre comillas simples (“ ’ ”) las cuales no cuentan para los 256
caracteres de la encriptacion. Estas comillas permiten tener texto coherentes que permitan el uso de
comas, por lo que tu versión de DCCorreos también debe poder escribir y leer archivos en este formato
sin perder coherencia del texto confundiendolo como si fuese otra columna.

No se si esto implica de alguna forma que en los inputs que utilizaran para probar nuestras tareas no utilizaran comillas simples dentro de las descripciones, titulos, etc para que no se confundan con las que van a ir alrededor de estas secciones. 

Por ejemplo, que el asunto de un mail sea: Duda sobre 'start ups'.

**Comment by lily416** [comment]
Se aplica lo que se dice en #128

Saludos 👋

**Comment by gnacrur** [comment]
@lily416  Hola, mi issue la verdad que no se trataba de lo que responden en #128. Yo quiero saber si van a poner comillas simples dentro de la descripción, asunto o nombre. Todo esto por el tema de que estoy buscando evitar que el split(",") considere estas comas (si es que existiesen) al separar cada linea.

**Comment by lily416** [comment]
La descripción, asunto o nombre no incluirán comillas simples, además de las que se usan para contener la string.

Saludos y éxito con la tarea 🍀
