### ISSUE TITLE
problema git pull

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#153]
hola, queria actualizar mi carpeta de syllabus, con git pull, pero me tira este error:
error: The following untracked working tree files would be overwritten by merge:
        Ayudantias/S02 - Funcional 101/.ipynb_checkpoints/Enunciado AY02 - Funcional 101-checkpoint.ipynb
Please move or remove them before you merge.
Aborting

no entiendo que debo hacer

gracias!!

**Comment by bimartinez** [comment]
Hola @pelao97 ,

Busque :mag:  tu problema en [Google](www.google.com) como `git pull The following untracked working tree files would be overwritten by merge` y encontré [esto](https://stackoverflow.com/questions/17404316/the-following-untracked-working-tree-files-would-be-overwritten-by-merge-but-i). Espero que te ayude :smile: 

Saludos!

**Comment by pelao97** [comment]
gracias!
