### ISSUE TITLE
Parte 5 - Cadena de Inicio

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#154]
Hola! No entiendo qué es la cadena de inicio o cómo obtenerla.

De antemano muchas gracias!

**Comment by ncasassas** [comment]
Por lo que yo entendí es repetir la clave que nos dan + la cadena aleatoria de los 10 caracteres hasta obtener los 256 caracteres.
Y con esa  y la sin desordenar hacer el paso 5 de la encriptación.
No se si te refieres a eso?
Saludos!
