### ISSUE TITLE
Usar una función de internet

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#155]
Hola! queria saber si puedo usar la función que sale acá: https://chrisalbon.com/python/data_wrangling/break_list_into_chunks_of_equal_size/
para dividir una lista en n partes iguales. La uso en la parte de encriptacion para decodificar. 
Gracias!

**Comment by FJavierOss** [comment]
Hola, 

Si quieres puedes hacerlo, pero hay formas más fácil de hacerlo que con generadores.  Por ejemplo >range(inicio, final, intervalo)

Saludos
