### ISSUE TITLE
2da pregunta del ejercicio 6.

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#156]
Como puedo ocupar por asi decir un defaultdict por compresion?? es para la 2da pregunta del ejercicio 6

**Comment by fringlesinthestreet** [comment]
Hola @marcotroncoso :)

Bien pensado lo del `defaultdict` :smile:, sin embargo, no se puede crear un `defaultdict` por comprensión :( .

Lo que sí se puede hacer es entregarle un tercer argumento a la función `reduce`, el cual se tomará como "inicializador". Si este argumento no se entrega, el reduce tomará como inicializador al primer elemento del iterable.

Un ejemplo sería hacer un `reduce` de una lista de números para obtener el factorial:

```
lista_numeros = [1, 2, 3]
multiplicador = lambda n1, n2: n1 * n2
>>> print(reduce(multiplicador, lista_numeros))
6
```

Esto va a hacer que el reduce vaya multiplicando los pares de números. Ahora, podemos darle como inicializador lo que queramos, a continuación haré unas pruebas:

```
>>> print(reduce(multiplicador, lista_numeros, 0))
0

>>> print(reduce(multiplicador, lista_numeros, -1))
-6
```

Ahora bien, se puede poner cualquier objeto como inicializador, un ejemplo:

```
>>> print(reduce(multiplicador, lista_numeros, ["hola"]))
['hola', 'hola', 'hola', 'hola', 'hola', 'hola']
```

Por último, recuerda que la función `reduce` recibe cualquier función como argumento (mientras esta reciba 2 argumentos). Veamos cómo sale esto:

```
def multiplicador_espia(num1, num2):
    mult = num1 * num2
    print("La multiplicación va en {}".format(mult))
    return mult

>>> print(reduce(multiplicador_espia, lista_numeros))
La multiplicación va en 2
La multiplicación va en 6
6

>>> print(reduce(multiplicador_espia, lista_numeros, 0))
La multiplicación va en 0
La multiplicación va en 0
La multiplicación va en 0
0
```

Con esta información ojalá que puedas logralo :wink:. Aunque si sigues teniendo preguntas, ¡no dudes en preguntar!

**Comment by cacoos** [comment]
Hola!

Para este ejercicio es legal crear una función aparte e incluirla en el _reduce_?

**Comment by fringlesinthestreet** [comment]
Hola @cacosandon

Sí, ¡Siempre es legal! Recuerda que tanto `reduce`, `filter` y `map` reciben una función como argumento y un iterable. A veces estas funciones son simples y se podrían hacer en una sola línea, por lo que utilizamos `lambda` para hacerlas. 

Recuerda que las funciones `lambda` son análogas a una función normal, su diferencia es que realizan una acción y **siempre** retornan el resultado de esa operación, por lo que es más entendible al leerlas. Si deseas realizar más de una acción (por ejemplo: la función `multiplicador_espia`), te recomiendo hacerlo con una función regular.
