### ISSUE TITLE
Duda largo encriptación

### ISSUE THREAD

**Issue by ncasassas** [IIC2233/syllabus-2018-2#157]
Hola, tengo una duda respecto de la encriptación: El largo del mensaje debemos considerarlo a la hora de generar la cadena de inicio(el largo de esta depende del largo del mensaje) o al momento de comparar el mensaje en binario con la lista de números ( ya desordenados) en binario ( ejemplo paso 6 de la guía ) tomando el mismo largo de la lista que del mensaje codificado en binario ??.
Por ejemplo si el mensaje es "hola":
1. Mi cadena de inicio seria más corta ?
2. Mi lista de números en binario sería del mismo largo que el mensaje transformado a binario?

Pregunto por qué en el enunciado en el pto. 4 se menciona que "Hay que tener en cuenta que no siempre se tendrá que repetir todo para obtener exactamente la cantidad de caracteres requeridos", lo que me generó la duda.

Saludos y gracias de antemano.

**Comment by kelseyfranken** [comment]
tengo la misma duda

**Comment by ncasassas** [comment]
Considerando el largo del mensaje al momento de compararlo con la lista de números en binario me encripto y desencripto según las bases que nos entregaron. Por si acaso
