### ISSUE TITLE
Herencia

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#158]
¿Puedo utilizar herencia de clases en la tarea?
ejemplo:
class ClaseDerivada(ClaseBase):
    <declaración-1>
    .
    .
    .
    <declaración-N>

**Comment by agustinkrebs** [comment]
Hola!

El enfoque de esta tarea no es ocupar Herencia o cosas relacionadas con los contenidos "avanzados" de OOP que se verán pronto en el curso. Puedes ocuparlos, pero sólo si están correctamente implementados. Aplican las mismas reglas que para el Try-Except (issue #104).

Recomendamos no ocuparlos dado que no es el enfoque de esta tarea.

Saludos!
