### ISSUE TITLE
Problemas con git

### ISSUE THREAD

**Issue by RobinCuevas** [IIC2233/syllabus-2018-2#159]
Estimados;

He intentado subir avances de la tarea y la consola me muestra lo siguiente;
![image](https://user-images.githubusercontent.com/37147631/44503262-d03a6700-a66b-11e8-9bdc-b5df29b1740b.png)

Como puedo solucionarlo?

Muchas gracias!

**Comment by pnheinsohn** [comment]
Hola! Es porque en el repo de github hay más archivos o hay algunas líneas de código que tu repositorio local no tiene. Para solucionarlo prueba haciendo un git pull y después haces lo de git push.
