### ISSUE TITLE
Formato consulta de eventos, múltiples campos

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#16]
Cuando dice "consultar eventos segun fecha, nombre y etiquetas" se refiere a que se puede consultar solo usando una de las tres opciones a la vez, o podria buscar diciendo solo fecha y etiquetas, dejando en blanco la opcion "nombre"? o acaso se refiere a **solo** hacer consultas con los 3 campos **al mismo tiempo**?

**Comment by nachocontreras** [comment]
Hola!

Se debe poder buscar utilizando cualquier combinación de esos 3 campos, es decir, pueden haber consultas con parámetros vacíos, pero estos no serán considerados en la búsqueda.

**Comment by fjtobar** [comment]
Hola! si el usuario no coloca nada en ningún filtro de búsqueda, el resultado serían todos los eventos o ninguno?

**Comment by nachocontreras** [comment]
El resultado serían todos los eventos.

**Comment by ararojas** [comment]
Hola! Si el usuario busca segun dos parametros (por ejemplo fecha y etiqueta), se le puede retornar los eventos que tengan esa fecha O esa etiqueta, o tienen que contener ambos?

**Comment by nachocontreras** [comment]
Tienen que contener ambos.
