### ISSUE TITLE
INTERCAMBIO Encriptacion

### ISSUE THREAD

**Issue by isavega** [IIC2233/syllabus-2018-2#160]
En el punto 5, pensando en el ejemplo "hola"

No entiendo porque en su ejemplo (las fotos), en la cadena de inicio que debe empezar con la clave 2233 en binario.... que seria 0010001000110011
Empieza  con 10112....

**Comment by kelseyfranken** [comment]
tengo la misma duda

**Comment by NatachaP** [comment]
Hola, tampoco entiendo eso. ¿La clave 2233 completa debería estar completa al inicio y usarse dentro del intecambio? , ¿o debe estar separada al igual que los otros números aleatorios (que están entre 0 y 9)?
¿o sólo se usa la clave para reconocer el mensaje a desencriptar?
