### ISSUE TITLE
Contenidos semana 2 – función map y listas por comprensión

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#162]
Hola!

Todo lo que se puede hacer con la función `map` se puede hacer con _listas por comprensión_ (y viceversa)? Si no, algún ejemplo?

Saludos y gracias.

**Comment by bimartinez** [comment]
Hola!

Efectivamente se pueden hacer las cosas que hace `map` tanto con *listas por comprensión (**lc**)* como con *generadores por comprensión*. 

Pero te pongo el siguiente caso, ¿***Que pasa si quiero aplicar una función para 3 iterables***?

En ese caso si intentáramos hacerlo por ***lc*** lo que pasaría sería que te quedaría una línea de código poco comprensible para la lectura (tendrías una iteración triple :sob:) ~tal vez ni nosotros entenderíamos que hacemos~, además de que podemos cometer errores intentando hacerlo así.

En cambio si ocupamos `map` sería algo de este estilo:

`map(lambda x, y, z: x + y + z, iter1, iter2, iter3)`

Mucho mas simple o no? :smile: 

También ocupar map es mas eficiente que ocupar ***lc*** (mas información [acá](https://stackoverflow.com/questions/1247486/python-list-comprehension-vs-map))

Saludos!

**Comment by ariel-m-s** [comment]
Muchas gracias @bimartinez ! Todo claro.
