### ISSUE TITLE
Crear eventos: tope de fechas

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#163]
El enunciado dice "Además, no pueden haber dos eventos con la mismas fechas y el mismo nombre". Ver si el nombre del nuevo evento se repite con otros eventos suyos es fácil, ¿pero cómo hacemos para ver si calzan fechas? Una opción podría ser que las fechas de inicio y/o término coincidan, otra opción podría ser que 2 eventos se sobrepongan en un intervalo. ¿Qué debemos considerar?

**Comment by FJavierOss** [comment]
Hola,

Esta duda se resuelve en la issue #62 

Saludos!
