### ISSUE TITLE
3.4.2 orden de aacion sobre eventos

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/syllabus-2018-2#164]
Para la parte de acciones disponilbes 3.4.2:

Puedo solo entregar la opcion de ejecutar una accion (editarlos) **solo** sobre los eventos de los que el usuario es dueño? Mi  pregunta es porque en el enunciado sale al revés, primero mostrar todos los eventos (independiente si es dueño o no) y luego elegir cual editar

Gracias

**Comment by lily416** [comment]
Como dice en el enunciado:
> Un usuario solo puede editar eventos que él haya creado.


Saludos 👋
