### ISSUE TITLE
Formato clave

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#171]
La clave se pasa a binario, a decimal, o no se pasa a nada y solamente puede recibir números?

**Comment by ncasassas** [comment]
Si con clave te refieres a la contraseña de cada usuario tengo entendido que esta no se encripta ni se transforma, si te refieres a la clave de la encriptacion (2233) al menos yo no la transforme nunca a binario, solo la use para mezclar la lista que va del 0 al 255. Luego, esta lista si hay que pasarla a binario para poder encriptar y desencriptar.
