### ISSUE TITLE
ord() para numeros ascii

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#172]
Hola, en el enunciado, en la parte de encriptación, en la parte 2.a) sale que tenemos que transformar los caracteres positivos según la codificación ascii. Para eso tenía pensado usar ord(), pero según lo que leí en stackowerflow, ord() no es para ascii. Por ejemplo ord("あ") es 12354.

Mi duda es, está bien usar ord() o recomiendan otra librería?

Gracias

**Comment by jeschuwirth** [comment]
Hola,
en el siguiente link tienes varios metodos de las strings de python, te recomiendo revisar .encode()
[url](https://www.w3schools.com/python/python_ref_string.asp)

**Comment by Kitaps** [comment]
Gracias
