### ISSUE TITLE
Duda nombre de la carpeta para archivos

### ISSUE THREAD

**Issue by carajila** [IIC2233/syllabus-2018-2#173]
Tengo una duda sobre cual debe ser el nombre de la carpeta donde se encuentran los archivos.
En el enunciado de la tarea en el punto 4 se dice que deben ser guardado en una carpeta llamada "datos", pero la carpeta que está en syllabus tiene el nombre de "data". ¿Con cual nombre debemos llamarla?

**Comment by FJavierOss** [comment]
Hola,

No te compliques con hacer una carpeta nueva, utiliza la carpeta "data" para  guardar los archivos. Mucha suerte en tu tarea :smile: 

Saludos
