### ISSUE TITLE
Duda con encriptacion

### ISSUE THREAD

**Issue by MartinAracena** [IIC2233/syllabus-2018-2#176]
Hola, he leido bastantes veces el enunciado y no entiendo muy bien de donde ni como se crea la cadena aleatoria usando los 10 primeros elementos del mensaje a descifrar.

**Comment by BFFV** [comment]
Se crea generando al azar los 10 números (cada uno entre 0 y 9) nomás. Lo de los 10 primeros elementos se refiere a la desencriptación, donde se obtiene de ahí la cadena aleatoria para realizar la decodificación.

**Comment by MartinAracena** [comment]
Gracias!
