### ISSUE TITLE
.DS_store en mac

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#177]
Holaa, al intentar hacer git pull en el syllabus me aparece que este no se puede actualizar ya que hay algo llamado ds_store que no me deja seguir la accion. Que se puede hacer para que eso no me ocurra??

**Comment by cilopez** [comment]
Si es el syllabus una solución rápida pero parche es volver a clonar el repositorio. Otra solución puede ser que corras los siguientes comandos  `git add --al`  y luego  `git stash` (esta solución también es parche, pero más decente, ojo que de esta forma se borran las cosas que no han sido agregadas al repositorio). Avísame si pudiste resolver el problema con alguna de las 2

**Comment by marcotroncoso** [comment]
con lo segundo me funciono, graciaaas
