### ISSUE TITLE
Base de datos y path relativo

### ISSUE THREAD

**Issue by isiguelfand** [IIC2233/syllabus-2018-2#178]
Hola! Ya sé que lo preguntaron antes pero no me quedó clara la respuesta. Al corregir mi tarea va a haber una carpeta llamada “data” en la misma carpeta?

**Comment by cilopez** [comment]
Si, la carpeta se llamará igual.

**Comment by bgsamilla** [comment]
Que hay de la carpeta "datos"?
Yo guarde mis archivos en esa siguiendo lo que dice el enunciado ...

**Comment by cilopez** [comment]
@BSamilla  Ese fue un error en el enunciado que aclaramos anteriormente, pero si tu programa funciona con una carpeta llamada `datos` no hay problema si es que lo mencionas en tu _readme_.
