### ISSUE TITLE
Largo mínimo cuerpo correo

### ISSUE THREAD

**Issue by felipearellanom** [IIC2233/syllabus-2018-2#179]
En el enunciado se menciona un largo máximo de 256 caracteres en el cuerpo de un mensaje.
¿Hay un largo mínimo? ¿O puede estar vacio?

**Comment by cilopez** [comment]
No se habla de un mínimo pero puedes tomar como supuesto para tu programa que no existiran mensajes vacíos.  Si lo haces señalalo en tu readme. Saludos 😄

**Comment by felipearellanom** [comment]
Perfecto, gracias
