### ISSUE TITLE
Limite de caracteres en descripcion de eventos

### ISSUE THREAD

**Issue by haarenas** [IIC2233/syllabus-2018-2#18]
En la descripcion de los eventos hay **limite de caracteres**?

Gracias de antemano.

**Comment by nachocontreras** [comment]
Hola!

No hay límite superior de caracteres para la descripción de los eventos. 
Por otro lado, si el evento no tiene descripción debe salir "sin descripción". Es decir, existe una cota inferior de 1 caracter o "sin descripción".

**Comment by haarenas** [comment]
Perfecto, muchas gracias.
