### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#180]
Hola, 
No entendí muy bien qué es el Readme, gustaría de tener una mejor idea para poder entregar el Readme de la tarea

**Comment by Drpinto1** [comment]
Saludos!
Se subió a todos sus repositorios, __no__ al Syllabus, en la carpeta de la tarea 0 un archivo _"Readme.md"_, con una guía detallada de como hacer tu readme y el mismo contiene una plantilla ordenada

**Comment by jeschuwirth** [comment]
En general el Readme es un archivo que le permite a un usuario que va a ocupar tu programa saber como funciona(lo básico que tiene que saber) junto con unos créditos al autor del archivo. Para razones del curso deben asumir que el usuario vamos a ser los ayudantes.

Se te entrega un Readme pre-creado con las partes que debería tener para facilitar la correccion de tu tarea, en la primera parte se deberá dividir el programa en las partes que se divide en el enunciado y decir que tanto lograste avanzar cada una de ellas y cuales hiciste a medias (y un porque), de este modo cuando corramos tu programa, si nos encontramos con un error nos tomará menos tiempo encontrar la parte del código que falló. 
En la parte de ejecución es básicamente decir cual de todos los archivos .py debemos ejecutar para que corra el programa.
En la parte de librerías se deben colocar todas aquellas que se utilizaron (especialmente aquellas que deben ser instaladas externamente, ya que sin ellas no podremos revisar el código, aquí igual van las librerias propias para saber que clases o funciones importaron de cual archivo .py.

Supuestos y consideraciones es cualquier comentario extra que desees agregar que le pueda ayudar al corrector a revisar tu tarea, (Supuse que los nombre de usuario están escritos con sólo minusculas y sin tildes). 

Eso es principalmente el readme, cualquier duda que tengas aún agregala a este mismo thread

**Comment by SergioGazali** [comment]
hola! subimos un archivo que reemplace el readme pre-creado o agregamos otro nuevo?

**Comment by rhanuch** [comment]
¡Hola @SergioGazali !

La idea es que rellenen y saquen lo innecesario (como por ejemplo supuestos en el caso de no hacerlos) del `README.md`✏️ que se encuentra en sus repositorios para que así estos sean ordenados y claros, por lo que no es necesario que agregues otro nuevo a menos que lo consideres necesario. 

Dicho lo anterior, te recomiendo fuertemente utilizar la plantilla entregada 😄.

¡Saludos! 🍀
