### ISSUE TITLE
Ejercicios Decoradores

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#184]
Hola!

Al hacer lo que pide el ejercicio 5

```python
@ejecutor(list)
def funcion_de_ejemplo(numero):
          return numero ** numero
print(funcion_de_ejemplo(3)) # Imprime [27]
```

No me imprime `[27]`, ya que al aplicar `list()` a un número me dice que no es un iterable. Cómo lo puedo manejar? No quiero hacerlo manual (si recibo `list()` entonces retornar ```[funcion(args)]```).

Gracias!

**Comment by fringlesinthestreet** [comment]
Hola @cacosandon 

Este fue un error de nosotros, está bien que se levante esa excepción. Intenta con el siguiente código:

```python
@ejecutor(lambda x: [x])
def funcion_de_ejemplo(numero):
    return numero ** numero
print(funcion_de_ejemplo(3)) # Imprime [27]
```

Con este nuevo _snippet_ debiese funcionar 😉.
