### ISSUE TITLE
Error commit Tarea 00 

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#185]
Ayer en la actividad hice un "git add --all" de desesperación por entregarlo a tiempo y por eso hice un "git push" con carpetas de la tarea 00 que no quería subir (datos no debería estar y data tiene archivos de prueba creados por mi). ¿Hay algún problema, o serán ignorados por haber subido esta "actualización no deseada" fuera del tiempo de entrega (que sería lo ideal)?

**Comment by Hernan4444** [comment]
Hola, cuando se hace la issue con el *commit a corregir", nosotros vamos a corregir lo que llevas hasta dicho commit, como el que hiciste ahora con `git add --all` es un commit posterior al indicado, no lo vamos a considerar.

Saludos ✌️
