### ISSUE TITLE
Duda diccionario por compresion Actividad

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#186]
Hola, en la actividad yo hice mi diccioanrio así:
```python
dicionario = dict()
    dicionario["a"] = "0"
    dicionario["r"] = "1"
    dicionario["q"] = "2"
    dicionario["u"] = "3"
    dicionario["e"] = "4"
    dicionario["t"] = "5"
    dicionario["i"] = "6"
    dicionario["p"] = "7"
    dicionario["o"] = "8"
    dicionario["s"] = "9"
    dicionario["1"] = "r"
    dicionario["2"] = "q"
    dicionario["3"] = "u"
    dicionario["4"] = "e"
    dicionario["5"] = "t"
    dicionario["6"] = "i"
    dicionario["7"] = "p"
    dicionario["8"] = "o"
    dicionario["9"] = "s"
    dicionario["0"] = "a"
    decodificado = list()
```

Lo que evidentemente no es funcional como se pedía. 
Probando un poco hice uno ahora:

```python
palabra = "arquetipos"
numeros = "0123456789"
generador_1 = zip(palabra, numeros)
generador_2 = zip(numeros, palabra)
diccionario_1 = {par[0]: par[1] for par in generador_1}
diccionario_2 = {par[0]: par[1] for par in generador_2}
print(diccionario_1)
print(diccionario_2)
diccionario = {**diccionario_1, **diccionario_2}
print(diccionario)
```

Mi duda es, esta manera es suficientemente funcional o como debería haber sido? Que no me acuerdo de como fue lo que mostraron en las soluciones.

**Comment by Mahund** [comment]
Hola!
Yo ocupé algo similar:
```python
from itertools import chain
key, values = "arquetipo", "123456789"
dicc = {
    x: y
    for x, y in chain(zip(key,values), zip(values,key))
}
```
No se si sirva, asi que me sumo a la consulta

**Comment by entamburini** [comment]
Hola!, 

@Kitaps, tu respuesta funcional hubiera servido porque es una actividad y entendemos que probablemente no se te ocurra la mejor de las soluciones. Se puede hacer mucho más corta como lo que propuso tu compañero @Mahund donde básicamente hizo lo mismo pero con ayuda del método `chain`.

De todas formas, felicitaciones por estar practicando, ahí está el secreto del éxito! Sigan así! 💪 
PD: Les edité sus comentarios porque me gusta que el código aparezca en colores :D
