### ISSUE TITLE
Tipo de dato para variables id: str o int

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#189]
Hola!
En el apartado __2.1.1__ se describe el id del pasajero como un int. Por otra parte, el apartado __2.1.3__ describe el id del vuelo como un string, en el __2.1.4__ ambos id son considerados como string.
Para efectos de implementación, creo que da exactamente igual asumir los id como string, asumo que no será necesario sumarlos entre ellos o algo que involucre números.
¿Existe alguna ventaja al asumirlos como enteros?
Saludos!

**Comment by jeschuwirth** [comment]
Saludos, 
Efectivamente ambos id pueden ser tratados todo el tiempo como strings, ya que no vas a necesitar sus valores numéricos, sin embargo igual puedes utilizar ambos como ints si te llegase a parecer más cómodo. No recomiendo hacerlo pasajeros como int y vuelos como string como dice el enunciado ya que eso sólo va a causar confusión.
Suerte con la Tarea :D
