### ISSUE TITLE
Bases de datos a abrir

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#190]
Hola!

En qué parte del programa le pedimos al usuario decidir por el tamaño de la base de datos, para así obtener el path?

**Comment by jeschuwirth** [comment]
Saludos!, eso queda a tu criterio, sin embargo debe quedar claro y especificado en el ReadMe, lo que te recomiendo es que el programa funciones por default con la base de datos mediana o pequeña y que al comienzo del archivo main.py se defina una varible: tamaño_base_datos = "medium", de modo que el abrir el archivo sea: with open(f"data/{tamaño_base_datos}/........","r") y que el corrector pueda cambiar rapidamente el string de la variable para abrir otra base de datos

**Comment by cilopez** [comment]
@cacosandon intenta probar inicialmente con las pequeñas , cuando estes terminando usa la base de datos grande para analizar si estas realizandolo en el tiempo correcto.

**Comment by RodrigoNazar** [comment]
@cilopez donde se especifican los "tiempos correctos"?

**Comment by cilopez** [comment]
@RodrigoNazar si ves en el feedback no existe puntaje por el tiempo, por ende poder realizar las consultas rápidamente es más un logro. Obviamente no te puedes demorar 2 minutos con la base small ni 10 minutos con la large para fijar rangos.
