### ISSUE TITLE
Forma consultas hechas por el usuario

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#191]
Cuando el usuario realiza una consulta, esperamos que escriba **literalmente** un string con forma de diccionario de la forma "{"nombre", [args]}" (o una lista de estas consultas) o en el main debemos preguntar esto por partes para luego crear dentro del programa un diccionario que luego tendremos como "input" con el cual trabajaremos?

**Comment by jeschuwirth** [comment]
Saludos, 
Queda a criterio suyo, siempre que se especifique en el Readme, recomiendo hacerlo como si el input fuera un diccionario en forma de string, por ejemplo: 
```Python
'{"filter_airports_by_distance": [{"load_database": ["Airports"]}, "SCQM", 31415.92]}'
```

**Comment by gnacrur** [comment]
En caso de hacerlo de la forma que recomiendas (o alguna parecida), aplicaría lo de las funciones de menos de 15 lineas para probar el input? Porque no se me ocurre como obligar al usuario a introducir un input tan complejo de forma compacta sin usar try, except.

**Comment by jeschuwirth** [comment]
puedes tener una función que retorne true si la key del diccionario es correcta, otra que haga lo mismo para sus argumetos y luego una tercera que ocupe las 2 anteriores y si ambas retornan true, entonces acepta el input, sino no. La filosofía "Do one thing and do it well" permite el uso de funciones dentro de otras siempre que estas estén justificadas y no sea sólo dividir una grande en dos más pequeñas.
