### ISSUE TITLE
Uso de loop while para main

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#192]
Se pueden usar loops como while para hacer que el programa no se caiga? estos ciclos permitirian preguntar al usuario hasta que ingrese un input en formato correcto, y notificar el error en caso contrario.

**Comment by cilopez** [comment]
~~Si, dale nomás~~

**Comment by rhanuch** [comment]
¡Hola @Cadagan ! 

El único `while` que pueden utilizar es el que fue subido ayer al repositorio ⚠️, el resto esta estrictamente **prohibido**, al igual que el uso de `for`, tal como fue publicado en el SIDING.

¡Saludos y suerte! 🍀

**Comment by Mahund** [comment]
@rihanuch tu comentario anula lo dicho en el anterior entonces?

En resumen solo se podra ocupar 1 while en todo el codigo?

**Comment by rhanuch** [comment]
@Mahund , sí
Esto está más claro en el anuncio publicado en el SIDING 😄
