### ISSUE TITLE
Header de db

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#193]
Podemos asumir que las columnas de las db seguirán siempre el mismo orden?

**Comment by fernandodediegoavila** [comment]
Hola!
No podrás asumir eso
Saludos y éxito!

**Comment by cacosandon** [comment]
Y podemos asumir que serán los mismos nombres? la base de datos **large** tiene header diferente a las otras bases de datos

**Comment by Gorgola22** [comment]
Pero como, si el header dice que es lo que tendrá cada columna. ¿O se refiere a otra cosa?

Gracias de antemano

**Comment by fernandodediegoavila** [comment]
Las columnas pueden cambiar de orden (por ejemplo, la que ahora está en la primera columna al corregir estará en la tercera). Esto es solo un ejemplo en todo caso.

**Comment by Fenho** [comment]
Creo que esto debería ser marcado como importante

**Comment by cacoos** [comment]
Yo tambien creo!

**Comment by rhanuch** [comment]
¡Hola!

Como norma general, **nunca** podrán asumir que el orden de las columnas que les entregamos será el mismo 😬. La única excepción fue la T00 debido a que no les permitíamos utilizar librerías que facilitaran la lectura de los datos.

A pesar de que suene terrible, **¡no todo está perdido!** 😲 Muchas veces (por no decir siempre) pueden encontrar __cosas útiles__ en las librerías permitidas al comienzo de la tarea (#188), simplemente es cosa de buscar y revisarlas. Por ejemplo una de las funciones de `csv` retorna un diccionario con `keys` (en este caso siendo los nombres de las columnas) y sus valores respectivos ordenados. En general, es cosa de ver qué herramientas les estamos entregando para poder facilitar su tarea (tampoco somos _taaaan_ malvados) 😅 

¡Mucha suerte en lo que queda de la tarea y ánimo! 🍀
