### ISSUE TITLE
Archivo Flights con error

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#194]
Hola!
El archivo `flights.csv`, tanto en la carpeta **medium** como en la carpeta **large**, presenta una línea en que el aeropuerto de llegada es "icao" en lugar del _icao_ real. Esto ocurre en el id `918` para `medium\flights` y en el id `32238` para `large\flights`.
Eliminé esas lineas de mis archivos para que no se cayera el programa, pero podremos asumir que las DB vienen limpias?

Saludos!

**Comment by cilopez** [comment]
Ni idea como apareció ese icao en la base de datos la arreglaré enseguida para que no existan problemas, Gracias @viantirreau. Y sí pueden asumir que las bases de datos no tendrán ese tipo de errores

**Comment by viantirreau** [comment]
Buenísimo, gracias!

**Comment by cilopez** [comment]
Ahí actualicé la base de datos, básicamente "icao" cambió por un icao real.

**Comment by diegovaras97** [comment]
Osea se puede asumir que siempre las bases de datos vendrán correctas en todo sentido?

**Comment by cilopez** [comment]
Si, puedes asumir eso
