### ISSUE TITLE
Header de archivos large

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#195]
Segun el PDF, el header de `airports.txt` en cuanto a latitud y longitud posee nombres _"lat"_ y _"long"_. Mientras que en la base entregada se llaman _"latitude_deg"_ y _"longitude_deg"_ respectivamente.
Con qué nombres trabajamos?

**Comment by cilopez** [comment]
Hola @cacosandon , trabaja con _"lat"_ y _"long"_, en small y medium es así,  ahora voy a actualizar los headers de large.
