### ISSUE TITLE
Consulta "favourite_airport"

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#197]
Al realizar esta consulta, me encontré que en algunos casos para un determinado pasajero no existe un único aeropuerto que sea el más visitado, si no más de uno.
En estos casos cual aeropuerto debiese tomar como el más visitado???

**Comment by jeschuwirth** [comment]
Hola, si dos aeropuertos fueron visitados el mismo número de veces, entonces queda a tu criterio cual de ellos entregas. Si puede recomendaría especificar en el readme para evitar problemas
Suerte !

**Comment by Banfanci** [comment]
Gracias, lo especificare en el readme.

**Comment by ariel-m-s** [comment]
Hola!

Y en el caso de que algún pasajero no tenga viajes asociados? Puedo hacer que el `value` sea `None`?

**Comment by jeschuwirth** [comment]
Saludos, 
te recomiendo que si el output debe ser una lista, entonces utilices una lista vacía,  o si es un string sea un string vacío, pero en el caso de los generadores no hay problema con usar None.
Suerte!
