### ISSUE TITLE
Consulta "passenger_miles"

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#198]
En esta consulta recibo generadores de pasajeros, vuelos y viajes, sin embargo me piden retornar un dict donde la key sea la id del pasajero y de value las millas acumuladas, sin embargo creo que me falta un generador de aeropuertos para calcular esto, dado que con los 3 generadores que recibo no tengo la información de lat y long para poder calcular las millas entre aeropuertos.

**Comment by rhanuch** [comment]
~~¡Hola @BBanfanci !~~

~~No, no es necesario recibir un generador con los aeropuertos 🛫, la consulta se puede realizar de~~ ~~igual manera. Lo que debes hacer es pensar en cómo conseguir los aeropuertos sin su~~ ~~generador y sin hacer el llamado a ellos mediante un parametro de esa función~~

~~¡Saludos y suerte! 🍀~~

**Comment by cacoos** [comment]
Aún así de alguna u otra forma se van a llamar a los aeropuertos o no? ya sea dentro de esa funcion o en otra que invoque dentro del scope. Me refiero a que quizás no se necesita input de usuario pero hay que tenerlos igual, no?

**Comment by Banfanci** [comment]
@rihanuch mmh mira la verdad no veo forma alguna de hacer lo que dices sin hacer algo "ilegal" en esta tarea, incluso ayer durante el horario de consultas sobre la tarea pregunte en voz alta y dijieron que si, faltaba un generador de aeropuertos tanto ahi como en furthest_distance. Y Digo que no veo una manera de hacerlo legalmente, dado que con lo que se me entrega en esa consulta solo puedo obtener el id de los aeropuertos pero no sus respectivas long y lat, y hacer algo como llamar a load_database dentro de la función a mi parecer es "ilegal" menos aún precargar una base de datos(dado que en el enunciado se explicita que no se puede hacer esto)

Saludos!

**Comment by bgsamilla** [comment]
Tengo el mismo problema en passengers_milles y en furthest_distance.

¿Entonces que hacemos?. Cargamos nosotros los aeropuertos con un generador para no ir contra las reglas ¿Estaría permitido?.
Porque es la única forma que veo de obtener los datos para calcular la distancia. 

O lo agregarán a los inputs como se dijo en la ayudantía de la tarea .... ?

Saludos!

**Comment by bgsamilla** [comment]
Otra pregunta sobre este método, dice que debemos retornar un diccionario con la persona como key, esto es la literal el objeto persona que estemos usando, o podemos usar la id como se pide en otros métodos?

**Comment by rhanuch** [comment]
A pesar de que se puede hacer sin los generadores, nos dimos cuenta que la dificultad de hacerlo de esta manera era mucho más elevada y no aportaba a la evaluación de la materia, por lo que **se puede agregar como parámetro** que recibe la función 😄 

De cualquier modo, voy a hacer un anuncio especificando mejor esto ahora ahora

¡Mucha suerte! 🍀
