### ISSUE TITLE
Consulta "popular_airports"

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#199]
Para calcular los más populares, consideramos solo los destinos, o también los aeropuertos desde donde partieron?
Y Cuando se refieren  "y retorna una tupla con los topn nombres de los aeropuertos más populares" se refieren a las id?(dado que en ninguna base de datos estan los nombres de estos), y de ser asi el generador de aeropuertos no estaria demás en esta consulta, dado que con vuelos y viajes podría obtener todo lo que necesito?

**Comment by cilopez** [comment]
Hola @Banfanci, en el enunciado dice _"... el aeropuerto más populares aquel que **recibe** a más gente"_, es decir el aeropuerto de destino 😅 . Efectivamente, conversaré esto con los ayudantes para ver si es que no es necesario recibir ese generador o retornar toda la información del aeropuerto, gracias por señalarlo 👍

**Comment by Banfanci** [comment]
hola @cilopez , me di cuenta que podria llegar a ser necesario aun cuando solo se deban devolver los id, dado que podria darse el caso en el cual en el generador de aeropuertos no nos entregan todos los aeropuertos, por ejemplo solo nos entregan los aeropuertos a menos de 40 millas nauticas del aeropuerto x, por lo que aqui no buscariamos el mas popular entre todos si no el más popular entre esos aeropuertos que estan a menos de 40 millas del aeropuerto "x"

**Comment by mericci** [comment]
En que quedo esto al final?, no estoy muy seguro si importa el generador de aeropuertos, ya que no tengo información de los vuelos que no están incluidas en el generados de vuelos.

Por otro lado, en el enunciado sale que hay retornar una tupla, pero en punto 3. popular_air.... ->LIST, aparece list, que debemos retornar?

**Comment by jncaceres** [comment]
Tengo la misma duda que @mericci

**Comment by bmorrisc** [comment]
Si no me equivoco, algo similar pasa con favourite_airport, porque sólo pide retornar un diccionario con las id de los pasajeros como keys. En ese caso, no sería necesario recibir un generador de los pasajeros porque sus ids están incluidas en el generador de viajes... No sé si es algo que no estoy viendo pero al menos como la tengo estructurada siento que no importa tanto el generador de pasajeros

**Comment by pablovejar** [comment]
Hola! @cilopez En el enunciado no queda tan claro que el aeropuerto que "recibe" es solo el de llegada, no lo dice explícitamente, es más, al leerlo inmediatamente pensé en ambos aeropuertos puesto que ambos reciben a los pasajeros.

**Comment by cilopez** [comment]
- @mericci @Banfanci  @jncaceres La consulta si va a recibir el aeropuerto, pero si pueden realizar la consulta sin el simplemente no lo ocupan. La va a recibir para que no existan problemas, ademas no cambia mucho.
- Retornen una lista, si ya lo implementaron como tupla, entonces señalenlo en su readme y hagan una referencia a esta issue
- @bmorrisc  Lo mismo que a tus compañeros, se recibe el argumento igual, si crees que no te sirve , simplemente no lo ocupas. 
- @pablovejar Nunca se dijo que recibe solo el de llegada, solo dije que el más popular se calcula a partir del que recibe más pasajeros.

**Comment by ararojas** [comment]
Hola! @cilopez en la issue #229 me dijeron que retornara una tupla.
¿A cual le hago caso?

**Comment by cilopez** [comment]
@ararojas puedes hacerlo de las dos formas, como no está claro en el enunciado. Señala cual hiciste nomás en el readme.
