### ISSUE TITLE
Cambio de nombre de usuario GitHub

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#20]
Hola!

Ayer cambié mi nombre de usuario de `GitHub`, hay algún problema con eso en relación al ramo? Tengo que notificárselo a alguien?

Saludos.

**Comment by Hernan4444** [comment]
@amartinezsilberstein si hay un problema 😢 , porque en este curso toda la información (incluido el nombre de tu repositorio y las notas) está utilizando tu antiguo nombre de github. Por esta vez actualicé el sistema y el nombre de tu repositorio de forma manual para que coincida con tu nuevo usuario.

**Importante**:  no cambien su nombre de usuario, esto solo los va a perjudicar al momento de recorregir porque ahí les solicitamos su usuario de github, pero el sistema tiene el antiguo usuario, no hará _match_ entre su solicitud y su evaluación corregida.

Saludos,
Hernán V

**Comment by ariel-m-s** [comment]
😬 Oops. Muchas gracias por arreglar el problema y por la información @Hernan4444 !
