### ISSUE TITLE
Comentarios y límite de lineas funciones

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#201]
¿Los comentarios cuentan en el máximo de 15 lineas por función? ¿Y los espacios en blanco?

**Comment by nachocontreras** [comment]
Hola!

No, no cuentan como líneas. 
Las 15 líneas son líneas de código.

**Comment by bgsamilla** [comment]
Si tengo una linea larga (mas de 80 caracteres) y la divido en 2 para seguir pep8 eso cuenta como 2 lineas o sigue siendo 1?

**Comment by nachocontreras** [comment]
Cuenta como 2 líneas.

**Comment by Marialuisaclaro** [comment]
El return cuenta también?

**Comment by nachocontreras** [comment]
Sí, el return cuenta.

**Comment by dlcartagena** [comment]
Cuenta la línea en que se define la función?
