### ISSUE TITLE
Agregar datos que reciben las consultas

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#202]
Hola! en las consultas se pueden agregar datos que estas reciban? Por ejemplo, hacer que reciban la variable "tamaño_base_de_datos" para poder abrir las bases de datos correctamente.

**Comment by cilopez** [comment]
Hola @kelseyfranken , no puedes. Te recomiendo crear una variable global en el programa tipo 
``
data_type = "large"
 ``
Así podrás cambiar más fácil el tipo de test al momento de abrir el archivo.
