### ISSUE TITLE
Generadores y funciones generadoras

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#203]
Al momento de definir una función, que procese una solicitud, por ejemplo "filter_flights" la cual recibe como parámetros "flights" que es un generador y "airports" que también lo es, se puede transformar uno de estos generadores a una estructura de datos almacenada en memoria? No se me ocurre como procesar la solicitud dado que al simplemente recorrer un generador para buscar la información este se "gasta".

**Comment by lily416** [comment]
Hola :)

No puedes transformar los generadores a estructuras de datos almacenadas en memoria, pero en cambio existen funciones que te permiten generar copias de un generador, como es el caso de la función `tee` de la librería `itertools`.

Éxito con la tarea 👋

**Comment by joaquinhernandezg** [comment]
Traté de hacerlo sin crear una estructura almacenada en memoria, la cantidad de operaciones es tremenda. 😢 . No puedo ocupar, por ejemplo, un diccionario, pero que esté hecho por comprensión y esté dentro del scope de la función?. El acceso a los datos es mucho más rápido que estar creando y recorriendo generadores una y otra vez.

**Comment by lily416** [comment]
Lo siento me exprese mal, solo se pueden usar estructuras que almacenan en memoria mientras sean hechos por comprensión. 

Disculpa el malentendido

**Comment by baaldana** [comment]
Hola, me queda la duda de si está permitido llamar directamente a la función "load_database()" , por ejemplo, si mi código requiere usar más de una vez algún generador que viene dado por el input de mi función.

**Comment by lily416** [comment]
@baaldana el problema de llamar directamente la función `load_database`, es que en funciones que no reciban este generador como input se estarían utilizando datos incorrectos, o mejor dicho, extras.

Un ejemplo sería:
```Python 
{"filter_flights": [{"filter_flights": [{"load_database": ["Flights"]},{"load_database": ["Airports"]}, "distance", ">", 200]},{"load_database": ["Airports"]}, "distance", "<", 400]}
```
La idea es que de este filter se obtengan todos los vuelos que viajan entre 200 y 400 millas, pero si al `filter_flights` de más afuera se le pasara `{"load_database": ["Arirports"]}` en vez del filter, solo se obtendrían los vuelos que recorren menos de 400 millas.

Ojala que eso responda tu duda.
Disculpa la tardanza
Saludos y éxito con la tarea 😄🍀

**Comment by baaldana** [comment]
@lily416 Entiendo, pero mi duda va por otro lado. Por ejemplo, si para la función `filter_flights` necesitara recorrer el generador `airports` que me entregan, más de una vez ¿existe alguna forma de clonar el generador? Lo digo porque hay inputs, como el de `passenger_miles` en que no necesariamente es el generador completo, sino algo ya filtrado, de modo que no puedo usar `load_database` para obtener otra "instancia" de ese generador. Es posible clonar el generador de alguna forma?

**Comment by bgsamilla** [comment]
Puedes usar
Itertools.tee(generador, n)
Retorna una tupla con n copias del generador

Saludos

**Comment by inveterate-cladocerus** [comment]
Hola @lily416, @BSamilla, tengo un par de dudas 

- ¿Se puede usar list(generador)?

- ¿En la Tarea se pueden crear diccionarios o estructuras de datos almacenados en memoria que no sean por compresión? Lo pregunto porque en el enunciado de la Tarea lo que se restringe es el uso del for y while a contenedores por compresión, pero no dice que no se puedan crear estructuras de datos almacenados en memoria que no sean por compresión.

- ¿Se puede usar sorted(lista)?

Saludos :)

**Comment by bgsamilla** [comment]
Tengo la misma pregunta, tambien considero que no hay nada que te prohiba usar estruccturas que no esten hechas por compresion al menos no directamente, aunque la restriccion de uso de loops dificulta crearlas y es claramente mas conveniente usar compresion  .....

En cuanto a lo de list muchos lo han preguntado pero creo que a nadie le han contestado, en lo personal no encuentro diferencia en poner list(generator) a [x for x in generator] ya que obtienes el mismo resultado

PD: Si me mencionaste por que crees que soy ayudante, no lo soy xD

**Comment by inveterate-cladocerus** [comment]
XDDDDDDDDDDDDDDD juraba que eras ayudante @BSamilla , pero gracias! Me sirvió mucho tu respuesta :)

**Comment by lily416** [comment]
@Prochotito 

1. Sí es válido el uso de `list(generador)` y equivalentes.
2. Puedes crearlas mientras no incumplas las **consideraciones de programación funcional** (punto 5.1). 
    Es decir, es válido que crees `lista = []`, pero el problema es cómo ingreses los datos, ya que no puedes usar _for_ ni _while_ fuera de generadores, funciones generadoras y lo especificado en el enunciado. 
   Siento que es mejor que utilices de `list(generador)` en el caso de que fuera necesario.
3. Sí puedes usar `sorted()` 👍 

Ojala que todo quede claro
Éxito con la tarea 🍀 

PD: @BSamilla gracias por también responder, se aprecia que ayuden a sus compañeros cuando tienen dudas 😄
