### ISSUE TITLE
Duda type hinting

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#204]
Hola! Tengo una duda, ¿con usar el formato type hinting se refieren a que al momento de definir una función que me permita realizar una consulta, esta se escriba con ese formato (type hinting)? Por ejemplo, acá explican como definir funciones con ese formato: https://docs.python.org/3.6/library/typing.html
Saludos.

**Comment by cilopez** [comment]
Hola @Prochotito , en el enunciado solo usamos el type hinting para que quede más claro que recibe cada función que tienen que desarrollar, no explicitamos que deben usarlo.  Si quieres usarlo utiliza el formato que anexaste.

salu2
