### ISSUE TITLE
Memoria v/s Rapidez

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#205]
Hola!

Segun la issue #203 no se pueden usar estructuras que utilicen memoria. Ahora, si trabajo solo con generadores se demora **mucho** comparado a utilizar estructuras que utilizan memoria pero trabajan eficientemente. Mi pregunta es, qué priorizo?
PD: Además, ¿efectivamente **no** puedo usar estructuras que utilicen memoria?, lo pregunto porque en el enunciado no se menciona y obviamente se vuelve mas complicado.

**Comment by viantirreau** [comment]
Complementando tu pregunta @cacosandon:
Según el punto `5.1.3` del enunciado, se puede usar 
> Contenedores (e.g. listas, diccionarios) por comprensión

por lo que asumo que se pueden cargar los generadores (de manera local, dentro del _scope_ de cierta función) en alguno de estos contenedores por comprensión. De lo contrario, como tu dices, se tendría que recorrer los generadores una cantidad extremadamente ineficiente de veces para encontrar los datos que, con otras estructuras, se encuentran en **O**(1) 🤔
