### ISSUE TITLE
Error de encoding al abrir base de aeropuertos

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#206]
Hola, al intentar abrir la base de datos de los aeropuertos mediana y grande, me aparece el siguiente error :UnicodeEncodeError: 'cp932' codec can't encode character '\ufeff' in position 0: illegal multibyte sequence. 
En mi funcion al abrir el archivo con with open ya puse encoding = 'utf-8' , y aún así me lanza el error. Cabe destacar que todas las demás bases de datos en todos los tamaños me funcionan menos esas 2. Alguna idea de que pasa ?

**Comment by viantirreau** [comment]
@InfiniteDreamX  Revisa el #194 :wink:

**Comment by jfacuse** [comment]
Lo ví ! Y tengo actualizadas ya las bases de datos, pero sigo con el mismo error. O aún no las cambian y confundí las cosas jajaja

**Comment by cacoos** [comment]
@InfiniteDreamX intenta usando `utf-8-sig` en el `encoding`

**Comment by jfacuse** [comment]
Ahi me funciona , muchas gracias!

**Comment by fernandamansilla** [comment]
utf-8-sig deberia funcionar en todas las versiones de python? le especifico ese encoding y lo ignora y revisa como si fuese solo utf-8 :(
