### ISSUE TITLE
Archivo gitignore

### ISSUE THREAD

**Issue by haarenas** [IIC2233/syllabus-2018-2#207]
En el enunciado dice que se deben ignorar los archivos .csv, esto haria que las carpetas /data/small || medium || large se suban vacias al repositorio. No seria mejor ignorar el directorio data/...?

**Comment by Drpinto1** [comment]
Saludos!
En general, Github automáticamente ignora las carpetas vacías, por lo que lo que mencionas no debería ser un problema. Habiendo dicho esto, puedes decidir ignorar la(s) carpeta(s) en lugar de los archivos si así lo prefieres, lo importante es que no se suban las bases de datos _.csv_ y, obviamente, que no ignores archivos que afecten la funcionalidad de tu código.

**Comment by fringlesinthestreet** [comment]
Hola @haarenas 

Si decides no subir la carpeta `data/`, recuerda probar tu código para ver si funciona **sin la carpeta en el directorio**. Esto porque puede levantar una excepción `FileNotFoundError`. 

Si deseas subir la carpeta vacía, puedes crear dentro de la carpeta `data/` un archivo `.keep` para que así _git_ reconozca la carpeta. ¡Cualquier duda pregunta nomás!
