### ISSUE TITLE
Máximo de lineas por funcion

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#208]
Hola, quería saber si lo de que las funciones tengan un máximo de 15 lineas también aplica para la definición de las consultas o no. Gracias.

**Comment by IchottMano** [comment]
@gnacrur Hola!

Efectivamente, ahí también aplica el máximo de líneas.

Saludos!

**Comment by haarenas** [comment]
Yo tengo otra consulta al respecto, si hay una funcion B con 10 lineas que esta dentro de una funcion A con 12 (sin contar las lineas de B), para efectos practicos la funcion A tendria 22 lineas o solo 12?

**Comment by IchottMano** [comment]
@haarenas Hola!

Se miden sólo los largos de la función, sin importar el largo de funciones dentro de otra, por lo que la función A sólo tendría 12 líneas.

Saludos!

**Comment by amartinezsilberstein** [comment]
Hola!

Los comentarios que se encuentren "dentro" de la función cuentan como líneas de la función (para el cálculo de su largo)?
