### ISSUE TITLE
Uso de "loops"  en expresiones generadoras

### ISSUE THREAD

**Issue by Tngarrido** [IIC2233/syllabus-2018-2#209]
Hola, en la parte del enunciado donde indican el uso permitido de "loops" (5.1) se menciona: expresiones generadoras, esto se refiere solo a cuando defino un generador por comprension o también a que puedo recorrer un generador ya definido, gracias de antemano.

**Comment by jeschuwirth** [comment]
Hola!, no entiendo tanto la pregunta, pero creo poder contestarla, una expresión generadora crea una estructura por compresión:
`generador = (dato for dato in otro_generador)`
por lo que efectivamente puedes recorres un generador ya definido, sin embargo esto siempre es para generar por compresión.
Ojalá haya respondido tu consulta, suerte en la tarea!
