### ISSUE TITLE
Error en archivo flights-passengers

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#210]
Hola!
Me encontré con que al menos en la carpeta small, el archivo flights-passengers tiene pares repetidos. Por ejemplo (0,1) y (1,6). Esto querría decir que una persona viajó 2 veces en el mismo vuelo (misma fecha). Eso está bien o deberíamos eliminar los repetidos de la base de datos?
Gracias!

**Comment by jeschuwirth** [comment]
Hola, revisé las bases de datos y alguien debió haberlas arreglado o estaban bien, pero no encontré los errores que dices. Revisa de nuevo las bases de datos y si el error sigue estando comenta nuevamente especificando un poco más donde esta el error.

**Comment by Franco1605** [comment]
puede pasar que esté en dos líneas el mismo valor? Por ejemplo, en el archivo flights-passengers, de la base de datos small, en la línea 9 y 10 aparece (0,35) dos veces (una en cada línea, por supuesto). Y así sucede en varias líneas más...

**Comment by jeschuwirth** [comment]
Eso no debería pasar, por ahora pueden ignorar los datos repetidos, pero en la noche voy a actualizar la base de datos para que no eliminar lo repetidos. Gracias por avisar

**Comment by BenjaminRubio** [comment]
Esto debería estar marcado como importante. Después de todo es un error en la base de datos que no se informó.

**Comment by Fenho** [comment]
Los archivos no están actualizados, en cambio se subió otro archivo (flights_passengers2.csv). ¿Ahora usamos este archivo nuevo o esperamos a que actualicen el archivo original? (relevante para la ruta).

**Comment by jeschuwirth** [comment]
se subio el archivo flights_passengers2.csv para evitar problemas si alguien ya habia terminado su tarea con la base de datos anterior, recomiendo usar la 2 si aún tienen tiempo (así se ahorran problemas con los repetidos), sino ocupen la normal. De todos modos es recomendable escribir en el Readme cual de las 2 usaron.
