### ISSUE TITLE
No puedo ver el diagrama de AY04

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#212]
Hola! estuve revisando la solución de la ayudantía de esta semana y en la parte que  debería estar el diagrama de clases me aparece esto: 
![hola](https://user-images.githubusercontent.com/42187498/45120114-99685480-b133-11e8-86f4-289c7641d3b5.jpg)
alguien le podría sacar foto y comentarla por acá por favor! :)

**Comment by entamburini** [comment]
Hola!, 

Se nos debió olvidar subirlo, perdón 🙃 
Ahora está subido y comprobé que se puede ver! :D
