### ISSUE TITLE
"filter_flights" 

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#213]
Cuando se hace esta consulta, y es con respecto a distancia, entre que aeropuertos se comparara para sacar la distancia??, uno saldra de iterar el generador con todos los vuelos, pero el otro cual deberia ser??

**Comment by Fenho** [comment]
Los vuelos son entre dos aeropuertos, tienen una columna airport_from y otra airport_to, así que se compara entre esos dos.

**Comment by marcotroncoso** [comment]
Ya entendi, gracias gracias.

**Comment by Cadagan** [comment]
Si mi funcion de esta busqueda me retorna un objeto de tipo filter (class 'filter'), cuenta como que retorno un generador? o tenemos que llegar al punto en que cuando se aplique la funcion type(funcion_que_retorna_generador_con_lo_buscado) retorne la expresion "class 'generator' "?
