### ISSUE TITLE
Formato salida generadores

### ISSUE THREAD

**Issue by BenjaminRubio** [IIC2233/syllabus-2018-2#214]
Para las consultas que retornan generadores, cuando dice que deben ser "de la misma forma de la base de datos especificada" se refiere al mismo formato de valores separados por coma de los archivos? O da lo mismo y puedo ir retonando como una estructura de datos a mi elección?

**Comment by jeschuwirth** [comment]
Hola,
para leer los datos de los archivos .csv siempre se ocupa la función load_database(), por lo que todas tus funciones que retornen generadores deben retornan la misma estructura de datos que esta función. No es necesario que se ocupe la coma de los archivos sino que puedes usar las que prefieras.
Suerte!
