### ISSUE TITLE
Elementos que reciben "passenger_miles" y "furthest_distance"

### ISSUE THREAD

**Issue by rhanuch** [IIC2233/syllabus-2018-2#215]
La consulta `furthest_distance` y `passenger_miles` podrán aceptar un generador de los aeropuertos existentes, dejándolas como 
```Python
passenger_miles(
    passengers: Generator, 
    airports: Generator,
    flights: Generator, 
    travels: Generator
    ) -> dict

furthest_distance(
    passengers: Generator,
    airports: Generator,
    flights: Generator, 
    travels: Generator, 
    icao: str, 
    n: int
    ) -> list
```
¡Éxito en la tarea! 🍀 

----
EDIT
Cambié el orden en que se recibe `airports: Generator` para que sea consistente con lo que sale en el archivo de `queries`

**Comment by Banfanci** [comment]
@rihanuch , en furthest_distance al agregar airports despues de n(el cual por default es 3) me tira un syntax error:,
"def furthest_distance(passengers, flights, travels, icao, n=3, airports): 
SyntaxError: non-default argument follows default argument"...

Entonces mi pregunta es ¿podemos poner airports antes que n?

Saludos

**Comment by rhanuch** [comment]
¡Hola @Banfanci !

Sí, si pueden. No hay ningún problema con eso 😄

¡Saludos y suerte! 🍀

**Comment by rhanuch** [comment]
Actualicé la función por consistencia

**Comment by Banfanci** [comment]
@rihanuch  en "queries.txt" lo llaman asi...

```Python
{"furthest_distance": [{"load_database": ["Passengers"]}, {"load_database": ["Airports"]}, {"load_database": ["Flights"]}, {"load_database": ["Travels"]}, "04IA", 5]}]
```

primero passengers luego airports, por que nos guiamos entonces??? el archivo o esta issue?

**Comment by cilopez** [comment]
@Banfanci Rodrigo edito el comentario, para que te fijes

**Comment by Banfanci** [comment]
@cilopez lo edito, pero si te fijas, el orden no es consistente con el entregado en queries.txt... dado que en el archivo "Airports" se encuentra despues de passengers y no antes como se indica en esta issue.
Y también pido disculpas, siento que ya he molestado mucho con el tema.

Saludos!!!

**Comment by rhanuch** [comment]
¡Hola @Banfanci !

Mala mía, lo cambio ahora, ¡gracias por avisar!

¡Saludos! 🍀
