### ISSUE TITLE
"airport_passengers"

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#216]
Para este método debemos considerar a los pasajeros de llegada, de salida o ambos?

No me queda claro con lo que dice en el enunciado.

Saludos!

**Comment by jeschuwirth** [comment]
Saludos, al final de la descripción de la consulta sale especificado:
![image](https://user-images.githubusercontent.com/37160256/45128298-a85eff00-b153-11e8-837a-964a525e15d2.png)
O sea que se consideran ambos.
Suerte!
