### ISSUE TITLE
maximo de lineas funciones

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#217]
Hola!
Para las 15 lineas maximas de las funciones, cuando tengo que separar una linea en 2 o 3 por los requerimientos de PEP8, ¿cuenta como la cantidad de lineas que se ven o como una linea?

**Comment by IchottMano** [comment]
@ararojas Hola!

Cuando separas líneas por PEP8, se cuenta la cantidad de líneas final, es decir que no se cuenta como una sola línea.

Saludos!
