### ISSUE TITLE
Problema archivo passengers

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#218]
Hola, tengo problemas para almacenar como tuplas los datos de passengers en cualquiera de sus tamaños (small, medium, large) y no tengo este problema con los otros archivos. Me aparece este error: 

in namedtuple
    'keyword: %r' % name)
ValueError: Type names and field names cannot be a keyword: 'class'

**Comment by IchottMano** [comment]
@Prochotito Hola!

El problema es que intentas llamar a cierto atributo de tu namedtuple "class" la cual es una palabra especial en python reservada para definir clases, por lo que tendrás que de algún modo cambiar esta palabra para que pueda ser aceptada como atributo de namedtuple.

Saludos!

**Comment by inveterate-cladocerus** [comment]
Gracias!!!!
