### ISSUE TITLE
Identificador para los eventos

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#22]
Hola, me surgio una duda, si utilizara identificadores unicos para diferenciar los eventos, seguiria siendo necesario que no puedan haber mas de 1 evento con el mismo nombre y fecha ? Ya que podrian ser diferenciados por el id, no tendria mucho sentido que existiera esa restriccion (y ademas si un sistema de calendarios grande no permitiera ese tipo de topes seria un muy mal sistema)

**Comment by cilopez** [comment]
Puedes desarrollarlo de esa manera que es más natural, si lo haces mencionalo en tu _readme_ y no existirán problemas 😄
