### ISSUE TITLE
Interpretación de Furthest Distance

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#220]
Hola!
En el enunciado, `furthest_distance`:
>Retorna una lista ordenada de forma decreciente con los n pasajeros
que pasaron por el aeropuerto cuyo destino final está más lejos de este.

Tengo 2 interpretaciones posibles para esta función:

1. Encontrar todos los vuelos que comienzan en este ICAO y terminan en uno lejano `->` los n pasajeros cuyos vuelos (de los encontrados anteriormente) tienen mayor distancia (esto por la parte de _"cuyo destino final está más lejos"_)
2. Encontrar el aeropuerto más lejano a este ICAO entre el generador de aeropuertos pasado como  argumento, independiente de si existe un viaje que conecte el ICAO entregado como argumento con dicho aeropuerto más lejano `->` listar los n pasajeros con vuelos de mayor distancia, en que el destino final sea ese aeropuerto más lejano, pudiendo ser el aeropuerto de origen el mismo pasado como argumento u otro, sin importar la distancia recorrida en este vuelo en particular, sino entre el aeropuerto de destino y el ICAO dado.

¿Es alguna de estas la forma correcta de interpretarlo? Si no es así, agradecería me pudieran explicar con más detalle.
Saludos!

**Comment by jeschuwirth** [comment]
Hola!
la forma correcta de leer la consulta es la primera, se busca el aeropuerto más lejano del ICAO que te dan

**Comment by viantirreau** [comment]
Perfecto, muchas gracias!

**Comment by bgsamilla** [comment]
En furthest_distance si tenemos repetido el pasajero dentro del top n que hacemos?
Lo colocamos repetido?

La posibilidad de que pase es remota, pero puede pasar

**Comment by jeschuwirth** [comment]
vamos a subir una base de datos donde no se pueden repetir pasajeros en el mismo vuelo (esto no debería pasar nunca), así que no te preocupes por eso

**Comment by joaquinhernandezg** [comment]
Que sucede si 10 pasajero viajan al aeropuerto mas lejano y me dan n=3? Debo retornar cualquiera de los 10?

**Comment by mericci** [comment]
Que pasa si un pasajero toma dos vuelos distintos, que salen del mismo aeropuerto, y ambos recorridos están dentro de los n viajes mas lejanos, se podria repetir el pasajero, solo nos quedamos con el recorrido mas largo?

**Comment by cilopez** [comment]
@joaquinhernandezg Si  cualquiera de los 3

**Comment by Coolgatty** [comment]
No me queda claro como se supone que ordenemos decrecientemente una lista con pasajeros
