### ISSUE TITLE
Comparación de fechas con datetime

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#221]
Hola! En la parte **3.1** del enunciado, no me queda clara la sugerencia que hacen de no guardar las fechas como objeto datetime. Por ejemplo, ¿es válido convertir 2 fechas a datetime para compararlas dentro de un filter ? O cada vez que se convierten a datetime dentro de un filter quedan utilizando espacio en la memoria, y por lo tanto sería mejor usar los "ticks del computador" que sugieren en vez de convertir las fechas a datetime? 
Además, no encuentro en qué momento es necesario guardar las fechas en la memoria, (aparte quizás en el archivo output.txt). 
Saludos!!

**Comment by rhanuch** [comment]
¡Hola @InfiniteDreamX !

Cuando tu defines una variable, ya sea de scope local o global, estás utilizando espacio en la memoria, el cual, _eventualmente_ es limpiado por el `garbage collector`. El problema es que asignar el espacio para un objeto es muy "caro", por lo que es mejor trabajar con los "ticks" o algo similar para evitar este problema de almacenamiento 😄

En esencia la idea detrás es la siguiente:
```Python
import datetime
import sys

mi_objeto_datetime = datetime.datetime.now()
mis_ticks = # alguna manera de convertir mi_objeto_datetime a ticks 

sys.getsize_of(mi_objeto_datetime)
# >> 48
sys.getsize_of(mis_ticks)
# >> 24
```

Considerando esto, ahora debes tener en mente que la cantidad de veces que vas a tener que instanciar objetos del tipo `datetime` son muchas, por lo que ahorrar un 50% de memoria por cada uno de ellos es harto y así no usas espacio innecesario en la RAM y potencialmente no colapsas el computador de tu corrector 😅

¡Ojalá con eso se entienda!

¡Saludos y suerte! 🍀 

----

 PS: Sí, a mi una vez me pasó corrigiendo que me apagaron mi computador porque la tarea consumió toda la memoria 🙃 

PS 2: Más de una vez me dejaron pegado el computador y tuve que hacer un "Hard Reset" 💻
