### ISSUE TITLE
Parametros de consultas a prueba de inputs

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#222]
Nuestro programa tiene que ser a prueba de inputs en cuanto a los generadores que se entregan?
Por ejemplo, en vez de entregar el generador de _passengers_ al argumento passengers, entregar un generador de _airports_ (ya que en este último caso el programa se caería).

**Comment by jtcaraball** [comment]
~Sí, tu programa no debe caerse si el usuario se equivoca al momento de ingresar un input.~ 
Saludos!

**Comment by NicolasCabello** [comment]
@jtcaraball Tengo una duda entonces, es que en el enunciado sale lo siguiente:
> Puede asumir que las consultas siempre estarán bien escritas, sin embargo, su programa no debe caerse si las opciones del menú son ingresadas erróneamente.

Entonces a que se refieren con que las preguntas estarán bien escritas? que los inputs estarán correctos, pero no quizas en el correcto orden o no? 😢

**Comment by agustinespildora** [comment]
up

**Comment by cilopez** [comment]
Hola @cacosandon @agustinespildora  @NicolasCabello porfavor lean #231
