### ISSUE TITLE
Retorno de consultas

### ISSUE THREAD

**Issue by carajila** [IIC2233/syllabus-2018-2#223]
Para las consultas que retornan otra base de datos se pide que devuelvan un generador con los vuelos, personas u otros, según consulta, que cumplan con la condición deseada. ¿El generador a retornar debe tener todas las características de cada vuelo, persona u otro, o se puede retornar solo el id de los que cumplan la condición?

**Comment by jtcaraball** [comment]
La idea de que una función retorne un generador es que luego puedas usarlo en otras consultas. Por ejemplo, si quieres consultar por las millas acumuladas de los pasajeros que volar a un aeropuerto entre dos fechas especificas, necesitas primero filtrar los pasajeros y luego calcular sus millas acumuladas. Por lo que no, no puede entregar solo el id, tiene que entregar toda la información de la entidad.

**Comment by carajila** [comment]
Perfecto, muchas gracias!!

**Comment by Cadagan** [comment]
Y si mi consulta retorna un objeto de clase "filter" (la funcion type en el objeto retorna: class "filter"), si bien filter retona un generador, cuenta como valido? o debe retornar algo que al aplicar la funcion type retorne (generator)?
