### ISSUE TITLE
Funciones generadoras

### ISSUE THREAD

**Issue by ninifdr** [IIC2233/syllabus-2018-2#224]
Hola! Tengo una duda sobre lo que es legal/ilegal hacer dentro de las funciones.
Que pasa si por ejemplo en filter_passengers(passengers, flights, travels, icao, start, end) recorro el generador passengers por lo tanto este "desaparece", entonces puedo llamar denuevo a load_databaste dentro de la función?
Y otra cosa, puedo además inventar otras funciones dentro de las funciones generadoras? Por ejemplo una función get_distance(airport1, airport2) que me retorne la distancia entre dos aeropuertos, que esté definida fuera de la función generadora?
Gracias!

**Comment by jtcaraball** [comment]
Si necesitas recorrer múltiples veces un grupo de items quizás te resulte útil guardarlos como una lista por comprensión.
En cuanto a las funciones auxiliares, si miras el punto 5.2 vas a ver que ninguna de tus funciones puede tener más de 15 lineas 😱. Así que sí, puedes definir cuantas funciones como encuentres necesario.
Saludos!

**Comment by ninifdr** [comment]
@jtcaraball pero no es "ilegal" meter todo mi generador de aeropuertos en una lista por compresión?

**Comment by jtcaraball** [comment]
Si tu función necesita recorrer varias veces un conjunto de ítems, no es ilegal usar una lista por comprensión como iterable.

**Comment by Marialuisaclaro** [comment]
y es legal usar list(generador)?
