### ISSUE TITLE
output funcion airport_passengers

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#225]
Hola!
En la funcion airport_passengers dice que hay que retornar el conjunto de los pasajeros (no id de los pasajeros cm sale especificado en otra funcion).
Hay que retornar el nombre del pasajero? 
Me entra la duda porque como el output es un set, si hay dos pasajeros llamados iguales se considerarían como uno solo.
Lo mismo para la funcion passenger_miles y furthest_distance.
Gracias!

**Comment by FJavierOss** [comment]
Hola,

Tienes que retornar como minimo el nombre + el id de los pasajeros, para esto puedes agruparlo en la estructura de datos que estimes conveniente para luego ingresarlo al set que será el output. Espero haber respondido tu duda. Mucha suerte en tu tarea :smile: 

Saludos

**Comment by BFFV** [comment]
¿En el caso del set y lista entonces se debe retornar al menos el nombre y id de cada pasajero?
¿Y en el caso de passenger_miles que devuelve un diccionario no será mejor usar los ids como keys solamente?
