### ISSUE TITLE
Uso lista de compresión

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#226]
Si tengo un diccionario donde inicialmente el value de cada key es una listas vacías, ¿es legal hacer una lista por compresión que lo que hace es agregar cosas a las respectivas listas?

por ejemplo:
```Python
diccionario ={'id':[]}
[ diccionario[id].append(p) for p in generador]
```

Muchas gracias!

**Comment by fgbruna** [comment]
El método `append` no retorna nada,o lo que és equivalente(en `python`), retorna `None`, por lo tanto tu lista tendría...🤔

**Comment by mericci** [comment]
No se usa, solo sirve para agregar cosas a otra lista... eso se puede hacer?, en realidad agrega cosas dadas ciertas condiciones

**Comment by fgbruna** [comment]
No deberías tener que recurrir a eso, por lo que intentas hacer, creo que te serviría recordar que puedes hacer iterables por comprensión con la siguiente sintaxis:
```python
x = [1, 2, 3, 4]
y = [[], [], []]
l = ((cosa, ([] + z*x)) for z in x for cosa in x)
print(list(l)) 
# [(1, [1, 2, 3, 4]), (2, [1, 2, 3, 4]), (3, [1, 2, 3, 4]), (4, [1, 2, 3, 4]), (1, [1, 2, 3, 4, 1, 2, 3, 4]),...
```
Es decir, sacando cosas de varios iterables a la vez (:

**Comment by mericci** [comment]
Lo que yo tengo es esto, la verdad trate de hacer algo con lo que me dices,
pero en cada for del diccionario la lista parte de nuevo porque no tengo
donde guardar el valor, y no tengo numeros para poder multiplicar. Esto me
esta funcionado, pero no se si esta permitido realizarlo de esta forma.


Muchas gracias, saludos!

**Comment by rhanuch** [comment]
¡Hola @mericci !

Parte de la gracia de las EDD por comprensión es que se pueden anidar, por ejemplo

```Python
mi_dict = {posicion: [numero for numero in range(20)] for posicion in range(2)]}
```

¡Suerte! 🍀

**Comment by jfacuse** [comment]
Tengo una duda parecida a la de @mericci. Por ejemplo si yo quisiera crear mi dict de la forma que propone @rihanuch , por cada elemento nuevo de mi_dict tendria que recorrer completamente el generador que en el ejemplo era range(20) . En cambio si lo hiciese de la forma que pregunto @mericci, sólo tendría que recorrer 1 vez el generador, lo cual sería mucho más eficiente. (O tambien hacerlo de una forma como for v, id in generador: dic[id].append(v)) Entonces por eso creo que sería mejor usar el método de @mericci para eso.

Por otro lado, buscando en internet (https://stackoverflow.com/questions/3749512/python-group-by) encontre que tambien se podía hacer esto mismo utilizando gruopby de itertools, pero para esto el input (en este caso lo que entrega el generador) necesitaba estar ordenado por los ids. Viendo las bases de datos (al menos flights y flights-passengers, que son las que utilizaria) están ordenadas por id, pero es posible asumir que en la corrección será así ? 
Perdón por la pregunta larga y de antemano muchas gracias!

**Comment by rhanuch** [comment]
Lamentablemente no puedes asumir eso 😔

**Comment by jfacuse** [comment]
OK perfecto. Y con respecto a lo primero, entonces se puede usar la lista por compresion para rellenar el dic como lo pusieron en el primer comentario ?
Para ejemplificar, si utilizo esa forma en mi codigo para la consulta favourite_airport la consulta se demora 10 segundos con las bases de datos large, mientras que si lo hago anidando se demora +30 minutos(lo corte antes porque ya era mucho tiempo)

**Comment by mericci** [comment]
@InfiniteDreamX  no pruebes mas de los 30, yo lo deje corriendo toda la noche y no paso nada.
(Funciona, para la medium se demora 4 min)

**Comment by rhanuch** [comment]
@InfiniteDreamX , debes hacerlo de manera funcional 😬 
@mericci 😐
