### ISSUE TITLE
Programacion funcional

### ISSUE THREAD

**Issue by agustinespildora** [IIC2233/syllabus-2018-2#227]
En el caso de que quiera llamar una función 1, previamente definida, dentro de una función 2, ¿es necesario incluir la función 1 en los argumentos de la función 2 para cumplir con el formato de programación funcional, aunque funcione sin tener que pasársela como argumento?

**Comment by vaguila95** [comment]
Hola @agustinespildora 

Si te refieres a algo como:

```python
def func1(algo):
    return algo

def func2(otro):
   return func1(otro) + otro
```
No sería necesario 😄 

Salu2
