### ISSUE TITLE
consulta load_database

### ISSUE THREAD

**Issue by tomasmetroy** [IIC2233/syllabus-2018-2#228]
En esta consulta, en qué momento se ingresa si quiero retornar la base de datos correspondientes a la categoría small, medium o large?

Gracias de antemano,
saludos

**Comment by FJavierOss** [comment]
Hola,

Esto ya esta respondido en la #190 
Mucha suerte en tu tarea :smile: 
Saludos

**Comment by tomasmetroy** [comment]
Gracias!
