### ISSUE TITLE
Duda creación cadena aleatoria

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2233/syllabus-2018-2#23]
En el punto 3.5, paso 3, tengo una duda respecto al enunciado el cual dice  "Luego, se crea la cadena aleatoria que consiste de una secuencia de diez dı́gitos elegidos al azar entre
0 y 9. Para descifrar el mensaje esta cadena aleatoria es obtenida de los primeros 10 elementos del
mensaje a descifrar.". Mi duda es a que formato sobre los elementos se esta hablando

**Comment by nachocontreras** [comment]
Hola!

A que te refieres con: ``a que formato sobre los elementos``

**Comment by arbiocanpion** [comment]
En verdad lo que no entiendo, es como realizo la cadena aleatoria, porque indican esto "Para descifrar el mensaje esta cadena aleatoria es obtenida de los primeros 10 elementos del
mensaje a descifrar." y le he dado varias vueltas a esa oracion pero no la comprendo, te agradeceria si me pudiesen dar un ejemplo

**Comment by nachocontreras** [comment]
La cadena aleatoria es una secuencia de diez dígitos al azar entre 0 y 9. Esta se usa para codificar el mensaje. Y como se establece en el paso 7: antes de enviar se une la cadena aleatoria al mensaje codificado.

Ahora, para descifrar el mensaje se debe utilizar la cadena aleatoria, que serían los diez primeros elementos del mensaje recibido.

Ej: mensaje original: hola
Cadena aleatoria: 1234567890
Mensaje codificado: secreto
Mensaje a enviar: 1234567890secreto

Al decodificar los 10 primeros elementos serían 1234567890, la cadena aleatoria.

Saludos!

**Comment by arbiocanpion** [comment]
Muchas Gracias!

**Comment by mericci** [comment]
Aqui se puede importar random al programa?

Saludos!
