### ISSUE TITLE
furthest distance

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#230]
Hola!
No entiendo muy bien esta función. Cuando dice "destino final" ¿se refiere a el aeropuerto al que llega un vuelo que parte desde el icao pedido? En este caso, todos los pasajeros de el vuelo que llega más lejos tendrían igual "valor". O hay que ver el ultimo destino al que llegó un pasajero que pasó por ese aeropuerto (fijandose en la fecha, no necesariamente que venga directo desde el aeropuerto pedido).

**Comment by daniellyonvald** [comment]
Tengo la misma duda; No se, si con destino final, se refieren al último aeropuerto de los pasajeros en función de las fechas de vuelo, o si el pasar por el aeropuerto, se refiere a aeropuerto de origen y destino final es el aeropuerto de destino

**Comment by daniellyonvald** [comment]
Tengo la misma duda

**Comment by daniellyonvald** [comment]
@ararojas tenía la misma duda, la respuesta está en la Issue#220

**Comment by ararojas** [comment]
Gracias!!!  @daniellyonvald
