### ISSUE TITLE
Menú a prueba de inputs

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#231]
Hola! 
Se que este tema ya se ha tocado en otras issues, pero sigo teniendo la duda de si nos debemos preocupar de que nuestro programa sea a prueba de inputs o no. Esto porque en la ayudantía de la tarea dijeron que no nos preocupáramos de eso ya que no era el objetivo de la tarea y en algún issue que leí pusieron lo mismo.
Saludos.

**Comment by johntrombon** [comment]
Me sumo a tu pregunta, en lo personal creo que son muchos los casos en los que se podría caer la consola como para lidiar con ellos sin uso de decoradores o excepciones 😢

**Comment by meceledon** [comment]
cps

**Comment by inveterate-cladocerus** [comment]
up

**Comment by cilopez** [comment]
Hola, en el enunciado se menciona esto:
> " ... Puede asumir que las consultas siempre estarán bien escritas, sin embargo, su programa no debe caerse si las opciones del menú son ingresadas erroneamente. "
>
Mencionenme que no queda claro de aquella linea y quizás les pueda responder más detalladamente.

**Comment by johntrombon** [comment]
Mi duda es si con eso se refiere solo a que el formato de las consultas estará bien escrito, o si se le entregaran siempre parámetros válidos. No sé si puedo asumir que por consola se le va a entregar siempre un generador que calce con el tipo pedido , por ejemplo si se ingresa un generador de _passengers_ en lugar de uno de _airports_ mi función se va a evaluar correctamente pero va a tirar un error en la mitad. No sé si ese caso vale por una "consulta mal escrita" o una "opción del menú ingresada erróneamente". 
Gracias de antemano y perdón por colarme al issue de otra persona 😄 .

**Comment by BenjaminRubio** [comment]
La confusión surge también por otros issues donde se ha dicho que partes de la consulta podrían estar mal ingresadas, lo que a mi parecer se contradice con lo dicho en el enunciado y da para la duda. Como es el caso de la issue #222

**Comment by joaquinhernandezg** [comment]
Cps

**Comment by cilopez** [comment]
Las consultas siempre van a estar bien escritas y van a recibir sus parámetros en su orden determinado (eso mencioné en la sala de ayuda). Los inputs que deben manejar son tipo:
``` 
Que consulta quiere hacer (1-9): oli
Consulta no válida, inserte un número del 1 al 9
 
```
Les encuentro la razón, es complicarles la vida gratuitamente pedirles revisar cada caso sin decoradores ni excepciones.

**Comment by inveterate-cladocerus** [comment]
Gracias cilopez!

**Comment by BenjaminRubio** [comment]
Deberían marcar este issue como importante para la gente que esta haciendo la función que revisa el input :disappointed_relieved:

**Comment by gnacrur** [comment]
@cilopez  Quería saber si es necesario darle la opcion de elegir el tipo de consulta, siendo que no lo piden explicitamente hasta donde yo entendi. 
También tengo la duda de como podemos probar inputs si no podemos usar loops.
Esto especialmente aplica para el caso de los archivos con consultas o cuando el usuario decide ejecutar algunas de las consultas guardadas en output.txt. Tengo que darle la opción de elegir algunas de las consultas (sin loops), al mismo tiempo que sea a prueba de inputs y tenga la opción de volver atras?

**Comment by rhanuch** [comment]
¡Hola @gnacrur !

No es necesario darle la opción de elegir la consulta, simplemente se debe poder ingresar una lista de consultas o una consulta por si sola. Pero tampoco nada te impide hacer las consultas de la manera que plantea @cilopez 😄 

Respecto a lo segundo, el archivo `output.txt` no debe ser leido (a menos que por algún motivo que desconozco quieras hacerlo 🤔), por lo que no debes preocuparte de eso. Este archivo simplemente está para poder mantener un `log` del resultado de las consultas 📜 

¡Saludos y éxito! 🍀

**Comment by gnacrur** [comment]
Gracias por tu respuesta @rihanuch!
En la parte 3 del enunciado, interaccion con consola dicen que el usuario debiese poder leer las consultas o eliminar algunas o todas las consultas. Ademas igual para los archivos en general (como queries) tenemls que poder leer algunas consultas dependiendo lo que indique el usuario. Tambien hay que considerar que nos piden que el usuario pueda volver al menu anterior. No es dificil volver al menu inicial perl si seria muy tedioso programar que vuelva al menu anterior (si esque este no es el inicial) sin loops. Todo esto sumado a que el programa sea a prueba de inputs termina complicando mucho pese a no tener nada que ver con programacion funcional.  Saludos!
