### ISSUE TITLE
input filter_flights, sintaxis y otros

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#235]
Hola, no comprendo bien como funciona ese input, en el enunciado me dice que es un generador con aeropuertos y un con vuelos, 

1. ¿esos generadores fueron los que yo hice en los pasos anteriores?  si lo fueran puedo ocupar load_detabase(db_type) para eso

2. otra duda es que si son los mismos yo hice una función generadora que me genera una namedtuple con los dados que quiero utilizar, podría yo hacer algo como:

```Python
lista_air = generador_airport
filter = filter(lambda x: función(x.info + x.other_info) == value, lista_air)
```

3. La ultima duda es sobre la sintaxis de como hacer una función como a de arriba en 2 lineas ejemplo:

```Python
filter = filter(lambda x: funcíon(x.info +x.other_info) "sintaxis_value"== value, lista_air)
```

Sintaxis_value seria lo que yo deberia utilizar para que python me  leese la función correctamente
Disculpe si hay algún error de escrita, muchas gracias desde ahora ♥

**Comment by lily416** [comment]
Hola :)

1.  El input de `filter_flights`, puede ser cualquier generador que se obtenga de una función que retorna generadores (valga la redundancia), entonces puede haber ocasiones en que sea los generadores de `load_database`, pero también puede ser el generador que se retorna al hacer un `filter_flights`. 

     Por ejemplo, para obtener todos los vuelos que recorren entre 400 y 200 millas tendrías que hacer:  
 ```Python
{"filter_flights": [{"filter_flights": [{"load_database": ["Flights"]},{"load_database": ["Airports"]}, "distance", ">", 200]},{"load_database": ["Airports"]}, "distance", "<", 400]}
```

2.  Sí, es válido lo que quieres hacer.
3.  No entiendo muy bien lo que quieres preguntar 😥 ¿Podrías tratar de explicarte mejor?

Saludos 👋

**Comment by csantiagopaz** [comment]
Gracias ♥
la 3. quiero saber como escribir una función por compresión  en 2 lineas, pues tengo esa función ocupando en 1 linea más de 80 caracteres, entonces para cumplir PEP8 me gustaria escribir en 2 lineas ejemplo


def funcion_que_haz_algo(parametro_ejemplo):
    resultado = 2 * parametro_ejemplo
    return resultado
def funcion_ejemplo(lista_ejemplo):
    if "algo se cumple":
        _generador_ejemplo = filter(lambda x: funcion_que_haz_algo(x.parametro), lista_ejemplo)_ ( <= tiene más de 80 caracteres)
queria escribir eso en 2 lineas

**Comment by lily416** [comment]
Cuando una función ocupa más de 80 caracteres aplicas saltos de líneas en lugares que no afecten la funcionalidad de la función, por ejemplo:

- ```Python 
  generador_ejemplo = filter(
      lambda x: funcion_que_haz_algo(x.parametro), lista_ejemplo
  )
  ```

- ```Python
   generador_ejemplo = filter(lambda x: funcion_que_haz_algo(x.parametro), 
                              lista_ejemplo)
   ```

Interfaces de desarrollo como PyCharm realizan estos saltos automáticamente, debes seleccionar **Code** y después **Reformat Code**, así se corregirán la mayoría de los errores de PEP8. (Solo en el caso de que tengas el límite de caracteres en 80)

Saludos 👋

**Comment by isavega** [comment]
Hola! Entiendo que la consulta relacione las bases de datos de aeropuertos y vuelos en el caso de que me filtre por distancias pero en el caso de filtrar por fechas no me hace sentido usar la base aeropuerto. Puedo hacer 2 funciones separadas para los distintos criterios o debe ser todo en una?? Muuuchas gracias

**Comment by lily416** [comment]
@isavega La idea de programación funcional es que simplifiques el problema el problema lo más posible, así que si puedes hacer funciones separadas 👍

Aunque debes considerar que ambas funciones tienen que llamarse a partir de una misma función ❗️
porque a fin de cuentas la función que se llama es `filter_flights` y para saber cómo filtrar es que se le pasa `date` o `distance`. 

A lo que me refiero:
```Python 
def función(*args, **kwargs):
   if caso_1:
      return función_caso_1(*args)
   elif caso_2:
      return función_caso_2(*args)
   ...
```    
Ojalá que te quede claro 😄 
Éxito con la tarea 🍀

**Comment by isavega** [comment]
Un millón de gracias !

**Comment by csolguin** [comment]
@lily416 hice exactamente el código que comentaste, sin embargo al evaluar el caso 1 que es attr == 'date' , siempre me ejecuta una lista vacia, lo raro es que si comento o elimino el elif attr =='distance' (caso 2), se ejecuta correctamente el caso 1, y mis generadores están dentro de los if, elif, por lo que no se gastan antes de ingresar.
¿A qué se debe esto?

**Comment by lily416** [comment]
@csolguin Lo siento no se a que de pueda deber 😞 lo comentaré con otros ayudantes para ver si saben la razón. 
Por mientras (y si tienes el tiempo) pon prints por esa parte del código y ve verificando el estado de las variables. En última instancia, si es que no llegas a encontrar nada que te llame la atención transforma los generadores a otras estructuras de datos y ve que pasa, pero ten encuenta que si lo dejas así podría afectar tu nota y el tiempo en que se demore en procesar la consulta.

**Comment by lily416** [comment]
@csolguin Comentan que puede deberse al uso de _if/elif_, tal vez deberías probar usar puros _ifs_:
```Python
def función(*args, **kwargs):
   if caso_1:
      ...
   if caso_2:
      ...
   ...
```

Además, piensa bien lo que necesitas y cómo se está ejecutando el generador.

Ojalá que esto funcione,
Saludos 🤞

**Comment by csolguin** [comment]
@lily416  Muchísimas gracias 👍, no sé a que se deberá pero tuve que pasar el generador a lista por comprensión y dicha lista iterarla y retornarla como generador
De esta forma se ejecuta perfectamente
Saludos
