### ISSUE TITLE
input tipo datetime

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#237]
Se puede asumir que los inputs de tipo "datetime" vendran en realidad como strings? (para luego pasarlos a datetime si quiero trabajarlos como datetime)

**Comment by lily416** [comment]
Sí, puedes asumir que los inputs tipo `datetime` serán entregados como strings, pero por si acaso especificalo en los supuestos del readme.

Saludos 👋

**Comment by isavega** [comment]
Asumi lo mismo, que los inputs "datetime" vienen como strings para luego transformarlos con datetime.strptime("string",formato). Pero me sale el error de que eso me devuelve un string, porque??
