### ISSUE TITLE
Archivo output.txt

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#238]
Hola!

El archivo output.txt vendrá vacío cuando revisen la tarea? Lo pregunto porque para leerlas/escribir las consultas hay un formato general pero no específico.
Además, en este archivo se debe poner el type() del resultado de la consulta, dado esto, ¿está bien que salga, por ejemplo, class -filter- en vez de class -generator-? o el resultado de nuestras consultas tiene que ser si o sí un generador?

Gracias!

**Comment by bgsamilla** [comment]
Tengo la misma duda con los tipos itertools.tee o map se consideran generadores a pesar que su tipo no sea exactamente generador?
Saludos!

**Comment by cacoos** [comment]
up
