### ISSUE TITLE
Interacción con consola

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#239]
Hola!
No entiendo muy bien esta sección de la tarea. De partida no entiendo para nada el primer punto que dice:
"Abrir un archivo con consultas, que se encuentre dentro de la carpeta del programa. Cada linea de
este archivo tendra una consulta valida.
El usuario debe ser capaz de escribir el nombre de un archivo presente en la carpeta del programa
y almacenar en memoria las consultas que aparecen en este. Luego podra elegir una, varias o todas
las consultas presentes en el archivo, y se deberan mostrar los resultados en la consola."

No entiendo de que archivo están hablando, primero pensé que se trataba de output.txt pero ese lo mencionan en el punto 3. No sé como almacenar las consultas y dar la opción de elegirlas si no se en que formato va a estar ese archivo.

Por último, tampoco entiendo el tip que dan al final, si lo hacemos así, entonces nunca se usaría el formato especificado en la parte 2.2.1, ¿o no lo entendí bien?

Ayuda :(

**Comment by bgsamilla** [comment]
Hay un archivo de ejemplo en el syllabus se llama queries.txt

En cuanto al tip lo que yo entiendo es que se refiere a cuando muestras los datos de los archivos en la consola, no a como los guardas.

Saludos compañero :)

**Comment by viantirreau** [comment]
Hola! Te puede servir el archivo queries.txt que subieron al syllabus hace poco! Ese tiene algunas búsquedas y su formato es exactamente el mismo en el que escribirán las consultas por consola, solo hay que hacerle un par de modificaciones para que funcione perfecto. Te comento lo que modifiqué:
- Eliminé las comillas de cada linea con un strip al momento de la lectura
- Cambié el orden de los argumentos en las queries `passenger_miles` y `furthest_distance` para que coincidiera con el #215.  En todo caso, en un comentario que sigue ese hilo, indicaron que se podía hacer estas búsquedas con otro orden de parámetros.
- Agregué `load_database` de _Airports_ para que no se cayera la consulta `popular_airports`
- Arreglé unos _typo_ en la consulta `airport_passengers` (decía **"load_databse"**)

Si te sirve puedo adjuntar el archivo queries que me sirvió finalmente (si no va contra las reglas 😆)

Saludos!

**Comment by ararojas** [comment]
Muchas gracias!!! @BSamilla @viantirreau

**Comment by pablovejar** [comment]
@viantirreau Hola! Te queria hacer una pregunta respecto a como lo hiciste con la lectura de ese archivo, al final te queda una lista con todos los diccionarios de las consultas realizadas? 
Por ejemplo, te queda así? 
['{"load_database": ["Airports"]}', '{"filter_flights": [{"load_database": ["Flights"]}, {"load_database": ["Airports"]}, "distance", "<", 400]}', ....
o te queda como una lista con diccionarios y sin las comillas?
