### ISSUE TITLE
Error al iniciar Atom en macOS

### ISSUE THREAD

**Issue by isiguelfand** [IIC2233/syllabus-2018-2#24]
Hola! Estoy teniendo problemas con atom, nunca me apareció la bienvenida, tampoco puedo ver la barra del menú (ya traté con Alt). 
Gracias!

**Comment by jecastro1** [comment]
Hola @isiguelfand,

¿Puedes dar un poco más de detalles de tu problema? Partiendo por:

1. ~~Especificar tu sistema operativo. ¿Es macOS como el ayudante puso?~~ Perdón, no miré bien el título.
2. El método de instalación.
3. Si probaste instalando otra vez (a veces las cosas funcionan así 🤷‍♂️)
4. Alguna screenshot.

Saludos.

**Comment by isiguelfand** [comment]
Lo instalé desde la página, me aparece así (en un principio se abrió como una ventana en blanco
<img width="435" alt="captura de pantalla 2018-08-13 a la s 16 08 29" src="https://user-images.githubusercontent.com/42189248/44090422-7c4d4378-9fa0-11e8-8dbd-ba410af62a82.png">
)

**Comment by isiguelfand** [comment]
<img width="1280" alt="captura de pantalla 2018-08-14 a la s 08 33 00" src="https://user-images.githubusercontent.com/42189248/44090442-8d061208-9fa0-11e8-974a-991d4c3a6baf.png">
Lo bajé desde la página, en un principio se abrió como una ventana en blanco.

**Comment by jecastro1** [comment]
Hola,

Según lo que encontré buscando el error de la derecha abajo (es una consola JavaScript, el lenguaje en que está escrito Atom) posiblemente se solucione borrando unos archivos de caché de Atom (https://github.com/atom/atom/issues/17348)

Prueba yendo a `~/.atom` y borrando la carpeta `compile-cache`.

**Comment by isiguelfand** [comment]
Gracias, lo pude resolve corriendo `sudo chown -R `whoami` ~/.atom`
