### ISSUE TITLE
db_type "travels" y archivo "flights_passengers.csv"

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#240]
Hola, supongo que siempre que cuando en la tarea se habla de travels, se refiere a flights_passengers. ¿Para load_database se usara "Travels" en las consultas (que es como sale en queries.txt) aunque el archivo se siga llamando flights_passengers.csv, cambiaran el nombre de flights_passengers .csv a travels.csv? Esto es importante para la función load_database(db_type, db_size).

**Comment by lily416** [comment]
Sí, cuando se habla de `Travels` se está haciendo referencia a `flights_passengers`.
Sí, en `load_database` se utilizará `Travels` como argumento para cargar `flights_passengers.csv`.
No se cambiará el nombre del archivo y en caso de que se hiciera les avisaremos por medio de alguna issue o similar 😃 

Saludos 👋
