### ISSUE TITLE
Cambios en los archivos del Syllabus de la Tarea 1

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2233/syllabus-2018-2#241]
Saludos a todos, les comento un poco sobre la tarea 1.
Se actualizo el syllabus y se hicieron los siguientes cambios:

- Se subió una nueva base de datos llamada flights-passengers2 la cual es la misma que la primera pero sin datos repetidos, a la hora de evaluar probablemente se utilice la nueva, sin embargo si ya la terminaron escriban en el Readme que se utiliza la base de datos antigua.

- Se actualizo el archivo queries.txt según lo comentado en la issue #236

**Comment by Banfanci** [comment]
@jeschuwirth holaa, sabes probando el archivo tuve problemas, dado que en el enunciado se explicita que las consultas se entregaran en el formato [consulta1, consulta 2...] Donde cada consulta vendria a estar en el formato ya conocido por todos... Entonces en teoría si me entregan solo una consulta, como vendría a ser el caso para cada linea de este archivo, deberían entregarmela como [consulta] entre corchetes, para mantener consistencia.
Preguntó esto ahora, porq no se cual sera el formato de los archivos con los que se probara el programa.
Saludos!!!

**Comment by jeschuwirth** [comment]
Gracias por notarlo, se subirá pronto nuevamente el archivo queries.txt para que vengan en formato lista con las consultas dentro. 👍

**Comment by Fenho** [comment]
y los "load_database.txt" estan escritos como "load_datebse.txt" en la penultima linea de queries.txt (para que lo arreglen jaja)
