### ISSUE TITLE
Forma de retorno de Generadores

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#243]
Es valido  para el retorno de generadores (en las bases de datos) ocupar lo siguiente:

`yield {Archivo(line[0], line[1:]) for line in archivo}`

siendo que Archivo es una namedtuple.
porque si ocupo 

`return (Archivo(line[0], line[1:]) for line in archivo)`

me sale el siguiente error al llamar al generador producido antes

`ValueError: I/O operation on closed file.`

**Comment by rhanuch** [comment]
¡Hola @fjlopez7 !

¿Estás seguro que el orden de lo que dices es correcto? Pregunto esto porque cuando uno hace un `return` la información se almacena en la estructura de dato antes de cerrar el archivo que estás leyendo 📖 

En cambio, si se usa un `yield` la información de ese archivo (asumiendo que estas usando un `with open`) no es instanciada, sino que simplemente se hace una referencia a la dirección de memoria y cómo producir esa información. Esto último provoca que cuando se haga el llamado al generador el archivo este cerrado y no se pueda acceder a el 🔏

Te dejo un [link más detallado](https://stackoverflow.com/a/39656712) de lo que ocurre al hacer `yield` vs `return`

¡Saludos y éxito! 🍀
