### ISSUE TITLE
Resultado consultas output.txt

### ISSUE THREAD

**Issue by chocopiano** [IIC2233/syllabus-2018-2#244]
Hola!
Me pueden explicar que es lo que se debe escribir en el output.txt como resultado. Ejemplo si la consulta es {"load_database":['Airports']}, me debe escribir como resultado el generador obtenido o simplemente que el resultado es tipo generador? y en el caso de las consultas que no me devuelven generadores debe escribir simplemente el diccionario, set o lista obtenido o no? 
Gracias!

**Comment by jeschuwirth** [comment]
Saludos,
En output.txt se debe imprimir por linea cada elemento del generador asociado, es decir, si el generador es de aeropuertos se debe imprimir toda la información que posee cada aeropuerto. En el caso de consultas que no retornen generadores queda a tu criterio como muestras la información de la respuesta, pero que quede clara para el ayudante que lo hiciste correctamente. (No es suficiente colocar que el resultado es una lista sino que se debe mostrar la información que esta contiene).

**Comment by cacoos** [comment]
Hola!
En caso de los generadores puedo ponerlo en una sola línea como una lista de los elementos?

**Comment by jeschuwirth** [comment]
Como dice el enunciado:
![image](https://user-images.githubusercontent.com/37160256/45265956-e2692300-b429-11e8-9b9d-808022d0b8c1.png)
