### ISSUE TITLE
Consulta favourite_airport

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#246]
Hola! si por algún motivo un pasajero que aparece en el db de pasajeros nunca viaja, es decir, no aparece en el db de Travels, puedo asumir que no tiene aeropuerto favorito y por lo tanto no aparecerá en el diccionario que retorna esta función? y el diccionario que retorna esta función puede ser un defaultdict?

**Comment by jeschuwirth** [comment]
Hola!,
acabo de responder la misma pregunta al final de la issue #197
