### ISSUE TITLE
Diccionario por comprensión a base de lista

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#247]
Hola, quiero crear un diccionario por comprensión a base de valores de una lista
Intente el siguiente código:
`lists = [['0', '1'], ['0', '3']]`
`{mylist[0] : mylist[1] for mylist in lists}`
Si no fuera una lista no habría problema, pero lo es. Me tira el error "TypeError: unhashable type: 'list'", aunque el key no es una lista, es un string (o numero, en verdad no importa).
¿Que estoy haciendo mal y que puedo cambiar para lograr esto mismo siguiendo programación funcional?

**Comment by bgsamilla** [comment]
Con mi poco conocimiento puedo decirte que debería funcionar.
De hecho lo copie y pegue, y me funciona, solo asigné el diccionario a una variable.
Aparte de eso recuerda que no puedes tener 2 keys iguales por lo que el diccionario de tu ejemplo queda como:
{"0": "3"}
Espero que mi irrelevante ayuda sirva de algo
Saludos!

**Comment by fgbruna** [comment]
Exacto, como dice @BSamilla, ese código es totalmente válido en `python 3.6`, verifica que no estés usando otra versión previa 😲

**Comment by Fenho** [comment]
Me funciono mucho jaja, en mi código original estaba usando un set de listas en vez de lista de listas. Gracias!
