### ISSUE TITLE
Anidar consultas

### ISSUE THREAD

**Issue by mvgil** [IIC2233/syllabus-2018-2#248]
Hola! Es posible hacer este tipo de consultas?
```python
{"filter_passengers_by_age": [{"filter_passengers": [{"load_database": ["Passengers"]}, {"load_database": ["Flights"]}, {"load_database": ["Travels"]}, "01WY", "2018-02-10 10:00:00", "2018-03-10 17:32:00"]}, 25, False]}
```

En este caso `"filter_passengers_by_age"` recibe un generador passengers, que corresponde al generador retornado por `"filter_passengers"`.   
Gracias!

**Comment by jeschuwirth** [comment]
Si, de hecho esa es un gran parte de la tarea, lograr anidar varias preguntas y utilizar el resultado de unas para preguntar otras con bases de datos filtradas.

**Comment by Kitaps** [comment]
Pero como se hace para que una funcion lea eso?
