### ISSUE TITLE
defaultdict

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#249]
para poder llenar mi defaultdict, se puede utilizar un ciclo que no sea por compresion? o existe otra manera de hacerlo?
De antemano muchas gracias.

**Comment by lily416** [comment]
Hola

Los únicos ciclos que se pueden utilizar son los especificados en el enunciado, como ingresar datos al defaultdict se parece al primer ejemplo que no se puede usar no es válido. :disappointed_relieved: 

Lo que podrías hacer es que en vez de usar defaultdicts podrías usar diccionarios por comprensión y hacer uso de if/else dentro de este.

Saludos :wave:

**Comment by marcotroncoso** [comment]
entonces puedo utilizarlos??

**Comment by lily416** [comment]
Disculpa, envíe la respuesta antes de terminar de escribirla 😅 revisa la respuesta actualizada

**Comment by marcotroncoso** [comment]
😭😭😭😭😭

**Comment by marcotroncoso** [comment]
como se puede ocupar el else en la lista por compresion??

**Comment by lily416** [comment]
Para utilizar if-else en cualquier estructura por comprensión debes hacer: 
```Python
(caso_1 if condición else caso_2 for i in algo)
```
Donde `caso_1` y `caso_2`, sería lo que sucede en el caso de que se cumpla o no la condición.

Un ejemplo sería:
```Python
a = [i if not i%3 else 0 for i in range(20)]
# Donde a es:
# [0, 0, 0, 3, 0, 0, 6, 0, 0, 9, 0, 0, 12, 0, 0, 15, 0, 0, 18, 0]
```
Lo que da una lista con números que son divisibles por 3 y que en el caso de que no lo sean, se pone un 0 en vez del número.

Ojala quede claro, saludos y éxito con la tarea 😄🍀

**Comment by marcotroncoso** [comment]
Graciaaas te pasaste, quedo clarisimo.
