### ISSUE TITLE
Mensaje encriptado

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#25]
En la sección **4.1.2**, dice que _db_emails.csv_ contiene el cuerpo de los correos **no encriptado**,  siendo que sí lo está. Trabajo con esos números para probar mi desencriptación?

**Comment by cilopez** [comment]
Efectivamente, los correos sí están encriptados, puedes probar con esos números tu encriptación.

**Comment by ninifdr** [comment]
esque creo que se confundieron porque en el enunciado sale que db_emails tiene los cuerpos no encriptados y que old_db_emails si los tiene encriptados y es al revés

**Comment by rhanuch** [comment]
¡Hola @ninifdr !

Efectivamente hay un error en el enunciado, `db_emails.csv` contiene los correos **encriptados** 🔢  y `old_db_emails.csv` contiene los **no encriptados** (en el enunciado sale que _ambos_ están no encriptados)

¡Saludos y éxito! 🍀
