### ISSUE TITLE
[favourite_airport] - Conteo de aeropuertos 

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2233/syllabus-2018-2#250]
"Recibe un generador con pasajeros, otro con vuelos y otro con viajes, retorna un diccionario con
keys igual a los identificadores de los pasajeros y values el código del **aeropuerto al cual ese pasajero
viajó más veces**"

Acerca de esto, ¿se cuenta tanto el aeropuerto de destino, como el de inicio?

**Comment by cilopez** [comment]
Hola @VicenteVicenteVicenteVicenteVicente**VicenteVicenteVicenteVicenteVicenteVicenteVicenteVicente**:
Según mi interpretación debería ser sólo el de destino, la otra interpretación es que se sumen ambos y si lo hiciste así señalalo en el readme ya que no es una diferencia fundamental, cualquier cosa señala esta _issue_ en tu readme para que no existan problemas.

**Comment by VicenteVicente** [comment]
¡Dale muchas gracias! 😹
