### ISSUE TITLE
Demora consultas

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#253]
Hola, 

lo que pasa es que mis consultas en las bases de datos grandes se demoran mucho (aprox 5 min por consulta)
Lo que pasa es que no se por que ni como hacerlo mejor, que puedo hacer?
No he usado listas, está todo con generadores (creo)

**Comment by cilopez** [comment]
Mmm 5 minutos igual es harto Patrick, pero te recomiendo enfocarte en las basesde datos de término medio y abarcar gran parte  de las consultas, si tienes tiempo luego puedes optimizarlas.
