### ISSUE TITLE
Duda sobre las funciones

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#254]
Respecto a las funciones que son pedidas (ejemplo: load_database(db_type)) ¿es obligacion que esta posean SOLO los argumentos mencionados en el encunciado?
Un ejemplo para aclarar mi duda:
Puede tener la misma funcion, pero del siguiente modo:
load_database(db_name, arg_1=None, arg_2=None)

**Comment by cilopez** [comment]
Hola @lucasvsj  esto se hablo en la issue #202.
- Resumiendo, sí es obligación que reciban sólo los argumentos del enunciado.
