### ISSUE TITLE
Actualizar valor de un diccionario

### ISSUE THREAD

**Issue by cjortuzar** [IIC2233/syllabus-2018-2#255]
Hola! Una pregunta: si hago un diccionario dentro de una función, puedo ir editando los values de ese diccionario? O una vez que ya esta hecho, no lo puedo modificar?

Gracias!

**Comment by jjaguillon** [comment]
Siempre puedes editar los values de un diccionario.

```python
def function():
    dictionary = {1: 'UNO', 2: 'DOS'}
    dictionary[1] = 'uno'
    return dictionary
```
Si no es el caso que esperabas ver, explaya un poco más la pregunta.

Saludos

**Comment by cjortuzar** [comment]
Si, perfecto. Pero en el contexto de la tarea, es legal ir cambiando los values de un diccionario creado dentro de una función?

Gracias!
