### ISSUE TITLE
Duda sobre funcion foreach

### ISSUE THREAD

**Issue by firulais33** [IIC2233/syllabus-2018-2#256]
Entiendo que la función _foreach_ no puede modificar el input que se le es entregado. Pero es legal tomar el input y crear otra estructura a partir de esta? Por ejemplo, si le entrego un diccionario, en vez de modificar el mismo diccionario creo uno nuevo y retorno ese?

Gracias.

**Comment by kelseyfranken** [comment]
tengo la misma duda

**Comment by inveterate-cladocerus** [comment]
cps
