### ISSUE TITLE
output.txt

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#257]
Hola!
Quería saber si las consultas que se guardan en el archivo output.txt son solo las que se ingresan directamente por consola, o también las que se hacen a través del archivo.
Gracias!

**Comment by cilopez** [comment]
No sale explicito en el enunciado que se deba hacer, pero si puedes da una opción de guardar las consultas que estan en el archivo, te va a servir para testear más rapido 😄 .  Si no puedes simplemente solo da la opcion de guardar las consultas realizadas por consola.

**Comment by ararojas** [comment]
Y las consultas que tienen que quedar guardadas en el archivo son las que se hacen durante una corrida del programa? o van quedando acumuladas de corridas anteriores? (pregunto porque no se me ocurre una forma fácil de saber en que numero de consulta se va si viene con consultas de antes el archivo)

**Comment by cilopez** [comment]
Puedes hacerlo de las dos maneras, un hint puede ser que guardes un numero en un archivo separado y así almacenes el número de la consulta en que vas.
