### ISSUE TITLE
Duda acerca de la funcion foreach

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#258]
Cuando nos dicen en el enunciado:

> _Si la función no altera el input el "foreach" está permitido,_

A que se refiere especificamente con alterar? . Podría ocupar el foreach para asignar elementos a un diccionario?

**Comment by cilopez** [comment]
Si _function_ altera a _iterable_ entonces estarías rompiendo las reglas.
Puedes poner un pseudocodigo para que entienda más el caso que quieres programar, pero al parecer ese caso no se podría hacer.

**Comment by gnacrur** [comment]
@cilopez En el caso de que se usara para asignar elementos a un diccionario (usando append  si es que los values son listas por ejemplo) y que el diccionario exista desde antes. Si estoy utilizando un iterable que no es mi diccionario sino una de las bases de datos por ejemplo, ¿Sería válido el uso? O cuando hablan de input se refieren a que no altere ninguna variable en el programa completo?

**Comment by Michelmagna** [comment]
En que quedo esto?
