### ISSUE TITLE
Cantidad de consultas por línea de queries.txt

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#259]
Hola!
¿Debemos esperar una sola consulta (léase diccionario) por línea en el archivo `queries.txt`?
¿O también pueden entrar múltiples consultas en una sola línea (como lista de diccionarios)?

Saludos!

**Comment by cilopez** [comment]
Hola @viantirreau , es una consulta por línea. 
saludos

**Comment by viantirreau** [comment]
Genial, gracias!
