### ISSUE TITLE
Intercambio de elementos

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#26]
En  el ítem **3.5.5. d)**, menciona sobre la última posición de la lista como caso especial. Este enunciado también abarca la posibilidad de estar en _i_ = 250 y moverme a un _j_ > 255? 
Por otra parte, si el _j_ cae en un índice > 255 y por tanto, se considera nuevamente la lista, se debe intercambiar por este elemento (en este caso uno del principio de la lista) o bien se reemplaza el valor que se encuentra ahí?

**Comment by johntrombon** [comment]
Tengo la misma duda

**Comment by ptflores1** [comment]
Hola !
Siempre que un j sea mayor a 255 debes volver a partir desde el inicio e intercambiar los números
Saludos !
