### ISSUE TITLE
Consultas con Filtros

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#260]
Buenas!, tengo una duda con la consultas con filtro. Por ejemplo en la 2.2.3.2 de _passenger_miles_ . Si le aplico el filtro de _filter_passengers_by_age_, se supone que tendre menos id de usuarios. Que se supone que hago con esos id que filtre? los muestro igual con value = 0, o simplemente los omito y no los entrego en el dict?.

Esta pregunta tambien afecta las otras consultas con filtro, ya que hago algun filtro con aeropuertos, existiran vuelos que no se podran hacer, y asi sucesivamente..

**Comment by cilopez** [comment]
Simplemente no los entregas, es como si reducieras tu base de datos. Respecto al segundo punto es un problema que deberías poder resolver con generadores, te recomiendo que te guies por esto y busques como funciona en internet (Esto se ve en profundidad en Bases de Datos).
![full-outer-join](https://user-images.githubusercontent.com/26127105/45271124-eec99c00-b47a-11e8-9772-40cde998341e.jpg)
Si tu duda fue resulta porfavor hazmelo saber, Saludos!

**Comment by NicolasCabello** [comment]
@cilopez La primera parte si la entendi perfecto. Respecto a lo 2do, entonces se supone que terminaré tambien filtrando los viajes debido a la filtracion en aeropuertos?

**Comment by cilopez** [comment]
Si deberías filtrarlos, o encontrar la forma de no entregar aquellos resultados que no tengan lógica. como por ejemplo las filas que tienen NULL en la imagen
