### ISSUE TITLE
Módulo iic2233_utils

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#261]
Hola!

Qué tanto puedo modificar el módulo `iic2233_utils`? Lo que me gustaría hacer a mí sería sacar las funciones que ahí se encuentran y llevarlas a otro módulo. Sino se puede, puedo cambiarle el nombre al archivo y/o agregarle funciones hechas por mí?

Saludos 🤓

**Comment by cilopez** [comment]
No, no se puede. Puedes importar las funciones del módulo y las funciones hechas por ti ponerlas en otro modulo y también importarlas, por lo que para que no existan problemas ese modulo **no** se podrá editar.

**Comment by rhanuch** [comment]
#188
