### ISSUE TITLE
Funcion furthest_distance

### ISSUE THREAD

**Issue by stmorales** [IIC2233/syllabus-2018-2#262]
Queria saber si la lista de los n pasajeros que más millas viajan teniendo como origen el aeropuerto del icao  puede repetir pasajeros o si sólo se considera la mayor distancia de cada uno. 

Cuál es la manera correcta?
1) lista = [ Pepe, Pepe, Juan, Pepe, Pedro, Pepe, José, ... , n]
2) lista = [Pepe, Juan, Pedro, José, ...., n]

Gracias

**Comment by cilopez** [comment]
Tienes que entregar todos, con repeticiones

**Comment by Coolgatty** [comment]
Lei en #220 que los pasajeros no debieran repetirse con las bases de datos actualizadas
