### ISSUE TITLE
Demora consultas que no retornan generadores con bases medium

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#263]
Hola, al ejecutar mis consultas que no retornan generadores con las bases de tamaño medium no estas se demoran mucho. He estado esperando como 10 minutos esperando y ya en cierto punto decido pararlo. Si trabajo pasando los generadores recibidos a listas se demora relativamente poco (dependiendo de que consulta entre 1 a 4 minutos) pero por lo que entiendo esto descuenta puntos. No tengo problema con las consultas que retornan generadores ni siquiera con las bases large. Habían preguntado esto antes pero solo le dijeron que siga trabajando (lo que si he hecho). Ojala nos pudiesen a ayudar para poder diferenciar entre funciones que son eficientes y las que no al trabajar con generadores o dar tips para mejorar la eficiencia de una función.

**Comment by kelseyfranken** [comment]
cps
