### ISSUE TITLE
Formato ingreso de consultas

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#264]
Hola!
En el enunciado dice:
"Por lo tanto, el programa recibirá un conjunto de consultas en la forma:
[consulta_1, consulta_2, ... , consulta_k]"
Esto quiere decir que aunque el usuario ingrese solo una consulta, igual la va a ingresar dentro de una lista?

**Comment by Arcoirisky** [comment]
Hola! 
La sección de formato de consulta se refiere a dos tipos de inputs O: Las consultas únicas y varias a la vez. Osea, puedo escribir mis consultas como diccionario si quiero que solo se ejecute esa ó una lista de diccionarios si deseo muchas respuestas de una :D 
¿Se entendió? O:

**Comment by Fenho** [comment]
¿Pero siempre se va a partir con un diccionario, como se hace en queries.txt?
