### ISSUE TITLE
duda modificar argumentos que reciben funciones de 2.3.3

### ISSUE THREAD

**Issue by BenjaCastillo** [IIC2233/syllabus-2018-2#267]
Hola quería saber si en la función passenger_miles puedo agregarle que reciba el generador con los aeropuertos, es que para sacar la distancia de aeropuertos necesito los aeropuertos, y para sacar los aeropuertos según su id (que es lo que viene en los vuelos) necesito el generador de aeropuertos.
Osea igual podría generarlo en el momento, pero seria un archivo con un tamaño especifico, en cambio si lo pongo como un argumento que recibe la función seria mas general y mejor creo yo

**Comment by cilopez** [comment]
#215
