### ISSUE TITLE
Modificar función foreach

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#268]
¿Es posible modificar el archivo "iic2233_utils" para que la función que entra como parámetro a foreach reciba más argumentos? Originalmente a cada elemento x de un iterable le aplica function(x). La pregunta es si podría modificar un poco el código y poner function(x, a, b) donde a y b son otros parámetros.

Gracias

**Comment by cilopez** [comment]
No se puede editar el archivo  _iic2233_utils_.
