### ISSUE TITLE
Extensión archivos Base de datos

### ISSUE THREAD

**Issue by Franco1605** [IIC2233/syllabus-2018-2#27]
Hola! No me queda claro si necesariamente tenemos que trabajar con los archivos en la extensión .csv, o podemos cambiarla a .txt y seguir trabajando con esta última.

**Comment by cilopez** [comment]
Debes trabajar lo archivos en  `.csv` por simplicidad, en caso que tu crees otro archivo donde guardes otra información puedes guardarla en `.csv` o `.txt` .
