### ISSUE TITLE
duda sobre la legalidad de namedtuple

### ISSUE THREAD

**Issue by ebrzovic** [IIC2233/syllabus-2018-2#273]
Es legal definir una namedtuple fuera de una funcion, asi  tipo:
A = namedtuple('arg1',['arg2','arg3'])
para asi poder llamarlos en funciones futuras
gracias :)

**Comment by ncasassas** [comment]
Tengo la misma duda ! ( si  es posible acceder a los datos como se hizo en la ayudantía N°2 )

**Comment by johntrombon** [comment]
Hola. Yo diria que mientras solo las definas y no precargues los datos es legal, igual me cabe la duda

**Comment by cilopez** [comment]
Es legal en el caso que menciona @jtescobar1

**Comment by ncasassas** [comment]
Hola, me enrede con esto nuevamente. Hablando con el profe le pregunte esto mismo, que desde mi punto de vista sería:
Definir una namedtuple por cada base que contenga todo lo que la base de datos entregue ( icao,lat,long, etc) y cada vez que quiero leer una consulta abro mi base de datos y creo una lista por compresión que contiene muchas namedtuples con los datos de la base de datos a la que quiero acceder para consultar.(Tal como se hizo para el ejemplo de la ayudantía 2)
Explicado como pretendo usarlas me interesa saber si es legal o no hacer eso ya que si bien el profesor me menciono que se podía hacer aunque no era lo óptimo, quizás pude haberle dado a entender otra cosa con mi consulta por lo que me gustaría confirmar que se puede hacer esto, debido a que he basado todo el código en las namedtuples que defino .

**Comment by cilopez** [comment]
@nko205 Dime que diferencia existe entre tu solución y haber creado una clase viaje que guardara esos atributos, si no existe diferencia, entonces no estas realizado programación funcional  pura.

**Comment by ncasassas** [comment]
Según entiendo por enunciado: "no quiere que utilices clases creadas con el keyword class" y "Para esta tarea no se permite el uso de clases, excepto para usar namedtuples, si es que lo considera necesario".
No podemos usar el keyword class para crear las clases aeropuerto por ejemplo pero si namedtuples que cumplan con un objetivo similar, donde en mi código estas son generadas mediante una lista por compresión. 
Ahora pregunté nuevamente hace un rato por que si bien el profesor me manifestó que lo que yo entendía era correcto ( aunque no óptimo) me generó cierta inquietud la respuesta anterior a mi segundo comentario.

**Comment by cilopez** [comment]
@nko205 si el profesor te respondio eso, no tengo  nada que refutar. Sigue la tarea con esa estructura entonces 😃

**Comment by ncasassas** [comment]
Vale, muchas gracias !
