### ISSUE TITLE
Generadores que no son generadores

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#274]
Hola
Para guardar las respuestas en output.txt tenemos que colocar el tipo de la respuesta, ahora los siguientes tipos son considerados (para efectos de la corrección) como generadores a pesar que su tipo especifico no es "generator"?

itertools._tee
map
filter

Saludos

**Comment by lily416** [comment]
Hola 😄 
Tu duda se responde en la issue #283 

Saludos 👋
