### ISSUE TITLE
Duda filter_passengers (start > end)

### ISSUE THREAD

**Issue by bjruano** [IIC2233/syllabus-2018-2#275]
¡Hola! En la función filter_passengers; si en dado caso no se cumple que start <= end, ¿retornamos un generador únicamente según el icao o se arroja un error?

Gracias!

**Comment by Arcoirisky** [comment]
ese caso especial sería culpa del input ingresado por el usuario? O: Porque puedes asumir que no haremos barbaridades como esa con las consultas xD
Los unicos errores de inputs que debes de controlar son los del menú
