### ISSUE TITLE
Lista de consultas

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#276]
Hola, 

en el enunciado indican que el programa recibirá un conjunto de consultas en formato 
`[consulta_1, consulta_2, ... , consulta_k]`

Esto es una lista, pero en el archivo `queries.txt` no están en este formato. 
Nosotros tenemos que leer un archivo de consultas, pasarlo a lista y luego esta lista procesarla, o nuestro programa debe que estar hecho para poder recibir consultas individuales (como en el caso de queries) como también una lista de consultas?

**Comment by Arcoirisky** [comment]
Hola :D 
vuestro programa debería poder recibir consultas individuales y listas de consultas c:

El archivo queries.txt si bien tiene las consultas individualmente en cada línea, el usuario decide si desea elegir una, varias o todas las consultas de una. Piénsalo como los inputs que algún usuario en el pasado le hizo a tu programa y los guardó para un uso futuro :3
