### ISSUE TITLE
Duda enunciado load_database

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#277]
Hola! No encontré ninguna issue referente al tema:

Al leer el enunciado sale que algunas funciones deben tener el formato:

> load_database(db_type:  str) -> Generator

Pero en los ejemplos y en el archivo *queries.txt* aparecen como:

> {"load_database": ["Airports"]}

Por lo que la variable db_type está contenida en una lista. Puedo asumir que siempre vendrá contenida en una lista y debo "convertirla" en string para llamar a la funcion?

Gracias

**Comment by Arcoirisky** [comment]
Hola :DD 
El enunciado dice, al final de la página 4, en Formato de consulta:

> El formato de una consulta será un diccionario, cuya única _key_ es el nombre de la consulta, y el valor será una lista de largo _k_ con los argumentos que requiere la consulta. Es decir:
{"nombre":  [arg_1, arg_2, ... , arg_k]}

¿Responde tu pregunta? O:
