### ISSUE TITLE
Duda estructuras por comprensión

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#278]
Hola!
¿Se pueden usar estructuras por comprensión que usen más de un for o que usen if y else?
Por ejemplo:
`lista_numeros = [j if j > 10 else j + 10 for i in numeros for j in pares]`
Saludos

**Comment by Arcoirisky** [comment]
Hola!
Tus expresiones generadoras pueden tener todos los for o if/else que gustes :D 

Ojo cuidado con instanciar muchas listas cuando podrían ser generadores 👀

**Comment by inveterate-cladocerus** [comment]
gracias @Arcoirisky!
