### ISSUE TITLE
[PyCharm] - Estructura de proyecto

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2233/syllabus-2018-2#279]
Cada vez que abro `PyCharm`, debo elegir manualmente la carpeta donde está mi proyecto, ya que cuando lo inicio está "trabajando" como dentro del archivo `.py`, (algo como `Tareas/T01/archivo.py`, en vez de `Tareas/T01`) ¿cómo puedo solucionar este problema?

Así se ve:

![image](https://user-images.githubusercontent.com/37163344/45330142-5c88cd00-b53a-11e8-93cd-25bd7eba9ebd.png)

Así quiero que se vea:

![image](https://user-images.githubusercontent.com/37163344/45330554-58f64580-b53c-11e8-9a60-a480e4ddd117.png)

**Comment by Arcoirisky** [comment]
¿Podrías decirme cómo creas tus proyectos? La forma convencional debería ser:
New Project > Pure Python > Location and Interpreter (puede ser una carpeta anteriormente creada o una nueva agregando al Path deseado "\T09") y se debería crear como deseas que se vea O: 

La verdad nunca me a dado ese problema, pero tratemos de ver que pasa! :D

**Comment by VicenteVicente** [comment]
Apreté botón derecho en la carpeta de la tarea, creé un `.txt` y luego lo renombré como `.py`.
¿Está eso mal? 😨

**Comment by VicenteVicente** [comment]
Creé un nuevo proyecto como señalaste, copié y pegué mi código y funcionó correctamente. ¡Gracias! 😸
