### ISSUE TITLE
orden de bases de datos

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2233/syllabus-2018-2#280]
Puedo asumir que las bases de datos vendrán siempre ordenadas de la misma forma?
ej. el archivo "flights-passenger.csv" siempre va vuelo por vuelo diciendo todos los pasajeros?
ej2. el archivo "flights" siempre viene ordendado de la forma airports from?

**Comment by Arcoirisky** [comment]
¿Te refieres a la estructura o al orden de las columnas? 🤔

**Comment by Tomas-Ira** [comment]
El orden de las filas

**Comment by Arcoirisky** [comment]
Aaaah, nop. Eso es mera casualidad y no puedes asumirlo uwu

**Comment by SergioZarateG** [comment]
se puede asumir que el orden de las columnas será siempre el mismo?

**Comment by Arcoirisky** [comment]
No pueden asumir eso o: de aquí en adelante esa suposición siempre será que No u-u
