### ISSUE TITLE
Resultados de consultas que retornan generadores

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#281]
¿Para las consultas que retornan generadores, en la respuesta se deben imprimir los elementos que contiene dicho generador hasta gastarlo?¿Y en este caso es a elección la forma en que dichos elementos se muestran?

**Comment by Arcoirisky** [comment]
Holaa~ 
Si deberías mostrar los elementos :D y la forma en que dichos elementos se muestran puedes dejarla a criterio, mientras se entiendan y sean correctos, estará bien uwu

**Comment by BFFV** [comment]
Ok, gracias!!
