### ISSUE TITLE
Duda furthest distance

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#282]
Hola, no entiendo si para esta consulta lo que hay que entregar es:
 
- Una lista de los n pasajeros que recorrieron más distancia en  _**1 vuelo**_, es decir, que recorrieron la distancia más grande entre el icao (airport_from) y el airport_to de las filas del archivo flights

- Una lista de los n pasajeros que recorrieron más distancia en  _**el total de sus vuelos realizados**_, es decir, que recorrieron la distancia más grande entre el icao (airport_from) y un airport_to más la suma de las distancias de sus otros vuelos.

Saludos

**Comment by nachocontreras** [comment]
Hola!

Hay que entregar la primera opción. 

Saludos! 😄

**Comment by Cadagan** [comment]
Pero esto al final hace que se elijan pasajeros del vuelo que sea hacia mas lejos, y en el enunciado dice que hay que entregarlos de forma decreciente. Como varios irian en un mismo vuelo mas lejano, ¿como los ordenamos?

Para que se entienda mejor: digamos que el vuelo mas lejano desde el icao es el que va hasta "00ID", viaje que tenia a 20 pasajeros.

Si el n viene siendo 10, podriamos entregar 10 pasajeros cualquiera del vuelo, total la distancia maxima se sigue respetando

**Comment by NickCastillo** [comment]
Up

**Comment by nachocontreras** [comment]
#220
