### ISSUE TITLE
Archivo output.txt

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#283]
Hola!

El archivo output.txt vendrá vacío (o no existirá?) cuando revisen la tarea? Lo pregunto porque para leerlas/escribir las consultas hay un formato general pero no específico.
Además, en este archivo se debe poner el type() del resultado de la consulta, dado esto, ¿está bien que salga, por ejemplo, class -filter- en vez de class -generator-? o el resultado de nuestras consultas tiene que ser si o sí un generador?

Gracias!

PD: No sé si es legal, pero cerré una issue que tenía la misma pregunta y pasó a segunda página sin respuesta 😬

**Comment by lily416** [comment]
Hola
 
Tu programa debe ser capaz de soportar si es que el archivo `output.txt` está o no. 
Y está bien que salga `filter`, ya que a fin de cuentas podríamos "decir" que es un generador.

Éxito con la tarea 🛫 
PD: Por favor no cierres las issues, aunque se repita la pregunta.

**Comment by cacoos** [comment]
Gracias!

Si el ```output.txt``` está, vendrá vacío? Ya que no dan un formato del **resultado** de la consulta puede que este esté en muchas lineas, o bien solo una, o distintas estructuras que son a criterio de cada uno.

Gracias!

**Comment by lily416** [comment]
Lo más probable es que no les pasemos el archivo `output.txt`, por lo que podría decirse que estará vacío, pero una vez que escribas tus outputs y consultas debe tu programa debe ser capaz leer la información que necesita del archivo.

Saludos :wave:

**Comment by mericci** [comment]
Esto quiere decir que el archivo output.txt no siempre estará?, en ese caso tendriamos que crearlo nosotros entonces cierto?

Y otra cosa, el archivo siempre tendra el nombre output.txt? o puede tener cualquier nombre que ingresara como input en la consola?

Muchas gracias!

**Comment by lily416** [comment]
@mericci Exactamente, no siempre estará el archivo `output.txt` por lo que se espera que su programa revise si existe y en caso de no ser así lo cree.

Aunque puede tener otro nombre si es que lo especificas en el `README.md`, es preferible que mantenga el nombre que se le pasa en el enunciado.

Saludos y éxito con la tarea 🍀
