### ISSUE TITLE
duda en que base de datos usar

### ISSUE THREAD

**Issue by baltasarluco** [IIC2233/syllabus-2018-2#284]
hola tengo dos dudas, la primera se puede usar Counter de la librería collections y la segunda si es necesario crear un input para escoger que base de datos usar, porque en una issue se respondió que no era necesario, solo se debía agregar un comentario en donde se especifica cual se usa, pero en el feedback aparece que se debe poder escoger cual usar

**Comment by FJavierOss** [comment]
Hola,

Primero para preguntar por librerías tienes que hacerlo en la issue de librerias permitidas. Segundo, como respondimos anteriormente, lo de escoger la base de datos a usar quedaba a criterio en que parte de tu código lo ponías, siempre que menciones su funcionamiento en el README.md. Por ejemplo, si quieres puedes hacer que cuando empieza tu codigo dar la opción de elegir cual base de datos usar para todas las consultas, o lo puedes hacer en cualquier antes de cualquier consulta, lo importante es que quede bien claro el mecanismo usado y bien referenciado. Suerte en tu tarea :smile: 

Saludos
