### ISSUE TITLE
popular_airports airports a considerar 

### ISSUE THREAD

**Issue by fjtobar** [IIC2233/syllabus-2018-2#286]
Hola, sé que en la issue #199 se habla de este tema pero no me queda claro del todo. 

Si un pasajero viaja del aeropuerto A al B, el contador de personas en A y B aumenta? o solo aumenta en B? (Es decir, solo consideramos el aeropuerto de destino del vuelo?).

Saludos

**Comment by nachocontreras** [comment]
Hola!

Solo se considera el aeropuerto de destino.
