### ISSUE TITLE
Interacción con Consola

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#287]
Hola, tengo una duda respecto a como se deben recibir las consultas, ya que en el punto de **Ingresar directamente una consulta por consola**, sale que debe recibirlas de la forma que sale en la sección 2.2.1.  Quería saber, si el tip aplica sobre este punto también, o en verdad la consola **debe** recibir la consulta en el formato que que aparece en la sección 2.2.1.

![image](https://user-images.githubusercontent.com/42249674/45375339-12036100-b5cb-11e8-8584-febb188e0c7d.png)
![image](https://user-images.githubusercontent.com/42249674/45375378-2a737b80-b5cb-11e8-8606-6bdf096c99a3.png)

Muchas gracias!

**Comment by nachocontreras** [comment]
Hola!

El tip también aplica sobre el punto: `Ingresar directamente una consulta por consola`.

Saludos!

**Comment by Cadagan** [comment]
Se supone que el usuario ingresara una a una las consultas? o al elegir esta opcion puede ingresar una lista de consultas tambien? no me queda claro

En la página 4 dice: "El programa a realizar debe soportar el ingrreso de varias consultas. Por lo tanto, el programa **recibira un conjunto de consultas"** de la forma [consulta_1, ..., consulta_k]

Pero en la pagina 8, seccion 3 "Interaccion con consola" solo esta la opcion de "Ingresar directamente **una consulta** por consola"

favor aclarar esto que no se cual de las dos opciones tomar :/

**Comment by nachocontreras** [comment]
Se debe poder ingresar de ambas formas. Un conjunto de consultas o consultas individuales.
