### ISSUE TITLE
Encoding 'utf-8-sig'

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#288]
Se puede trabajar con encoding = 'utf-8-sig'? Que a la hora de trabajar los archivos medium y large, se me agrega el str '\ufeff ' al principio del archivo y me arruina el programa. El encoding con sig lo ignora. (Tengo Mac)

**Comment by Benjadef** [comment]
me pasa exactamente lo mismo, misma pregunta
pd: @NicolasCastillo24 gracias por la solución

**Comment by cilopez** [comment]
Si, perdón ese fue un error mío y de maldito Windows 😭 . Si pueden usar ese encoding, ya arregle las bases de datos para cuando corrigamos asi que si alguien lo tiene en utf-8 y le funciona no tiene porque preocuparse.
