### ISSUE TITLE
Editar valor diccionario anidado

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#290]
Hola!
Estoy tratando de implementar una función con una estructura parecida a esta:

> diccionario = { key : defaultdict( int ) for key in generador }

Y luego iterando sobre 2 estructuras de datos utilizo algo así:

> diccionario[ key ][ key2 ] += 1

El plan es que si el valor no existe se cree y le sume 1 y que si existe le sume al valor existente. Pero por alguna razón me quedan todos los diccionarios anidados con el valor de 1. Me consta que se recorre la base de datos completa y que no se salta valores, pero al parecer si las keys se repiten, se reinicia el contador por alguna razón.

Agradecería alguna forma de solucionar esto :)

**Comment by nachocontreras** [comment]
Hola!

Que raro que se reinicie el contador, porque lo probé y funciona correctamente.
No estarás creando el `diccionario` nuevamente al iterar?
