### ISSUE TITLE
Busqueda binaria en generadores

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#292]
Hola, 

respecto a mi programa que corría muy lento, estuve buscando y una buena forma de hacer que corriera más rápido sería con una búsqueda binaria. El problema es que como son generadores no puedo indexar, por lo que quería saber que opinan al respecto.

Gracias

**Comment by cilopez** [comment]
No se me ocurre como hacer busqueda binaria sin indices,  si corre muy lento no te desesperes concentrate en realizar las consultas.
