### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#293]
Que significa que me apaezca este error??

KeyError: '73'

De antemano muchas gracias.

**Comment by cilopez** [comment]
Hola @marcotroncoso KeyError probablemente significa que estas accediendo a una llave que no existe, a la '73' en particular. Te recomiendo que busques en Google los tipos de errores, en este caso bastaba con buscar 'KeyError' y hay bastante información 😅 .
Saludos.

**Comment by marcotroncoso** [comment]
Jajajajaj yaya esque pense que el '73' significaba algo en particular. Graciaas.

**Comment by marcotroncoso** [comment]
Entonces mi pregunta cambia ahora. Es posible que los archivos esten mal coordinados por asi decir? porque derrepente la consulta si es valida y retorna, pero con otras consultas me tira error.

**Comment by marcotroncoso** [comment]
por ejemplo al hacer consultas con consultas??

**Comment by Fenho** [comment]
me pasa lo mismo, de hecho hice una issue (#300)
