### ISSUE TITLE
Anidar consultas por un filtro de airports

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#295]
Hola!

Habrán consultas donde existan filtros de _airports_ y que pueda fallar la consulta?
Por ejemplo, filtrar _airports_ en ```passenger_miles``` debería eliminar los vuelos que vayan/partan desde esos aeropuertos? o suponemos simplemente que no se filtrará en este tipo de consultas.

Gracias

**Comment by lily416** [comment]
En el caso de que se filtren los aeropuertos o vuelos, solo debes considerar los que quedaron del filtro.

Saludos 👋
