### ISSUE TITLE
Feedback: "Las bases de datos son entregadas como diccionario o namedtuple"

### ISSUE THREAD

**Issue by chocopiano** [IIC2233/syllabus-2018-2#296]
Hola!
 Mi duda va ya que desde el primer día que subieron la tarea me enfoque en que load_database me retornara un generador con cada línea y en cada una de las funciones voy transformando el generador a diccionario. ¿Puedo dejarlo así?, ya que mis funciones que retornan generadores lo estan haciendo de igual forma que mi load_database y no quiero desordenarme con mi codigo. Gracias!

**Comment by lily416** [comment]
Aunque pueda desordenar tu código lo recomendable es que cumplas con lo que se pide en el feedback, por lo que sino no se te podrá dar el puntaje completo en el item 😞 

Aún quedan tres días, 
Ánimo y éxito con la tarea 💪🍀

**Comment by jfacuse** [comment]
Con respecto a esa misma parte del enunciado, no entiendo que es lo que debe ser entregado como dict: Que al consultar sea un dic como el formato que se especifíca en el enunciado o que load_database entregara un dic ? Si es esto último, creo que no está bien debido a que en el enunciado claramente dice que load_database debe devolver un generador, no un diccionario. Lo mismo para todas las otras consultas que retornan bases de datos( Y ya tengo toda mi tarea hecha en base a eso)
O también se me había ocurrido que al hacer la consulta dentro del programa te diera el resultado en forma de diccionario, es eso ?
Salu2 y gracias de antemano!

**Comment by lily416** [comment]
@InfiniteDreamX A lo que se refiere el feedback es que los elementos del generador (los elementos que guardan la información) son diccionarios o namedtuples, no que lo que retorne `load_database` sea un diccionario, si fuera así nos contradeceriamos con el enunciado 👉👈 

Las consultas que deben ir en forma de diccionario, son las que en el enunciado se especifica que ese debe ser su output.

Saludos 🛫
