### ISSUE TITLE
Queries formato

### ISSUE THREAD

**Issue by stmorales** [IIC2233/syllabus-2018-2#297]
Hola!

Nuestro programa debe ser capaz de recibir los parámetros en cualquier orden? O son especificamente los que aparecen en el enunciado. En caso afirmativo de esto último, de las dos consultas en las que se autorizó agregar los aeropuertos, en qué posición las definimos?

Gracias!

**Comment by lily416** [comment]
Debe recibirlos en el orden que aparece en el enunciado. 
Debe estar en la posición que se indica en #215.

Saludos 👋
