### ISSUE TITLE
Duda sobre formula Haversine (Tarea 1)

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#298]
hola!
Tengo la duda de si se debe hacer algo especial al evaluar en la formula de Haversine, algo así como pasar los valores a radianes, etc. porque comparé los resultados de mi función definida en Python con exactamente la misma pero escrita en Wolfram Mathematica y obtengo resultados distintos.

**Comment by lily416** [comment]
Sí, debes pasar las latitudes y longitudes a radianes y el radio de la tierra debe estar en millas.

Saludos 👋🛫

**Comment by BenjaminRubio** [comment]
@lily416 con millas te refieres a millas náuticas como en el enunciado? (3440 millas náuticas)

**Comment by lily416** [comment]
@BenjaminRubio Exacto
