### ISSUE TITLE
Instalar git en macOS

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#3]
- **Sistema Operativo: macOS**
- **Programa a instalar: Git**

- Descripción del problema: mi mac no viene con git instalado y quería saber cual es la mejor forma de instalarlo ya que cuando lo intento descargar por la página de Git no me funciona.
Muchas gracias!!

**Comment by jecastro1** [comment]
Hola!

Como usuario de macOS lo más cómodo es, primero, instalar [`brew`](https://brew.sh/). `brew`, tal y como se define a sí mismo, es el gestor de paquetes que le falta a macOS.

Con `brew` es súper fácil instalar muchas cosas, entre ellas, `git`. Ya teniendo `brew`, sólo basta poner el comando `brew install git`. 

Saludos.
