### ISSUE TITLE
Formato Del Calendario

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#30]
¿Como debo mostrar el calendario? Lo pregunto porque en mi mente me imagine literalmente un calendario con eventos en las casillas de cada día (en el que hubiese un evento) pero aquello ocuparía mucho espacio, ¿Se puede hacer un listado que diga próximos eventos en orden o {sin eventos}?

**Comment by cilopez** [comment]
- Como no sale específicado en el enunciado puedes desplegar el calendario como quieras, **cumpliendo** los requisitos señalados. 
- Puedes agregar una pequeña descripción de porqué lo hiciste así en tu _readme_ y si es que es necesario detallar cómo funciona tu visualización. 
-  Puedes hacerlo con ese listado si te parece prudente y no dejas nada de lado.
