### ISSUE TITLE
Data que usaran al evaluar

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#300]
Hola, me di cuenta que algunas consultas de queries.txt no sirven para el data small y medium, al no exisitir cosas como por ejemplo el icao "SJCO" de la consulta: 

> {"filter_airports_by_distance": [{"load_database": ["Airports"]}, "SCJO", 3141.59, True]}

Todo, por ahora, existe en los datos de "large".
Pensaba que podíamos suponer que el input existiría y no tendría errores (en esta parte).
¿Van a corregir solo con los datos de large?

**Comment by cilopez** [comment]
No te puedo responder con que vamos a corregir , pero el queries lo puedes editar, lo hicimos para que tuvieran un archivo con el cual probar y si puedes suponer que el input existirá.
