### ISSUE TITLE
Duda ejemplos de furthest_distance

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#301]
Hola, leyendo otra issue entendí que en esta consulta se deben considerar sólo vuelos que parten desde el icao dado como argumento, lo que significa que si ningún vuelo parte desde el icao dado, la lista que se retorna será vacía. Esto ocurre para ambos ejemplos del enunciado, por lo que me entró la duda de si simplemente los ejemplos no eran los mejores para probar, o si en realidad sí se consideran vuelos que parten de otros aeropuertos.

**Comment by Coolgatty** [comment]
Tengo la misma duda los icaos de los ejemplos no estan en ningun "airport_from"
