### ISSUE TITLE
Formato del output de passenger_miles

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#302]
En otra issue se mencionó que en las consultas que pedían personas (sin especificar qué atributo), se debía retornar como mínimo el nombre e id de la persona. En el caso de la consulta passenger_miles que retorna un diccionario, ¿no se pueden utilizar mejor los id de cada persona para que tenga más sentido como key del diccionario?

**Comment by lily416** [comment]
Sí, puedes hacerlo. Por si acaso especificalo en el readme.

Saludos 🛫

**Comment by BFFV** [comment]
Gracias!
