### ISSUE TITLE
Desempaquetar generadores

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#303]
Se que se ha preguntado anteriormente y que se explica breve mente en el enunciado de la tarea, pero sigo sin entender una cosa. Mi duda es que si yo tengo el generador "airport", puedo desempaquetarlo con un "for".

Ejemplo:

For x in airport:

Gracias!

**Comment by IchottMano** [comment]
@ftrejoc Hola!

No, no puedes hacer esto a menos que se trate de un *loop* permitido, es decir que esté dentro de una expresión generadora, una función generadora, contenedores por comprensión o un *forEach*

Saludos!
