### ISSUE TITLE
further_distance

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#306]
En el enunciado, se expresa que la función further_distance  "retorna una lista ordenada de forma decreciente con los n pasajeros que pasaron por el aeropuerto cuyo destino ﬁnal está más lejos de este". Para saber qué tan lejos está cada aeropuerto necesito un generador con los aeropuertos. Sin embargo, en el enunciado no aparece como argumento de la consulta. ¿Puedo usar la base de datos de los aeropuertos de todas maneras?

**Comment by BenjaminRubio** [comment]
#215
