### ISSUE TITLE
Uso correcto de foreach y formas de iteración

### ISSUE THREAD

**Issue by FelipeBodelon** [IIC2233/syllabus-2018-2#308]
Hola,

Me gustaría saber si este uso de la función **foreach** es legal o si se considera un abuso de las condiciones:

```
dicc = {"1": [], "2": [], "3": []}
iterable = [("1", 123), ("1", 122), ("2", 123), ("2", 323), ("2", 133), ("3", 123)]  
foreach(lambda x: dicc[x[0]].append(x[1]), iterable)
```

para obtener un diccionario de la forma:

`dicc = {"1": [123, 122], "2": [123, 322, 133], "3": [123]}`

Además, he notado que haciendo lo siguiente se obtiene lo mismo, pero sin el uso de foreach:

```
dicc = {"1": [], "2": [], "3": []}
iterable = [("1",123), ("1",122), ("2",123), ("2",323), ("2",133), ("3",123)]
generador = map(lambda x: dicc[x[0]].append(x[1]), iterable)
_ = [x for x in generador]
```

¿Están algunos de los 2 casos prohibidos? Asumiría que el primer caso sí, ya que quizás se consideraría que se esta modificando algo con el foreach, pero estoy en duda con el segundo caso ya que no se utiliza el foreach y solo se utiliza map y una estructura por comprensión (que según el enunciado se pueden utilizar), aunque se hace lo mismo.

**Comment by johntrombon** [comment]
Tu primer ejemplo no me parece ilegal. En el enunciado dice que los foreach son legales mientras no se altere el "input" de la función. Si se entiende como _input_ al iterable que recibe foreach como parametro, no lo estas editando, solo estas escribiendo la informacion de tu iterable en otras estructuras de datos. De hecho, se parece al ejemplo _save_flight_ que está en la parte 5.1 del enunciado.
Por otra parte, el segundo hace lo mismo pero con la diferencia que cuando creas tu lista "_",  si no me equivoco, estás usando memoria en una lista que almacena puros _None_.
De todas formas me interesa mucho lo que tengan que decir los ayudantes sobre esto 👀, +1 a tu issue.

**Comment by gnacrur** [comment]
Yo también le he dado muchas vueltas a esto y creo que la primera forma es ilegal (algo que concluí después de revisar la tarea funcional del semestre pasado donde se entendía mejor que se podría y no podía hacer). Ojala la segunda forma sea legal y ojala alguien responda antes de que sea fin de semana! 
cps

**Comment by Michelmagna** [comment]
Comento para sabeeer.

**Comment by NachoJuanDev** [comment]
A mi se me ocurrió algo muy similar a la segunda idea de @FelipeBodelon , creo una función `my_function` que recibe dos valores los que, según la necesidad que tenga, serán añadidos a un diccionario vació. Esto lo aplicaría de la siguiente forma:

    dic = dict()
    def my_function(x, y):
        #Añadiría a dic después de aplicar algún criterio
        dic[x] = y
        return False
    #No necesito guardar nada de map, sólo me interesa dic
    map(lamba a: my_funcition(a.x, a.y), iterable)

Me gustaría saber si esto es legal o ilegal.

**Comment by camichavez** [comment]
Hola! 
El primer caso si está prohibido pero el segundo no :) 
Ánimo a todos!
