### ISSUE TITLE
Duda sobre las 15 líneas máximas

### ISSUE THREAD

**Issue by firulais33** [IIC2233/syllabus-2018-2#309]
Hola, 

Una duda sobre el largo de las funciones. Primero, ¿las líneas de comentario cuentan dentro de las 15? Con comentarios me refiero a la documentación.

Y en segundo lugar, hay casos en donde declaro funciones dentro de otras funciones. Con esto me paso de las 15 líneas. Ahora bien, podría cumplir con el requisito fácilmente declarando estas funciones fuera del _scope_ de mi función grande, pero no tiene ningún sentido declararlas de manera tan general. ¿Qué sugieren?

Saludos!

**Comment by bgsamilla** [comment]
#208 
:D

**Comment by FJavierOss** [comment]
Hola, 

Efectivamente la #208 responde a la segunda pregunta. Para la primera pregunta las lineas de codigo son las que se cuentan, los comentarios no se cuentan dentro del limite de 15 lineas. Suerte en tu tarea.

Saludos

**Comment by firulais33** [comment]
Gracias!!
