### ISSUE TITLE
furthest_distance

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#310]
Hola! 

Leyendo las issues sobre esta función, leí dos cosas que creo que son contrarias:

Entiendo que la función furthest_distance debe retornar a los n pasajeros que toman el vuelo con destino más lejano desde el icao dado. (*Está bien, no?*)

En la issue #262 se dijo que se debe incluir más de una vez a una persona en caso de repetirse     *(para un n grande por ejemplo, en el que hay que tomar más de un vuelo lejano desde el icao en cuenta)*.

Pero en #220 se preguntó:

> En furthest_distance si tenemos repetido el pasajero dentro del top n que hacemos?
Lo colocamos repetido?

A lo que se respondió:

> vamos a subir una base de datos donde no se pueden repetir pasajeros en el mismo vuelo (esto no debería pasar nunca), así que no te preocupes por eso

Por lo que no sé si tomar en cuenta solo una vez a cada pasajero o debo hacer listas y luego ir usando el mayor elemento cada vez que aparece la persona. ~~¿O Con destino final se refiere a que se deben tomar en cuenta series de vuelos? Ej: icaoinicial -> icao1 -> icao2 -> icaofinal~~

Gracias!

**Comment by inveterate-cladocerus** [comment]
> ¿O Con destino final se refiere a que se deben tomar en cuenta series de vuelos? Ej: icaoinicial -> icao1 -> icao2 -> icaofinal

revisa el #282 :)
