### ISSUE TITLE
Manejo de generadores en funciones

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#311]
Hola, 

lo que pasa es que tengo los generadores de los archivos, que son todos en forma de yield de nametuple de cada fila. 

La cosa es que trabajar con esos es incomodo y a veces poco eficiente (en filter flights paso por cada vuelo encima de todos los aropuertos). 

No será mejor convertir al generador en un diccionario(icao: aeropuerto) una sola vez con todos los aeropuertos y de ahi buscar los aeropuertos en ese diccionario para todos los vuelos?
Que opinan?

**Comment by inveterate-cladocerus** [comment]
cps

**Comment by BenjaminRubio** [comment]
Si se puede (#203)

**Comment by Kitaps** [comment]
gracias
