### ISSUE TITLE
Abrir un archivo y listar generadores

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#312]
Hola! Dos dudas:
1.¿Podemos asumir que cuando el usuario quiera abrir un archivo de consultas ingresará el nombre de un archivo que realmente existe? (¿O siempre se llamará queries.txt?)
2. Si se que en otras issues ya respondieron que se pueden convertir generadores a lista por comprensión para que no se "gasten" y se puedan utilizar mas veces, es legal usar list(generador) en vez de hacerlo por comprensión?

**Comment by cilopez** [comment]
- Eso no está explicíto en el enunciado, puedes tomar un supuesto y mencionarlo en el readme.
- No estoy 100% seguro por lo que no te puedo responder a secas, probablemente si puedas.
