### ISSUE TITLE
Duda favourite_airport

### ISSUE THREAD

**Issue by iamoreno** [IIC2233/syllabus-2018-2#313]
Hola, leí la issue #197, mi duda es la siguiente, dado que no todos los pasajeros que hay en la base viajan, ¿puedo hacer esta función de modo que retorne como keys solo el id de los pasajeros que viajan? y que no tenga entre sus keys todos los id, de todos los pasajeros de la base.
Graciaaas!

**Comment by lily416** [comment]
Sí puedes, por si acaso especificalo en el readme.

Éxito en la tarea 🍀
