### ISSUE TITLE
Demora consultas con bases de datos "large"

### ISSUE THREAD

**Issue by dtmaltrain** [IIC2233/syllabus-2018-2#314]
Hola!, quería saber cuál es el limite "aceptable" de tiempo para que se demoren las consultas en las bases de datos "large" 🤔 ⏲

**Comment by Coolgatty** [comment]
🤔 🤔 🤔 🤔

**Comment by degutierrez1** [comment]
:thinking: :thinking: :thinking: :thinking: :thinking:

**Comment by cilopez** [comment]
Hola @DaToMC9 @degutierrez1  @Coolgatty  si ven en el feedback no se especifica puntaje por la demora en las consultas, pero obviamente si te corregimos con la base small y te demoras 2 minutos o con la large 10  o más minutos  entonces revisaremos con mayor atención tu código, porque de seguro que si te demoras eso estas aplicando mal tus funciones generadoras.
