### ISSUE TITLE
Uso de Ticks

### ISSUE THREAD

**Issue by fabarros** [IIC2233/syllabus-2018-2#315]
En mi vida había escuchado eso, y en internet no encuentro información relacionada con el uso de datetime. Pueden especificar por qué recomiendan su uso?
Gracias y saludos.

**Comment by cilopez** [comment]
¿Te has preguntado como el computador almacena el tiempo, bueno la verdad es que a eso apuntaba la recomendación, puedes leer en profundidad del tema [aquí](https://en.wikipedia.org/wiki/System_time).

Básicamente como los computadores "funcionan" con 1 y 0's entonces existe una forma de guardar las fechas y tiempos solo con números.
