### ISSUE TITLE
Duda enunciado filter_passengers

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#316]
Hola, en filter_passengers dice "Recibe un generadores con pasajeros, vuelos y viajes"  eso me dejo confuso, pues Recibe **_UN_** generador(**ES**) con pasajeros,vuelos y viajes, no entendí si recibo 3 generadores, un con cada elemento, o si recibo 1 generador con las 3 cosas.
♥

**Comment by lily416** [comment]
Recibe **3** generadores.

Perdón por el error de tipeo,
Saludos 🛫
