### ISSUE TITLE
duda funcion filter_airports_by_distance

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#317]
hola!

tengo la duda de que el generador que debe retornar debe incluir al mismo aeropuerto de referencia en el caso de que me pidan todos los aeropuertos a una distancia menor a 'X', ya que la distancia desde un aeropuerto a el mismo aeropuerto es 0 y cumple con la condicion

**Comment by vjlira** [comment]
Hola, esto queda a tu criterio, no hay problema con ninguno de los casos. Suerte!
