### ISSUE TITLE
Pasar de string a operador de comparación

### ISSUE THREAD

**Issue by Etienne99** [IIC2233/syllabus-2018-2#318]
Hola, en caso de que tenga que hacer una comparación y no sepa con qué operador se va a hacer esta comparación (>, <, ==, !=, etc.) ¿hay alguna forma de generalizarlo para que python lo interprete como comparación y no como string?

Por ejemplo, si quiero comparar dos ints:

```python
operador = input( )
expresion = 100 + " operador " + 200
if expresion:
    print(True)
```

Algo así, pero que funcione como comparación y no como string. 😅

**Comment by fgbruna** [comment]
Te recomiendo pensar en cual estructura de datos puedes asociar strings a funciones y echarle un  👀  a [#188](https://github.com/IIC2233/syllabus/issues/188)

**Comment by Etienne99** [comment]
Gracias😁
