### ISSUE TITLE
Generadores en output.txt

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#319]
En el enunciado me piden que escriba en output.txt el resultado de cada consulta según el formato 2.2.1.. En el caso de los generadores, ¿habría que escribirlos en el archivo de la forma '<filter object at 0x000002893E301630>' así no más, o habría que convertirlos a listas o algo por el estilo?

Muchas gracias!

**Comment by lily416** [comment]
Como se dice en #283 se espera que hagan `type()` del output, por lo que estaría correcto.

Saludos 👋
