### ISSUE TITLE
Lectura de archivos

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/syllabus-2018-2#320]
Cuando leo los archivos, mi programa crea namedtuples con la información de cada linea, pero me di cuenta que con los archivos médium y large, mi programa al parecer sin ninguna razón se salta muchísimas lineas, 2000 en el médiums y 50000 en el large, no se porque podría estar pasando esto, ayuda por favor, me di cuenta al hacer un:
for line in file:
       print (named tuple)

tambien, al hacer print de estos archivos, me salen cosas raras en los primeros prints, como strings cortados, es como que se bugeara siento

**Comment by NicolasLahsen** [comment]
Probaste con `with open ()`?

**Comment by Benjadef** [comment]
si claro, para hacer el "for line in file" , antes va el with open, solo que no lo puse en la issue 🤔

**Comment by bgsamilla** [comment]
Yo en tu lugar intentaría hacer print tanto de la linea sin procesar y de la linea procesada, para saber si esta ignorando completamente la linea del archivo o hay algún problema con como estas generando la namedtuple. Encontrar alguna relación entre las lineas problemáticas puede ayudar también .....

Es muy raro esto .....

**Comment by Benjadef** [comment]
hice lo que me dijiste, sigue pasando lo mismo, las ignora cuando quiere, ahora con los datos médiums mágicamente no los ignora, pero con los large sigue pasando lo mismo, pero por ejemplo si hago un 
for line in file:
     print(line)
     time.sleep(1)

ahí no los ignora, es muy extraño, tengo la tincada de que es un problema de pycharm y que enrrealidad si los imprime pero no se ven algo así, preguntare en clases mejor, gracias!

**Comment by felipegarcia98** [comment]
a mi tmbn me pasa, pero segun yo es porque la consola tiene limite de caracteres y lineas. Creo que la consola tiene un limite de 150000 lineas y cada linea un limite de 1050000 caracteres (mostrando esos ultimos caracteres del print de la linea

Si pones lo siguiente puedes ver el bugazo en numeros
`i=0; while True: print(i for i in range(1000000); i+= 1`

**Comment by jecastro1** [comment]
Me parece muy familiar esta pregunta 🙂

Contesté en clases, pero lo dejo para todos: efectivamente, tiene relación con el límite de líneas de la consola. No todas tienen el mismo límite, y a veces, este límite puede ser pequeño. En este caso, al parecer, el límite del simulador de consola de PyCharm no es muy alto. 

No está de más decir que esto no tiene ningún efecto en los datos que maneja el programa.

Saludos.
