### ISSUE TITLE
Largo de funciones: uso de variables globales

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#323]
¿Es legal definir un diccionario que uso en una función fuera de esta? (pensando en que las funciones tienen como máximo lineas)

Muchas gracias

**Comment by rhanuch** [comment]
¡Hola @mericci !

Lo que preguntas no es permitido, ya que implicaría el uso de variables globales, las cuales, en general, son mala práctica 😬

¡Saludos y éxito! 🍀

**Comment by inveterate-cladocerus** [comment]
Hola @rihanuch , no me quedó claro lo de las variables globales, es decir, si yo defino una namedtuple fuera de una función, por ejemplo 
```python
Pelicula = namedtuple('Pelicula', ['nombre', 'actores', 'director'])
```
 y después la uso en una función, ¿contaría como malo en la Tarea?

**Comment by rhanuch** [comment]
¡Hola @Prochotito !

En **ese caso** en específico no. **Pero** esto es porque definir una `namedtuple` es diferente a guardarla. Piensa que definir una `namedtuple` es como definir una clase. La definición por si sola no hace nada. Lo que **sí** sería el uso de una variable global sería el instanciar una `namedtuple` fuera de funciones y hacer llamados a esa instancia ☎️ 

¡Saludos y éxito! 🍀

**Comment by inveterate-cladocerus** [comment]
Gracias!
