### ISSUE TITLE
Función generadora  con doble for 

### ISSUE THREAD

**Issue by jptorres1** [IIC2233/syllabus-2018-2#325]
¿Se puede hacer una función de la siguiente forma?
>_def_ _funcion(x):_
>>_for a in x:_
>>>_for b in a:_
>>>>_yield a, b_

**Comment by vjlira** [comment]
Hola, no hay ningún problema con hacer eso. Suerte

**Comment by tamaralues** [comment]
y se puede hacer si el yield aqui:
def funcion(x):
              for a in x:

                        for b in a:
               
                         yield a, b

**Comment by tamaralues** [comment]
y si esta asi 
def funcion(x)
 .       for a in x:
 .                 for b in a :
                    yield a, b 


???

**Comment by miguelramirezv** [comment]
Hola! Y hacer esto?:

def funcion(x):

    for a in x:

        for b in a:

    yield a, b
