### ISSUE TITLE
Eliminar consultas de output.txt

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#326]
Hola, tengo una pregunta un poco obvia, pero al momento de eliminar una consulta de output.txt es necesario cambiar los numeros del resto de las consultas cierto?

Muchas gracias!

**Comment by cacoos** [comment]
Según yo es a tu criterio🤷🏽‍♂️. No indican nada al respecto
En mi caso no cambié los numeros, para así saber cuándo las había hecho

**Comment by inveterate-cladocerus** [comment]
cps

**Comment by jecastro1** [comment]
No se compliquen con eso. Queda a su criterio.
