### ISSUE TITLE
*args,**kwargs en clases abstractas

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#327]
![image](https://user-images.githubusercontent.com/41979332/45466726-fc3c8b80-b6f1-11e8-8fbb-9a41e29e4321.png)

He revisado este código con detención pero no logro entender por qué arroja errores al inicializar una subclase utilizando *args y **kwargs.

**Comment by jfacuse** [comment]
es porque el init de consola y portatil no tiene el parametro **kwargs! (Al menos así me resulto a mi)

**Comment by jmndoza** [comment]
Como dice @InfiniteDreamX, portátil y consola no tienen **kwargs.
intentas enviarle 3 parámetros a cada uno y esperan 1 o 2 (consola y portátil, respectivamente)

**Comment by santilaguna** [comment]
Hola @danielaguilera efectivamente como menciona @InfiniteDreamX  debes incluir *args y **kwargs en los __init__ de las clases padres, puesto que al realizar `super().__init__(*args, **kwargs)` le estás entregando todos los argumentos a los métodos de las clases padres. Es decir, el problema surge porque el método `__init__` de Consola y Portatil reciben más argumentos de los que les estás permitiendo recibir.  Además recuerda que como Portatil y Consola heredan de ABC también debes llamar al `super().__init__()` para utilizar el constructor de la clase ABC. 
=D

**Comment by fgbruna** [comment]
Hola @danielaguilera ! lo que te dijo @santilaguna es, en resumen, lo que está pasando.
Si lo pensamos un poco más en detalle
resulta que lo que necesitas hacer para poder usar tanto `kwargs` como `args` en los llamados a la clase hija debes "preparar" a las clases padre para recibir cualquier tipo de argumento, ya que, por el `__mro__` el orden de herencia se linealizará.Es decir, en este caso, los argumentos que reciba `NintendoSwitch` pasaran primero a `Consola` y luego a `Portatil` las cuales en el codigo de la ayudantia no estaban preparadas para recibir ni `kwargs` ni una cantidad arbitraria de argumentos posicionales `args`.
Es decir si le pasabas argumentos posicionales que no estaban definidos de manera previa, se iba a gatillar un error en `Consola`.
El siguiente código funciona ya que permitimos que `Consola` y `Portatil` reciban todo lo que les pasemos, __tomen__ lo que necesiten y le pasen el resto a la siguiente clase en el `mro`.
```python
from abc import ABC  # En caso de no haberlo hecho antes


class Consola(ABC):
    """Consola de videojuegos regular"""

    def __init__(self, cable, *args, **kw):
        super().__init__(*args, **kw)
        self.cables = cable


class Portatil(ABC):
    """Consola de videojuegos portatil"""

    def __init__(self, bateria, pantalla, *args, **kw):
        super().__init__(*args, *kw)
        self.bateria = bateria
        self.pantalla = pantalla


class NintendoSwitch(Consola, Portatil):
    """Consola hibrida! :o"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


def main():
    switch = NintendoSwitch("VGA", bateria="1KAh", pantalla="22in")
    # {'bateria': '1KAh', 'pantalla': '22in', 'cables': 'VGA'}
    print(switch.__dict__)
    print(NintendoSwitch.__mro__)
    # (<class '__main__.NintendoSwitch'>, <class '__main__.Consola'>,
    # <class '__main__.Portatil'>, <class 'abc.ABC'>, <class 'object'>)


if __name__ == '__main__':
    main()

```
Si no te queda claro, me dices (:

**Comment by danielaguilera** [comment]
Hola @fgbruna!
Me funcionó y entendí la explicación. Sin embargo, cuando llamo a los atributos de la nintendo switch, el programa me tira error diciendo que no existen los atributos bateria y pantalla:

![image](https://user-images.githubusercontent.com/41979332/45496892-ce386500-b74c-11e8-8718-764b9b4618f9.png)

Gracias!

**Comment by fgbruna** [comment]
@danielaguilera , te faltó llamar a `super` con los args y kwargs en los init de las clases
