### ISSUE TITLE
Consulta popular_airport

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#328]
Hola!

tengo la duda de que: en el caso de que nos pidan los aeropuertos que reciban más gente, como gente debo considerar la cantidad de personas que visitaron el aeropuerto o la cantidad de visitas? ya que se puede dar el caso de que un pasajero visite el mismo aeropuerto más de una vez, entonces la cantidad de personas que pasan por el aeropuerto puede ser menor a la cantidad de visitas que ha tenido el aeropuerto y cual es el correcto.

**Comment by cilopez** [comment]
Si se visita más de una vez, el pasajero se vuelve a contar.
