### ISSUE TITLE
Uso de split()

### ISSUE THREAD

**Issue by jncaceres** [IIC2233/syllabus-2018-2#329]
Hola :) 
¿Se puede utilizar split para generar una lista de las consultas que quiere realizar el usuario?
me refiero a la parte en que se lee un archivo y puede escoger varias consultas de el

**Comment by fernandodediegoavila** [comment]
Hola!
No está permitido utilizar split en tal situación, por lo que deberás buscar una solución alternativa.
Mucho éxito!

**Comment by cacoos** [comment]
Una pregunta, por qué no se podría utilizar split?
Tampoco sé por qué hay que preguntar estas cosas, siendo que en la Issue de _built-in_ prohibidos no se menciona nada, y en el enunciado tampoco.

Además, este split se podría utilizar dentro del _scope_ de la función, donde después de retornar ya no estaría ocupando memoria, por lo que no veo el problema. Por otra parte, qué pasaba si esta Issue no se publicaba? baja puntos tener split?

**PD**: Sorry por editar tantas veces

**Comment by fernandodediegoavila** [comment]
Las consultas del archivo queries.txt fueron pensadas desde un comienzo para ser respondidas sin utilizar split, ya que consideramos que hay un método más efectivo que conocen hace tiempo (como hint, quizás les sea útil consultar las issues de la Tarea 3 del 2018-1).
Recuerda que, pese a que algo no sea mencionado en enunciado, al momento de aparecer en las issues se considera como información oficial. Nunca está de más preguntar si un built-in se puede utilizar o no (en el caso de las librerías es obligación si no aparece entre las librerías permitidas).

**Comment by jncaceres** [comment]
Pero no es para responder las queries, yo me refiero a cuando yo le muestre todas las consultas, y el usuario escriba las consultas que quiere realizar en este formato:
1,2,3,4..etc
poder usar split para almacenar los numeros de las consultas que quiere realizar.
Muchas gracias 😊

**Comment by cacoos** [comment]
Eso! yo también me refiero a lo de arriba.

Gracias por la respuesta

**Comment by fernandodediegoavila** [comment]
Te refieres a lo mencionado en la sección 2.2.1? Mientras las consultas sean independientes,  utilízalo como estimes conveniente. Para resolver consultas anidadas se espera que utilices el método del que hablamos anteriormente. Ojo con no traspasar las otras restricciones de las funciones descritas en enunciado.
Saludos!

**Comment by cacoos** [comment]
Nos referimos al input del usuario del estilo
numeros = input("Escribe consultas a abrir")
mostrar_consultas(numeros.split)

Muchas gracias!

**Comment by fernandodediegoavila** [comment]
Sí pueden.
