### ISSUE TITLE
¿Puedo utilizar la librería collections?

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#33]
Hola, quería preguntar si puedo usar la librería collections para utilizar estructuras de dato eficientes en memoria para la tarea, como namedtuples y defaultdicts.

Muchas gracias

**Comment by naquiroz** [comment]
Hola! Para estas dudas debes revisar y comentar la issue correspondiente a la tarea en cuestión. En este caso es la #12.
