### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#331]
Que es lo que le pasa a mi codigo si aparece el KeyboardInterrupt del except de main.

**Comment by bimartinez** [comment]
Hola!

Puedes dar más detalles del error? Generalmente la excepción KeyboardInterrupt viene dada por que tu programa fue interrumpido por una combinación de teclas (generalmente es CTRL + C).

Saludos!

**Comment by marcotroncoso** [comment]
Graciaas
