### ISSUE TITLE
StopAsyncIteration

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#332]
Hola! se puede usar StopAsyncIteration para detener la iteración una vez que un generador se haya acabado para así evitar el tipico error "list index out of range"? No se si esta "función" (StopAsyncIteration) cuenta como algo dentro de 'Exceptions' o no 🤔

**Comment by Drpinto1** [comment]
Saludos!
Las preguntas de este tipo se deben hacer en [#188](https://github.com/IIC2233/syllabus/issues/188) :smile:
