### ISSUE TITLE
generadores a partir de funcion filter

### ISSUE THREAD

**Issue by dberezin** [IIC2233/syllabus-2018-2#333]
para la función que filtra vuelos por distancia o por fecha, recibo un generador de aeropuertos y otro de vuelos. En el caso del de fecha, utilizo la funcion filter. El pseudocódigo es algo así:

for i in filter(lambda x: x filtrados, vuelos)
yield i

Al correr el programa me da el error NoneType is not an iterator. Sin embargo, si reemplazo yield por print, obtengo exactamente el resultado que quiero. Cómo puedo hacer un generador a partir de la función filter?

**Comment by lily416** [comment]
De por sí se puede decir que filter es un generador, así que no debería haber problema con que lo retornes tal cual está.

Saludos :wave:

**Comment by dberezin** [comment]
Si dentro de la función escribo 
    gen = filter...
    print(next(gen))

entonces funciona. pero si hago
    gen = filter....
    return gen

y luego llamo a la funcion 
    vuelos = filtrar()
    print(next(vuelos))

me dice que no es iterable, que es un NoneType.

**Comment by dberezin** [comment]
Disculpa, ya lo solucioné! 

Era una cadena de funciones que se llaman sucesivamente y en una de esas llamaba a una función sin que fuese el return. estaba ejecutandola sin devolver el valor.
