### ISSUE TITLE
KeyboardInterrupt()

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#334]
Hola! Se que respondieron una issue en la que decían que este problema puede ser por un (Ctrl + C) pero e intentado escribirlo a mano y me sigue tirando el mismo error de:
except KeyboardInterrupt():
TypeError: catching classes that do not inherit from BaseException is not allowed

Espero su respuesta,
 muchas gracias!

**Comment by jecastro1** [comment]
Hola @ftrejoc 

Muchas gracias por tu comentario. 

La materia de excepciones se ve después en el curso, pero a grandes rasgos, esa línea intentaba que cuando se hiciera un CTRL+C, el programa se cerrara "bien", llamando explícitamente a `exit()`. 

Y claro, el programa se cierra, pero además tira ese error que describes. Eso es porque lo que esa línea debería decir es:

```python
except KeyboardInterrupt:
```

La diferencia, como puedes ver, son los paréntesis. En todo caso, esta situación no tiene ninguna repercusión en esta tarea, por lo que no hay nada de que preocuparse (aunque si quieres, puedes cambiar la línea a la que puse yo).

Sin embargo, si este error te está apareciendo sin hacer CTRL+C, entonces tienes otro error en alguna parte de tu programa. Deberías poder ver el _traceback_ de tu error un poco antes de este error que nos estás mostrando.

Cualquier duda adicional estamos para responder,

Saludos
