### ISSUE TITLE
Filter_flights y el símbolo de comparación

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#335]
Hola, 
En FIlter_flights recibimos un símbolo de comparación, pero no estoy logrando ocupar ese símbolo sin que me genere error o que me pase de 15 lineas la funcion, Ejemplo: filt = filter(lambda x: x.date símbolo value, list(generator_vuelos))
        return (filt)
cuando hago eso python me tira SyntaxError: invalid syntax, intente definir simb = > por default y me tirar error tambien, y si hago para todos los casos me pasa de 15 líneas. Intente hacer en una función, pero no se como retornar >,<,!=,>= etc (tambien me tira error) 
Disculpe tener una duda tan idiota 
Muchas gracias adelantado ♥

**Comment by fernandodediegoavila** [comment]
Hola!
Existen librerías predeterminadas que te pueden ayudar. Te recomiendo revisar #188!
Saludos
