### ISSUE TITLE
Counter de collections

### ISSUE THREAD

**Issue by gejohow** [IIC2233/syllabus-2018-2#336]
Hola queria saber si como esta permitido usar la libreria collections se puede usar la herramienta Counter perteneciente a esta libreria que me salió buscando en Stackoverflow (https://stackoverflow.com/questions/2161752/how-to-count-the-frequency-of-the-elements-in-a-list/2162045).
Saludos

**Comment by fernandodediegoavila** [comment]
Hola!
Pregunta en #188, que es la issue de librerías y built-ins permitidos.
Saludos
