### ISSUE TITLE
Uso de list(generador) 

### ISSUE THREAD

**Issue by adpolanco** [IIC2233/syllabus-2018-2#337]
Tengo una lista de generadores y quiero pasarlo a lista de listas para imprimirlos después. La única manera que se me ocurre es haciendo list(generador) para cada uno de ellos, es legal hacer eso?
Saludos

**Comment by rhanuch** [comment]
¡Hola @adpolanco !

Esto ya fue respondido en la issue #203 

¡Saludos y buen [18 💃🍷](https://www.youtube.com/watch?v=660flk1hiDM)!
