### ISSUE TITLE
diccionario de funciones

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/syllabus-2018-2#338]
Hola!
Sé que en otras issues han dicho que no es bueno definir variabes globales, pero me gustaría saber si es ilegal definir como variable global un diccionario de funciones para leer las consultas que vienen como string (uso como keys los nombres de las funciones y como valores del dict las funciones). No sé si hay otra forma de hacerlo pero al menos es lo que se me ocurre para simplificar un poco el procesamiento de las consultas
De antemano gracias  :)

**Comment by cilopez** [comment]
Suena bien, como usas esa variable solo para ahorrar lineas de código no veo el porqué de negartelo.
