### ISSUE TITLE
tamaño base a usar

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#339]
Hola, solo quería saber si es necesario preguntarle al usuario que tamaño de base desea usar? No encontré nada al respecto en el enunciado pero en el feedback se entiende que tiene puntaje. Hasta ahora la forma de cambiar el tamaño de la base en mi programa era cambiando el path escrito directamente en el codigo. En el caso de que sea necesario, podría como excepción usar un input que queda como variable global para no tener que cambiar todo el código?

**Comment by cilopez** [comment]
Usalo como una variable nomás, mencionalo en tu readme y deja por defecto la base medium.

**Comment by gnacrur** [comment]
@cilopez Gracias por responder tan rapido! No me quedo claro si te refieres a que si le pregunte al usuario y defina el input como variable global o que no.

**Comment by cilopez** [comment]
Puedes hacerlo de ambas formas, si lo haces como variable global entonces señalalo porfavor y referencia a esta issue.
