### ISSUE TITLE
.gitignored

### ISSUE THREAD

**Issue by skarlezib** [IIC2233/syllabus-2018-2#341]
Antes de proceder a hacer la issue, pregúntate: 

1. ¿Está esto en el [feedback](https://docs.google.com/spreadsheets/d/1KIr7m7c84R1EMRuSgVwRFfPoA1tFHWmwKtauQ1TxBIs/edit#gid=0)?

2. ¿Me estoy sobre-complicando con cosas que no se evalúan?

3. ¿Alguien más ya preguntó esto o algo similar en alguna issue anterior?

4. ¿Aparece en el enunciado?

5. ¿Es algo pertinente a la tarea?

De hacer una issue que no corresponda a lo anterior, simplemente se cerrará y se hará referencia a lo establecido en otras issues o en el feedback.

Si consideras que las preguntas no aplican a tu duda, entonces borra lo todo esto y haz la issue. De no borrarlo debes repetir: "no se leer las instrucciones, no borré las instrucciones y estoy haciendo preguntas ya resueltas 🙃🐥"

**Comment by skarlezib** [comment]
Hola,
Aun no logro entender como se usa el .gitignore, hay algún instructivo o algo para poder ver como se usa?
Gracias

**Comment by cilopez** [comment]
Hola @skarlezib existen muchos instructivos en la web, en este [video](https://www.youtube.com/watch?v=ErJyWO8TGoM) explican un poco. Para más información puedes leer la documentación de git [aquí](https://git-scm.com/docs/gitignore).

Lo otro es que no costaba mucho buscar "how create a gitignore", está bien que preguntes pero ojalá en el transcurso del curso trates de buscar estas documentaciones por tu cuenta. Si no te quedo muy claro porfavor pregunta por algo más específico.
