### ISSUE TITLE
Supuestos en consultas que no retornan bases de datos

### ISSUE THREAD

**Issue by jaromero6** [IIC2233/syllabus-2018-2#343]
Hola, tenia la duda respecto a las consultas que no retornan bases de datos, como por ejemplo passenger_miles. Mi duda es  si es necesario incluir a los pasajeros que no recorrieron ninguna milla. Esto aplica tambien para las otras consultas de este tipo, es decir, si hay id de "Passengers" que no estan en "Travels" por ejemplo, debo incluir estos id en el output?

**Comment by cilopez** [comment]
Como no está explicíto en el enunciado puedes hacer las dos opciones, en particular yo no los retornaría. Señala tu decisión en el README porfavor para el ayudante corrector. 
Saludos !

**Comment by jaromero6** [comment]
Gracias
