### ISSUE TITLE
furthest_distance y pasajeros en mismo vuelo

### ISSUE THREAD

**Issue by dhvasquez** [IIC2233/syllabus-2018-2#344]
En la funcion furthest distance me debe retornar una lista con los n pasajeros que han recorrido mayor distancia desde el aeropuerto indicado, pero ¿Que ocurre si me dicen que n=3, y el vuelo que a partir del aeropuerto indicado que a volado mas lejos tiene 15 pasajeros en su interior, entonces escojo a 3 pasajeros al azar de ese vuelo, o escojo solo uno y paso a otro vuelo?

**Comment by lily416** [comment]
Queda a tu criterio, pero especificalo en el readme

Saludos 🛫
