### ISSUE TITLE
Tiempo de lectura en diccionario

### ISSUE THREAD

**Issue by dlcartagena** [IIC2233/syllabus-2018-2#345]
Cuando creo el diccionario en favourite_airports al momento de querer leer información ingresando una key se demora mucho tiempo. Mi pregunta es si afecta que el diccionario sea muy grande al momento de querer leerlo?

**Comment by lily416** [comment]
La idea es que generes el diccionario y que lo muestre en el output (consola y/o archivo), no es como que vayamos a buscar información en el diccionario o que se vaya a usar como input de otra función 👀 

Saludos 👋
