### ISSUE TITLE
duda interacción consola

### ISSUE THREAD

**Issue by BenjaCastillo** [IIC2233/syllabus-2018-2#346]
**Abrir un archivo con consultas, que se encuentre dentro de la carpeta del programa. Cada linea de
este archivo tendrá una consulta válida.
El usuario debe ser capaz de escribir el nombre de un archivo presente en la carpeta del programa
y almacenar en memoria las consultas que aparecen en este. Luego podrá elegir una, varias o todas
las consultas presentes en el archivo, y se deberán mostrar los resultados en la consola.**

Mi duda sobre esto es de donde sale ese archivo, ese archivo es algo que ya existe?, entiendo que el tipo me da el nombre, pero por que después debo almacenar en memoria las consultas, no se supone que el archivo ya esta presente en la carpeta del programa? o que es lo que significa almacenar en memoria

Lo de que el puede elegir que consultas ver del archivo lo tengo claro, pero lo anterior no, que alguien me explique que debo hacer, o un ejemplo pls :(

**Comment by BenjaCastillo** [comment]
Otra pregunta, puedo hacer un foreach asi?

def foreach(function, iterable):
    for x in iterable:
        function(*x)

**Comment by adpolanco** [comment]
Me sumo a esta pregunta, supongo que se refiere al archivo queries.txt ,ya que es el único que tiene consultas, además de output.txt, pero éste se ve en detalle en los puntos 2 y 3. En ese sentido (si estoy en lo cierto), cuando se pide el nombre del archivo presente en la carpeta, podríamos definir como válido sólo cuando el usuario escribe "queries"?

**Comment by Coolgatty** [comment]
En relacion a esto yo queria saber como podemos hacer para que el usuario ingrese cuales consultas quiere revisar 
Sin un while se me hace muy dificil

**Comment by Arcoirisky** [comment]
¡Hola a todos! :DD 

@adpolanco El archivo de consultas al que se refiere el enunciado si es el queries.txt el cuando es en el menú que deben implementar, el cómo está a su criterio :D

 @BenjaCastillo a lo que se refiere a guardar en la memoria es que el usuario debe decidir cargar las consultas del archivo y luego de leerlo poder mantener esas consultas accesibles al usuario ¿Se entiende un poco mejor?

@Coolgatty lo siento pero la idea es que lo piensen por ustedes mismos. Pasea un poco más entre tus ideas y mucho ánimo!

Cualquier cosa no duden en preguntar! :D 

Oh! Cualquiera sea su decisión por favor recuerden agregar una explicación al readme!
