### ISSUE TITLE
Duda funciones generadoras

### ISSUE THREAD

**Issue by benjayousef97** [IIC2233/syllabus-2018-2#347]
Hola!

En funciones generadoras se pueden utilizar dos fors y solamente realizar un yield? Como en el siguiente ejempo:

for i in x:
    for j in y:
        ....
       .....
   yield algo

**Comment by Arcoirisky** [comment]
Hola! Puedes utilizar cuantos fors quieras en tu generador* y si lo que quieres usar es yield, también es válido. Mientras siga cumpliendo con el enunciado y te funcione estará bien :D
