### ISSUE TITLE
Importar modulos a main

### ISSUE THREAD

**Issue by danustilovsky** [IIC2233/syllabus-2018-2#348]
Hola, como se debe hacer para importar los modulos con las funciones creadas en el archivo main? ya que si las coloco al comienzo del archivo como siempre, este recive inputs pero no corre nada de lo que esta escrito.

Gracias

**Comment by Arcoirisky** [comment]
¿Te refieres a importar como "import <archivo>"?

De todas formas, deberías fijarte que no tengas código para correr en los archivos que vas a importar sin que estén en el "if __name__ == '__main__' para que no se ejecute al ser importado.

**Comment by danustilovsky** [comment]
Si, esque cuando trato de hacerlo no corre el resto del codigo, y en los archivos que estoy importando no hay nada que se ejecute solo funciones

**Comment by Arcoirisky** [comment]
Intenta con "from . Import <archivo>"
