### ISSUE TITLE
Base de datos y planilla feedback

### ISSUE THREAD

**Issue by PaoloFabia** [IIC2233/syllabus-2018-2#349]
Hola, 
en la planilla de feedback apraece el punto ```"Se puede elegir la base de datos que se retorna"```. 
Con esto se refiere a elegir entre "Airports", "flights", etc... O elegir también entre small, medium o large.
Pregunto porque esta útlima opción no se especifica en el enunciado.
Gracias!

**Comment by lily416** [comment]
Se refiere a Small, Medium o Large.

Saludos :wave:
