### ISSUE TITLE
Archivos "data"

### ISSUE THREAD

**Issue by igbasly** [IIC2233/syllabus-2018-2#35]
Al cargar la información de los archivos con la información rescatada del Dr. H, ¿debo mantenerla en esos archivos _(db_emails, db_events, db_users)_ o puedo cargarla a mi base de datos y olvidarme de los otros archivos?

**Comment by IchottMano** [comment]
@igbasly Hola!

Si quieres puedes cargarla a tu propia base de datos, sin embargo tu código debe poder funcionar sólo con las bases de datos entregadas (debe ser capaz de crear los archivos extra que necesite, no debes subir tus bases de datos extras a tu repositorio).

Saludos
