### ISSUE TITLE
Abrir base de datos small, medium, large en consola

### ISSUE THREAD

**Issue by dlcartagena** [IIC2233/syllabus-2018-2#352]
Se supone que load_database abre un tipo de base de datos y solo recibe el db_type, mi pregunta es si en la interacción con consola el usuario debe elegir si trabajar con la base de datos small, medium o large?

**Comment by lily416** [comment]
Puedes pedir la base de datos al principio del programa, pero recomiendo crear una variable global con la base de datos a abrir, como la que explican en #202. Cualquier opción que elijas especificalo en el readme. 😉 

Saludos 🛫
