### ISSUE TITLE
Base de datos medium y large aeropuertos 

### ISSUE THREAD

**Issue by jdiaztoledo** [IIC2233/syllabus-2018-2#353]
Hola. Para no tener problemas con el orden de las columnas en la base de datos utilice el comando DictReader de la libreria csv. Mi problema es que al usarlo me arroja arroja un error al momento de leer la base de datos en medium y large puesto que en la primera linea, a la llave icao la lee como \ufefficao, lo que encuentro raro, porque para small y las otras bases de datos (pasajeros, vuelos y viajes) no tengo ningun problema. Mi duda es, puedo asumir que esto no pasará para las bases de datos con las que se va a probar el funcionamiento de la tarea?
De antemano gracias :)

**Comment by dhvasquez** [comment]
al abrir el archivo debes poner `encoding="utf-8-sig"`

**Comment by jdiaztoledo** [comment]
Me funcionó. Gracias!
