### ISSUE TITLE
Output de consulta cuando return -> dict

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#354]
Hola.
En la parte de las funciones que no entregan generadores, tengo una consulta acerca del formato de despliegue en consola. Estoy entregando sets, dict, etc. cuando es estimado, pero por ejemplo en los sets, transformo las consultas individuales a str para poder meterlo al set, en la de lista, entrego sublistas (printea una lista por linea) y en el dict tengo un problema, porque entrega solo la key. Podría hacerle que entregue que la key sea un str(dict que se quiere entregar): dict que se quiere entregar, para que se vea toda la info en pantalla. ¿Estaría bien esto? Digo, para que se vea bien la info en la parte de consultas.

Gracias de antemano,
Saludos

**Comment by cilopez** [comment]
Si, pareciera estar bien

**Comment by Gorgola22** [comment]
algo como {"{0 : 9203}" : 9203, {"{1: 8800}" : 8800} } para que printee así lo necesario, aunque la key sea confusa, esta bien entonces?
