### ISSUE TITLE
Duda respecto Interaccion con consola

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#355]
Citando a cilopez:

> Las consultas siempre van a estar bien escritas y van a recibir sus parámetros en su orden determinado (eso mencioné en la sala de ayuda). Los inputs que deben manejar son tipo:
> 
> ```
> Que consulta quiere hacer (1-9): oli
> Consulta no válida, inserte un número del 1 al 9
>  
> ```
> Les encuentro la razón, es complicarles la vida gratuitamente pedirles revisar cada caso sin decoradores ni excepciones.

Podemos asumir que luego de que el usuario se equivoque, ingresará un input valido, ya según el archivo main.py de la tarea:

# rellenar esta parte con el llamado a sus funciones
# sigue corriendo el uso restringido en toda situacion
# de los for/while/etc dentro de este main a excepcion
# del que se encuentra arriba, por lo que no se puede
# agregar ninguno mas

Y realizar esta parte de "corregir inputs" sin while serían infinitos if's (ya que dependen la las veces en que el usuario ingrese mal el input)

**Comment by lily416** [comment]
No puedes asumir que el próximo input vaya a ser uno válido. 😞 
Aunque no puedes usar whiles, para poder hacer uso de _if_ infinitos existe la **recursión** (no puedo decirte más que esto 🙊).

Saludos y éxito con la tarea 🛫🍀
