### ISSUE TITLE
Correr programa de python

### ISSUE THREAD

**Issue by Coolgatty** [IIC2233/syllabus-2018-2#356]
Hola! Tengo un problema que cuando trato de correr un archivo de python se abre y se cierra por lo que he hecho un RUN.bat para las tareas 0 y 1. En la correccion de la tarea 0 me recomendaron encontrar una manera de evitar el uso de un RUN pero la verdad no se como hacerlo.
Cualquier consejo o guia de como hacer que el programa se ejecute abriendo el main.py se agradece!

**Comment by cilopez** [comment]
Hola @Coolgatty puedes especificar un poco más tu problema:
- Estas ejecutando el programa por consola o estas usando un IDLE.
- ¿Que sistema operativo usas?
- ¿Que versión de python estas utilizando?
- Alguna vez te funcionó correr archivos

**Comment by Arcoirisky** [comment]
Hola! 
A mí me pasa exactamente lo mismo. Cuando quiero correr un programa al hacerle doble click falla. 

Pero, si lo corro con el editor o directamente con la consola de comando usando python/py archivo.py funciona.

¿Por qué no lo intentas?
