### ISSUE TITLE
Borrar data despues del plazo

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#357]
Hola, el día después del plazo de la tarea, me di cuenta que tenia subido el data aunque lo tenia en el .gitignore, entonces lo borre de mi repositorio. ¿Estos commits cuentan para el descuento?. ¿Si es que cuentan se puede volver al commit anterior al plazo de la entrega? Porque el descuento por haber fallado con el gitignore es solo 2 décimas, mientras que el descuento de atraso puede ser mucho mas.
Gracias.

**Comment by Hernan4444** [comment]
Hola, mientras no respondas el formulario, se va a considerar el último commit antes de la fecha de entrega ( y sin descuentos) aunque hagas muchos comimos después. Si es que respondes el formulario y nos indicas un nuevo commit, ahí se aplicará el descuento pertinente a corregir un commit posterior a le fecha de entrega.

Saludos ✌️
