### ISSUE TITLE
Recorrección presencial tareas

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#359]
Hola!

¿Por dónde se solicita re-corrección presencial para las tareas?

**Comment by FJavierOss** [comment]
Tienes que mandar la solicitud por el form de recorreccion y en la sollicitud poner que quieres presencial (el form esta en el link que esta a lo más abajo en el readme del syllabus). Por regla general esto se puede hacer solo si el ayudante corrector sugeria o recomendaba recorreccion presencial. Finalmente, una vez enviada la solicitud, el ayudante se pondrá en contacto via mail y se pondrán de acuerdo donde y cuando será la recorrección presencial.

**Comment by danielaguilera** [comment]
Hola! Entré al formulario, sin embargo, no me aparece la opción de la recorrección presencial para la tarea 00, solo la de actividades y controles. En el feedback de la tarea se me sugirió una recorrección presencial.

**Comment by FJavierOss** [comment]
Trata de ingresarlo en el item Recorreccion general, basicamente se debe ingresar como un comentario dentro de ese item. No existe un boton o item especial donde se haga un click o un check para ingresar la opción de recorreccion presencial.
Saludos
