### ISSUE TITLE
Duda fechas de correos

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2233/syllabus-2018-2#36]
No debería ademas de tener from,to,title,body,classifications también llevar una fecha y hora para poder ordenarlos correctamente?

**Comment by cilopez** [comment]
Hola @Tomasalvarez15 , debes ordenarlos pero esto se puede hacer de distintas maneras una de ellas es con fecha, otra simplemente es utilizar una lista por ejemplo. Depende de ti la solución que apliques

**Comment by bgsamilla** [comment]
Pero el enunciado dice:
" El usuario deberá poder ver en su bandeja todos los correos recibidos ordenados desde el más reciente al más antiguo"
Si no tienen fecha ¿como sabemos cual va antes y después?
¿Con el orden en el que están en el .csv?

**Comment by cilopez** [comment]
Toma como supuesto que ya estan ordenados desde el más reciente al más antiguo

**Comment by cacoos** [comment]
Puedo tomar como supuesto que están ordenados del más antiguo al más reciente?

**Comment by ptflores1** [comment]
@cacosandon Si puedes asumirlo. De todas maneras si piensas usar una lista para guardar los correos, el método `sort` de las listas puede recibir dos argumentos que te pueden ser útiles ([documentacion](https://docs.python.org/3.6/tutorial/datastructures.html)) y la funcion [`sorted`](https://docs.python.org/3.6/library/functions.html#sorted) tambien !
