### ISSUE TITLE
Duda feedback T00

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#362]
Hola! No encuentro el feedback de la tarea 0 
Saludos

**Comment by cilopez** [comment]
Hola @Prochotito , el feedback debería estar en las _issues_ de tu repositorio con el nombre Tarea 0.  Si no es así puede existir un error con tu repositorio o algo por el estilo, en ese caso respondeme.
Salu2

**Comment by inveterate-cladocerus** [comment]
gracias @cilopez
