### ISSUE TITLE
Duda en contenido semana-06

### ISSUE THREAD

**Issue by catorres8** [IIC2233/syllabus-2018-2#363]
Hola ✋  estaba leyendo los contenidos de esta semana y hay algo que no entiendo en la clase `ListaLigada`,  más concretamente en el módulo `obtener(self, posición)`
```python
def obtener(self, posicion):
        """Busca el valor del nodo que está en la posición indicada, partiendo de 0"""
        # Empezamos en la cabeza
        nodo_actual = self.cabeza

        # Recorremos secuencialmente la lista ligada siguiendo los punteros
        # al nodo siguiente.
        for i in range(posicion):
            if nodo_actual:
                nodo_actual = nodo_actual.siguiente
        
        # Si buscamos una posición mayor a la longitud de la lista ligada
        if not nodo_actual:
            return "Posición no encontrada"
        return nodo_actual.valor`
```
En el ciclo `for`, según yo la linea `if nodo_actual:` debería tener una comparación, no sé en que momento `nodo_actual` sirve como bool ahí, pero probablemente me equivoque y esté pasando algo por alto.  Agradecería que me explicaran por qué esta escrito así 😄

**Comment by Drpinto1** [comment]
Saludos!
En python cada vez que haces `if instancia`, de un objeto de alguna clase, python llamará a la operación `bool()`; que intentará realizar, en orden, las siguientes 3 cosas:

1. Buscar en la clase a la que pertenece el objeto el dunder method `__bool__`; que indica el _"valor de verdad" _ correspondiente al objeto en cuestión (y retorna dicho booleano).

2. Buscar en la clase a la que pertenece el objeto el dunder method `__len__`; que como ya saben, indica el largo correspondiente al objeto en cuestión y retornará un booleano indicando si el largo es distinto de cero.

3. De no estar definidos ninguno de los dos métodos, el valor de cualquier instancia de esta clase será `True`  (Este punto fue editado, la respuesta anterior correspondía al comportamiento de python 2)

EDIT: En particular, en este caso, `nodo_actual` podría tener el valor `None`, y el valor de `bool(None)` será `False`

Si aún te quedan dudas al respecto, te invito a leer los detalles de `__bool__` en la [documentación de python](https://docs.python.org/3.6/reference/datamodel.html#object.__bool__) :smile:
