### ISSUE TITLE
Actividad 6

### ISSUE THREAD

**Issue by Mahund** [IIC2233/syllabus-2018-2#364]
En la actividad de hoy cree la siguiente clase:
```python
class Entidad:
    "Clase entidad"
    def __init__(self, rango=None, items=[],
                 superior=None, subordinados=[]):
        self.rango = rango
        self.items = set(items)
        self.superior = superior
        self.subordinados = subordinados
```

Posteriormente en el metodo agregar_subordinado utilice:
```python
def agregar_subordinado(self, entidad):
        "Agregar"
        if self.rango is None:
            self.rango = entidad.rango
            self.items = entidad.items
            return

        if entidad.rango == ORDEN[self.rango]:
            self.subordinados.append(entidad)
            entidad.superior = self
            return True
```

Pero al ejecutar el codigo, en el momento que se apendiza la primera entidad, las instancias siguiente al hacer por ejemplo `Entidad()`, sus subordinados dejan de ser `[]` y pasa a ser la lista con la entidad anteriormente apendizada.

**Comment by fringlesinthestreet** [comment]
Hola @Mahund 

Esto pasa porque en tu `__init__` dejas como valor por defecto una lista, la cual es un objeto mutable. Por lo tanto, todas las instancias de `Entidad`, si no se les pasa un valor de subordinados, toman por defecto a **la misma lista**. Esto se arregla así:

```python
class Entidad:
    "Clase entidad"
    def __init__(self, rango=None, items=None,
                 superior=None, subordinados=None):
        self.rango = rango
        self.items = set(items) if items else set()
        self.superior = superior
        self.subordinados = subordinados if subordinados else []
```

---

Un ejemplo de esto de los valores por defecto mutables:

```python
def prueba(a=[]):
    a.append(1)
    print(a)
```

Esta función recibe 1 argumento `a`, que por defecto es una lista vacía. Probemos qué pasa:

```python
>>> prueba()
[1]
>>> prueba()
[1, 1]
```

Aquí no le pasamos argumento a la función `prueba` por lo que `a` toma su valor por defecto. En el primer llamado, `a` toma el valor de una lista vacía, pero, en el segundo llamado, la lista **ya contiene un elemento** por lo que queda finalmente con dos.

**Comment by Mahund** [comment]
Gracias!
