### ISSUE TITLE
Juegos / Instalaciones

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/syllabus-2018-2#369]
Según lo que entendi de la Tarea los juegos no son instalaciones, pero en este caso, no entiendo como funcionarían los juegos, ¿cuanto tiempo duran? ¿una iteración? 

muchas gracias

**Comment by Arcoirisky** [comment]
Eso queda a tu criterio O: igual puedes especificarlo en el Readme O dejarlo como una variable externa por juego. Pero recuerda tener cuidado con el resto del enunciado. 

Por ejemplo, si decides que se juegue "n" veces y entre esas "n" jugadas me quedo sin dinero, que no pueda seguir jugando O:

**Comment by Benjadef** [comment]
si si claro, ya ósea podría perfectamente hacer que cada juego dure una iteración, que podría ser un segundo y no habría problema. Tampoco veo ninguna restricción de capacidad de los juegos, o ¿un dealer atiende un juego en el que puede jugar solo una persona? 
gracias por las respuestas

**Comment by Arcoirisky** [comment]
Sip, por ejemplo, en el caso de los tragamonedas, imagina que los dealera cuidan que no metan mano en las máquinas a pesar de que son de una persona o: 

Sobre la capacidad dejame revisar bien uwu
