### ISSUE TITLE
Duda correos en papelera

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#37]
¿A qué se refiere el enunciado con los correos guardados en papelera?

**Comment by akrebs2** [comment]
Hola!

Podrías ser más específico en tu pregunta? Qué parte es la que no entiendes?

Saludos!

**Comment by jecastro1** [comment]
Hola

La única parte donde aparece la palabra "papelera" en el enunciado es en la página 9, respecto a las cosas que deben ser respaldadas.

<img width="424" alt="screen shot 2018-08-14 at 5 43 03 pm" src="https://user-images.githubusercontent.com/5043042/44117425-9d733f5a-9fe9-11e8-8f79-0db13356326e.png">

Esto se trata de un error. Tal papelera no existe, por lo que puedes omitir ese ítem de esa lista.

Saludos

**Comment by jecastro1** [comment]
Hola, por favor no cierres la _issue_, menos cuando es etiquetada como importante. Los ayudantes se encargan de eso.

Gracias

**Comment by Gorgola22** [comment]
¿Pero tengo que dar la opcion de que borre los mensajes?

Gracias

**Comment by rhanuch** [comment]
@Gorgola22 , asumiendo que con mensajes te refieres a correos y no a los eventos, entonces no, no es necesario que se de la opción ya que no sale en el feedback entregado. Si se trata de los eventos, entonces solo el propietario debe tener la opción de eliminar un evento
