### ISSUE TITLE
Tiempo de cada Iteración

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/syllabus-2018-2#370]
Según lo que dice la introducción cada tick de la simulación es de un segundo, sin embargo en la tarea la mayoría de los parámetros están en minutos, por lo que si la simulación es en segundos habrán muchos segundo en los que no pase nada. esto es correcto o quizá lo estoy analizando mal, siento que tendría más sentido hacer la simulación con cada tick en minutos. 

gracias!

**Comment by Kitaps** [comment]
A mi me hace sentido que sea con segundos, ya que recuerda que hay una interfaz gráfica. 
Si fuese solamente un tick por minuto solo verías saltos. Al ser segundos probablemente vas a poder ver como interactuan las entidades en la interfaz gráfica. 

Igual esperemos a ver que es lo que te responden.

**Comment by camichavez** [comment]
Hola! Lo que tienen que considerar (y a lo que hace referencia el enunciado) es que un segundo en la ‘vida real’ corresponde a un minuto en la simulación 
Éxito!:)

**Comment by Benjadef** [comment]
ya perfecto, pero entonces, cada iteración de la simulación de cuanto debería ser (en tiempo de simulación)?

**Comment by camichavez** [comment]
Cada iteración de la simulación, en tiempo de simulación, dura un minuto. Sin embargo, lo que nosotros vemos es que en cada minuto que avanza la simulación,  un segundo que pasa para nosotros. Me entiendes mejor? 
Edit: **revisar último comentario**

**Comment by cacoos** [comment]
Hola! y podemos hacer que cada iteración de la simulación dure un segundo, y así que un segundo de simulacion se vea como 1 segundo / 60? No sé si me explico
Me refiero a simular cada segundo pero aún así cada minuto sera un segundo de la vida real

**Comment by camichavez** [comment]
Si tu simulación  fluye bien de esa manera, no hay problema en que lo hagas así :)

**Comment by Benjadef** [comment]
@Cschavez y si uso cada iteración como un minuto de la simulación, ¿no tendré el problema de ver como saltos en la interfaz gráfica?

**Comment by camichavez** [comment]
**Aclaración**: La primera duda que respondí fue que el **enunciado** dice en la introducción que cada tick de la simulación es de un segundo, sin embargo, en la tarea la mayoría de los parámetros están en minutos. A lo que el enunciado hace referencia es que un minuto en la vida de la simulación corresponde a un segundo en la vida real. Sin embargo, el hecho anterior no los obliga a que cada iteración ocurra cada un minuto (en tiempo de simulación). Tienen que considerar que no pueden existir saltos en la interfaz, por lo que ustedes deben definir la rapidez que le den al tick de forma que esto no suceda.

**Comment by Benjadef** [comment]
ahhhh yaya me quedo mucho más claro, gracias!

**Comment by Kitaps** [comment]
Solo para asegurarme de que entendí bien:
Si es que hacemos el run con 16ms de delay eso serían 60 ticks en un segundo, lo que serían 60 segundos de simulacion en un minuto dentro de la simulacion y es en nuestra realidad sería solo 1 segundo?

**Comment by camichavez** [comment]
Exacto! 👍

**Comment by ararojas** [comment]
Hola! 
No entiendo muy bien todo esto, en mi simulacion cada tick corresponde a un minuto de simulacion, pero en tiempo real es mucho menos tiempo. No quiero hacer que cada tick se demore un segundo de tiempo real porque de esa manera la interfaz se movería muy lento y además se demoraría mucho en correr una simulación. ¿No puedo dejarlo como que un tick se demore lo menos posible, en lugar de un segundo?

**Comment by camichavez** [comment]
Si puedes dejarlo así :)
