### ISSUE TITLE
Error módulo PyQt5 - Pycharm - Mac

### ISSUE THREAD

**Issue by baaldana** [IIC2233/syllabus-2018-2#371]
Hola, estoy teniendo problemas para trabajar con PyQt5. Uso Mac y Pycharm. Cuando corro el demo me tira un error, que en principio fue que no encontraba el módulo de PyQt5. Una de las ayudantes de tareas intentó ayudarme con el problema y me dijo que desinstalara Anaconda porque se comía las librerías, pero cuando lo hice no cambió nada. Tengo la impresión de que Pycharm no reconoce PyQt5 (que instalé usando ```brew install pyqt5```), por lo que encontré una forma de instalarlo desde dentro del mismo Pycharm. Ahora reconoce que existe el módulo, pero me tira ``` ImportError: cannot import name 'QTimer'```.  
La verdad no sé qué más hacer, he casi todo lo que he encontrado en internet y nada ha resultado.

**Comment by agustinkrebs** [comment]
Hola!

Quizás en esta discusión hay algo que te pueda servir:
https://github.com/pyinstaller/pyinstaller/issues/2402

Saludos!

**Comment by baaldana** [comment]
Gracias @akrebs2 ! Por si a alguien le sirve, logré arreglar el problema. Al final era que anaconda había reescrito el ``` bash_profile``` y obligaba a todas los módulos instalados por pip a entrar a esa carpeta por defecto. [Acá](https://stackoverflow.com/questions/22585235/python-anaconda-how-to-safely-uninstall) encontré la solución para borrar correctamente **todo** lo que modifica anaconda. Y para modificar el ```bash_profile``` usé este comando en terminal: ```touch ~/.bash_profile; open ~/.bash_profile``` desde el archivo .txt directamente.

**Comment by cdlanas** [comment]
Holaa! me pasó algo similar en windows donde la consola cmd no me reconocía el comando 'python' (lo cual solucioné volviendo a instalar python 3.6 apretando en la casilla de "Añadir Python al PATH") y cuando volví a instalar PyQt5 ya no me daba el error "ImportError: cannot import name 'QTimer'".
Comento por si a alguien le sirve.

**Comment by cpgarrido** [comment]
Hola @baaldana tengo tu mismo problema, pero nunca he descargado Anaconda. Quiero saber que modificaste específicamente en el bash_profile, a mi me sale el path de python 3.6 y el 2.7. No se si eliminar alguno o que debo hacer, agradecería mucho tu ayuda.

**Comment by baaldana** [comment]
@cpgarrido Cuando trataba de usar el comando ```pip``` en terminal me arrojaba error porque no encontraba el ```pip```en el path que estaba por defecto en el ```bash_profile```. Lo que yo hice más detalladamente fue borrar el path que había sobreescrito Anaconda.  Luego entré a ```~/Library``` desde ```Finder -> Go -> Go to Folder...``` y borré todo de python, anaconda, pycharm, y cosas similares. Después desde el Terminal borré ```python3``` y ```pyqt5```usando ```brew```. Después hice todo el procedimiento del wiki que nos subieron a principio de semestre de cómo instalar ```python3``` y las demás cosas. Cuando terminé, no tuve problemas en instalar nada ni en usar ```PyQt5``` en Pycharm.  En tu caso, quizá te la tendrías que jugar eliminando tanto python 3.6 como 2.7 y reinstalarlos usando el Terminal desde 0 y ver si se arregla el tema con los paths. A mí me bastó eliminar el path de anaconda, y reinstalar todo desde 0. Espero que te sirva de algo!

PD: Me acabo de acordar que en Pycharm también hay una opción para instalar dentro del mismo software el módulo de ```PyQt5```. ```Preferences -> Project -> Proyect Interpreter``` y ahí agregas el package de ```PyQt5```. Eso también lo hice y corre bien.

**Comment by tsgonzalez** [comment]
Hola! me pasaba lo mismo pero en vez de borrar todo solo abri la terminal, puse open .bash_profile y cambie el 'export PATH' a 'export PYTHONPATH=`brew --prefix`/lib/python3.6/site-packages:$PYTHONPATH' y luego añadí el package pyqt5 a el proyecto de pycharm de mi tarea y funcionó.

**Comment by cpgarrido** [comment]
Hola, muchas gracias a todos, he intentado todo lo que dicen, incluso borré python y lo volví a instalar. Pero me sigue saliendo el error. Algún ayudante me podría ayudar dentro de la semana con el error, por favor.
