### ISSUE TITLE
Carpeta decoracion

### ISSUE THREAD

**Issue by haarenas** [IIC2233/syllabus-2018-2#372]
Hola, tanto en el archivo ```demo.py``` como en el enunciado se hace alusión a los decoradores, pero dentro de la carpeta ```gui/assets``` no esta la carpeta *decoracion*.

**Comment by ariel-m-s** [comment]
up

**Comment by NachoJuanDev** [comment]
up

**Comment by mihenriquez** [comment]
cps

**Comment by ariel-m-s** [comment]
Quedan dos días y no han respondido esta issue.

**Comment by NatachaP** [comment]
Yo tengo la misma duda pero lo que hace "gui/assets/decoracion / bullet.png" es tomar la imagen según el tipo del elemento. Así, lo que permite el cambio de imágen es el atributo type_ de las entidades que nos dieron. 
Ojalá sirva :D
