### ISSUE TITLE
Cantidad de juegos e instalaciones

### ISSUE THREAD

**Issue by ninifdr** [IIC2233/syllabus-2018-2#373]
Hola, hay alguna cantidad específica de juegos e instalaciones que hay que poner? 
Aparece en el enunciado la cantidad de personal pero sobre lo otro no dice nada. Asumo que es 1 de cada 1?
Gracias!

**Comment by agustinkrebs** [comment]
Hola!

Puedes poner instalaciones y juegos repetidos, sin embargo, considera que el espacio del mapa es fijo, por ende, no podrás poner infinitos ya que se comenzarían a sobreponer.
Recomendaría partir con uno de cada uno, y si te funciona todo ok, tratar de poner más. De todas maneras, no se exigirá más de uno por cada tipo de instalación o juego.

Saludos!

**Comment by fabarros** [comment]
Entonces la cantidad de Juegos e Instalaciones la decido yo a priori arbitrariamente y será fija durante todo mi programa?
