### ISSUE TITLE
Id único

### ISSUE THREAD

**Issue by ninifdr** [IIC2233/syllabus-2018-2#374]
En el enunciado sale que cada cliente, personal e instalación tienen un id único, eso es dentro de su mismo grupo?
A lo que voy es, un cliente no puede tener el mismo id que otro cliente, pero puede tener el mismo id que una instalación? O todos tienen que ser diferentes
Gracias!

**Comment by agustinkrebs** [comment]
Hola!

Lo que dices está bien: un cliente no puede tener el mismo id que otro cliente, pero puede tener el mismo id que una instalación.
Se extiende la misma lógica para el resto de las clases que crees.

Saludos!
