### ISSUE TITLE
Duda archivos gui

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#375]
Duda simple y corta:
¿Se pueden modificar los archivos .py que estan en la carpeta gui?

**Comment by agustinkrebs** [comment]
Hola!

Nop, no debes modificarlos.
La tarea se corregirá con los archivos originales de esta carpeta.

Saludos!

**Comment by lucasvsj** [comment]
@akrebs2 
¿Puedo sugerir que en el archivo __init__.py en el metodo add_entity agreguen la siguiente linea:
entity.updatePixmap()?
