### ISSUE TITLE
Funcionamiento Juegos y Instalaciones

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#376]
Hola, 

en el enunciado podemos entender, que los juegos funcionan siempre (haya o no haya dealer)?

Porque las instalaciones se cierran si no están siendo atendidas por Personal, pero no sale nada respecto a los juegos. Los juegos simplemente siguen sin supervisión?

Y respecto a lo mismo, los dealers pueden pillar a personas contando las cartas en el tragamonedas? / 
Se pueden contar las cartas en el tragamonedas?

**Comment by nachocontreras** [comment]
Hola!

Los juegos necesitan al menos un dealer para funcionar.
Sólo pueden contar cartas en la ruleta.

Saludos!

**Comment by pbyoma** [comment]
Hola 
No me queda claro lo de los dealer en los juegos, ya que hay otras issues donde responden que debe existir al menos un dealer por juego para funcionar

**Comment by nachocontreras** [comment]
#382 Al menos un dealer por juego para funcionar.
