### ISSUE TITLE
Contador de Ticks

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#377]
Tengo una pregunta con los ticks, estoy jugando con la demo para ver que puedo y que no hacer. 
Ahora mismo estoy intentando que la variable ticks aumente cada tick. Pero al poner dentro de la función ticks += 1, me lanza error "local variable 'ticks' referenced before assignment".

ticks esta definida fuera de la función y por eso no me deja aumentar su valor, pero si la defino dentro se sobrescribe cada vez que que llamo.

Me dan un hint para resolver esto?  :P

Saludos!

**Comment by Kitaps** [comment]
Crea una clase Simulacion y ahi adentro define la funcion tick, o eso por lo menos es lo que estoy haciendo y me funcionó.

**Comment by johntrombon** [comment]
En este caso usar una variable global es necesariamente una mala practica 🤔 ?
