### ISSUE TITLE
problema con instalar PyQt5 windows

### ISSUE THREAD

**Issue by Tngarrido** [IIC2233/syllabus-2018-2#379]
hola, des-instale e instale python porque  en el cdm de windows no lo reconocía, finalmente escribí el codigo de "pip3 install pyqt5" en la consola cdm, el cual cargo inicialmente pero después me arrojo el siguiente error:
 Could not install packages due to EnvironmentError: [WinError 5] Access Denied: 'c: \\ program files \\ python36 \\ Lib \\ site-packages \\ PyQt5'
Consider using the `--user` option or check the permissions.
he intentado buscar soluciones [como esta](https://stackoverflow.com/questions/32167418/python-pip-install-trouble-shooting-permissionerror-winerror-5-access-is), pero no me manejo mucho con windows y no entiendo como aplicar las soluciones que entregan, espero resolverlo pronto porque aun no puedo entender bien la tarea ya que no puedo ver el funcionamiento de la interfaz :(

**Comment by Arcoirisky** [comment]
*Usas anaconda por casualidad?
*Al re-instalarlo recordaste agregar python Al path? O: 

Si la respuesta es "no" y "si" puedes intentar instalar el whl de este link 
https://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype
Buscas pyqt5 y descargas según las especificaciones del computador y tú python. No es tan terrible como se ve :D

**Comment by Tngarrido** [comment]
@Arcoirisky mi respuestas coinciden exactamente con las que mencionas, pero creo que solo veo "PyQt4", es compatible con PyQt5 ?

**Comment by Arcoirisky** [comment]
Lamentablemente no. 
¿Intentaste abriendo el CMD como administrador? ¿Tienes sólo Python 3?

**Comment by Arcoirisky** [comment]
Intenta hacerle un upgrade a pip e intenta de nuevo o:

**Comment by Tngarrido** [comment]
@Arcoirisky  abrí el CMD como administrador y al fin pude, gracias ;-)

**Comment by Arcoirisky** [comment]
Yaaay <3 me alegro
