### ISSUE TITLE
Duda Github

### ISSUE THREAD

**Issue by IriSalazar** [IIC2233/syllabus-2018-2#38]
Hola! Estaba en la pagina principal de Github y vi esto:

![image](https://user-images.githubusercontent.com/26166202/44114410-79f27260-9fe1-11e8-801f-0bffd5256c0c.png)

Hice click en el tercero y me dice que esta forked al repo original (el que tiene un candado, el primero):

![image](https://user-images.githubusercontent.com/26166202/44114488-b6d64846-9fe1-11e8-9c6f-e29c5d8b27bd.png)

Honestamente no se que hice... y cuando hago push se sube al repo original, el que tiene un candadito en la primera foto. 
Lo dejo como esta? O tengo que borrarlo? Tampoco se borrarlo... no se como lo hice aparecer o si ya estaba desde antes.

**Comment by bimartinez** [comment]
Hola!

Basicamente lo que hiciste ~~sin querer~~ fue crear una copia del repo original (el que tiene :lock: es el original donde debes subir tus actividades y tareas), un punto **importante** es que los cambios que hagas en la copia no se verán reflejados en el original. 

Para borrar el repo *forked* (el tercero en tu primera imagen, **el sin candado!**:eyes:) debes ingresar a el (haciendo click sobre su link) y en *settings* escoges la opción de borrar el repositorio.

Coméntame como te va con esto que te digo.

Saludos! :smile:

**Comment by IriSalazar** [comment]
Listo! Funciono perfecto. Muchas gracias :)
