### ISSUE TITLE
Recorrección T00

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#380]
Hola!

Quería preguntar cómo solicito recorrección presencial de la T00 (la cual fue sugerida por el ayudante con usuario Hernan4444), ya que he abierto el form para las recorrecciones y no me aparece esa opción.

![image](https://user-images.githubusercontent.com/41979332/46083989-fb3b3d80-c178-11e8-8fc4-7a967428ed3e.png)

**Comment by rhanuch** [comment]
¡Hola @danielaguilera ! 

El plazo para la recorrección terminó el domingo a las 23:59 😢

¡Saludos!🍀

**Comment by Hernan4444** [comment]
Estimado, cuando se te notificó que no se podía responder por dicho medio es porque mandaste un mail personal lo cual se indicó al inicio del semestre que no se hiciera. Todo mail es por el mail oficial iic2233@ing.puc.cl.

**Comment by danielaguilera** [comment]
Vale, pero estuve preguntando lo de la recorrección desde antes del domingo y nunca apareció esa opción en el form. Incluso mandé una notificación con un comentario, como me fue sugerido, pero no me ha llegado respuesta.

**Comment by Hernan4444** [comment]
Estimado,
En el aviso de la tarea se mandó el link del cuestionario (https://goo.gl/forms/sIkxzrqRqlktDg3A2). En el  otro, su título dice "Formulario Recorrección (Control y Actividad)", lo cual dice que es solo de controles y actividades.
