### ISSUE TITLE
Modelación del problema

### ISSUE THREAD

**Issue by Franco1605** [IIC2233/syllabus-2018-2#381]
Hola, mi pregunta es la siguiente: ¿Está mal modelar a los clientes pidiéndole un atributo de personalidad definido del init y que de acuerdo a esa personalidad se le asignen los demás atributos como dinero, suerte, etc. de acuerdo a una función externa a la clase?,  ¿o es un mejor  hacer una clase con cada personalidad?

**Comment by agustinkrebs** [comment]
Hola!

Creo que responderte esa pregunta sería soplarte directamente la respuesta de algo que se está evaluando en esta tarea.

Aún así, puedes pensar lo siguiente en el contexto de esta tarea:
¿Las diferencias que tienen dos personas con la misma personalidad, es comparable a las diferencias que tienen dos personas de distintas personalidades? Para cada caso: ¿es sólo un tema de parámetros con valores distintos, o cada personalidad se comenzará a comportar de manera distinta a lo largo de la simulación?

Espero eso te haya servido para guiarte hacia la respuesta correcta.

Saludos!

**Comment by Franco1605** [comment]
si, gracias @akrebs2
