### ISSUE TITLE
Características de los juegos

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#382]
Hola!

Mis preguntas son varias.

1. En el enunciado no dice nada acerca del **costo** de los juegos.
    * Asumo que este costo es nulo? Es decir, que basta únicamente con apostar para acceder al juego? 
    * Existe un monto mínimo al apostar? O puede un cliente apostar cero?
----
2. En el enunciado no dice nada acerca de la **duración por persona**, **gente en espera** ni **capacidad máxima** de los juegos.
    * Asumo que la duración de estos es nula?
    * Asumo que no hay fila ni capacidad máxima? Es decir, que los clientes pueden participar de cualquiera de los juegos en todo momento?
----
3. En el enunciado no dice nada acerca de la cantidad de **personal del juego**.
    * Asumo que es exactamente un _dealer_ por juego?

Saludos y gracias,
Ariel

**Comment by Arcoirisky** [comment]
Holaaa 
1) En el enunciado sí se habla del costo de juego. Por ejemplo, el tragamonedas cuesta un dinero.

2) Si hay filas y pueden producirse en los juegos. No puedes asumir que la capacidad en estos es infinita.

3) sobre el personal del juego se dan números específicos de dealers, misters T y otros. 

Podrías echarle otro ojo al enunciado o:

**Comment by ariel-m-s** [comment]
Hola @Arcoirisky ! Muchas gracias por la respuesta.

1. Tienes razón, el enunciado dice que la apuesta mínima es de uno, entonces entiendo que aparte de esto no existe ningún **costo** adicional (aparte de la apuesta).

2. El enunciado no dice nada acerca de la **duración por persona**, **gente en espera** ni **capacidad máxima** de los juegos, solamente menciona estas características específicamente para las instalaciones en la sección 3.4.1.
Como me dices tú, sí pueden producirse filas en los juegos. Entonces, los valores de **duración por persona** y **capacidad máxima** los defino yo tal que sí exista la posibilidad de producirse filas?

3. En la sección 3.2 se detalla la cantidad de **personal del casino** y se menciona que cada uno tiene un lugar de trabajo permanente. Además, en la sección 3.4.2 se detalla cuántos _bartenders_ y _Mr. Ts_ hay por instalación. Sin embargo, mi pregunta es cuántos _dealers_ necesita para funcionar (y cuántos puede tener) cada uno de los juegos del casino. Es exactamente uno?

**Comment by Arcoirisky** [comment]
1) Para los juegos nop. No hay costo adicional en jugar pero en cada vuelta del juego se debe pagar la apuesta inical 

2) La duración se deja a su criterio. Si desean que una persona vaya y juegue 5 veces o un número random antes de volver a pensar en su siguiente acción. Capacidad de los juegos lo puedes definir tu pero sé razonable :D 

3)  En los juegos debe de haber al menos uno para funcionar. Pueden haber más pero en principio uno. Para las otras instalaciones están definidos tal como dices :D

**Comment by ariel-m-s** [comment]
Gracias @Arcoirisky, todo claro!

**Comment by Cadagan** [comment]
Continuando: y para la estadistica de "tiempo total sin funcionar de cada instalacion", los **juegos** entrarian en esta estadistica? (debido a que si no tienen a ningun dealer, no puede funcionar)

**Comment by javierabao** [comment]
No, como dice "instalaciones", solo se consideran las instalaciones propiamente tales.
