### ISSUE TITLE
Parámetros Actividades (porcentaje o puntos)

### ISSUE THREAD

**Issue by pgarnham** [IIC2233/syllabus-2018-2#383]
En la sección de Actividades a veces se nos habla de los parámetros explícitamente como porcentajes, pero otras veces no. (por ejemplo en conversar)
¿Siempre son porcentajes, o en caso de que no esté señalado son aumentos/disminuciones de puntos porcentuales?

**Comment by IchottMano** [comment]
@pgarnham Hola!

Una aclaración general sobre los parámetros:

- No todos los parámetros son porcentajes, por ejemplo el parámetro gamma está explícito que es un número natural.
- Cuando un parámetro es una **probabilidad**, puedes asumir que es un número entre 0 y 1.
- Si un parámetro modifica alguna característica de la persona en un **a%**, puedes asumir que **a** es un número entre 0 y 100.
- Finalmente, si un parámetro modifica una característica **directamente**, puedes asumir que es un número entre 0 y 1.

En resúmen, tienes que sacar los posibles valores de las variables del contexto.
Espero te haya quedado claro.
Saludos!

**Comment by jeschuwirth** [comment]
todas las variables que luego tengan un % disminuyen porcentualmente, mientras que las otras disminuyen en su valor.
En el ejemplo de conversar:
ε disminuye porcentualmente
Χ disminuye en su valor
