### ISSUE TITLE
Materia - Tarea 02 - Diagrama de clases

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#384]
Cual seria una forma correcta de explicitar una property en el diagrama de clases?... y otra pregunta, si defini un abstactmethod, pongo el metodo en la clase abstracta, tanto en la abstracta como en la clase que hereda de esta, o solo en la que hereda?

Saludos!!!

**Comment by lily416** [comment]
Para escribir properties el diagrama debes poner:

> <get/set/del> nombre_property  : tipo

Dependiendo de si realizarse el `setter` o el `deleter` de la property los pones dentro de los `<>` o no.
En el caso de los los métodos y atributos que se heredan, esta bien si sólo los ponen en la clase padre.

Saludos y éxito con la tarea 👋🎲
