### ISSUE TITLE
creando clientes en la simulacion

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2233/syllabus-2018-2#385]
Hola, estoy intentando hacer una función que cree clientes con probabilidad p. El problema es que no se como crear clientes en mi función tick y agregarlos a la interfaz. Usar gui.add_entity(...) no tiene efecto si lo intento hacer dentro de la función que le doy a tick entonces como que tendría que saber desde antes que entidades se van a ir creando durante la simulación. 
La verdad es que no entiendo muy bien como usar lo de la simulación y menos aun con la interfaz gráfica al mismo tiempo. Ojala me puedan ayudar porque estoy muy perdido en ese sentido. 
Saludos.

**Comment by bgsamilla** [comment]
Sumándome al tema de la pregunta, cuando creo los personajes fuera de la función tick (como esta en la demo) funciona bien, pero cuando lo hago dentro aparecen con mas tamaño del que deberían, mientras que el height() de los primeros es 36 el de los nuevos es 110, es algo que pasa en los módulos que nos pasaron ya que tengo un print( height( ) ) justo después de cada instancia de Human, y no tengo la menor idea de que lo causa ni como arreglarlo.

Ayuda :(

**Comment by fabarros** [comment]
Ward

**Comment by sicalderon1210** [comment]
.

**Comment by viantirreau** [comment]
@BSamilla A mí me funcionó con ejecutar `cliente.setFixedSize(36, 36)` cada vez que se agrego un cliente a la interfaz (no es necesario hacerlo en cada _tick_). No es un método muy ortodoxo, pero funciona 🙈 
Saludos!

**Comment by bgsamilla** [comment]
@viantirreau 
Me funciona! 
Muchas gracias!

**Comment by isavega** [comment]
@BSamilla use lo mismo y me arregla el cuadrado que rodea la imagen, no la imagen misma. Te paso?

**Comment by bgsamilla** [comment]
Segun entiendo mi unico problema era el cuadrado negro, la imagen en si era como en la demo.
No sabria decirte tampoco cual es el tamaño que deberia tener las imagenes, he visto gente que le aparecen gigantes y a algunos tan pequeños que ni se ven.

**Comment by isavega** [comment]
@BSamilla lo arregle! muchas gracias por responder :)

**Comment by danustilovsky** [comment]
@miguelramirezv Hola, como hiciste para arreglar tu problema?? gracias
