### ISSUE TITLE
exit code -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by SantiagoHintze** [IIC2233/syllabus-2018-2#386]
Estimados, 

Al intentar instanciar un cliente (la clase super hereda de la clase Human de gui), el código corre, pero se finaliza diciendo "Process finished with exit code -1073740791 (0xC0000409)", no arroja ningún error, solo dice eso.

Al intentar printear algún atributo de la persona luego de haberla instanciado no pasa nada, por lo que el código se detiene en la parte en que se instancia el objeto.

A pesar de todo esto, al correr demo.py, que instancia al cliente de la misma forma que yo, el programa funciona.

No hay mucha información sobre este problema en internet, pero la poca que encontré señalaba que podía ser un problema con los drivers de la GPU, por lo que los actualicé, aunque funcionara la demo, sin resultados positivos.

help:(

**Comment by Arcoirisky** [comment]
Intentas instanciarlos separados de la interfaz? Por ahí podría estar tú problema.

**Comment by SantiagoHintze** [comment]
> Intentas instanciarlos separados de la interfaz? Por ahí podría estar tú problema.

Funciona al correr git.init() al comienzo del programa, graciass!!

**Comment by felipegarcia98** [comment]
Para que quede registro de quien venga por ayuda

 -1073740791 significa problemas con el gui

(0xC0000409) significa que te falta hacer gui.init() antes de crear llamando a human, entity, etc

(0xc0000005) significa que estas violando permisos, por lo que puede que hayas hecho gui.init() 2 veces (a mi me paso al importar un modulo con gui.init() )
