### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#388]
Hola!
Si creo una clase Padre con ciertas properties, y luego las heredo a otra clase Hijo y hago overriding de estas (lo hago porque la clase Padre tiene funciones que usa properties que van a cambiar), debo poner todas estas properties en ambos cuadros de clases del diagrama? 
Gracias!

**Comment by lily416** [comment]
No es necesario volver a poner los métodos/properties a los que haces overriding, pero si sientes que tu diagrama queda más completo puedes hacerlo 😄 
Si es que lo haces, puede escribirlos como:
> \+ method(input type): output type <<override>>
> <get/set/del> property: type <<override>>


Éxito con la tarea 🃏👋
