### ISSUE TITLE
Caminata personas

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#389]
Nos van a dar imagenes para hacer animaciones de caminata? o no se pide que caminen? (si estan en un lugar del mapa y deciden jugar en tragamonedas, simplemente aparecen en la maquina o deben "moverse"?)

**Comment by Arcoirisky** [comment]
No se verá un movimiento animado como el que todos conocemos y amamos pero deben "moverse". Lo que no queremos es que se teletransporten estando en el casino. Aunque no hay problema que al momento de aparecer o irse aparezcan en una posición X o se desvanezcan (en el caso de que se vayan)

**Comment by johntrombon** [comment]
Hola !,¿que se entiende por teletransportarse? Es decir, ¿más o menos cuantas unidades deberíamos permitir que se muevan nuestros clientes por _tick_ ? Teniendo en cuenta que los ticks son cada 1 seg.

**Comment by felipegarcia98** [comment]
UP a esta ultima pregunta

**Comment by Arcoirisky** [comment]
No hay unidad específica con la que te pueda decir “oh si, mira que si avanzas cada X no es teletransportarse”. La idea es que ustedes sean conscientes y hagan que se muevan sin que estén pegando saltos por la pantalla. 

¿Se entiende? O: Básicamente sean prudentes y suerte!!! OuO No será un movimiento animado como todos conocemos y amamos Pero, debe “moverse” como tal (Todo se mantiene excepto la animación de caminar que no existe)
