### ISSUE TITLE
Descarga archivos para poder ocupar jupyter

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#39]
Ya instale jupyter, pero por lo que entiendo debo descargar las cosas que quiero abrir en él, esto como se realiza?

gracias!!

**Comment by naquiroz** [comment]
Hola! Técnicamente no necesitas descargar todo lo que quieras abrir en el, solo tienen que estar en tu computador. Para abrirlos solo

**Comment by bimartinez** [comment]
Hola! :smile: 

Lo que te sugiero es clonar el repositorio (`git clone url_repo`) donde se encuentran los archivos *.ipynb*, luego de haber hecho esto abre la terminal en la carpeta :file_folder: donde clonaste el repo con el [contenido](https://github.com/IIC2233/contenidos) y ejecutas el comando `jupyter notebook`. Se debería abrir tu [navegador](https://www.mozilla.org/en-US/firefox/new/) :fox_face: con los *notebooks* listos para interactuar con ellos!

Saludos!

**Comment by pelao97** [comment]
buenisimo, gracias!

**Comment by skarlezib** [comment]
Se puede hacer que el repositorio clonado se vaya actualizando solo con los cambios y los nuevos archivos que se van subiendo?

**Comment by bimartinez** [comment]
Hola @skarlezib!

Efectivamente **si se puede** 👍😄 solamente debes abrir la terminal en la carpeta donde clonaste el repo y luego hacer `git pull`. Tu repositorio local de contenido debería actualizarse al estado actual del remoto.

Saludos!
