### ISSUE TITLE
Contar cartas

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#392]
En el enunciado dice
> **Contar cartas**: Tiene como requisito haber hablado con alguna persona y ser de personalidad
_kibitzer_. Luego de estudiar, la persona puede decidir ir a una mesa a contar cartas con probabilidad
igual a su parámetro de deshonestidad.

Pero al escoger esta actividad ya hemos escogido la actividad misma de **Contar cartas**. Para contar cartas entonces se debe escoger esta actividad y **además** ver si se realiza con probabilidad igual a su parámetro de deshonestidad?

**Comment by javierabao** [comment]
Hola!
Claro, una vez que elige la actividad lo que hace es estudiar la ruleta. Una vez estudiada, vuelve a tomar una decisión, que es si ir o no a la ruleta a predecir resultados.

**Comment by cacoos** [comment]
Gracias!
Y si decide no ir a predecir, entonces habría sido solo una perdida de tiempo?

**Comment by javierabao** [comment]
Exactamente jajaja.

**Comment by cacoos** [comment]
Muchas gracias! Una última pregunta.
Se me hace mucho mas fácil interpretar lo siguiente 
> Si es que decide predecir los resultados, lo
realiza en las siguiente _v_ rondas.
>
como que, si decide predecir, entonces cada vez que juegue a la ruleta va a predecir (hasta que pasen _v_ rondas). Esto en vez de que esté si o sí _v_ rondas jugando a la ruleta seguidas.
Es viable este supuesto?
Muchas gracias de nuevo!

**Comment by inveterate-cladocerus** [comment]
cps

**Comment by javierabao** [comment]
Es viable tu supuesto, especifícalo en el readme!
