### ISSUE TITLE
Duda enunciado 3.4.2

### ISSUE THREAD

**Issue by jncaceres** [IIC2233/syllabus-2018-2#394]
Hola:)
Me surgió la duda de si es que en el Restobar, donde dice "Estas ultimas disminuyen en 0;2 la
lucidez de los clientes, en 0;15 su ansiedad y en 0;3 la probabilidad de que se retiren del casino"
¿Esto hace variar directamente la probabilidad de que se retiren? ¿o varia la stamina de la persona?

**Comment by lily416** [comment]
Varía la stamina de la persona.

Saludos 👋
