### ISSUE TITLE
Criterio para elegir qué decisión tomar (3.1.3)

### ISSUE THREAD

**Issue by PaoloFabia** [IIC2233/syllabus-2018-2#395]
Hola!
No me queda claro como se elige la decisión que reliza el cliente. Entiendo que cada una tiene una probabilidad de ocurrencia, pero cuál sería el criterio para elegir una sobre por sobre otra? Aquella que tiene mayor probablidad, un "random ponderado" por sus probabilidades o queda a nuestro criterio?
gracias

**Comment by javierabao** [comment]
Hola!
Vendría siendo la opción de "random ponderado". En el fondo, asignas intervalos a cada decisión ponderándolos según su probabilidad, haces el random sobre el intervalo total, y dependiendo del valor obtenido tomas la decisión.

Saludos!
