### ISSUE TITLE
Dinero maximo

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2233/syllabus-2018-2#397]
Hola, quería saber si el atributo "dinero" puede sobrepasar el valor de 1. De no ser el caso, como se trata la plata extra que gana una persona? Nunca puede tener mas de 200?

**Comment by javierabao** [comment]
Hola!
Como dice el enunciado: 
"La cantidad de dinero inicial de un jugador depende directamente del parámetro aleatorio dinero. Un
cliente entra al casino con: dinero de entrada = dinero × 200".
Es decir, inicias con una cantidad de dinero que es el atributo "dinero" (que depende del tipo de personalidad) multiplicado por 200. Cuando ganas o pierdes dinero, se suma o resta a este monto, así que eventualmente puedes superar los 200.

**Comment by diegovaras97** [comment]
Si, pero en la página 5 antes de la sección 3.1.3 dice 

> "...notar que **todos los valores** de los parámetros no pueden ser menores a 0, ni mayores a 1"

¿Que seguimos? @javierabao

**Comment by javierabao** [comment]
El "dinero de entrada" no es parámetro, el "dinero" si lo es, siendo este último el que calculas en los rangos de alto, medio y bajo, por lo que no puede estar bajo 0 ni sobre 1. Pero una vez calculado ese dinero, si puedes superar el 1. De hecho hay instalaciones que cuestan más de 1.
