### ISSUE TITLE
Aumento ansiedad

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2233/syllabus-2018-2#398]
"Ansiedad: Atributo que influye en la frecuencia con que se visitan los juegos y la cantidad de
dinero que se apuesta en ellos. Aumenta en un 25 % si el jugador posee mas del doble o menos
de la quinta parte del dinero inicial."

El aumento es de forma multiplicativa o aditiva?

**Comment by nachocontreras** [comment]
Hola!

En cualquiera de los dos casos aumenta igual. Por ejemplo:
ansiedad = 10
ansiedad * 1.25 = 12.5
ansiedad + ansiedad * 0.25 = 12.5

Saludos!

**Comment by Tomas-Ira** [comment]
Yo tenia entendido que ansiedad era un numero entre 0 y 1.
Lo que no entiendo es:
si ansiedad inicial = 0,4
       ansiedad despues del aumento = 0,65 (0,4 + 0,25)
       ansiedad despues del aumento = 0,5 (0,4 * 1,25)

**Comment by nachocontreras** [comment]
Es un número entre 0 y 1.

La ansiedad aumenta en un 25%, no en 0.25. Por lo tanto, el segundo caso es el correcto (0.4 * 1.25).
