### ISSUE TITLE
Ganar al primer intento en el tragamonedas

### ISSUE THREAD

**Issue by dtmaltrain** [IIC2233/syllabus-2018-2#399]
En el caso de que un cliente sea el primero del día en usar el tragamonedas (pozo vacío) y este gane, cual seria su ganancia de dinero?.

Pregunto esto ya que si (por ejemplo) este apuesta 10 de dinero, 9 irían al pozo y 1 al casino, pero si gana a la primera, ganaría solo 9, lo que significa que estaría perdiendo dinero por ganar en el tragamonedas. :dizzy_face:

¿Qué hacemos en este caso?🤔

**Comment by javierabao** [comment]
Hola!
Claro, pasaría eso. Se supone que la gente no sabe que es la primera en jugar, así que simplemente pasaría que gana 9, aunque esté perdiendo 1, porque eso es lo que hay en el pozo. Mantenlo así no más!
