### ISSUE TITLE
Problema con PyQt5

### ISSUE THREAD

**Issue by rjcavada** [IIC2233/syllabus-2018-2#4]
**- Sistema Operativo:**
macOS (Sierra)

**- Programa con el problema:**
PyQt5

**- Descripción del problema:**
Luego de seguir los pasos que se encuentran en la wiki "Software Obligatorio", al intentar importar PyQt5 desde python, este dice que no existe el modulo(imagen 1), sin embargo PyQt5 si esta instalado correctamente ya que al ejecutar el comando de instalación el terminal muestra un mensaje diciendo que el programa ya se encuentra instalado (imagen 2)

- **Imágenes adjuntas:**
Imagen 1
![Imagen 1](https://user-images.githubusercontent.com/42159180/43802202-182228d8-9a63-11e8-9615-adbf80bf83dd.png)
Imagen 2
![Imagen 2](https://user-images.githubusercontent.com/42159180/43802323-7004a710-9a63-11e8-98c8-823d32283ea1.png)

**Comment by jecastro1** [comment]
Hola!

Mi intuición dice que no instalaste Python con Homebrew, porque de ser así, hubiera instalado Python 3.7. El punto es que ese modo de instalar PyQt funciona bien cuando la versión de Python se instala con Homebrew (_disclaimer_: basado en mi experiencia como usuario)

Sin embargo, se puede instalar PyQt con el siguiente comando: `pip3 install pyqt5`. Prueba si te funciona.

Saludos

**Comment by rjcavada** [comment]
Gracias, con el comando funciono.
