### ISSUE TITLE
Guardar Contraseñas en base de datos

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#40]
Hola! 🐱 

Las contraseñas que se guardan en db_users y utilizamos en el programa están encriptadas (de la misma forma que se encriptan los mensajes u de otra forma), o simplemente se trabajan como su valor original?

**Comment by FernandoPieressa** [comment]
Hola! 

Las constraseñas no estan encriptadas, lo único que pasa por el sistema de encriptación son los emails, por lo tanto se trabajan con su valor original.

Saludos!
