### ISSUE TITLE
Modificar codigo entregado (dimensiones ventana inicial)

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#400]
Estimados, se puede modificar el codigo **solo** para cambiar las **dimensiones iniciales y el nombre** de la ventana? (es solo para que cuando haga correr el codigo se abra de un tamaño mas comodo, lo del nombre es irrelevante)

**Comment by IchottMano** [comment]
@Cadagan Hola!

Lamentablemente, no puedes hacer eso, puesto que el código entregado no debe ser subido, por lo que to código posiblemente no corra con una copia limpia de la GUI.

Saludos!

**Comment by Cadagan** [comment]
ok, perfecto! muchas gracias! :)

**Comment by Cadagan** [comment]
Se puede heredar de las clases del codigo entregado o no? (hasta ahora lo habia hecho, pero si van a cambiar el codigo... 😕)

**Comment by IchottMano** [comment]
@Cadagan Si puedes, lo que hacemos es poner una copia limpia de la misma GUI que entregamos.
