### ISSUE TITLE
Requisitos para realizar "fisico determinista"

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#401]
En el nuevo enunaciado, en la actividad "fisico determinista" cuando dice:

 "_Tiene como requisito haber hablado con alguna persona y ser de personalidad **kibitzer.**_"

Se refiere a que **el cliente** que va a realizar la actividad "_fisico determinista_" debe ser de tipo "kibitzer" para hacerla, o se refiere a que debió de haber **conversado con una persona** de tipo "kibitzer"?

Muchas gracias por aclarar esto :)
saludos

**Comment by IchottMano** [comment]
@Cadagan Hola!

Se refiere a que el mismo cliente debe ser kibitzer.

Saludos!

**Comment by nachocontreras** [comment]
Hola!

El cliente debe ser de tipo "kibitzer".

Saludos!

**Comment by Cadagan** [comment]
En ese caso, el parametro "deshonestidad" solo es relevante para los de tipo "kiblitzer"? Debido a que cuando se conversa, este aumenta (para los dos que conversaron), pero el parametro solo se aplica cuando un kiblitzer decide o no realizar "fisico determinista" :confused: entonces para que lo tienen los demas?

**Comment by danaebardi** [comment]
Entonces, ¿solo los clientes tipo "kiblitzer" pueden ser expulsados por hacer trampa?

**Comment by nachocontreras** [comment]
@danaebardi Si.
@Cadagan Como un parámetro extra.
