### ISSUE TITLE
Razones de salida

### ISSUE THREAD

**Issue by Cadagan** [IIC2233/syllabus-2018-2#402]
En la estadistica "Razones de salida", solo consideramos "sin dinero" o "descubierto haciendo trampa", o cuando hablamos del caso en que se queda sin dinero, debemos entregar el **nombre de la ultima actividad que realizó** que lo dejo sin dinero? 

(ejemplo: perdio sus ultimos 50 pesos en la ruleta, la razon seria "ruleta")

Saludos :)

**Comment by agustinkrebs** [comment]
Hola!

No es necesario llegar a ese nivel de detalle, con lo primero que dijiste está bien.

Saludos!

**Comment by Cadagan** [comment]
@akrebs2 Gracias!!
