### ISSUE TITLE
Tiempo de simulación

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#405]
Hola!

Quería preguntar qué pasa cuando pasa más de un día en el casino (1440 minutos). ¿En ese caso se van todos los clientes y entran de nuevo?

**Comment by SantiagoHintze** [comment]
>El gran DCCasino pretende estar abierto siempre, ya que los apostadores llegan día y noche, como ocurre en Las Vegas. Aún así, asume que el casino abre un día cualquiera al mediodía. En otras palabras, el casino no cierra nunca, solo cuando la simulación termina.
