### ISSUE TITLE
Valor atributos según personalidad

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#407]
Para darle un valor a cada atributo de un cliente de acuerdo a los intervalos definidos para cada tipo de personalidad, ¿tiene que cumplirse que estos intervalos sean abiertos por arriba? Es decir, ¿un atributo que tiene un nivel bajo puede tomar un valor 0,3? Pregunto esto porque no encuentro ningún método de random que permita incluir intervalos abiertos.

Gracias.

**Comment by IchottMano** [comment]
@JavierNarvaez Hola!

Si, debe cumplirse lo de los intervalos. Podrías aprovechar la función random de la librería random que entrega números al azar en el rango [0, 1).

Saludos!

**Comment by gnacrur** [comment]
@IchottMano No entiendo cual es la importancia de que sea abierto o no si a fin de cuentas es un valor "continuo". La probabilidad de que salga un entero es casi 0. Considerando esto, ¿Nos descontaran si no programamos que sea abierto?  Solo pregunto porque ya lo hice así y si lo cambio no es como que mi simulación va a funcionar distinto.

**Comment by IchottMano** [comment]
@gnacrur Hola!

La idea que sea abierto es para que los intervalos no tengan valores compartidos.

Si tienes la elección de dos conjuntos, por ejemplo [0, 1] y [1, 2], en el caso que el numero elegido al azar sea exactamente 1 tendrás el problema de que este pretenece a ambos.

Espero esto haya aclarado tu duda.

Saludos!
