### ISSUE TITLE
Problema con tamaño de los personajes

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#408]
Tengo problemas con el tamaño de las imágenes cuando creo las entitys de Human dentro de mi simulación, estas aparecen mucho mas grandes (La imagen en sí esta bien pero el rectángulo negro es al menos 2 veces mas grande). 

He estado mirando los módulos que nos dieron y creo que el problema es la variable _SCALE, hice un print de ella dentro del init de Human y justamente los que aparecen mas grandes el valor deja de ser 0.5 y pasa a ser 1.515625

Como soluciono esto? ¿Es efectivamente un problema en los módulos de la interfaz? ¿Existe alguna manera de solucionarlo?

Help :(

Saludos

**Comment by Arcoirisky** [comment]
Holaaa~ Por casualidad eres ubutu/linux? o:

**Comment by bgsamilla** [comment]
Nop, Windows

**Comment by danaebardi** [comment]
Me ocurre lo mismo y también soy Windows . 
Adjunto imagen , el celeste es la nueva entidad que agregué y el verde es la que ya estaba agregada por la demo. 
Igual lo único que cambia es la imagen, el cuadro negro sigue del mismo tamaño, por lo que ¿influye en algo? ¿Las dimensiones son erróneas ? 
![image](https://user-images.githubusercontent.com/42223656/46261556-83984600-c4cb-11e8-9bf8-3e2d7b9b5bca.png)

Gracias (:

**Comment by bgsamilla** [comment]
O.o
Tenemos un problema similar no el mismo, por otro lado me preocupa tu imagen tengo resultados muy distintos.

![captura](https://user-images.githubusercontent.com/37226243/46263963-f534bc00-c4ec-11e8-97f3-2fd328c08c03.PNG)

Mi problema es el del team rocket mas bien su rectángulo.

**Comment by Arcoirisky** [comment]
La verdad es que no influye el tamaño o como se vea el borde. Mientras que cumpla con las restricciones está bien :) 

En el caso de los bordes, el choque debería controlarse según el tamaño de la imagen (sino podría ocasionar una saturación y nadie se movería :S)

Si recuerdan el spoiler que se les subió, las entidades también eran pequeñas. Esto se debe a que las imágenes se escalan al mapa y a sus contrapartes. 

Espero haberles ayudado y perdón por tardarme :’(

**Comment by Coolgatty** [comment]
Hola! No soy ayudante pero les puedo decir que pude replicar su problema poniendo el gui.set_size(x, y) antes de los gui.add_entity(entidad). Esto ocurre porque la variable _SCALE cambia con la funcion set_size().

Traten poner el gui.set_size() justo antes del gui.run() para evitar el problema.

**Comment by Coolgatty** [comment]
Hola! No soy ayudante pero pude replicar el problema poniendo gui.set_size(x, y) antes de los gui.add_entity(entidad). Esto ocurre porque la funcion set_size() de gui cambia la variable _SCALE en entities. 

Para arreglar este problema lo que hice fue poner el set_size() justo antes del gui.run(tick, n) y actualizar los angulos (entidad.angle += 0) en cada tick pues este ejecuta una funcion updatePixmap(), lo cual deja todo en una escala mas normal.

Ojala algun ayudante pueda responder si esta bien hacer esto.

**Comment by jpfernandez3** [comment]
a mi tambien me pasaba que el margen era mucho mas grande que la imagen del cliente.
lo solucioné poniendo cliente.setFixedSize(36,36)

**Comment by dberezin** [comment]
> Holaaa~ Por casualidad eres ubutu/linux? o:

Yo tengo este problema en ubuntu
