### ISSUE TITLE
Dealers por juego

### ISSUE THREAD

**Issue by adpolanco** [IIC2233/syllabus-2018-2#409]
Cual sería la capacidad máxima de dealers por juego? Esque suponiendo que son muchos, la probabilidad de descubrir personas que cuentan cartas sería prácticamente 1 (dependiendo de la constante de probabilidad claramente). Esto porque existen 62 dealers y está la posibilidad que existan como mínimo dos juegos.
Saludos

**Comment by IchottMano** [comment]
@adpolanco Hola!

Queda a tu criterio si poner un máximo de dealers por juego, no es importante que la probabilidad de contar cartas sea muy alta o no.

Saludos!

**Comment by NicolasCabello** [comment]
@IchottMano consulta, podria existir la posibilidad de que existan menos de 2 personas, o siempre deberan haber minimo 2 personas. En caso de ser la primera se asume que no se puede ocupar el juego/instalacion?
