### ISSUE TITLE
Citar códigos de StackOverflow

### ISSUE THREAD

**Issue by baaldana** [IIC2233/syllabus-2018-2#41]
Encontré un código útil que quiero incluir en mi tarea. ¿Cómo es el procedimiento para citarlo? Debo incluir el vínculo en el README, o hacer mención de que lo obtuve de otro lado con un comentario dentro del propio archivo.py?

**Comment by cilopez** [comment]
Hola @baaldana  puedes hacerlo de las dos maneras, yo te recomendaría comentarlo e incluirlo en el _readme_

**Comment by santilaguna** [comment]
Sobre como citar dentro del código, esta issue del semestre anterior te puede ser de ayuda: https://github.com/IIC2233/Syllabus-2018-1/issues/121
