### ISSUE TITLE
Porte de las entidades

### ISSUE THREAD

**Issue by Franco1605** [IIC2233/syllabus-2018-2#410]
Hola, mi pregunta apunta al porte de las entidades. Pasa que si no utilizo el atributo angle, todo tipo de figura se ve extremadamente pequeña. Y si lo utilizo (colocando, por ejemplo, entidad.angle+=0), esta se agranda bastante. ¿Con cuál me quedo?
![image](https://user-images.githubusercontent.com/42159289/46248981-bf61db80-c3f7-11e8-962a-b95169cabcff.png)
P.d: La ruleta y el tragamonedas agregado utilizan el atributo angle y se ven de esa forma. Y por si no se ve, hay un "ludópata" agregado en el punto 0,0 del mapa y que no se puede ver porque es enano.

**Comment by lily416** [comment]
Quédate con los de `entidad.angle += 0`, la otra opción es demasiado pequeña para verla la simulación.

Saludos 👋🃏

**Comment by Franco1605** [comment]
¿Y existe alguna otra forma de obtener esas entidades (grandes) sin tener que variar el ángulo?
@lily416

**Comment by lily416** [comment]
@Franco1605  Por ahora no, ya que no pueden modificar los archivos de la GUI.

Saludos 👋🎲

**Comment by lucasvsj** [comment]
DATO:
Puedes escribir: 
*nombre_de_entidad*.updatePixmap() 
despues de que agreges la entidad a tu interfaz para obtener el mismo resultado que al escribir:
*nombre_de_entidad*.angle += 0
