### ISSUE TITLE
Formato del diagrama de clases

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#411]
Hola

Para la entrega preeliminar del diagrama de clases entregare un pdf (bastante desordenado, pero se entiende). Sin embargo para la entrega final me gustaría entregar algo mas elaborado, recuerdo que un ayudante mencionó donde se podían hacer algunos como los que están en los contenidos.....

¿Como/Donde puedo hacer diagramas mas bonitos? :3

Saludos!

**Comment by Polea012** [comment]
Hola! Las páginas draw.io y Lucidchart te podrían ser de utilidad para crear diagramas.

Saludos

**Comment by bgsamilla** [comment]
Muchas Gracias!

**Comment by Gorgola22** [comment]
Entonces se puede entregar un archivo con extensión .xml?
