### ISSUE TITLE
Últimas chauchas

### ISSUE THREAD

**Issue by cristianhdez** [IIC2233/syllabus-2018-2#412]
Hola,

Si un jugador se queda con menos dinero del que puede usar en cualquier juego/instalación y quiere gastarlo, puede completar la acción en la que gasta el dinero? (si me queda 1 de dinero y quiero apostar en la ruleta, por ejemplo). Si intenta jugar con lo poco que le queda (pueda apostar o no), entra a las ganancias del casino? Si tiene dinero suficiente como para realizar una acción "x", pero no una acción "y", y decide hacer la "x", lo intenta con el dinero que le queda o desiste de la acción? Gracias de antemano!

**Comment by cacoos** [comment]
Me sumo a la pregunta. Qué pasa si partió con 150 de dinero y en algun momento dado pierde casi todo y queda con 0.7.
Se debe ir?

**Comment by cristianhdez** [comment]
bump
