### ISSUE TITLE
[Superclases] - Interacción con subclases

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2233/syllabus-2018-2#413]
¿Es recomendado definir un método en una _superclase_ **que utilice atributos de su _subclase_**, para así llamarlo desde la _subclase_ misma?

**Comment by agustinkrebs** [comment]
Hola!

Puedes dar un ejemplo para clarificar?

**Comment by VicenteVicente** [comment]
Creo que ya no es necesario, fue un malentendido mio el intentar hacer esto, saludos!
