### ISSUE TITLE
funcion deleteLater()

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#414]
Hola!
En el enunciado sale que existe una función llamada deleteLater() la cual elimina una entidad de la interfaz. En ningún lado de la clase Entity existe una función llamada así y tampoco funciona al ocuparla (por si no la hubiera visto pero existiera). Es por esto que quería preguntar si nosotros tenemos que crear esta función o sino como podemos eliminar una entidad del casino si es que se quiere ir?.
Muchas Gracias!!

**Comment by bgsamilla** [comment]
No esta en los módulos pero si que existe y funciona.
Lo único que se me ocurre que ocasione que no te funcione es porque estas llamándola así:

deleteLater(Entity)

Mientras que debería ser:

Entity.deleteLater()

Saludos!
