### ISSUE TITLE
Probabilidad de ir a una instalación

### ISSUE THREAD

**Issue by FloValdes** [IIC2233/syllabus-2018-2#415]
Hola! La probabilidad de ir a una instalación me da 0 en la gran mayoría de los casos (según la parte 3.1.3, decisiones, del enunciado). 
Está pensado así?

**Comment by fernandodediegoavila** [comment]
Hola!
Es bastante probable que, dadas las características de cada cliente, dicha probabilidad te de 0. Fue pensado así, para priorizar el juego (que es característico de un casino). Si te interesa saber cómo evoluciona tu programa cuando un cliente va a una instalación, puedes modificar los rangos de los valores que toma cada característica según personalidad.
Saludos!
