### ISSUE TITLE
Puntaje Tarea2 y simulacion

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#416]
Leyendo el feedback de la tarea me di cuenta, que en ninguna parte se hace mencion de las colisiones o de cosas relacionadas con la interfaz gráfica. Es que acaso no tiene puntos?

y segundo respecto a la simulacion, si hacemos un segundo por minuto en la simulacion, no seria demasiado larga la simulacion, 1 solo dia tardaria 24 minutos. Que hay con respecto a esto?

Saludos!

**Comment by IchottMano** [comment]
@Banfanci Hola!

En primer lugar, si se evaluarán las colisiones de las entidades.

En segundo lugar, eso queda a tu criterio, si crees que es mucho tiempo, puedes bajarlo.

Saludos!

**Comment by NicolasCabello** [comment]
@IchottMano en el punto 2, a que te refieres con bajarlo?, onda simular con fracciones de dias o por ejemplo decir que 1 segundo se simulacion es, por ejemplo, 5 minutos del programa?

**Comment by felipegarcia98** [comment]
> @IchottMano se refiere a disminuir los milisegundos que tiene la funcion gui.run como delay
