### ISSUE TITLE
Cantidad apostada en tragamonedas

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#417]
Hola! Para los tragamonedas también corre la misma formula de la cantidad que apuesta cada persona ? Pregunto esto porque no hay ningún beneficio en apostar más o menos en este juego, ya que tanto el premio como la probabilidad de ganar son independientes de la cantidad apostada. A mi parecer es mucho más lógico que la cantidad apostada en este juego sea una cantidad fija

**Comment by nachocontreras** [comment]
Hola!

Para el tragamonedas corre la misma fórmula.

Saludos! :smile:
