### ISSUE TITLE
Dealers comprados por la mafia

### ISSUE THREAD

**Issue by cjortuzar** [IIC2233/syllabus-2018-2#419]
Hola!

Una pregunta, como se cuantos y qué dealers están comprados por la mafia? O es random?

Gracias!

**Comment by lily416** [comment]
Puede haber una cantidad fija de dealers comprados por la mafia y repartirlos entre los juegos o pueden tener una probabilidad. A fin de cuentas queda a tu criterio, pero debes especificarlo en el readme.

Saludos 👋 🃏
