### ISSUE TITLE
Problema al escribir base de datos, PermissionError

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#42]
Estoy tratando de escribir un email nuvo en la base de datos, utilizando el método del path relativo que se enseña en la tarea, pero recibo el siguiente error:

 PermissionError: [Errno 13] Permission denied: 'data/db_users.csv'

Esto a que se debe?

**Comment by cilopez** [comment]
Quizás algun programa tiene el archivo abierto , puedes tratar de cerrar cualquier cosa relacionada con ese archivo y me dices que tal.

**Comment by pelao97** [comment]
lo intente, pero tengo el mismo problema, nose si sera, porque en una misma funcion primero abro el archivo en formato de lectura (con with open ...) , y luego a la misma altura pero al final de la funcion lo abro en forma de escritura, tal vez eso genera un error

**Comment by santilaguna** [comment]
Si, ese es el problema! Cuando usas with estás bloqueando el acceso al archivo para evitar problemas no esperados, esto lo entenderás mejor cuando veamos threads. 

Nota: Si los abres de la manera normal probablemente también se levante un error, pues python no permite cambiar desde formato lectura a escritura sin cerrar el archivo previamente (lo cual la sentencia with hace por si sola)

**Comment by danielaguilera** [comment]
Hola! He intentado abrirlo de todas las maneras posibles y tengo el mismo problema. ¿Qué se puede hacer para resolverlo?
