### ISSUE TITLE
Duda sobre estadística #10

### ISSUE THREAD

**Issue by matiasop** [IIC2233/syllabus-2018-2#422]
Hola 

Tengo una duda sobre la estadística número 10, que dice lo siguiente: "Número de personas que visitó cada juego en promedio por día".
 No estoy seguro a que se refiere con la frase 'cada juego', ya que este podría referirse a 2 cosas distintas:

a) Número de personas que visitan los juegos (ejemplo: Ruleta: 10 clientes, Tragamonedas: 15 clientes)

b) Personas que visitaron la instancia de cada juego (ejemplo: Ruleta_1: 3 clientes, Ruleta_2: 7clientes, Tragamonedas_1: 10 clientes, Tragamonedas_2: 5 clientes)

Mi pregunta es: ¿A cuál de estas dos se refiere?

**Comment by rhanuch** [comment]
¡Hola @movalle4 !

La estadística se debe realizar como planteas en a), es decir, por tipo de juego y no por instancia de estos 💎🍒💰

¡Saludos! 🍀

**Comment by faandrade** [comment]
Hola!, y si un cliente utiliza por ejemplo un Tragamonedas, luego decide hacer otra accion y posteriormente vuelve al mismo Tragamonedas, se cuenta como 1 persona o como dos distintas para efectos de las estadisticas?

**Comment by rhanuch** [comment]
¡Hola @faandrade  !

¡Cuenta como una!

¡Saludos! 🍀🎰
