### ISSUE TITLE
gui en feedback

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#423]
Hola, 

hago está issue para preguntar el puntaje que dará el usar correctamente la interfaz grafica. Esto ya que revisé el feedback y no encuentro nada que hable respecto a ello.

Saludos

**Comment by javierabao** [comment]
Hola!
Fernando respondió esta duda hace poco en un mail. Lo dejo aquí por si alguien olvida lo que dice el mail:
"Para la tarea 2, es obligatoria la utilización de la interfaz, tareas que no tengan interacción con esta, solo podrán tener puntaje en el apartado de programación orientada a objetos, teniendo 0 puntos en el resto de los apartados."

**Comment by Kitaps** [comment]
Gracias, 

y como pondera el puntaje de la gui?

**Comment by javierabao** [comment]
No tiene una ponderación en particular, simplemente es un criterio necesario para poder corregir la tarea (menos la parte de OOP, que se corrige aunque no implementen la gui).

**Comment by jdiaztoledo** [comment]
Hola, en el caso de que se interactúe con la interfaz, pero el desplazamiento no sea el ideal (por ejemplo, los personajes se teletransportan), ¿el descuento quedará a criterio del ayudante?
