### ISSUE TITLE
Mapa de la simulación

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#424]
Hola!

Para la parte de la simulación en la interfaz, ¿puedo hacer que se cree un mapa con las instalaciones precisamente donde yo quiera y que los clientes si quieren ir a algun lugar, sepan hasta donde avanzar Y a donde ir, ya que cree un mapa específico? ¿O mientras avanza el cliente se tiene que dar cuenta de lo que hay alrededor? Ej.: si el jugador quiere ir al baño, entonces que se mueva hasta la posición (x,y), que es el baño más cercano.

Gracias de antemano

**Comment by lily416** [comment]
Sí, puedes ubicar las instalaciones y juegos donde quieras 😄 pero debes tener cuidado con no colisionar con las instalaciones y juegos en el mapa 👀 
Aunque no es una obligación que los clientes "se den cuenta" de lo que hay alrededor, es una buena práctica aplicarlo, por lo menos en el sentido de avanzar hasta la instalación o juego más cercano (dentro del tipo elegido).

Saludos 👋🃏
