### ISSUE TITLE
[Error PyQt5] ImportError: DLL load failed: %1 no es una aplicación Win32 válida.

### ISSUE THREAD

**Issue by mihenriquez** [IIC2233/syllabus-2018-2#425]
Llevo infinito 👵  tratando de solucionar este error. He hecho muchas cosas que he encontrado en internet pero nada ha servido, y la verdad tampoco entiendo muy bien que estoy haciendo 😞 .

Por favor ayudenme! Me he atrasado demasiado por esto 😭 

` File "C:\Users\Maria Ignacia H\Desktop\T02\gui\main_widget.py", line 2, in <module>
    from PyQt5.QtCore import QTimer
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.`

**Comment by naquiroz** [comment]
Hola! podrías correr `pip list` en tu terminal y enviar un pantallazo de que te aparece? Saludos!

**Comment by mihenriquez** [comment]
![captura](https://user-images.githubusercontent.com/42191893/46266220-f02f3700-c503-11e8-9c7a-5a2bd772d9d3.PNG)

**Comment by naquiroz** [comment]
Ok! Y ahora `python -V` que te aparece?

**Comment by mihenriquez** [comment]
Tenía la última versión de pyqt5 pero en un lado lei que a veces se solucionaba descargando la 5.9, en ninguno de los dos casos funcionó.
![captura2](https://user-images.githubusercontent.com/42191893/46266256-3ab0b380-c504-11e8-9ad6-4dbfb31aff59.PNG)

**Comment by naquiroz** [comment]
Ok, ahora, puedes hacer lo siguiente? (todo esto es para saber que versiones de cosas tienes)

1. abre un terminal con permisos de Administrador (busca en tu buscador `powershell` haz click con boton derecho y coloca `Abrir como administrador`, pon "Aceptar" (o algun equivalente))
2. abre la consola de python (ejecuta `python` a secas y apreta enter)
3. envía un pantallazo de lo que te sale al comienzo de la consola.
4. sal de la consola con `exit()`
5. Ejecuta en la misma terminal `wmic os get osarchitecture` y envía un pantallazo de eso.

**Comment by mihenriquez** [comment]
![captura3](https://user-images.githubusercontent.com/42191893/46266469-bbbc7a80-c505-11e8-8f8f-b92f9212a694.PNG)
![captura4](https://user-images.githubusercontent.com/42191893/46266471-bbbc7a80-c505-11e8-9c46-6fe6a3c31eb6.PNG)

**Comment by naquiroz** [comment]
Ok intenta la siguiente solución:

1. Entra [aquí](https://sourceforge.net/projects/winpython/files/WinPython_3.6/3.6.6.2/WinPython64-3.6.6.2Qt5.exe/download) y deja que se descargue el ejecutable WinPython.exe
2. Abre el instalador (el .exe), selecciona una ubicación para los archivos y busca el `python3.dll`dentro de ellos (una vez instalado).
3. Copia ese archivo `python3.dll`y busca la ubciación de tu archivo `python36.dll` (yo lo que hice fue abrir la barra buscadora de windows y buscar `python3 .dll` (nótese el espacio entre python3 y `.dll`, para encontrar todos los posibles resultados)
4. En la misma ubicación de este archivo (asegúrate que sea dentro de la ubicación donde tu python está instalado) pega el `python3.dll`.
5. Prueba si se arregló 🤞 

Coméntame como te fue! Saludos!

PS: Si se arregló puedes borrar todas las otras cosas que creó WinPython , simplemente borrando la carpeta que elegiste como ubicación para la descarga de los archivos .

**Comment by mihenriquez** [comment]
Tengo un python36.dll en la misma carpeta de WinPython pero no encuentro otro. Cuando dices "en la misma ubicación donde tu python esté instalado" te refieres a donde haya un ejecutable o donde tengo el IDLE y todo eso (en la carpeta programas)?  porque en esta última no tengo otros archivos además de los típicos 3 o 4 que se crean cuando descargas python (como el IDLE).

Ya había descargado un par de veces antes WinPython así que siento que tengo una ensalada de archivos en mi computador 😢

**Comment by mihenriquez** [comment]
![captura5](https://user-images.githubusercontent.com/42191893/46267502-b9f5b580-c50b-11e8-8a21-09c08bc98cf3.PNG)

**Comment by naquiroz** [comment]
Escribiendo ... ⌨️  ⏳

**Comment by mihenriquez** [comment]
Y en WinPython tengo python3.dll y python36.dll

**Comment by naquiroz** [comment]
No, me refiero a que tienes que pegar el archivo `python3.dll` (creado por winpython), en la ubicación donde tienes instalado python. Esta ubicación suele ser en `AppData`, adjunto mi caso, donde `nicol` es mi nombre de usuario.

![image](https://user-images.githubusercontent.com/29825816/46267591-325c7680-c50c-11e8-893d-489cf978ee6a.png)

Si no sabes como acceder a `AppData`, la forma facil es apretar `Win + R` y colocar en la ventana que aparece `%APPDATA%` y volver un directorio hacia atrás (Dado que puede abrirse en `AppData>Roaming`). Como verás, en la ubicación donde tengo instalado python hay un `python36.dll`, ahí debes pegar (y reemplazar si necesario) el `python3.dll` creado por python. (**Debes pegar el `python3.dll` no el `python36.dll`**)
