### ISSUE TITLE
Probabilidad tragamonedas

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#426]
En la parte de tragamonedas, la probabilidad α es la probabilidad de ganar, pero no deberia ser la probabilidad del juego, de esa forma poder ocupar la ecuación que aparece arriba. 
![image](https://user-images.githubusercontent.com/42160988/46267405-215f3580-c50b-11e8-9f28-064a81362468.png)

**Comment by IchottMano** [comment]
@fjlopez7 Hola!

Efectivamente, alfa es la probabilidad del juego.

Edit: Buena foto jajaja

Saludos!
