### ISSUE TITLE
Jornada del Personal

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#427]
Hola, en el enunciado sale que el personal del casino debe trabajar entre 6 y 9 horas diariamente, y que luego debe descansar entre 8 y 20 horas. Mi duda es si debemos controlar que cada día (24 horas) se trabaje la cantidad pedida y luego no se vuelva hasta el día siguiente o si en realidad se refiere a que cada TURNO debe durar de 6 - 9 horas sin importar el día. Esto porque en el primer caso se podría trabajar por ejemplo 6 horas y luego descansar 8 y al momento de volver puede que aún sea el mismo día (por lo que habría que 'evitar' que entre a la 'hora del siguiente turno' hasta que cambie el día), en el segundo caso esto no importaría.

**Comment by cilopez** [comment]
Cada día sí o sí un trabajador debe trabajar sus 6-9 horas por "contrato", como dices en el segundo caso.

**Comment by BFFV** [comment]
Entonces puede ocurrir que el personal trabaje 2 veces dentro de las mismas 24 horas? (Ej: trabajar 6-9 descansar 8 y trabajar 6-9 todo en el mismo día)

**Comment by cilopez** [comment]
No , son maximo 9 horas por dia

**Comment by cacoos** [comment]
Entonces tendría mas tiempo de descanso 🧐, siendo que este tambien tiene un maximo

**Comment by joaquinhernandezg** [comment]
ward

**Comment by jcechavarri** [comment]
@cilopez 

> Entonces puede ocurrir que el personal trabaje 2 veces dentro de las mismas 24 horas? (Ej: trabajar 6-9 descansar 8 y trabajar 6-9 todo en el mismo día)

> No , son maximo 9 horas por dia

Entonces el tiempo de descanso no podría ser una distribución normal como dice en el enunciado, debido a que no siempre la combinación de la distribución triangular de trabajo con la distribución normal de descanso cumplirá con ese requisito :/

**Comment by cilopez** [comment]
@cacosandon @joaquinhernandezg  @jcechavarri @BFFV 
Pueden hacerlo de las dos formas modelar como 6-9 horas fijas pero su descanso pasaría a ser 18-15 horas diarias, o obtener una instancia de trabajar (trabaja X tiempo) y luego una instancia de descansar (descansa Y tiempo) t así hasta que termine la simulación.

**Comment by joaquinhernandezg** [comment]
@cilopez En cualquiera de la las dos opciones estariamos violando lo que dice el enunciado. No hay problema si se especifica en el readme?

**Comment by cilopez** [comment]
Si no hay problemas, esto es un dato menor que no tiene demasiada relevancia mientras tenga sentido, usen una de esas dos opciones.

**Comment by BFFV** [comment]
Con la segunda opción te refieres a simplemente obtener al azar el tiempo del turno y de descanso (con las distribuciones) y no preocuparse de que entre a trabajar el siguiente turno en el mismo día ?

**Comment by cilopez** [comment]
Si me refiero a eso.

**Comment by BFFV** [comment]
Gracias!
