### ISSUE TITLE
Duda sobre Apuestas

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#428]
Hola, según la sección notas del enunciado un ludópata debería apostar más que alguien normal, pero según lo indicado en la sección de los atributos del cliente la cantidad a apostar depende de la ansiedad, por lo que pueden existir casos en los que otra personalidad apueste más que un ludópata. También me preguntaba si en el caso de no tener suficiente dinero para apostar según la fórmula se debe denegar esta opción al cliente o este igual puede apostar lo que le queda de dinero.

**Comment by Arcoirisky** [comment]
La idea es que al apostar en un juego debe de cumplir con la apuesta base. Sino no puede jugar :’c 

Sobre lo primero, no entiendo dónde está la pregunta 🤔

**Comment by BFFV** [comment]
La primera era para ver si había algo que controlar con respecto a las apuestas de un ludopata y otro personaje (independiente de la ansiedad), pero veo que no. Respecto a lo segundo con apuesta base te refieres a la fórmula (1 + theta*ansiedad)*apuesta base juego? Porque sale que así se debe calcular la apuesta del cliente. Aparte de eso se supone que la apuesta base del juego es la apuesta mínima que es igual a 1 o no?

Gracias!

**Comment by javierabao** [comment]
Claro, calculas lo que apuesta la persona como (1 + theta*ansiedad)*apuesta_base_juego, siendo apuesta_base_juego la apuesta mínima que es 1. En caso de que no tenga el dinero para apostar, no puede jugar.

**Comment by BFFV** [comment]
Gracias!
