### ISSUE TITLE
Fila Instalaciones

### ISSUE THREAD

**Issue by sicalderon1210** [IIC2233/syllabus-2018-2#429]
Si un cliente decide ir a una instalación y esta ya cuenta con su capacidad máxima, se debe poner a la fila.
Mi duda es, el cliente está obligado a esperar hasta que le toque? O sea, no se puede salir de la fila?

**Comment by vjlira** [comment]
Hola, si la fila está llena no debería poder entrar a la instalación ni a la fila. Si ya se está en la fila se queda esperando hasta que pueda entrar. Suerte!

**Comment by cacoos** [comment]
La capacidad indicada en el enunciado es de la instalacion o de la fila?

**Comment by vjlira** [comment]
Aclaración, la capacidad es de las instalaciones.  No se indica nada sobre la capacidad de las filas pero queda a tu criterio, pero si debería esperar un tiempo, ya que si está todo lleno no podrá realizar ninguna actividad y solo deambulará.
