### ISSUE TITLE
Duda base de datos

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#43]
Hay alguna restricción sobre como debería crear mi base de datos? Puedo tomar los datos de los archivos, pasarlos a mi base datos para luego continuar trabajando sobre esta?

**Comment by bgsamilla** [comment]
Tengo la misma pregunta, en caso de poder traspasar los datos:
 ¿Tengo que hacer que el programa lo haga? 
En tal caso podemos asumir que la base de datos antigua tendrá la misma ruta relativa y los mismos nombres que los .csv del enunciado?

**Comment by ptflores1** [comment]
Hola !
Su programa debe ser capaz de leer las bases de datos que nosotros les dimos, a la hora de corregir usaremos la misma estructura que estas tienen. Para guardar la nuevos datos les recomiendo que los guarden los mismos archivos que les dimos, aun asi si quieren manejar las bases de datos de otra manera son libres de hacerlo pero, repito, tengan en cuenta que nosotros **revisaremos con los archivos (o con la misma estructura) que les dimos**.

Saludos !

**Comment by Franco1605** [comment]
Entonces en la carpeta datos que tenemos que crear, deberíamos colocar las bases de datos que ustedes nos dieron :o ?

**Comment by ptflores1** [comment]
Si, tu programa debe ser capaz de partir con esos archivos y luego es decision tuya si sigues usando los mismos o si creas nuevos.

**Comment by alexaptib** [comment]
Tengo una duda sobre esto, ya que originalmente las bases de datos entregadas estan en un directorio 'data', pero en el enunciado pide que lo guardemos en uno llamado 'datos'. Serian el mismo directorio? puedo simplemente editar las bases de datos entregadas y leer de esas misma?

**Comment by ptflores1** [comment]
Hola !
Da lo mismo el nombre de la carpeta. Si puedes utilizar los archivos que les dimos como tus bases de datos.
Saludos !
