### ISSUE TITLE
Stamina a 0

### ISSUE THREAD

**Issue by FloValdes** [IIC2233/syllabus-2018-2#430]
Hola! El enunciado dice que la stamina debería ser 0 si es que el cliente ya no tiene dinero (y con eso se iría del casino), sin embargo como las apuestas y el dinero inicial no es un número entero, (y aunque lo fueran igual está el baño), que el dinero inicial llegue a 0 exacto es bastante poco probable, podría hacer que la stamina baje a 0 si tiene menos de 1 en dinero? Ya que con eso no puede hacer nada más que ir al baño.

Gracias.

**Comment by nachocontreras** [comment]
Hola!

Sí, se puede decir que la stamina baja a 0 si tienes menos de 1 en dinero.

Saludos! 😄
