### ISSUE TITLE
Elección comportamiento de jugador

### ISSUE THREAD

**Issue by pablovejar** [IIC2233/syllabus-2018-2#431]
Tengo una duda con respecto a las decisiones de los jugadores, por ejemplo en la ruleta, ¿podemos asumir que ningún jugador tendrá alguna preferencia por algún numero para apostar por ese? Y asumir que en cada turno el jugador ira variando el número por el cual quiere apostar? ¿O cada personaje debe tener un comportamiento distinto (en cuanto al tema de la ruleta en específico)?
Muchas gracias!

**Comment by vjlira** [comment]
Hola, la elección del numero es al azar, por lo que no hay preferencias. En cada turno el jugador varía su apuesta según su ansiedad (explicado en el enunciado). Suerte!
