### ISSUE TITLE
entities: Human, Building, etc ...

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#434]
Hola! Tengo una duda con respecto a las clases que nos entregan en entitities.py. 
Como debería hacer para poder ver mis clases en la interfaz gráfica? Deberían heredar de las clases entregadas en entities.py? O que otra opción existe?
Muchas gracias 😭

**Comment by ChaparoD** [comment]
justamente, te recomiendo heredarlas y jugar con las funciones que aplica demo.py para relacionarte con lo que ya viene implementado. 💯
