### ISSUE TITLE
Cantidad de juegos o instalaciones

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#436]
Hola, me parece que en ninguna parte del enunciado especifican la cantidad de mesas de ruleta, tragamonedas, baños o restobares que deben haber (respecto al Tarot se puede inferir algo más pero tampoco es determinante). Me parece que tampoco se especifica la probabilidad de que un dealer esté comprado por la mafia. 

¿La definición de estos parámetros es decisión nuestra? Gracias de antemano

**Comment by vjlira** [comment]
hola, #419 y #373 resuelven tus dudas.
