### ISSUE TITLE
Capacidad Juegos

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#437]
Los juegos tienen una capacidad máxima? Por ejemplo, pueden jugar 20 personas simultáneamente en el mismo tragamonedas?

**Comment by javierabao** [comment]
Hola!
Intenta que tu modelación quede lo más similar a la realidad, al final ese es el sentido de la simulación. Teniendo esto en consideración, lo más correcto sería que no pudiera haber 20 personas simultáneamente en el mismo tragamonedas.
Igualmente, cualquier supuesto que hagas, puedes especificarlo en el readme!

**Comment by javierabao** [comment]
Aclarando un poco más, lee la issue #382. En esta se dice "Si hay filas y pueden producirse en los juegos. No puedes asumir que la capacidad en estos es infinita". Para que consideres el modelar filas en los juegos y no jueguen personas simultáneamente.
