### ISSUE TITLE
Ruleta

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#438]
Hola!
Cuando un cliente juega a la ruleta y se necesita calcular si gana o pierde no entiendo si debemos realizar una "simulación", ósea que escoja un numero al azar y la ruleta también y ver si coinciden. O simplemente calcular la probabilidad de ganar y crear un criterio tipo: prob>0.6: cliente gana.
Lo otro, se dice que el cliente decide apostar por un numero o color al azar, pero dentro de color, ¿Nosotros decidimos cual es la probabilidad de que escoja cada color (por ejemplo 1/3)?  ¿O se debe calcular una probabilidad proporcional a color-cantidad de numero?

Gracias!

**Comment by javierabao** [comment]
Hola!

No es necesario crear un criterio. Primero, lo que tienes que hacer es ver si elige número o color, al azar. Si elige número, no es necesario que simules que el usuario elige "x" número y que en el juego sale "y" número, porque la probabilidad de achuntarle sigue siendo la misma (1/(γ + 1)).

Con respecto al segundo punto, puedes hacer que al principio, elija al azar entre número, rojo, verde y negro, en vez de elegir solo entre número y color. Igualmente lo puedes dejar a tu criterio, no es de vida o muerte. Especifica ese tipo de decisiones en el readme, para entender tu razonamiento.
