### ISSUE TITLE
Tragamonedas mafiosos

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#439]
Hola, 

duda corta,
Los tragamonedas pueden ser manipulados por (dealers) mafiosos, para aumentar la chance de ganar de clientes mafiosos? O los mafiosos solo son ayudados en la ruleta?

Gracias

**Comment by javierabao** [comment]
Hola!
Como en el enunciado dice que aquellos que hablan con Tini, son los que aumentan su probabilidad de ganar en las mesas, considera que los mafiosos solo son ayudados en la ruleta. Si ya lo consideraste de otra forma, igual puedes especificarlo en el readme.
Saludos!
