### ISSUE TITLE
Creación de módulos

### ISSUE THREAD

**Issue by cegalleta** [IIC2233/syllabus-2018-2#44]
Hola!
Voy súper creando mis códigos y tengo varias maquetas para distintas cosas en la tarea, el punto es que no me quedó muy claro de las clases como llamar y guardas los módulos correctamente.
Tengo que dejarlos en otra carpeta o en la misma? Python buscará en las carpetas cercanas al código o...?
No sé muy bien el formato para modulalizarlo, y no entiendo muy bien tampoco la lógica del if __name__ == “__main__”, significa que si el nombre es el de nuestro código no se ejecuta el resto del código importado que no define variables? En introducción a la programación escribía un código de 1000 líneas y me está jugando muy en contra ahora, así que si me resuelven esta duda, sería como si lloviesen sopaipillas (mejor día ever)
Desde ya, muchísimas gracias!
P.D: Gracias por agregarme la etiqueta, no sabía como hacerlo

**Comment by Arcoirisky** [comment]
Hola~ deja ver si puedo iluminarte con las frituras más deseadas de la galaxia uwu 

1) el "if __name__ == '__main__':" es para que puedas probar el funcionamiento de tu módulo/archivo sin la necesidad de borrar esas pruebas al momento de que el programa principal lo ejecute. Otra forma de verlo es que, todo lo que esté dentro de ese if se ejecutará **únicamente** al ejecutar ese archivo en particular. 

Más información en [este link](https://es.stackoverflow.com/questions/32165/qu%C3%A9-es-if-name-main)

Igual te daré un ejemplo muy piola, a ver si te ayuda a entender xD

Piensa que tengo un archivo `printear.py`
```python
def hola(): # Una super función de ejemplo
         print("hola mundirijillo")

hola() # llamo a la función sin hacer uso del if __name__ porque sólo quería probar la función
```

y luego tengo otro archivo `main.py` en la misma carpeta que `print.py`
```python
from printear import hola # Es una forma de importar funciones específicas
# otra comúnmente utilizada es:
# import printear as pr 
#el "as pr" es para que no tengas que escribir "printear.<funcion>" sino "pr.<funcion>"

hola() #Cómo dije antes, al printear una función específica no necesito ponerle apellido al frente
```

Al momento de ejecutar `main.py` el output sería
```python
"hola mundirijillo" #El del archivo printear.py
"hola mundirijillo" #El de main.py
```

Si sólo quieres que `main.py` diga el hola entonces el `printear.py` debió ser:
```python
def hola(): # Una super función de ejemplo
         print("hola mundirijillo")


if __name__ == '__main__':
         hola() # Ahora el mundo es bello y puedes probar tus funciones sin miedo <3
```

_____________

2) Modularizar no es tan terrible, vas separando los archivos según su tipo o funcionalidad. Por decirte algo, las clases personas en un archivo, funciones sueltas que sirven para no repetir código y que usas seguido en un archivo a parte, etc. La idea es que las separes de forma inteligente para que todo se mantenga ordenado y no tener que buscar una sola linea dentro de un archivo de 800+ líneas D: 

En el ejemplo anterior te dije unas de las formas del cómo importar pero en este [link](https://stackoverflow.com/questions/10501724/how-does-python-importing-exactly-work) puedes encontrar más información.

______________

Cualquier cosa pregunta con confianza :D

**Comment by cegalleta** [comment]
Ohhh, muchas gracias c:
Una última cosa! los módulos tienen que estar siempre en la misma carpeta? O los puedo ir dejando en otras carpetas? Creo que en clases nos mostraron una diapo donde salía el orden de prioridad que tenía python para eso, pero no la encuentro :(

**Comment by Arcoirisky** [comment]
pueden estar en distintas carpetas :D pero te sugiero que al importarlos des la dirección O:! onda
```
import archivos/funciones #ó
from archivos/funciones import funcion
```
por orden estaría bien aunque debes tener cuidado porque debe seguir funcionando tu tarea al momento de probarla en nuestro computador xD así que mientras no salgas de la carpeta T0X puedes hacer las carpetas o módulos que sientas que convienen más :D

**Comment by cegalleta** [comment]
beiobeio, gracias! 
Por cierto, cierro el issue o lo dejo abierto?

**Comment by Arcoirisky** [comment]
Tranqui uwu nosotros le agregamos un label "resuelto" :D déjalo abierto ouo
