### ISSUE TITLE
 [Error] QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by cristozille** [IIC2233/syllabus-2018-2#440]
Hola, intente correr mi código pero me aparece este error. Alguien sabe a que se puede deber?
Gracias

**Comment by IchottMano** [comment]
@cristozille Hola!

Hiciste gui.init() ?

Saludos!

**Comment by tiarasilva** [comment]
Hola, me ocurre lo mismo y si hice gui.init().
Me funciona sin instanciar mis clases, pero cuando llamo algo de mi archivo tarea_2 se cae y me muestra ese error.
:( gracias :(
![captura de pantalla 2018-10-02 a la s 23 59 41](https://user-images.githubusercontent.com/37164177/46387843-42f12600-c69f-11e8-8a52-77a88e463893.png)

**Comment by IchottMano** [comment]
@tiarasilva Hola!

En tu módulo tarea_2, tienes código que corre solo? Cuando importas un módulo python corre ese código, en ese caso tienes que poner

```python
if __name__ == "__main__":
    # tu código
```

De esta manera el **código suelto** no corre al importar el módulo.

Dime si esto te resulta.

Saludos!

**Comment by tiarasilva** [comment]
Ahí me funcionó, muchas muchas graciaaaas <3
