### ISSUE TITLE
Problema con Modularización Cíclica

### ISSUE THREAD

**Issue by AndresFaure** [IIC2233/syllabus-2018-2#441]
Hola, tengo el siguiente problema: 

Digamos que tengo un dos archivos llamados **a.py** y **b.py** que tienen definidas **funcion_a** y **funcion_b** respectivamente. Resulta que quiero que **ambos** archivos (a.py y b.py) tengan acceso a **ambas** funciones, sin tener que reescribirlas. Para eso uso `import  a` en b.py e `import b` en a.py para así tener acceso a ambas funciones.
De lo que he buscado en Google, entiendo el problema que esto causa, y he encontrado un par de soluciones (por ejemplo, solo importar módulos cuando sean ocupados, dentro de clases, en funciones, etc. en vez de al principio del archivo como es costumbre) pero no me convencen. 
¿Cuál es la mejor forma para abordar este problema?
¡Gracias!

**Comment by rhanuch** [comment]
¡Hola @AndresFaure !

Digamos que en tu archivo `a.py` tienes la siguiente función:

```python3
def pasar_ramo(ramo="IIC2233"):
    return "Pasé el ramo: {0}".format(ramo)
```

Mientras que en tu archivo `b.py` tienes:
Hay dos maneras de solucionar esto:

```python3
def pasar_ramo(ramo="IIC2233"):
    return "No mentiré, no pasé el ramo: {0}".format(ramo)
```

1. Hacer un import genérico, es decir:

```python3
import a
import b

print(a.pasar_ramo())
# > "Pasé el ramo: IIC2233
print(b.pasar_ramo())
# > ""No mentiré, no pasé el ramo: IIC2233
```

2. Renombrar tus funciones para evitar el override que se hace por debajo. Una manera de entender lo que ocurre es pensar que cada módulo de `Python` tiene, por debajo, asociado un diccionario en el cual su `key` es el nombre de a función, clase, variable, etc. y su value es la dirección en memoria de lo que se está almacenando, por lo que se puede tener un [puntero](https://es.wikipedia.org/wiki/Puntero_(informática)) ⬇️. Es por lo anterior que es las dos cosas siguientes son diferentes:

```python3
a.pasar_ramo
# > Imprime dirección en memoria
a.pasar_ramo()
# > "Pasé el ramo: IIC2233
```

Uno se está refiriendo a la dirección en memoria, mientras que el otro está haciendo el llamado al método. En este sentido, lo que tu quieres hacer, sería que con una misma llave se llame a dos lugares diferentes en memoria, lo cual no es posible (al menos de manera simple y convencional), ya que los diccionarios son como funciones sobreyectivas (si, como las de cálculo) 💉. 


¡Ojalá te quede más claro ahora! 😄 

¡Saludos y éxito! 🍀
