### ISSUE TITLE
Elección apuesta ruleta

### ISSUE THREAD

**Issue by benjayousef97** [IIC2233/syllabus-2018-2#442]
Hola, tengo una duda sobre la elección de los jugadores en la ruleta. Por ejemplo, si un jugador decide apostar a un color, como se cual color? Lo que había deducido del enunciado es que luego del que elija apostar a un color, la elección del color también sea al azar con igual probabilidad para todos. Lo mismo sería para los números, pero quería saber si eso era correcto. Muchas gracias por su tiempo

**Comment by javierabao** [comment]
Hola!
La issue #438 responde tu duda.

**Comment by benjayousef97** [comment]
Muchas gracias!
