### ISSUE TITLE
[Error]archivo __init__.py

### ISSUE THREAD

**Issue by SergioZarateG** [IIC2233/syllabus-2018-2#443]
Al querer correr el codigo del archivo  __init__.py, me arroja el siguiente error:
ImportError: cannot import name 'main_widget'. Busque por google, pero no me aparece nada relacionado con este error. No se que puede ser.

**Comment by lily416** [comment]
¿Te fijaste si se encuentra el archivo `main_widget.py` en la misma carpeta en la que se encuentra `__init__.py`?

Saludos 👋🃏

**Comment by SergioZarateG** [comment]
Logré solucionarlo, gracias :).
