### ISSUE TITLE
Consideraciones para una Colision Personaje-Instalacion

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2233/syllabus-2018-2#444]
Buenas, me vino una duda que no me quedo tan clara en la ayudantía. Para considerar que un personaje esta colisionando con una instalacion (o atravesandolo) deberiamos ver que sus encuadres se cruzan, que sus imagenes se cruzan, o que el encuadre de uno se solape con la imagen del otro. 

PD: Lo anterior también aplica para las paredes del casino?

![screenshot_1](https://user-images.githubusercontent.com/42228743/46331529-be46cf00-c5ee-11e8-96f5-e2ac849d0009.png)
![screenshot_2](https://user-images.githubusercontent.com/42228743/46331530-be46cf00-c5ee-11e8-8aab-968797332be5.png)
![screenshot_3](https://user-images.githubusercontent.com/42228743/46331531-bedf6580-c5ee-11e8-8ed5-60f1c990151c.png)

**Comment by lily416** [comment]
Se considera colisión cuando se cruzan los contornos del personaje con la instalación o juego.
No es necesario que veas la colisión con las paredes, pero es recomendable que te fijes que los personajes no salga del mapa.

Saludos y éxito con la tarea 👋🎲
