### ISSUE TITLE
Entregable T02

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/syllabus-2018-2#446]
A continuación se muestra una serie de comentarios que surgieron tras leer los diagramas de clase que entregaron:

1) No todo tiene que ser un atributo, recuerden que las properties también existen. Aprovechen sus ventajas y no olviden señalarlas en el diagrama.
2) Ver bien cómo se relacionan todas las entidades con el casino, a fin de cuentas es la clase principal de la simulación.
3) Utilizar correctamente la herencia, a menos que las clases tengan métodos las diferencien puede que no sea necesario realizarla.
4) Hacer que el cliente maneje la conversación con otra persona genera que cada cliente tenga que revisar quien quiere hablar. Podrían usar el motor de simulación para realizar esta función de mediador entre los clientes. 
5) Tener cuidado con la programación circular, ¿es correcto que un cliente tenga el objeto de alguna instalación o juego? Buscar el manejo de esto a través de alguna clase superior.
6) Recordar que pueden hacer más de una “cadena de herencia”.
Por ejemplo: Una clase madre “Animal” puede tener como hijos a las clases “Perro” y “Gato”, las cuales pueden tener como hijos a “PastorAlemán” y “Siamés” (respectivamente).
7) Recordar que una de las utilidades de las clases abstractas es que sirven para prohibir la instanciación de éstas (es decir, solo permite la instanciación de sus clases hijas). Podría servirles para esta tarea.
 

Saludos y éxito en la tarea ✌️

**Comment by Kitaps** [comment]
Dos dudas:
5.: Tengo `simulacion` que tiene una property tiempo. Tambien tengo `casino` (que es componente de `simulacion`). Si hago que `casino` al instanciarlo reciba `parent=simulacion` para hacer `casino.time=parent.time`. Eso entonces está mal? Porque he visto varias veces que objetos al instanciarse reciban al parent (sobre todo en guis).

7.: Si es que al tener una clase Base heredando de clase abstracta y en pasos siguiente se forman complicaciones (por multiherencia y el no poder hacer el orden de herencia) si para ahorrar tiempo no basta en la descripción de la clase poner que es base, no instanciable? Esto me pasa por ejemplo cuando creo una clase base `Persona(ABC)` y cliente heredando de `Persona` y `Human`. Entonces siento que no vale la pena hacerlo heredar de `ABC` si igual no aporta nada en funcionalidad.

**Comment by viantirreau** [comment]
Me pasa lo mismo respecto al punto 7. El error que lanza es 

> metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Entiendo que ocurre porque la clase que hereda de ABC trae consigo como "bonus" una metaclase, que es diferente a la que viene al heredar de Entity directa o indirectamente, y parece que el intérprete no es capaz de encontrar una prioridad al heredar de esas dos simultáneamente 🤔
