### ISSUE TITLE
Métodos de la Interfaz para Arreglar Tamaño

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#447]
¿Se pueden usar los métodos updatePixmap() y setFixedSize(x, y) que vienen con la interfaz para poder mejorar el tamaño de las entidades?
Pregunto porque sin usarlos algunas entidades se muestran de manera errónea como se ha mencionado en otras issues.

**Comment by isavega** [comment]
Tengo la misma duda! Que tanto podemos modificar el demo que nos entregan de interfaz gráfica...

**Comment by inveterate-cladocerus** [comment]
cps

**Comment by NachoJuanDev** [comment]
cps
