### ISSUE TITLE
Ubicación de instalaciones

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#448]
Hola! Me preguntaba si a la hora de testear la simulación, cambiarían la ubicación de las instalaciones? O es una coordenada fija que no debo preocuparme de modificar. 
Muchas Gracias 🙏🏻

**Comment by Arcoirisky** [comment]
Puedes crear tu propio casino como más lo desees :DD No te preocupes por que nosotros cambiemos la posición de tus juegos. De todas formas mencionalo en tu Readme :D
