### ISSUE TITLE
Probabilidad de retirarme tras acción

### ISSUE THREAD

**Issue by Istuan** [IIC2233/syllabus-2018-2#449]
Luego de hablar con _Tini, il padrino_ y de ir al restobar cambia la probabilidad de retirarme. ¿Esto es la probabilidad de retirarme inmediatamente después de realizada la acción y sólo por ese turno, o se refiere a que se ve afectada mi probabilidad de retirarme desde ahora en adelante cada vez que la calcule?

**Comment by fernandodediegoavila** [comment]
Hola!
La probabilidad se ve afectada desde ese momento en adelante. Es decir, la stamina disminuye.
Saludos!
