### ISSUE TITLE
Paso 2 Encriptación del mensaje

### ISSUE THREAD

**Issue by cdlanas** [IIC2233/syllabus-2018-2#45]
Hola!! en el paso 2 se dice que hay que tranformar el mensaje primero a su codificación ASCII y luego a código binario, pero en la tabla de la sección 6, en que se ejemplifica este proceso, se omite el traspaso del mensaje a codificación ASCII y se aplica el código binario directamente. ¿Debemos seguir lo que se indica en el paso 2 y no en la ejemplificación?
Gracias!!

**Comment by lily416** [comment]
Holo :)

Sí hay que aplicar lo que se indica en el paso 2, simplemente que en la tabla/ejemplo que se muestra en el paso 6 este proceso se encuentra simplificado.  

Saludos 👋

**Comment by cdlanas** [comment]
Graciaaas!!  :)

**Comment by Cadagan** [comment]
entonces pasamos a binario el numero ascci +10? no me quedo claro, siguiendo el ejemplo del enunciado, el ASCII de "h" es 104, entonces tenemos que pasar a binario el numero 114? (en la tabla ejemplo pusieron el binario de 104 y no de 114)

**Comment by lily416** [comment]
Hola :) 

En la tabla del ejemplo solo se muestra cómo se cifrar en _CipherSaber_ sin tomar en cuenta el "Cifrado César". Como dices, cuando se utilizan los dos cifrados el número que hay que pasar a binario es el orden ASCCI de cada carácter más 10.

Ojalá quede claro.
Saludos 👋
