### ISSUE TITLE
pip install PyQt5

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#450]
Estoy tratando de instalar PyQt5 , pero me sale que no se reconoce pip, tambien trate con pip3 y no pasa nada. Busque esto en Internet pero no encontré nada, ¿Como puedo instalarla?

Muchas gracias!

![image](https://user-images.githubusercontent.com/42249674/46373586-c6415600-c664-11e8-8211-716f427bfe00.png)

**Comment by cmarquez1** [comment]
prueba con py -m pip install PyQt5 o py -m install PyQt5

**Comment by mericci** [comment]
Ahora me aparece esto

![image](https://user-images.githubusercontent.com/42249674/46376525-91390180-c66c-11e8-986a-86326e133d50.png)

**Comment by mericci** [comment]
Ahora me sale esto
![image](https://user-images.githubusercontent.com/42249674/46378204-3c4bba00-c671-11e8-8505-f8569f0a53e0.png)

y tampoco me deja correr le programa

![image](https://user-images.githubusercontent.com/42249674/46378225-48d01280-c671-11e8-8241-9212c7f77567.png)

que puedo hacer ahora

Muchas gracias
