### ISSUE TITLE
Error: wrapped C/C++ object of type Human has been deleted

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#451]
Hola!

Cuando intento mover a los clientes en mi simulación, se arroja el error que sale en el título. ¿Por qué pasa eso?

Muchas gracias.

**Comment by viantirreau** [comment]
Me pasó lo mismo cuando intentaba modificar la posición de algún cliente después de haber llamado al método que los elimina (`deleteLater`). Revisa si estás moviendo solo los clientes que siguen realmente en el casino, creo que puede ser por eso 😉
