### ISSUE TITLE
Presencia de instalaciones/juegos en la interfaz grafica

### ISSUE THREAD

**Issue by Faalfaro** [IIC2233/syllabus-2018-2#452]
Hola,
Para efectos de lo que se muestra en la interfaz gráfica, ¿ las instalaciones y juegos siempre deben estar fijos en la interfaz gráfica o aparecen/desaparecen dependiendo de la cantidad de personal disponible?, por ejemplo, ¿si tengo una instalación/juego funcionando y después de un tiempo ya no tengo el personal suficiente para mantenerla funcionando, estas quedan ahí pero no se les puede acceder o deben desaparecer de la interfaz? 
!Gracias!

#

**Comment by Arcoirisky** [comment]
Eso no está explicito en el enunciado o: Puedes hacerlo como más te acomode y mencionarlo en el Readme :D
