### ISSUE TITLE
Duda ganancia ruleta

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#453]
Hola, mi duda es muy breve, a qué se refiere en el juego de la ruleta con que la ganancia es X5?
5 veces el costo del juego?
Saludos

**Comment by SantiagoHintze** [comment]
Lo que entiendo es que sería 5 veces el monto de la apuesta definido en 3.1.1 en la parte de Ansiedad

**Comment by IchottMano** [comment]
@Prochotito Hola!

Es 5 veces la apuesta.

Saludos!
