### ISSUE TITLE
Apostar con Poco Dinero

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#454]
¿Si al cliente le queda menos dinero del que apostaría utilizando la fórmula de la ansiedad, entonces apuesta todo lo que le queda o no tiene permitido jugar?  (la apuesta mínima de los juegos es 1, por lo que teóricamente podría seguir jugando hasta tener menos de 1 en dinero)

**Comment by IchottMano** [comment]
#430
