### ISSUE TITLE
Dimensiones entidades

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#455]
Como puedo saber o donde puedo ver cuales son los tamaños de las distintas entidades en pixeles?
Además, la posición x, y de la imagen son medidas desde el centro de esta?

**Comment by lily416** [comment]
Como se dice en el enunciado: para obtener el alto y el ancho están las funciones `height` y `width`, respectivamente. 

Cuando se obtiene las coordenadas de alguna entidad se entregan las coordenadas de la esquina superior izquierda.

Saludos 👋🃏

**Comment by joaquinhernandezg** [comment]
Bacán, muchas gracias 😄
