### ISSUE TITLE
Movimiento de clientes en la interfaz

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#456]
Hola, ¿cómo debe representarse el desplazamiento de los clientes dentro del casino? En alguna issue leí que no se pueden teletransportar, pero, ¿cómo sería un desplazamiento razonable en la interfaz? 
Gracias de antemano

**Comment by Arcoirisky** [comment]
un desplazamiento razonable sería como el que venía en la demo. La idea es que no se peguen saltos ni nada por el estilo.

**Comment by ararojas** [comment]
Hola!
Para hacerlos que caminar habría que hacer que den un paso en un tick (osea un minuto) entonces pasarían demasiado tiempo caminando. No importa? o hay otra forma de hacerlo?
