### ISSUE TITLE
 PyQt5

### ISSUE THREAD

**Issue by isavega** [IIC2233/syllabus-2018-2#458]
Se que no puedo modificar el demo base, pero puedo agregar cosas? especificamente, más modulos de  PyQt5

**Comment by Arcoirisky** [comment]
Cuando revisemos las tareas lo haremos con la gui básica que les entregamos o:

**Comment by BFFV** [comment]
¿Y se pueden usar métodos que ya vienen libremente, mientras sea para tratar con el tamaño de las entidades?
