### ISSUE TITLE
PyQt5 error cannot import name 'QTimer' Mac

### ISSUE THREAD

**Issue by BlancaMunizaga** [IIC2233/syllabus-2018-2#459]
Instale el modulo PyQt5 en la terminal y me dice que esta fue exitosa pero luego al intentar correr el demo.py me aparece el siguiente error
![captura de pantalla 2018-10-02 a las 23 26 46](https://user-images.githubusercontent.com/42193404/46387123-9f524680-c69b-11e8-828f-0ade6da259e9.png)

Ademas me dijeron que podía deberse a que por alguna razón no tenia descargado un interprete que no se sea el virtual pero tampoco se como arreglar esto o por que no tengo el interprete que se descarga con python.
![captura de pantalla 2018-10-02 a las 23 28 29](https://user-images.githubusercontent.com/42193404/46387238-21db0600-c69c-11e8-9682-16d905aecf83.png)

¿Que puedo hacer para que corra correctamente el demo?
Muchas gracias!

**Comment by entamburini** [comment]
Hola! :D 
Si corres el programa desde el terminal, te aparece ese mismo error?

**Comment by BlancaMunizaga** [comment]
si me aparece el mismo error de que no se puede importar Qtimer

**Comment by meceledon** [comment]
Hola!! 

Me ocurre el mismo error! Leyendo la documentación de `PyQt5`, encontre que `Qtimer` debe ser importado desde `QtCore`, por lo que cambié el import de

```python3
from PyQt5.Qt import QTimer
# lo cambié a 
from PyQt5.QtCore import QTimer
```

El problema es que ahora al hacer el cambio de importación me aparece el siguiente error:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtCore.so, 2): Symbol not found: __os_log_default
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.11)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
```

aiuaaa 😢 

Muchas gracias!

**Comment by entamburini** [comment]
@meceledon tu error es de lo más extraño ajajja según lo leído en varias partes me dicen que es la instalación con anaconda el problema principal :/ pero no sé si será tu caso en particular. En la mayoría de los casos, reinstalando el intérprete de python dice funcionar.
No sé si será el mismo problema que tiene @BlancaMunizaga, cuando sale ese error es normalmente debido a que hay algún problema con pyqt :o
