### ISSUE TITLE
Uso de .gitignore

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#460]
Hola!
¿Para esta tarea se debe utilizar .gitignore para no subir la carpeta 'gui' ?
¿Da lo mismo subir el archivo 'demo.py'?

**Comment by javierabao** [comment]
Hola!
Sí, debes utilizarlo, aparece en el feedback de la tarea! Si no se descuentan 5 décimas. Cualquier archivo que les hayamos dado, y ustedes no hayan tenido que modificar, no lo tienen que subir. Eso incluye el demo.py.

**Comment by BFFV** [comment]
Gracias!
