### ISSUE TITLE
Personal por instalación

### ISSUE THREAD

**Issue by degutierrez1** [IIC2233/syllabus-2018-2#461]
Hola,

Tengo dos dudas que creo que no aparecen en otras issues que son más específicamente sobre los restobares. La primera es que existe personal mínimo por instalación ¿pero la cantidad de personal "máxima" asignada a cada restobar es arbitraria?
La segunda es ¿cada bartender puede trabajar en cualquier restobar o sólo uno determinado?

**Comment by lily416** [comment]
La cantidad máxima de personal queda a tu criterio, aunque recuerda que tu simulación debe cumplir con una cantidad específica de _bartenders_ 👀  

En la sección 3.2.1 del enunciado aparece:
> **Juego/instalación:** Corresponde a su lugar de trabajo. Cada uno tiene asignado un juego o instalación en la cual trabaja **permanentemente**.

Por lo que se entiende que trabaja en uno  determinado.


Éxito con la tarea 👋 🃏

**Comment by degutierrez1** [comment]
Gracias!
