### ISSUE TITLE
Problemas para instalar PyQt5 en Mac

### ISSUE THREAD

**Issue by meceledon** [IIC2233/syllabus-2018-2#462]
Tengo un problema super especifico para instalar PyQt5 en mi computador. Ya leí todas las issues al respecto y pedí ayuda a mis amigos y ayudantes pero sigo sin poder resolverlo. Hay un problema que me aparece constantemente cuando trato de instalar el paquete, trate de miles de maneras, pero sigue apareciéndome el mismo mensaje en consola y pycharm:

<img width="567" alt="screen shot 2018-10-03 at 10 38 33" src="https://user-images.githubusercontent.com/42249542/46413971-82982c00-c6f8-11e8-9ac1-ae7ff397c315.png">

Por favor ayuda :(

**Comment by fgbruna** [comment]
Hola, si ejecutas
```bash
pip3 install -U pip3
pip3 install PyQt5
```
qué pasa?

**Comment by meceledon** [comment]
Esto
<img width="568" alt="screen shot 2018-10-03 at 11 15 22" src="https://user-images.githubusercontent.com/42249542/46416573-35b75400-c6fe-11e8-8c13-0762a94eb777.png">

**Comment by fgbruna** [comment]
Te recomiendo revisar esta [issue](https://github.com/pypa/pip/issues/5236)

**Comment by meceledon** [comment]
Ya, la segui yme paso esto:
<img width="618" alt="screen shot 2018-10-03 at 11 42 44" src="https://user-images.githubusercontent.com/42249542/46418633-92b50900-c702-11e8-9173-4bb8a0d16351.png">
EDIT: Tengo que decir que igual ahora algo diferente me aparece por lo menos

EDIT_2: ME FUNCIONOOOOOOOO!!!! Use "pip3 install pyqt5" y FUNCIONOOOOO!!!!!
<img width="616" alt="screen shot 2018-10-03 at 11 56 06" src="https://user-images.githubusercontent.com/42249542/46419042-5f26ae80-c703-11e8-9b2f-d3bb98386ba8.png">

GRACIAAAAAS!!!!!

**Comment by meceledon** [comment]
Al final estaba tratado de usarlo en PyCharm y no me sale instalado el paquete dentro de este, cuando trato de instalarlo dentro de PyCharm me vuelve a salir el mismo problema:
<img width="723" alt="screen shot 2018-10-03 at 12 01 47" src="https://user-images.githubusercontent.com/42249542/46419392-2509dc80-c704-11e8-907a-5aa5fc1113d7.png">

**Comment by fgbruna** [comment]
Intentaste hacer lo que te dice pycharm? Puedes hacer que ejecute `pip3` y no `pip`?
Si no funciona, tienes que instalar pyqt5 en el entorno virtual ubicado en la carpeta de tu repo.
