### ISSUE TITLE
tiempo actividad v/s duracion fisico determinista

### ISSUE THREAD

**Issue by jpfernandez3** [IIC2233/syllabus-2018-2#463]
Hola! en el enunciado sale que cada actividad debe durar 
 `max(self.lucidez + self.sociabilidad - self.ansiedad, 0.1) * pi ** 2`
pero a la vez sale que el fisico determinista debe jugar a la ruleta por ν turnos, lo que probablemente tome un tiempo distinto. que hacemos? lo hacemos irse ante de que termine los turnos que debe jugar? o hacemos que se quede esperando en nada? no pescamos la duracion de la actividad?
o hacemos cualquier cosa y lo especificamos en el readme?
saluos

**Comment by ararojas** [comment]
Hola!
No se si esta bien pero lo que yo entendí era que el cliente tenía que "estudiar" las cartas por esa cantidad de tiempo, y despues de haberlas estudiado decidia si hacer trampa o no. Si decidia hacer trampa lo hacía por v turnos.

**Comment by javierabao** [comment]
Sí! Ese tiempo es el de la actividad, que es "estudiar" las cartas.

**Comment by jpfernandez3** [comment]
aaah buenisimo, gracias!
