### ISSUE TITLE
Apuesta ruleta

### ISSUE THREAD

**Issue by degutierrez1** [IIC2233/syllabus-2018-2#465]
¿Qué pasa si un cliente gana en la ruleta cuando el casino tiene saldo 0 o saldo menor a la apuesta?
¿El casino queda con saldo negativo como si quedara "debiendo" o le entrega le saldo que le queda al cliente?

**Comment by degutierrez1** [comment]
Otra cosa que se me ocurre es que la apuesta se ajuste al saldo del casino. Aunque no sé si queramos que el cliente sepa los fondos del casino.

**Comment by BFFV** [comment]
Yo al menos lo pensé como que el casino siempre tiene dinero para entregar y las pérdidas o ganancias de éste en los juegos no representan su dinero total, sino una variación (positiva o negativa) en el dinero que el casino ya tenía de antes
