### ISSUE TITLE
Duda de enunciado sobre niveles de características 

### ISSUE THREAD

**Issue by fernandamansilla** [IIC2233/syllabus-2018-2#466]
Cuando se dice que un cliente tiene por ejemplo lucidez alta , entiendo que quiere decir que  que se obtiene un numero al azar entre 0.7-1 . Pero este se mantendrá "fijo" osea si yo reviso la lucidez de ese cliente en un momento y es 0.8 , y luego la reviso en otro momento (y no a participado de actividades que la modifiquen) debería ser de nuevo 0.8 o  podría ser 0.9 (otro numero al azar en el intervalo) ?

**Comment by javierabao** [comment]
Hola!
Lo deberías considerar un valor fijo. EL cliente llega con cierto nivel de lucidez, y no se modifica a menos que haya participado de una actividad.
