### ISSUE TITLE
Tarea 2, Probabilidad de ganar

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#467]
Hola, estaba un poco entusiasmado en la hora de hacer esa parte y acabe me equivocando en la hora de definir la probabilidad de ganar, (debería ser probabilidad de ganar = probabilidad juego + 0,2×suerte−0,1), pero yo hice distinto, hice 1 para ruleta y una para traga_monedas, com mis proprios parámetros , (yo encontro que fico mejor u.u,  también ocupo la suerte, además ocupo la lucidez ) gustaria de saber si puedo dejar como esta ó si tengo que cambiar para lo que pide el enunciado?

**Comment by IchottMano** [comment]
@csantiagopaz Hola!

Lamentablemente, tendrás que cambiarlo y usar los valores del enunciado o no te podremos dar puntaje en esa sección.

Saludos!

**Comment by csantiagopaz** [comment]
=(   , okay gracias
