### ISSUE TITLE
Herencia y ABC

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#468]
Hola! 
Tengo una clase(cliente) que hereda de una clase abstracta(Persona) y de Human, lo que me tira el siguiente error:
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Que puedo hacer? Es mejor que haga la clase Persona no abstracta o que no herede de Human?
Por que cuando saco cualquiera de las dos herencias no me tira error

**Comment by Michelmagna** [comment]
Tengo el mismo error! Comento para saber (Porfa respondan a la brevedad... :( )

**Comment by isavega** [comment]
Tengo lo mismo :(

**Comment by NatachaP** [comment]
Yo igual D:

**Comment by csolguin** [comment]
. . .

**Comment by naquiroz** [comment]
-----
### IMPORTANTE

No comenten una issue con comentarios como "me ocurre lo mismo", "yo igual no puedo", etc. Esto es una mala práctica y no es deseado que lo hagan. Si tienen el mismo problema, pueden seguir la issue para observar sus comentarios. Lo mismo aplica para los "CPS" o "Up". Si desean seguir una issue sólo deben ir a la barra lateral y apretar "Subscribe"

![1a83a2957c1b36e067a3ea788a6d9538](https://user-images.githubusercontent.com/29825816/46583952-2a349780-ca34-11e8-862f-07ea0b6ad89a.png)


Si desean mostrar que tienen el mismo problema, pueden ponerle :+1:  a la publicación y eso nos hará ver que tienen la misma duda. Pero nunca _comenten para saber_.

Dicho esto, responderé.
-----

Hola :wave: ! El problema es un poco complejo. :boom: 

Para entenderlo, tendrán que creerme :crossed_fingers: que existe un cosa en _python_ llamada _metaclass_. Esto, a grandes rasgos son clases, que brindan instrucciones a _python_ de como crear una clase en particular. Por defecto, todas classes en python tienen como _metaclase_, la clase `type`. 

Sin embargo, el módulo `PyQt5` es un módulo super complejo, dado que es lo que se llama, una _implementación en python, de una librería en `C++` (otro lenguaje mas complejo que python :man_technologist: )_. Debido a esto, para que pueda funcionar, es necesario entregar otras _metaclases_ distintas a las clases como `QWidget` :computer:. Ocurre algo similar en las clases que son abstractas. El problema que arroja ahí dice que las clases que estás heredando, son dos clases que tienen _metaclases_ distintas, cosa que no está permitido en python. No hay una forma directa de resolver esto, por lo que te sugiero modelar el problema de una forma distinta. Espero haberlos ayudado!
