### ISSUE TITLE
Duda sobre materia en T02(@staticmethod)

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#469]
class Toilet(Instalaciones):
    def __init__(self):
        self.duracion = self.definir_duracion (queria saber que pongo aqui , si pongo self.definir_duracion o se pongo Toilet.definir_duracion pues use staticmethod abajo
        
    @staticmethod
    def definir_duracion(element):
        return normalvariate((3 * (1 - element.lucidez), 2))

**Comment by naquiroz** [comment]
Hola! Desde el punto de vista de python (no sé a nivel de la tarea), cuando creas un método estático, lo puedes llamar de las dos formas. La única diferencia es que cuando lo llamas con self, lo que hace python es ver si existe un método (no estático) con ese nombre. Si lo anterior no ocurre, busca por métodos estáticos. Personalmente creo que se ve mejor con self, pero a nivel de tarea, no sé. Espero que te haya ayudado. Saludos!
