### ISSUE TITLE
PEP8, Restricción 80 caracteres, Comentarios

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#47]
La restricción de PEP8 sobre no exceder los 80 caracteres por linea ¿aplica también a los comentarios?

Es que si quiero comentar algo sobre una linea del código me parece natural ponerlo en la misma linea pero me quedo sin espacio.

**Comment by rhanuch** [comment]
Hola!

Aplica a **todo**. Lo más común es poner el comentario en la línea anterior a la línea de código

Saludos!

**Comment by Arcoirisky** [comment]
Hola @BSamilla 

Recuerda que puedes comentar con las *box*'s. Usar """ 3 veces (si es que no me equivoco) para abrir el *box*, escribir lo que desees y luego cerrarlas con otras 3 "s :D. Un ejemplo:

```
# ... Mucho código útil
"""
Lo que se quiere hacer aquí es poner un comentario tan largo que ocupe más de una
sola línea. De esta manera se vuelve útil esta forma de 'comentar'.
"""
# Más código útil ...
```

Espero haberte ayudado :3. 

Saludos!

**Comment by Cadagan** [comment]
En mi caso solo me pase con los links haciendo referencia a codigos de stackoverflow, eso tambien cuenta para descuento? si pongo el link entre las 3 comillas, tambien? (el link es infinito)

**Comment by rhanuch** [comment]
@Cadagan , solo **en ese caso** no cuenta :smile:
