### ISSUE TITLE
problema subir archivo a traves de git

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#472]
Hola, queria subir los aances de mi tarea pero recibo este mensaje al hacer el git satus de lo que quiero subir:
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

gracias de antemano

**Comment by isavega** [comment]
Cuando me pasa, pruebo con git stash antes de hacer git add. Ojala te sirva!

**Comment by naquiroz** [comment]
git status te dice los cambios que han ocurrido en tu repositorio desde la ultima vez que subiste las cosas. Por lo que veo, el mensaje te está diciendo que no hay cambios. Eso puede implicar  2 cosas.
1. Ya lo subiste a tu repositorio.
2. No estás haciendo cambios en tu repositorio.
