### ISSUE TITLE
Probabilidad de retirarse

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#473]
Se supone que cada vez que un cliente debe tomar una decision, este puede elegir irse. Entonces, un cliente que tenga baja stamina por defecto (Kibitzer) va a tener una alta probabilidad de irse del casino en la primera decision que tome, que pasa en este caso? El cliente llega y se va nada más?

**Comment by lily416** [comment]
Exactamente

Saludos 👋 🎲
