### ISSUE TITLE
Duda interaccion ansiedad y dinero

### ISSUE THREAD

**Issue by Coolgatty** [IIC2233/syllabus-2018-2#475]
Hola, el enunciado no especifica si debemos reducir la ansiedad en el caso de que el dinero disminuya luego de que hay aumentado tal que la ansiedad aumenta en 25%. 
Queda a criterio mio?

**Comment by lily416** [comment]
Se puede interpretar como que la ansiedad aumenta en un 25% mientras se cumpla alguna de las condiciones del dinero.

Saludos 👋🎲
