### ISSUE TITLE
Dudas Estadísticas

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#476]
Hola, tenía las siguientes dudas con respecto a las estadísticas:

1) ¿Las ganancias promedio del casino cuentan los costos de utilizar instalaciones y actividades, o solamente las apuestas en los juegos?  
2) ¿En el juego que genera la mayor ganancia se debe obtener el tipo de juego ('ruleta') o la instancia ('ruleta_2')?
3) ¿En el tiempo total sin usar instalaciones se cuentan los juegos (ya que necesitan de un dealer) o no?

**Comment by alexaptib** [comment]
Tengo las mismas dudas

**Comment by cristianoberpaur** [comment]
Yo asumí que las ganancias eran generadas por los juegos y las instalaciones, ya que la unica actividad que tiene un costo es hablar con el mafioso. Y este se quedaria con el dinero ?? (por ser mafioso).
Además sumo a las preguntas, cuando nos pregunatn por las ganancias del casino en un día. Son las ganancias generadas en  86400 ticks o por simulación por separado sin importar la duración de esta?

**Comment by miguelramirezv** [comment]
Hola! Yo tengo duda similar en este tema, en la parte de juego que generó mayor ganancia en comparación al dinero que entregó en premios. Esto se refiere al juego que ganó más dinero neto (total ganado - total "perdido")?
@BFFV Según yo sí tu pregunta 1, en la pregunta 2 creo que es la instancia y en la 3 solo se pide sin usar las instalaciones, no los juegos. Ojalá te sirva! Igual cualquier cosa se puede poner en el README

**Comment by javierabao** [comment]
Sobre tu pregunta 1 y tu pregunta @miguelramirezv, pueden leer la issue #484.
Sobre la 2., es por tipo de juego, no instancia. 
Sobre la 3., está respondido al final de la issue #382. Solo instalaciones propiamente tales, no juegos.
