### ISSUE TITLE
Tamaño instalaciones

### ISSUE THREAD

**Issue by gejohow** [IIC2233/syllabus-2018-2#477]
Hola, al momento de agregar las imagenes de las instalaciones al mapa me salen mucho más grande de lo que deberían ser, no he cambiado nada de los archivos que se nos dieron. Quería saber si alguno sabe que podría estar pasando. Saludos

**Comment by fjtobar** [comment]
a mi me salen mucho más chicas :(

**Comment by NatachaP** [comment]
Intenten con la issue #410 a mi me sirvió :D 💃
