### ISSUE TITLE
Aumento de ansiedad

### ISSUE THREAD

**Issue by iamoreno** [IIC2233/syllabus-2018-2#478]
El aumento de ansiedad se produce máximo una vez a cada cliente o más? Hay algún numero de veces que se produce ? o sigue aumentando repetidas veces hasta llegar a 1 cuando se cumplen las condiciones?

![image](https://user-images.githubusercontent.com/42228256/46512006-2502fd00-c828-11e8-8c00-5b777f6639e2.png)

**Comment by inveterate-cladocerus** [comment]
cps
