### ISSUE TITLE
Tiempos tick (delay)

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#479]
Hola! 

En la issue #370 se aclaró que un segundo en la vida real debe ser un segundo simulado. 

Poniendo delay = 16,66666 logro que 60 ticks sean 1 segundo, pero mi código, al iterar sobre cada persona, termina haciendo que entre tick y tick haya una demora y por esto 1 segundo real no equivale exactamente a un minuto simulado.

 ¿Debemos controlar esto o podemos asumir el tiempo de ejecución es 0?

**Comment by rhanuch** [comment]
¡Hola @jcechavarri !

Puedes asumir que el tiempo de ejecución es 0 ⏲ 

¡Saludos! 🍀
