### ISSUE TITLE
Encriptación, paso 5

### ISSUE THREAD

**Issue by pglavin8** [IIC2233/syllabus-2018-2#48]
Que se debe hacer si la posición de intercambio sale del rango de la lista?, por ejemplo en la posición 254, cadena de inicio[254]=8, j=254+8=262, pero este valor no existe en la lista de números (que posee 256 elementos) por lo que no se puede intercambiar el valor.

**Comment by IchottMano** [comment]
@pglavin8 Esto se responde en la sección d del punto número 5 del ítem 3.5 del enunciado.

Saludos
