### ISSUE TITLE
[URGENTE] Perdida de datos Tarea

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#480]
holaa, necesito ayuda urgente, me pasó que por X razon git no me dejaba hacer push de mi progreso para la tarea, por lo que decidí buscar en internete como solucionarlo y llegué a este  foro de stackoverflow:

https://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to4

seguí los pasos y ahora me deja hacer push, pero me di cuenta que mi repositorio local fué cambiado por una version anterior de mi tarea, lo que me hizo perder una parte importante de lo que llevaba

hay alguna solucion?

**Comment by naquiroz** [comment]
Hola, viendo la página, corriste el codigo en esta imagen?

![image](https://user-images.githubusercontent.com/29825816/46512211-16691580-c829-11e8-8bb0-46d437e5e661.png)

PD: **No lo corras si no lo hiciste**, es para saber si lo corriste o no.

**Comment by jlperez6** [comment]
corrí este codigo, creo que está más arriba
`git pull --rebase origin master`
`git push origin master`

**Comment by naquiroz** [comment]
Ok. El mensaje de error que buscaste lamentablemente es muy amplio, dado que `failed to push some refs` es lo que git dice en cualquier caso que no se pueda hacer push al repositorio remoto (github). Por eso, necesito que hagas lo siguente:

1. Idealmente, si no has cerrado la consola donde intentaste hacer `git push`, necesito que compartas un _screenshot_ del error que te apareció (completo) cuando intentaste hacer `git push`.

Vamos a intentar resolverlo con eso primero. Sólo si no logramos nada con eso, necesito que procedas a hacer lo siguiente.

2. Corre `git log` en la consola. Con eso verás un historial de todos los commits en tu repositorio. Se te debería abrir ahí mismo en la consola. Sube un _screenshot_ de esto tambien. Notarás que es un poco extraña la forma como se abre dado que parece un "editor" en la misma consola. Para salir de este, solo debes escribir `:q` o `q` en tu teclado.

**Comment by jlperez6** [comment]
lamentablemente cerré la consola, asi que solo puedo mostrar lo que me aparece al escribir git log
![1](https://user-images.githubusercontent.com/42221871/46512765-11599580-c82c-11e8-957b-9de259210ddd.PNG)
![2](https://user-images.githubusercontent.com/42221871/46512766-13235900-c82c-11e8-9fad-4ef56c4944f2.PNG)

**Comment by naquiroz** [comment]
Ok, podrías correr ahora `git status`? (De ahora en adelante, a menos que indique lo contrario, por favor envía un _screenshot_ del resultado que te aparece 😄 )

**Comment by jlperez6** [comment]
oka
![3](https://user-images.githubusercontent.com/42221871/46512980-d310a600-c82c-11e8-8e04-6d652b511377.PNG)

**Comment by naquiroz** [comment]
Ok, encontré la solución (espero) 🎉 . La escribiré en un mensaje aparte.

**Comment by jlperez6** [comment]
uuuuh buenisima, muchas graciaaas!!!!

**Comment by naquiroz** [comment]
En git, cuando tu haces `git pull`,a grandes rasgos sólo estás agregando cambios que otra gente (hacer tu readme en internet cuenta tambien como alguien más ) ha hecho al repositorio. Es muy buena práctica (y en el futuro lo verás si sigues por la rama de la computación) siempre hacer `git pull` antes de hacer `git push`, dado que así primero te pones al día con los cambios que otras personas han hecho, antes de subir tu tus cambios. El error que te tiró git probablemente era eso. Al menos en el caso del [link que compartiste](https://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to4), lo que ocurrió en su consola era que git le estaba diciendo "porfavor sincroniza tu repositorio en tu computador, con los cambios remotos. Después te dejaré hacer git push". La solución más directa a eso es hacerle caso. Un simple `git pull` debería resolver todo . En en link sin embargo, le agregan la opción `--rebase`, que cambia la forma en como se hace git pull. A grandes rasgos es lo mismo, y no tiene mucho sentido explicarte por qué son distintos, pero si te interesa saber cual es la diferencia, puedes leer una respuesta [aquí](https://stackoverflow.com/questions/36148602/git-pull-vs-git-rebase).

Volviendo al problema, tu le hiciste caso pero al parecer (viendo el git log), tuviste conflictos al hacer pull. Eso significa que hay archivos que cambiaste, y que también cambiaron en el repositorio remoto, por lo que debes resolver los conflictos. Y en eso está tu carpeta actualmente, esperando a que los resuelvas. SI te fijas, en tu consola sale (`REBASE 1/3`) eso es porque hay tres archivos con conflictos (creo) y debes resolverlos antes de continuar. Dado que no tiene mucho sentido explicarte el porqué pasa esto, procedré a explicarte como resolverlo.

1. `git rebase --abort`, eso cancela el `git rebase` y por tanto el `git pull --rebase` que hiciste.
2. Ahora deberías tener tus commits, pero no los del respositorio, por eso corre `git pull`
3. Puede pasar que te aparezca `Merge conflicts`, de ser así por favor comenta después de este mensaje para explicarte como resolverlo. En caso contrario, debería resultar bien.
4. Otra cosa que puede pasar es que aparezca un mensaje como `Merge branch from ...`, en un editor en la consola. Solo te está pidiendo un mensaje para juntar lo que hay online, con tus commits . Escrbir `:wqa!` deberia resolver esto.
5. Ahora podras  hacer `git push` 🎉 

Comenta si no lograste resolverlo!

Saludos ✌️

**Comment by jlperez6** [comment]
acabo de probar la solucion, me aparecieron Merge cnflicts, aqui adjunto un screenshoot de lo que aparece:
![image](https://user-images.githubusercontent.com/42221871/46513633-ec672180-c82f-11e8-868d-faab2acf3988.png)

**Comment by naquiroz** [comment]
Ok, esto es un poco mas complejo, así que si no logras entenderlo, pregunta nomás.

Lo que ocurrió fue encontró cambios online, que tu también cambiaste en tu repositorio local, y git no fue capaz de juntarlos automaticamente. Por eso te tira `CONFLICT(content)`. Para resolverlo:

1. Anda a cada archivo que sale `CONFLICT`.
Lo que viene a continuación debes hacerlo para cada archivo
2. En tu editor favorito, abre el archivo, y busca `>>>>>`. Notarás que hay una (o varias, revisa bien), partes que tienen ese simbolo. Todos deben lucir algo similar a esto:

```
If you have questions, please
<<<<<<< HEAD
open an issue
=======
ask your question in IRC.
>>>>>>> branch-a
```

Asegúrate de hacer lo que viene para cada uno de esos "bloques"
3. Ese bloque es el bloque donde hay conflicto. Lo que está entre `<<<<<<< HEAD` y `=======` es lo que tu tienes en tu computador, y  lo que está entre `=======` y  `>>>>>>> branch-a` es lo que viene desde el repositorio remoto. Ahora debes decidir con cual quedarte (puedes quedarte con ambos).
4. Una vez que decidiste, borrar los  `<<<<<<< HEAD` , `=======`  y `>>>>>>> branch-a` **sólo de ese bloque**, y quedarte con las lineas que te interesan.
5. Repetir para cada bloque.
6. Repetir para cada archivo.
7. Una vez listo lo anterior, un simple `git commit -m "Porfin lo solucione"` debería resolver todo, y dejarte hacer `git push`

Saludos ✌️

**Comment by jlperez6** [comment]
ya está solucionado !! recuperé la información y me deja hacer push
De verdad muchas graciaaas !! <3 <3 <3

**Comment by naquiroz** [comment]
Denada!
