### ISSUE TITLE
[Error con interfaz]

### ISSUE THREAD

**Issue by SergioZarateG** [IIC2233/syllabus-2018-2#481]
Tengo un problema con la interfaz. Cuando corro la simulación, el programa me arroja lo que se muestra en la imagen. Esto pasa con cada decisión del cliente del casino, menos cuando la decisión es jugar. He buscado por internet pero no encuentro respuesta. Necesito solucionarlo, porque el programa se cierra antes de tirar una excepción de la simulación.
![image](https://user-images.githubusercontent.com/42163514/46517308-1414b480-c845-11e8-9dad-96fe5c6e3971.png)

**Comment by jfacuse** [comment]
prueba correr el programa sin la interfaz (haciendo un for o algo asi), a mi me paso muchas veces eso y era porque algo salia mal en el programa, pero como estaba la interfaz abierta no tiraba la exception sino que solo se caia como te pasa a ti

**Comment by prod-bysilva** [comment]
Hola!,

Tal y como dice @InfiniteDreamX  es una excepción que no se imprime en tu consola al estar trabajando con la interfaz gráfica. Prueba corriendo el código en Sublime Text, debería imprimir el error aún cuando la interfaz se caiga.

Saludos.

**Comment by SergioZarateG** [comment]
@InfiniteDreamX  y @pcrodriguez , muchas gracias por la respuesta. Con lo que me dijeron puede solucionar el problema :) .
