### ISSUE TITLE
Finalidad Dealer Tragamonedas

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#482]
Hola!
Tengo una duda sobre la función de los dealers en el tragamonedas, se que debe haber como mínimo uno para que esta funcione pero ¿hace algo en ella?
Según lo que entendí del enunciado y otras issues es que los clientes solo pueden contar cartas en la Ruleta y solo se coluden con los dealers de la Ruleta también. 
Ojalá puedan aclarar este tema!
Gracias!

**Comment by ncasassas** [comment]
Hola, tengo entendido que los dealers no tienen ninguna función para efectos de la simulación en los tragamonedas(como afectar las ganancias o algún atributo de cada cliente), simplemente tiene que haber uno "cuidando" una maquina.

**Comment by lily416** [comment]
Es como dice @nko205

Saludos 👋🎲

**Comment by Seld0nn** [comment]
Puede juegarse a la tragamonedas si no hay un dealer en ella?

**Comment by lily416** [comment]
@Seld0nn Como se dice en #382 debe haber por lo menos un _dealer_ para que el juego funcione.

**Comment by NatachaP** [comment]
Pueden estar coludidos y cuando la persona habla con tini tiene ventajas en ese tragamonedas 😞

**Comment by lily416** [comment]
@NatachaP Como se dice en #439 si es que llegan a realizarlo deben especificarlo en el readme
