### ISSUE TITLE
Físico Determinista

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#483]
Hola, me esta costando un poco interpretar cierta frase en el enunciado: 

> Luego de estudiar, la persona puede decidir ir a la ruleta a predecir los resultados con
probabilidad igual a su parametro de deshonestidad. Si es que decide predecir los resultados, lo
realiza en las siguiente v rondas.

Quería saber si la persona decide ir a jugar directamente o la próxima vez que juega a la ruleta tendrá una probabilidad (igual a la honestidad) de hacer trampa.  Además, las siguientes v rondas deben ser seguidas o puede ser que simplemente se juegue una ronda de ruleta y luego tome otra decisión, pero la próxima vez que juegue ruleta siga haciendo trampa (en caso que las v rondas sean mayores que 1). ¿O puede ser a mi criterio simplemente?

**Comment by viantirreau** [comment]
Hola! 
Según mi interpretación, se refiere a que en el momento que está "estudiando" la posibilidad de "predecir los resultados", se decide hacer eso con probabilidad igual a la deshonestidad. Luego de terminado el tiempo de dicha actividad, en caso de elegir predecir, lo hará siempre que juegue en la ruleta, durante las siguientes v rondas (de ruleta, no de cualquier actividad/tick/decisión).
Saludos y esperemos la confirmación o corrección por parte de un ayudante 👍
