### ISSUE TITLE
Estadísticas -> Ganancias

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#484]
Hola!
En la parte de estadísticas, en relación a las ganancias tengo un par de dudas:

1. Las ganancias en promedio por día del casino: ¿incluyen las ganancias por costos de instalaciones? 
2. ¿En las ganancias de la ruleta, se deben descontar los premios?

Después, en la parte de ganancias de cada juego en comparación a los premios que entregó, me imagine que tenía que calcularse [ganancias - premios], pero en el tragamonedas esto no tiene sentido ya que en general da negativo porque los premios son muy grandes, y esto hace que parezca como que el casino pierde plata, cuando en realidad no es así. ¿Aún así tengo que descontar esos premios? ¿O los premios se descuentan solo en la ruleta?
Gracias!

**Comment by javierabao** [comment]
Hola!

1. Las ganancias en promedio por dia del casino, incluyen tooooodo lo que entra, menos tooodo lo que sale, así que cualquier transferencia de dinero cliente-casino-cliente va en este item. Costos de instalaciones incluidos.

2. Siguiendo con lo del punto anterior, se considera cualquier interacción monetaria en cada juego, para el item de ganancias del casino en promedio por día. O sea, tienes que descontar premios tanto en tragamonedas como en ruleta. 

Para el item 6 en particular, tienes que ver el juego que genero mayor ganancia en _comparación_ a su pérdida. Para este caso, es un radio de comparación, es decir, ganancias/pérdidas. El juego con mayor radio, es el que cuenta para este item.

**Comment by ararojas** [comment]
Hola @javierabao !
Ya gracias! Pero lo que yo digo es que en el tragamonedas los premios que se entregan no son pérdidas del casino, es dinero que nunca perteneció al casino sino que siempre estuvo destinado a entregarse.  Por lo que yo considero que en el tragamonedas no hay perdidas. Siento que sería incoherente restarlo.

**Comment by javierabao** [comment]
Ya, entiendo a lo que vas. Ahí lo que consideras, es que todo dinero que te quede acumulado en el pozo al finalizar la simulación, más las ganancias de 10% acumuladas, son tu ganancia para el tragamonedas. La pérdida, es lo que la gente aposto, se fue acumulando, y eventualmente alguien que ganó se llevó. Por mucho que no haya "pertenecido" nunca al casino, al ser ganancia del jugador, es pérdida del casino.

¿Quedó claro ahí?

**Comment by ararojas** [comment]
Si ahi si. Pero una ultima duda, para calcular ese radio, en las ganancias de la ruleta se considera solamente lo que entró, sin restarle lo que salio? O es: (entro - salio)/salio ?

**Comment by javierabao** [comment]
Me refería a entró/salió, pero viendo el enunciado, sería más correcto entender la tuya. En cualquier caso, especifica la que uses en el readme.
