### ISSUE TITLE
Fórmula de apuesta distinta según personalidad

### ISSUE THREAD

**Issue by tfflores** [IIC2233/syllabus-2018-2#485]
¡Hola! En el enunciado se deja bien claro la fórmula de la "apuesta_base" de cada cliente. Sin embargo, ¿es posible que cada personalidad además tenga su apuesta característica? Por ejemplo, hacer que el millonario siempre apueste su apuesta_base + un porcentaje fijo de su dinero (dado que el millonario siempre apuesta grandes sumas), o que el dieciochero mientras más apuestas n haya hecho en el casino vea multiplicada su apuesta_base por ese n, etc.

**Comment by fernandodediegoavila** [comment]
Hola!
Creo que quizás te estás complicando de más o no? De todas formas, si quieres hacerlo no debe pasar a llevar otros criterios de evaluación y tienes que dejarlo bien explícito en el Readme, de manera que el ayudante corrector no se confunda.
Saludos y éxito!
