### ISSUE TITLE
Process returned 3221225725 (0xc00000fd)

### ISSUE THREAD

**Issue by Franco1605** [IIC2233/syllabus-2018-2#489]
Hola. Tengo el siguiente problema cada vez que intento simular el casino: Process returned 3221225725 (0xc00000fd). Esto sale al final en la consola, y no es capaz de completar el tiempo de simulación que le estoy pidiendo (1 día). Por más que intenté buscar el error en internet, sigo sin poder solucionarlo. ¿Me podrían decir en que consiste este problema?

**Comment by IchottMano** [comment]
@Franco1605 Hola!

Con respecto a tu problema, es muy probable que python elimine algo de tu programa que luego queras acceder, lo que se llama [garbage collection](https://pythonprogramminglanguage.com/garbage-collection/).

Lo que puedes hacer es guardar en algún lado las referencias (los objetos) de todo lo que estés ocupando en tu interfaz (como una lista de todos los clientes que estén en el casino) así python no lo elimina antes de lo necesario.

Si esto no resuelve tu problema, por favor comenta mas detalles de tu problema, como en que caso se queda pegado, que función causa esto, entre otras cosas.

Saludos!

**Comment by Franco1605** [comment]
@IchottMano Cómo? creo otro archivo.py para almacenar los objetos ?

**Comment by IchottMano** [comment]
@Franco1605 No, me refiero a que los almacenes ya sea en una lista o en algún otro lado dentro de tu interfaz.

**Comment by Franco1605** [comment]
@IchottMano En una clase simulación, tengo varios diccionarios en el __init__ en los cuales se almacenan los clientes, instalaciones, juegos y personal. Aparte, debería almacenarlos en una lista?

**Comment by IchottMano** [comment]
@Franco1605 Tambien almacenas los objetos de la GUI? Como Entity?
Si están en un diccionario debería estar bien, es para que no se pierda la referencia a estos.

**Comment by IchottMano** [comment]
Nuevamente reitero, puede que esto no sea la causa de tu problema, ayudaría mucho si explicas a mas detalle que está pasando en la simulación al momento de caerse.

**Comment by felipegarcia98** [comment]
un clasico problema es cuando llamas a gui.init() mas de una vez. Vale decir, lo llamo en el main y en un modulo, lo llamo dos veces en el main, lo llamo dos veces en un modulo. Revisa que no estes haciendo algo asi

**Comment by Franco1605** [comment]
@IchottMano @felipegarcia98  Lo solucioné. Efectivamente, no había guardado las clases entity creadas, por lo que el programa colapsaba. Gracias !
