### ISSUE TITLE
Uso de tab en Atom

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#49]
Hola! 

Por casualidad también está prohibido usar tab en Atom, tomando en cuenta que está configurado para dejar los 4 espacios que pide el pep8? 

O hay que poner los cuatro espacios de manera manual si o si?

Gracias y saludos!

**Comment by Drpinto1** [comment]
Saludos :D
Si tienes Atom, o cualquier editor de texto, configurado para poner 4 espacios al presionar _tab_, no es necesario que los pongas manualmente para seguir el PEP8, pues para efectos del código como texto, no es existe diferencia.

**Comment by hbkim94** [comment]
Muchas gracias!
