### ISSUE TITLE
Heredar clases de entities

### ISSUE THREAD

**Issue by danustilovsky** [IIC2233/syllabus-2018-2#491]
Hola, si intento crear un objeto de la clase Human como atributo de alguno de los clientes, juego o instalacion del casino directamente no aparece nada  y me sale: Process finished with exit code -1073740791 (0xC0000409), y no he logrado entender o encontrar la solucion para este problema ¿A que se pueden deber o que puedo hacer para arreglaro?

gracias

**Comment by NatachaP** [comment]
Eso también está en otra issue pero no se ha respondido aún :c

**Comment by danustilovsky** [comment]
@NatachaP En cual??

**Comment by felipegarcia98** [comment]
ese error sale cuando ya no hay avances aplicando gui.run() o cuando llamas mas de una vez al gui.init() (ya sea 2 en main, 1 en main y otro en modulo o 2 en modulos)

**Comment by NatachaP** [comment]
@danustilovsky  en la #468 y #366

**Comment by IchottMano** [comment]
@danustilovsky Hola!

Has probado con la respuesta a la issue #489 ?

Si no te resulta, hazmelo saber :)

Saludos!
