### ISSUE TITLE
Contar_cartas_poco_probable

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#492]
Hola, tengo un problema, que en mi código muchas de las estadísticas son raras porque nadie cuenta cartas, me pregunte porque pasaba pensando que era un error pero al final resulta que es simplemente poco probable que ocurre, para empezar debe ser kibitzer, luego debe no irse (se suelen ir rápido por tener baja stamina), luego debe elegir hacer una actividad, luego debe haber hablado, luego debe volver a hacer una actividad sin haberse ido y luego de todo esto hay un filtro mas que es el de la deshonestidad. 

La pregunta es, ¿estoy entendiendo mal el enunciado o es normal que sea tan poco probable que ocurra esto?

**Comment by johntrombon** [comment]
+1

**Comment by javierabao** [comment]
Es poco probable que ocurra, puede ser un porcentaje sea bajísimo. Mientras hayas hecho bien el procedimiento hasta llegar a esa actividad, que tu estadística sea "rara" está bien.
