### ISSUE TITLE
Digrama de Clases

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#493]
El digrama se entrega el domingo a las 24:00 o se puede entregar junto con el Readme?

**Comment by Arcoirisky** [comment]
Hola! El diagrama se entrega junto con la tarea, como lo dice el enunciado. No junto al Readme ya que a penas se termina el tiempo de la tarea se recolecta todo a evaluar ouo. 

Ánimo y suerte en lo que queda de la tarea!! :D
