### ISSUE TITLE
Descuento desplazamiento

### ISSUE THREAD

**Issue by jdiaztoledo** [IIC2233/syllabus-2018-2#494]
Hola, tengo la duda de que tanto será el descuento si los clientes no se desplazan como es pedido, esto ya que por alguna razón cuando hago que se muevan como es pedido el tiempo que tarda en simularse un solo día es mucho más (demasiado) a cuando solo se "teletransportan" de un lugar a otro. Como no sale cuanto serán los descuentos por la interfaz me tiene un poco preocupado esto, ya que no sé que tanto afectará en la evaluación:(
Gracias de antemano

**Comment by Arcoirisky** [comment]
No podemos decirte eso O: Es por eso mismo que no les damos los puntajes. Pero buen intento ouo)/ y ánimo con la tarea!
