### ISSUE TITLE
Problema con entities.py

### ISSUE THREAD

**Issue by jbartolomev** [IIC2233/syllabus-2018-2#497]
Hola!
Al abrir el archivo entities.py me aparecen errores.
En la clase Entidad, PyCharm me dice que en el super().init(parent), falta un parámetro.
También en la función y e x, me indica esto: Signature of method 'Entity.x()' does not match signature of base method in class 'QWidget'
Yo no he cambiado nada del archivo. Lo googlee y no obtuve solución. ¿Qué puedo hacer?
Muchas gacias!

**Comment by IchottMano** [comment]
@jbartolomev Hola!

Estos son cosas típicas de pyqt5, no hay nada que hacer, sólo debes ignorar esas advertencias.

Saludos!

**Comment by jbartolomev** [comment]
Muchas gracias!
Aun así cuando instancio el casino me da un error relacionado con las coordenadas:

    self.move(self.x, self.y)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'int'
  move(self, int, int): argument 2 has unexpected type 'str'

Si no es por lo anterior, cual puede ser la razón?
gracias!

**Comment by IchottMano** [comment]
@jbartolomev Revisa que los números que le entregas a la función sean **ints** y no **strings**

**Comment by jbartolomev** [comment]
Son ints! igual que los de la demo

**Comment by IchottMano** [comment]
@jbartolomev Seguro que 
```python
self.y
```

Es un int? 
El error se debe a que para la clase de **self**, existen dos llamadas distintas a funciones **move**, una que recibe un **QPoint** y otra que recibe dos **ints**.
La primera falla porque el primer argumento no es un **QPoint**, mientras que el segundo tabién falla (aunque no debería) ya que recibió un **int (self.x)** y un **str (self.y)**.

Revisa **bien** si self.y es efectivamente un int.

Saludos!

**Comment by jbartolomev** [comment]
Efectivamente uno era string. Tenía los nombres de los parámetros en desorden.
Muchísimas gracias!

Saludos.
