### ISSUE TITLE
Modularización

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#498]
Hola, en mi programa tengo alrededor de 1200 líneas de código, de las cuales unas 20 son del main y de las importaciones que hago. ¿Igual debo modularizar? Si hago un módulo con todas las clases que hice igual voy a tener 1180 líneas en ese módulo.

Gracias

**Comment by IchottMano** [comment]
@JavierNarvaez Hola!

Puedes separar tus clases en distintos módulos, pero es requisito modularizar para evitar el descuento.

Saludos!
