### ISSUE TITLE
Elección de recipientes de los correos o invitados a eventos

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#50]
Hola de nuevo!

Cuando el usuario le escribe un mail a alguien o a varios, esos mails tienen que existir necesariamente? O pueden ser cualquier palabra (como "adiawjd21312")?

**Comment by nachocontreras** [comment]
Hola!

¿A qué te refieres cuando dices que `esos mails tienen que existir necesariamente`? 
Como dice el enunciado, los correos deben tener destinatarios, asunto, cuerpo y opciones.

**Comment by hbkim94** [comment]
Sorry, me expliqué remal! 

Me refería a si los destinatarios tienen que existir en la base de datos necesariamente. Osea, si colocar "to: fulanito@gmail.com" estaría bien, aunque fulanito@gmail.com no esté registrado. O si se pudiera poner "to: jadijwaidasd" y el correo se pueda crear igual.

Espero que se entienda mejor.

**Comment by nachocontreras** [comment]
No necesariamente deben existir en la base de datos, sin embargo, deben ser correos electrónicos válidos. No se puede poner "to: jadijwaidasd".

**Comment by kelseyfranken** [comment]
Hola! puedo asumir que los usuarios ingresaran correos electrónicos validos?

**Comment by ptflores1** [comment]
No puedes asumir eso. Saludos !

**Comment by cpgarrido** [comment]
Hola esto igual sucede con los invitados a eventos?, es decir, se debe verificar que los invitados son correos válidos?

**Comment by nachocontreras** [comment]
Hola @cpgarrido ! Se habló en la issue #53. Deben ser válidos.
