### ISSUE TITLE
Problema con carpeta gui en gitignore

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#500]
A pesar de agregar la carpeta gui, de la forma (/gui) en mi gitignore, igual me lo esta subiendo al hacer git add --all, además utilice git rm gui, pero obtuve este mensaje:

```bash
$ git rm gui
fatal: not removing 'gui' recursively without -r
```

lo cual no se que significa

gracias por la buena onda, sorry el cacho

**Comment by fgbruna** [comment]
Lo que dice git es que debes eliminar la carpeta de manera recursiva con la opción `-r`.
Esta todo explicado en la [documentación de git](https://git-scm.com/book/es/v1/Fundamentos-de-Git-Guardando-cambios-en-el-repositorio#Eliminando-archivos)
