### ISSUE TITLE
Error al guardar estadísticas cuando el main.py se abre directamente con Python

### ISSUE THREAD

**Issue by tfflores** [IIC2233/syllabus-2018-2#501]
Hola, tengo una duda, yo hice la tarea en Pycharm y ya tras los últimos arreglos se ejecuta bien. Sin embargo, si abro el main.py con Python directamente (click derecho y abrir), al terminar la simulación no deja guardar el archivo con las estadísticas, y muestra esto.
![image](https://user-images.githubusercontent.com/37163421/46587800-f3787480-ca67-11e8-8f79-610c75c84d91.png)
Además, se cierra inmediatamente lo cual no deja tiempo suficiente para revisar las estadísticas que se imprimen en pantalla.

Esto no sucede si accedo al archivo de la tarea mediante el Command Prompt de Windows (lo de hacer cd /rutadelatarea, y después poner python main.py), puesto que ahí sí guarda el archivo. ¿Puedo asumir que el corrector abrirá de esta forma mi tarea?

**Comment by cilopez** [comment]
Mmm no puedes asumirlo pero puedes señalarlo , si al ayudante que se le asigno tu tarea no le funciona y lo señalaste, probablemente  otro ayudante con pycharm lo pruebe
