### ISSUE TITLE
Diagrama en .xml?

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#502]
¿Se puede entregar el diagrama en .xml (hecho con draw.io)? En un screenshot es muy chico el espacio, así que es difícil de leer.

**Comment by bimartinez** [comment]
Hola @Fenho 

En *draw.io* en vez de guardar el diagrama en XML existe una opción que se llama `Export as`, en la cual puedes exportar tu diagrama en forma de imagen o PDF.

Saludos! 😄
