### ISSUE TITLE
Duda Descuento Entrega Atrasada

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#503]
Hola! Haciendo arreglos de ultimo minuto en mi tarea, cometí un error (🙃) y a causa de este mis clientes no podian llegar a las instalaciones en la interfaz grafica. Entregue la Tarea con este error, sin embargo ya encontre como solucionarlo (un cambio de 2 lineas). Mi pregunta entonces es, me convendria realizar una entrega con atraso y recibir el descuento o es posible señalar el problema en el readme ya que no es un cambio drastico ☹️? 
Gracias!

**Comment by rhanuch** [comment]
¡Hola @NicolasCastillo24 !

Es tu responsabilidad decidir qué hacer y ver qué te conviene más 😬 

¡Saludos! 🍀
