### ISSUE TITLE
Entrega atrasada

### ISSUE THREAD

**Issue by mathiasvaldebenito** [IIC2233/syllabus-2018-2#504]
Ayer subi la entrega de mi tarea a último minuto, pero según mi reloj estaba en el plazo y ahora revisando el commit me di cuenta que no ;(, para subir mi tarea actual tengo que rellenar el form también? Lo que me preocupa es qué pasará con el descuento continuo de décimas considerando que recién hoy mandaron el commit que se revisaría.

**Comment by Hernan4444** [comment]
Hola, me aparece que el commit a corregir es el último que has hecho en tu repositorio (no encuentro el problema). Sobre el descuento, si ahora haces push ahora y mandas el commit de ese push, será el descuento asociado desde las 00:00 hasta ahora. Si tienes dudas con tu commit, mándame un mail al mail oficial.

Saludos ✌️
