### ISSUE TITLE
Problema consola Python 

### ISSUE THREAD

**Issue by rsnegrin** [IIC2233/syllabus-2018-2#505]
Por que puede ser que al ejecutar mis programas en la consola de Python estos se caigan, pero al hacerlo en Pycharm funcionan bien. Hay unos que simplemente se caen al abrirlos desde la consola y otros que, al escribir un input en PyCharm el programa funciona pero al copiar el mismo input a la consola esta se cae.

**Comment by bimartinez** [comment]
Hola @roberto009 

Puedes explicar mejor el problema que arroja la consola de *Python* y de que manera ejecutas el programa?. Siempre es recomendable correr los programas desde la terminal del computador (en el caso de *Windows* puede ser el `cmd` o `Windows Powershell`) a través del comando `python {nombre_archivo}.py`.

Saludos!

**Comment by rsnegrin** [comment]
El programa lo ejecuto haciendo click derecho y "abrir con Python". Como esta consola no muestra los errores, sino que simplemente se cierra, no puedo saber el error. En cambio, el mismo programa ejecutado en PyCharm no se cae, sino que corre perfecto y no arroja error.
Al correrlo desde el cmd funciona bien, pero de la otra forma se cae.

**Comment by bimartinez** [comment]
@roberto009 lo que pasa es que la consola de *Python* se cierra apenas termina la ejecución de un programa, sin importar si este falla❌  o su resultado es exitoso ✔️  (lo puedes probar poniendo un `print` para saber que tu código se ejecuto bien y un `sleep`🕐 al final para que la consola no se cierre inmediatamente). Finalmente, te recomiendo siempre ejecutar el programa directamente desde la `cmd` o la `Powershell`.

Saludos 😄
