### ISSUE TITLE
Readme T02

### ISSUE THREAD

**Issue by topkaj** [IIC2233/syllabus-2018-2#506]
Hola,

Tanto en el feedback de la T00 y la T01, se me notificó que no subí el Readme, pero en ambas me preocupé de entregarlos dentro del plazo. Por lo que quería saber cómo puedo asegurarme de que esta vez si estoy en lo cierto (lo terminé de modificar hace poco). :sweat_smile:

**Comment by NatachaP** [comment]
Al subirlo, revisaste que estuviera en tu carpeta personal de T02?
Debería aparecer con las modificaciones que le hiciste.

**Comment by lily416** [comment]
Además, si pones el mouse sobre la fecha del último commit relacionado con el archivo, te sale la fecha y hora exactas en las que se realizó el commit.

<img width="753" alt="fecha commit" src="https://user-images.githubusercontent.com/26393515/46643082-e71c1680-cb50-11e8-986b-f14fdada54a1.png">

Saludos 👋🍀

**Comment by topkaj** [comment]
gracias!
