### ISSUE TITLE
Entrega tareas atrasadas

### ISSUE THREAD

**Issue by jmndoza** [IIC2233/syllabus-2018-2#507]
Hola, cuantos puntos por hora de atraso se descuentan?

**Comment by Hernan4444** [comment]
Hola, el [descuentos.md](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md) está el detalle de dicho descuento:

![image](https://user-images.githubusercontent.com/15641721/46662793-bfe63900-cb92-11e8-8320-f5edb5b668d2.png)

Saludos ✌️
