### ISSUE TITLE
read me 

### ISSUE THREAD

**Issue by tsgonzalez** [IIC2233/syllabus-2018-2#508]
Hola,

Por un problema personal ayer no pude subir el Readme antes de la hora indicada. Hoy pregunté a un ayudante y me dijo que preguntara en una issue cual era el procedimiento en estos casos. Es decir, si aun puedo subirlo, o ya no se recibe por ningún motivo. Además, si es que aplica algún tipo de descuento en ese caso. 

Gracias!

**Comment by Arcoirisky** [comment]
Holi~
Tranquilidad ante todo. Sube el readme lo antes posible. Mientras más te tardes caes en el riesgo de que corrijan tu tarea. Si el ayudante es más rápido que tú entonces GG. Caso contrario, no pasa nada malo :D 

Ahora run! Qué hay un Readme que subir!! Kskdkskd
