### ISSUE TITLE
Duda AY09

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#509]
En la ayudantia de ayer se utilizo el siguiente código:

```python
  def run(self):
        moves = cycle(range(1,3))  # gen(1, 2, 1, 2, 1, 2, ...)
        for move in moves:
            if not self.robot.life or not self.mega.life:
                return  # Si alguno muere, el run retorna
```
quería saber para que se utiliza ese `cycle` y porque se recorre?

gracias!!

**Comment by naquiroz** [comment]
Hola! El enunciado dice que cada dos movimientos, el piloto debe atacar. Se usa mas abajo cuando dice

```python
if move == 2:
    # Atacar
```

Eso significa que cuando el numero de movimiento es :v: , ataca :crossed_swords: .

Se entiende?

Saludos!

**Comment by pelao97** [comment]
si si perfect, pero el hecho de que sea un cycle y no un range es para que sea infiinto para la simulacion?

**Comment by naquiroz** [comment]
Exacto, para eso. Es un for infinito. Saludos!
