### ISSUE TITLE
No puedo descargar Jupyter Notebook

### ISSUE THREAD

**Issue by tomasmetroy** [IIC2233/syllabus-2018-2#51]
Siguiendo todos los pasos especificados sobre cómo descargar la aplicación no he tenido éxito. ¿Hay algún error común que pueda explicar esto? Gracias.

**Comment by bimartinez** [comment]
Hola!

Puedes ser un poco más específico en el error que tienes?

Saludos!

**Comment by IchottMano** [comment]
@tomasmetroy Hola!

Podrías especificar de que modo estas intentado descargar jupyter y en que parte de la instalación estas teniendo errores/problemas?
Además sería util saber que sistema operativo tienes.

Saludos

**Comment by tomasmetroy** [comment]
Lo he intentado de dos formas:
1) Probar directamente con las instrucciones de la página de jupyter ejecutando el comando:
python3 -m pip install --upgrade pip
python3 -m pip install jupyter

En donde me entrega: 'python' is not recognized as an internal or external command,
operable program or batch file.

2) situándome en la carpeta de scripts de la carpeta de Python y ejecutando:
pip3 install jupyter

en donde me entrega: 'Fatal error in launcher: Unable to create process using '"c:\users\tomas\appdata\local\programs\python\python36\python.exe"  "C:\Users\tomas\Desktop\Python36\Scripts\pip3.exe" install jupyter'

Gracias de antemano!

**Comment by IchottMano** [comment]
@tomasmetroy Puedes intentar con
```bash
pip install jupyter
```
O de otra manera
```bash
python -m pip install --upgrade pip
pip install jupyter
```

Muchas veces ocurre que al poner "pip3" no es reconocido o del mismo modo "python3"

Si nada de esto funciona, por favor hazmelo saber.
Saludos.

**Comment by tomasmetroy** [comment]
@IchottMano Ninguna de las dos formas me sirve.
Creo estar haciéndolo bien, pero por si acaso
¿En qué carpeta debo estar parado con el terminal para ejecutar estos comandos?
Gracias

**Comment by IchottMano** [comment]
@tomasmetroy Por lo que veo tienes pip y python instalado en dos lugares distintos 
"c:\users\tomas\appdata\local\programs\python\python36\" y
"C:\Users\tomas\Desktop\Python36\Scripts\pip3.exe"
Intenta desinstalar ambas versiones (además de cualquier otra que puedas tener) y volver a instalar python desde cero.
Cuando te pregunte si quieres instalarlo para todos los usuarios pones que sí, para que se instale en ProgramFiles en vez de tu appdata, además de aceptar cuando pregunte si quieres poner python en tu PATH.
Luego, hazle un update a pip para tener la última versión e intenta instalar jupyter.
Para las carpetas, sólo quedate en la que ponga por default el terminal.

Saludos

**Comment by dgfluxa** [comment]
A mi me funcionó cambiando el python3 por py.
Te quedaría así:
py -m pip install --upgrade pip
py -m pip install jupyter

**Comment by tomasmetroy** [comment]
Me funcionó!
Muchas gracias @IchottMano , @dgfluxa
