### ISSUE TITLE
Criterios de corrección Tarea 01

### ISSUE THREAD

**Issue by rafafdz** [IIC2233/syllabus-2018-2#510]
Hola, tengo un par de preguntas respecto a los criterios de corrección de la Tarea 01:

1.- ¿Corresponde que se asignen **0 puntos** en consultas que funcionaban correctamente con los casos básicos, es decir, donde las bases de datos se entregaban directamente con ```load_database``` , pero que no funcionaban cuando se combinan consultas (Se entregaron los vuelos con ```filter_flights```, por ejemplo)? Me parece bastante estricto si este es el criterio correcto de corrección.
2.- ¿Es correcto que se obtenga la mitad del puntaje en consultas que funcionan correctamente en todos los casos, pero no se muestra el tipo de la estructura de datos que se está retornando? Esto es considerando que ya se aplicó el descuento correspondiente a no mostrar el tipo de respuesta en el ítem *interacción con el usuario*.

Sería ideal si algún ayudante puede verificar si estos son los criterios correctos de corrección, o si algún compañero me puede decir si le aplicaron los mismos.
Gracias!!

**Comment by Arcoirisky** [comment]
Hola!!
Lo siento pero, según las reglas del foro #6:

> El foro no es un medio de reclamos. Cualquier mensaje de este tipo debe ser enviado mediante el mail de ayudantes encontrado en la página principal. Procura ser respetuoso/a. Tampoco debes enviar mails a los ayudantes en caso de necesitar ayuda, a menos de que te lo hayan dicho ellos mismos. 

Si tienes alguna duda respecto a los criterios puedes enviarlo al mail de ayudantes :DD Pero este no es el medio uou)
