### ISSUE TITLE
Corrección de actividades

### ISSUE THREAD

**Issue by danielaguilera** [IIC2233/syllabus-2018-2#511]
Hola! Tengo la siguiente duda: Me llegó un mail con el commit a revisar de la actividad 9. ¿Ese commit me corresponde revisarlo a mí o todavía no corre eso? De ser lo primero, ¿en dónde se llena el form para poner los puntajes y la nota?

**Comment by entamburini** [comment]
Hola Daniel! :D

Como todas las actividades hasta ahora ese es el commit que dice qué es lo que te vamos a revisar. 

Esta no es la actividad que te toca corregir, es la de la siguiente clase. Cuando sea el momento les llegará todo lo necesario :)

Saludos y buen fin de semana :D

**Comment by danielaguilera** [comment]
Gracias! Pero, soy hombre jajaj

**Comment by entamburini** [comment]
ajajaja perdón Daniel! :B fue por leer rápido
