### ISSUE TITLE
Estructuras de datos

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#513]
Holaa, no se si entendí muy bien el tema de las estructuras de datos. En el enunciado sale que están prohibidas las estructuras de Python. Entonces, si necesito ocupar algo parecido a una lista por ejemplo, tengo que crear la clase por completo, o puedo heredar de list e implementar las cosas que necesito?

**Comment by cilopez** [comment]
Tienes que crear tus estructuras por completo, no puede heredar de list ni otra estructura.

**Comment by joaquinhernandezg** [comment]
Ok, gracias. Otra duda. No puedo heredar de estructuras de datos, pero, ¿Se pueden crear clases que utilicen estas estructuras? Por ejemplo, para crear nodos y utilizar listas o diccionarios guardar los otros nodos con los que relaciona? O estas estructuras debo crearlas?

**Comment by cilopez** [comment]
No,  no puedes utilizar ninguna estructura  que venga por defecto en python. Debes implementar tu propia lista o diccionario si es que lo necesitas usar. En particular los diccionarios son una estructura difícil de crear ya que no se ven funciones de hash en este curso, de todas formas puedes investigar e implementarlas.
