### ISSUE TITLE
duda archivo centrales large

### ISSUE THREAD

**Issue by BenjaCastillo** [IIC2233/syllabus-2018-2#514]
Hola tengo una duda sobre este archivo, es que en la linea de la central que tiene id 85, en el nombre aparece "LAGUNA VERDE (U1, U2, TG)", entonces cuando hago split(",") creo que me esta separando en "LAGUNA VERDE (U1", " U2" y al final recibo mas argumentos de los que espero.

Entonces debería buscar otra forma de extraer los datos o es que esta malo el archivo?

**Comment by ptflores1** [comment]
Hola !
Te recomiendo que uses la libreria de python `csv`, con ella no deberias tener problemas.
Saludos !

**Comment by ptflores1** [comment]
Agrego que debes tener en cuenta lo mencionado en la issue #518

**Comment by BenjaCastillo** [comment]
Muchas gracias!

**Comment by diegovaras97** [comment]
¿Para la lectura de archivos puedo usar estructuras de datos?:

Ej modulo csv.DictReader() de la libreria csv que retorna un diccionario

Gracias!
