### ISSUE TITLE
Interpretación del valor consumo en subestaciones

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#515]
Hola!
Entiendo que cada casa considera, para el cálculo de la potencia demandada, un término que incluye su consumo propio (c3 en la imagen) y otros para los eventuales "colgados": 
![imagen](https://user-images.githubusercontent.com/42223959/46982713-cf461480-d0b3-11e8-8d5c-22151ab15d69.png)

Por otra parte, en la base de datos se nos proporciona una columna con el consumo para todas las subestaciones, que tiene unidades de MW. Mi pregunta es qué representa este valor, puesto que según el cálculo de ejemplo para una subestación de distribución:
![imagen](https://user-images.githubusercontent.com/42223959/46982834-55625b00-d0b4-11e8-9d74-1bc3e41ab539.png)

no existe ningún término que considere su consumo propio.
Análogamente, en la sección de consultas se indica en el quinto punto que se preguntará por el consumo de una subestación dado su id. Me parece que lo lógico a retornar en este apartado es la suma de las potencias demandadas por cada uno de sus hijos, en lugar de devolver simplemente el float que se entrega en las bases de datos correspondientes.

Gracias desde ya, saludos!

**Comment by ptflores1** [comment]
Hola !
Debes considerar el consumo de cada subestación en la formula, faltó agregarlo, perdón. El consumo de cada subestación es el consumo propio más el consumo de sus hijos.
Saludos !
