### ISSUE TITLE
Límite de potencia en las casas

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#516]
Hola!
En la sección de manejo de Excepciones se menciona lo siguiente:

![imagen](https://user-images.githubusercontent.com/42223959/46983558-737d8a80-d0b7-11e8-966b-14990e33ff47.png)

¿A qué límite se refiere este valor? Me parece que hace referencia a las casas colgadas a la actual, porque de lo contrario todas las casas lanzarían esta excepción (todas tienen una demanda basal entre 10.000 y 14.000 kW). De ser un límite para las casas colgadas, probablemente la demanda de ellas nunca sería satisfecha, a menos que se cuelguen a ~100 casas.

Saludos!

**Comment by ptflores1** [comment]
Hola !
Estas en lo cierto ese límite es muy bajo para las demandas de las casas. Usen 30.000kW. Perdón por la confusión.
Saludos !
