### ISSUE TITLE
Problema al hacer git pull del último commit (Sprites de ayudantía S10)

### ISSUE THREAD

**Issue by Conjo1** [IIC2233/syllabus-2018-2#517]
Tiene que ver con el archivo Icon. Aún así descarga los archivos, pero según git sigo al menos un commit atrasado (y los archivos quedan como untracked).  
Cuando busqué encontré que *quizás tenga que ver* con Windows y palabras reservadas, aunque no encontré que Icon por si solo sea una.  

Estos son los errores que muestra git al ejecutar los comandos en ese orden
```
$ git pull  
error: unable to create file Ayudantias/S10 - Interfaces Gráficas/sprite/Icon?: Invalid argument  
Updating f4c8d41..6c7c2d9  
```  
```
$ git status
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "Ayudantias/S10 - Interfaces Gr\303\241ficas/sprite/"

nothing added to commit but untracked files present (use "git add" to track)
```
```
$ git pull
error: The following untracked working tree files would be overwritten by merge:
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - DuckL.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - DuckR.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - JumpL.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - JumpR.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - Walk1.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - Walk1L.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - Walk2.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - Walk2L.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - Walk3.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super Mario - Walk3L.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super MarioL.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/Super MarioR.png
        Ayudantias/S10 - Interfaces Gráficas/sprite/background.png
Please move or remove them before you merge.
Aborting
Updating f4c8d41..6c7c2d9
```

**Comment by Arcoirisky** [comment]
¿por qué no intentas con
```
git fetch --all
git reset --hard origin/master
```
?

~~En el peor de los casos clona de nuevo el repo. Es la forma menos formal pero funciona~~
ojalá te resulte O:!!

**Comment by bgsamilla** [comment]
Tengo el mismo problema
Ninguno de los 2 comandos me funcionó
Intente clonado el repo de nuevo pero solo conseguí perder el repo ya que no me dejó clonarlo. (Lo rescaté de la papelera)
:(

**Comment by Conjo1** [comment]
Tampoco me funcionó, pero creo que ya sé por donde va el problema

del .gitignore del repo:
```
# Icon must end with two \r
Icon
```
Al parecer, el archivo solo tiene un `\r` (al ver el [link](https://github.com/IIC2233/syllabus/blob/master/Ayudantias/S10%20-%20Interfaces%20Gr%C3%A1ficas/sprite/Icon%0D), termina en `%0D`, que sería `\r`).
Asumo que el archivo no debió haberse subido (después de todo, no tiene nada).
Y bueno, quizás [esto](https://stackoverflow.com/questions/1761051/difference-between-n-and-r) explique porqué presenta problemas al menos en Windows

**Comment by fringlesinthestreet** [comment]
Hola :)

El archivo fue borrado. Disculpen las molestias.

Avisen si el error continúa :P.

Saludos

**Comment by entamburini** [comment]
En caso de que no les sirva, deben volver a un commit anterior a la ayudantía:
```bash
git reset --hard d10d8b9002d3550b4cce7a7a9e032085e46fb324
```
Luego de eso, podrán hacer `pull` como siempre :)
```bash
git pull
```
Espero que les sirva :D
