### ISSUE TITLE
Funciones que retornan estructuras prohibidas

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/syllabus-2018-2#518]
Si necesitas usar alguna función perteneciente a algún módulo de la librería estándar de Python que
retorne alguna de las estructuras prohibidas, deberás desempaquetar los valores de la estructura mediante el operador * y luego usarlos en tu propia implementación. Por ejemplo, el siguiente código es válido:

``` python

class MiLista:
    def __init__(self, *args):
        for arg in args:
            # do something
            pass
separa2 = "lorem ipsum dolor sit amet".split(" ")
lista_legal = MiLista(*separa2)
lista_legal.mi_append("consectetur")

```

Saludos!

**Comment by mericci** [comment]
Hola, 
para desempaquetar, es valido hacerlo como:

     id, nombre, .... = linea.strip().split(',')

donde linea corresponde a una linea de la base de datos, o hay que hacerlo mediante el operador *.

Muchas gracias!

**Comment by pbyoma** [comment]
up

**Comment by miguelramirezv** [comment]
up

**Comment by Coolgatty** [comment]
Puedo hacer una funcion que haga yield y hacer 
for i in funcion: 
   print(i)

??

Al final mi pregunta es si puedo usar generadores para cargar la base de datos

**Comment by FernandoPieressa** [comment]
@mericci lo que tu dices retorna una tupla, por ende, prohibido

@Coolgatty lo que tu dices retorna un generador, por ende, prohibido

**Comment by Coolgatty** [comment]
Con respecto a lo que pregunto @mericci que le dijeron que no; 
Puedo hacer x, y = milista[0], milista[1] 
Se considera eso como una tupla? Segun yo no deberia ser ya que eso se hace para ahorrar lineas

**Comment by SergioGazali** [comment]
Hola! 
Todavía me quedan dudas sobre lo permitido en la tarea,
puedo usar range() dentro de un método en una estructura creada por mí?
y puedo usar yield para hacer iterable una estructura propia?(se ha preguntado en otras issues, sin respuesta todavía, así que lo pregunto acá también)
Muchas gracias

**Comment by alexaptib** [comment]
Hola, tengo una duda sobre si esta permitido algo con respecto a dictreader. Es esto permitido:




def read_conexiones_casas_distribucion(path):

    conexiones = Dict()
    line_count = 0
    input_file = csv.DictReader(open(path))
    for row in input_file:
        if line_count > 0:
            **conexion = Conexion(row['id_distribucion'], row['id_casa'], row['distancia'])**
            conexiones.add_key(conexion.id)
            conexiones.add_values(conexion.id, conexion)
        line_count += 1
        
    return conexiones

**Comment by IchottMano** [comment]
@alexaptib Hola!

No, no puedes hacer eso.

Saludos!
