### ISSUE TITLE
Cálculo de demanda

### ISSUE THREAD

**Issue by isavega** [IIC2233/syllabus-2018-2#519]
Tengo las siguientes dudas: 

1. A que se refiere la demanda de cada casa? Al consumo de potencia de cada una? 
2. Dado que hay conexiones de casas en cada comuna, la demanda o consumo de cada casa tiene que ser diferenciado según su comuna? 
3. Asumo que el consumo es constante en el tiempo? No cambia según la hora ni el tipo de planta?

Gracias!

**Comment by ptflores1** [comment]
Hola !
- 1 Si
- 2 En la base de datos se especifica cual es el consumo de cada casa
- 3 Si, es constante

Saludos !
