### ISSUE TITLE
Recuperación de datos Tarea 0

### ISSUE THREAD

**Issue by firulais33** [IIC2233/syllabus-2018-2#52]
Hola,

Tengo una duda respecto a los datos que se salvaron del supuesto hackeo de DCCorreos en la Tarea 0. Los archivos que contienen a los usuarios viejos y sus emails y eventos, debo leerlos cada vez que corra el programa? O se puede hacer que la primera vez UE corra elpprogramaa, este recupere los datos viejos y los reescriba en los archivos actuales (base de datos)

Muchas gracias

**Comment by Arcoirisky** [comment]
Puedes hacerlo como más te acomode. Yo te sugiero más la segunda opción pero, mientras tengas claro que los archivos con los que se probará tu programa serán como los que les dimos, todo bien :D
