### ISSUE TITLE
Agregación de casas

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#521]
Hola! En la sección de agregación de casas (consumidores) a la red, la energía necesaria recalculada es la siguiente
![1206477a-c684-4b73-bcf5-f40a0f412e8d](https://user-images.githubusercontent.com/30879716/46990626-98cec080-d0d8-11e8-9749-d61a651791b0.jpeg)
Pero no entiendo de qué forma se agregaría la casa para que la energía quede de esta forma, ya que P_4 / 3 y P_5 / 3 podrían surgir únicamente si tienen 3 casas proveedoras. Está mal la ecuación? 

Saludos!

**Comment by rhanuch** [comment]
¡Hola!

El ejemplo fue corregido en el nuevo enunciado 😅
