### ISSUE TITLE
Agregar aristas y lectura de archivos

### ISSUE THREAD

**Issue by firulais33** [IIC2233/syllabus-2018-2#522]
Al minuto de agregar una nueva arista a la red, cual sera la distancia entre los dos puntos? Entiendo que hay archivos que contienen las conecciones. Esto me sirve para inicializar la red, pero nose de donde sacar la distancia al minuto de agregar una nueva arista a la red.

Tambien tengo otra duda con la lectura de archivos. Cuando leo los archivos, puedo hacerle un filter a las lineas del archivo y luego desempaquetar esas lineas?

Saludos!

**Comment by FJavierOss** [comment]
Saludos,

Para el primer punto para poder ingresar la arista tambien se debe ingresar la distancia. 
Para el segundo punto, el filter solo será valido si se utiliza sobre una estructura creada por ti, cualquier filter utilizado sobre una estructura de python esta malo. Animo y suerte en tu tarea :smile:

**Comment by dlcartagena** [comment]
@FJavierOss Lo que yo entiendo es que si quiero conectar dos puntos, entonces debo calcular la distancia entre ellas. Cuál de estas dos formas sería la correcta?

Saludos!

**Comment by FJavierOss** [comment]
Por simplicidad no hay que calcularla, puedes poner la distancia que te parezca.

Saludos
