### ISSUE TITLE
 Id Bases de Datos

### ISSUE THREAD

**Issue by mvgil** [IIC2233/syllabus-2018-2#524]
Hola,

En la base de datos small, aparentemente los id de cada archivo consideran los id del resto de los archivos, de manera que no existan id repetidos, incluso en nodos de distinto tipo (salvo en dos casos).

En cambio, en la base de datos large, cada archivo parte desde el id 0.(nodos de distinto tipo tienen el mismo id).

Asumo que la enumeración de ids está bien? porque si es así, tendría que poner ids propios (distintos a los de la base de datos) a los nodos de mi grafo para poder diferenciarlos.

Gracias!

**Comment by ptflores1** [comment]
Hola !
La base de datos small es un extracto de la base de datos large, si los id's de la bd small nunca coinciden es una casualidad. Los id's son únicos para cada entidad, es decir son únicos para cada archivo.
Saludos !
