### ISSUE TITLE
Perdida de potencia através de los cables

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#525]
En el enunciado se dice lo que sigue:

" Para simpliﬁcar el problema general, deﬁnimos fi,j como la función que determina la pérdida de potencia a través del cable que va desde i hasta j, como:
  fi,j = Pi Ri,j 
Donde Pi es la potencia disponible para la casa i, y Ri,j es la resistencia del cable que va de i hasta j."

Pero no me hace sentido, ¿como se supone que sepa la potencia de la entidad i sin antes calcular la demanda de j y distribuir la energía?

O lo estoy entendiendo mal?

**Comment by rhanuch** [comment]
Hola! Esto fue corregido en el nuevo enunciado, espero que ahora quede más claro!
