### ISSUE TITLE
Duda desempaquetar datos

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#526]
Hola! Es válido lo siguiente?
```python 
def __init__(self, *args):
        self._elementos = args
```
Gracias de antemano, saludos!

**Comment by nachocontreras** [comment]
Hola!

No es válido debido a que se estaría guardando una tupla. En cambio, se puede iterar sobre la tupla desempaquetada pero no guardarla.
```python
for arg in args:
    self.append(arg)
```
