### ISSUE TITLE
Plazo Entregable

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2233/syllabus-2018-2#527]
Buenas, disculpen. Después de la sala de ayuda de la T03, me quedó la idea de que iban a arreglar el enunciado  por cosas no consideradas o mal explicadas, lo que supondría una disminución del tiempo considerado inicialmente para el desarrollo del entregable. Entonces, me surge la duda sobre si están considerando extender en un par de horas-día más el plazo para el entregable de la tarea.
Atentamente T-Student 😄

**Comment by agustinkrebs** [comment]
Hola!

Estamos trabajando para hacer todos los cambios de enunciado lo antes posible. Aún así, no extenderemos el plazo del entregable ya que en éste no necesitan conocer los cambios que se efectuarán porque la lógica general se mantendrá. Básicamente, tienen que hacer pseudo código de cómo implementarán el calculo de la demanda de la red, o sea, cómo van a generalizar el ejemplo del enunciado en su programa, y eso ya lo pueden hacer con el enunciado actual.

Saludos!
