### ISSUE TITLE
Base de datos y conexiones

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#528]
Tengo una duda en el enunciado. En la base de datos small existe solo un "elevador" el cual tiene que estar conectado a las centrales. Mi pregunta es si es que hay algún criterio para el cual algunas centrales se puedan conectar y otras no?, como por ejemplo "que tengan que estar en la misma provincia". 
Muchas Gracias!

**Comment by rhanuch** [comment]
Hola,
No, solamente deben estar en el mismo sistema, ya que todas las centrales eléctricas de un sistema van conectadas a la eleveadora del mismo sistema eléctrico 🔌 

Saludos
