### ISSUE TITLE
Editar eventos, invitados. Formato invitados/destinatarios

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#53]
Hola!

1. El enunciado dice que se debe editar cualquier cosa, incluido las etiquetas, descripción, nombre, etc. ¿Esto incluye a los invitados?

2. ¿Para los correos y los eventos, los destinatarios/invitados deben existir en la base de datos? ¿Se les debe pedir que los corrijan/cambien si no existen?

Gracias de antemano

**Comment by nachocontreras** [comment]
Hola!

1. No se puede editar a los invitados. Eso sería como desinvitar a alguien de un evento y sería muy mal visto.

2. No necesariamente deben existir en la base de datos, sin embargo, deben ser correos electrónicos válidos.

**Comment by Gorgola22** [comment]
Muchas Gracias!
