### ISSUE TITLE
Solucion ayudantia 10

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#530]
Hola queria saber si iban a subir la ayudantia 10, porque estaba tratando de hacerla pero me quede estancado en una parte.

Gracias!

**Comment by entamburini** [comment]
Hola!, 

Disculpen la demora, hemos estado ocupados :c pero ya está subida!! :tada: 

Haremos lo posible para que no se vuelva a repetir :smile:
