### ISSUE TITLE
Columnas de las bases de datos

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#531]
Hola!

Dado que no se puede usar ni listas ni diccionarios, podemos asumir que las columnas siempre estarán en el mismo orden? 

Gracias!

**Comment by jeschuwirth** [comment]
No pueden asumir eso, recuerda que aunque no se pueden utilizar las listas ni diccionarios implementados en python, pueden crear los suyos propios que funcionen de manera equivalente y utilizarlos.

**Comment by tamaralues** [comment]
No entiendo muy bien, ¿Esto significa que puede pasar que las columnas esten intercambiadas? Es decir, que por ejemplo en las conexiones de casas  en vez de (origen, destino, distancia) , nos den (destino, distancia, origen) ? o se refiere al orden dentro de la misma columna?

**Comment by jeschuwirth** [comment]
no entendí a lo que te refieres con la segunda explicación pero es la primera, en vez de entregar (origen, destino, distancia) puede estar como (destino, distancia, origen), por esta razón deben leer las columnas por headers y no por el número de columna que es
