### ISSUE TITLE
Duda base de datos y exceptions

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#532]
Hola! Puedo asumir que en la configuración de red que establecen las bases de datos no se generan exceptions del tipo Electricaloverload/Forbiddenaction? Si no es así, como debería proceder en estas situaciones?

Saludos! :cat:

**Comment by rhanuch** [comment]
Hola!

Sí, puedes asumir eso.

Saludos

**Comment by IriSalazar** [comment]
Tenemos que manejar los errores de tipo ASCII que pueden surgir al usar las bases de datos ? O no debería pasar ?

**Comment by rhanuch** [comment]
@IriSalazar , sí. Debes manejar ese tipo de errores.
