### ISSUE TITLE
Duda botones Interfaz gráfica

### ISSUE THREAD

**Issue by Franco1605** [IIC2233/syllabus-2018-2#533]
Hola ! tengo un problema que no he podido solucionar: estaba resolviendo una actividad de interfaces gráficas en la cual me piden implementar una ventana principal con un QLineEdit y un QPushButton, el cual, cada vez que se presione, agrega una nota a la MainWindow con algún texto. El punto es que, al agregar una nota, el botón y el rectángulo de texto de la ventana principal "dejan de funcionar". Esto es, no me deja ingresar otro texto y tampoco puedo presionar el botón otra vez... ¿Qué puede ser?
Gracias de antemano!

**Comment by fdduarte** [comment]
Hola! Tu problema se puede deber a muchas cosas, no te podría decir exactamente porque. Si puedes adjuntar el código podría ver con mas detalle. Saludos

**Comment by Franco1605** [comment]
Aquí está la imagen del código. No se ve, pero hay una clase que es de notas.
![image](https://user-images.githubusercontent.com/42159289/47157048-ce350300-d2be-11e8-9a4b-000607c0acf0.png)

Cuando lo ejecuto, me aparece así:
![image](https://user-images.githubusercontent.com/42159289/47157123-05a3af80-d2bf-11e8-91d6-46af1e8bc519.png)
Y no me deja utilizar el botón send de nuevo.
