### ISSUE TITLE
Entregable t03

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#535]
Hola! Donde está el link para el entregable de la t03? Y hasta que hora del día viernes se puede subir?
Gracias!!

**Comment by rhanuch** [comment]
¡Hola!

El plazo del entregable no cambiará debido a que no es afectado por los cambios en el enunciado.

¡Saludos y éxito! 🍀

**Comment by gatochico** [comment]
Me parece que en el enunciado actualizado todavía no esta el link del google form del entregable 😿
gracias!!

**Comment by Cadagan** [comment]
Entonces el entregable lo subimos a los repositorios nomas? o si es que todavia esta en pie lo del google form, cuando van a mandar el link?

**Comment by Franco1605** [comment]
En qué quedó esto ? :o

**Comment by rhanuch** [comment]
¡Hola!

Se subió el link al SIDING👷

¡Saludos y éxito! 🍀
