### ISSUE TITLE
Cantidad de Estaciones Elevadoras

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#539]
En la descripción de la red del enunciado se indica que debe haber al menos 1 estación elevadora por sistema (o sea puede haber más de una), pero luego en el ejemplo de la exception ForbiddenAction se indica que si hay una estación elevadora en el sistema entonces no se puede conectar otra. ¿Con cual debemos quedarnos?

**Comment by agustinkrebs** [comment]
Hola!

Yo diría que te quedes con la segunda. Y lo leería como “Al menos debe de haber una (es decir que no pueden NO estar conectada a una elevadora) y solo a una”

Saludos!

**Comment by bgsamilla** [comment]
Pero en la parte agregar nodos dice:

"Por otro lado, cuando se añade una nueva estación elevadora, esta debe poder asociarse a alguna(s) generadora(s) para obtener energía eléctrica. Si se quiere asociar a una generadora que ya está ocupada, la energía de la generadora se divide entre las dos estaciones elevadoras."

Entonces podemos o no agregar mas elevadoras a un sistema?

**Comment by IchottMano** [comment]
Hola!

Ese es un ejemplo que quedó obsoleto con el cambio en el enunciado, simplemente ignórenlo.

Saludos!
