### ISSUE TITLE
Formato del proveedor de servicio

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#54]
En el correo electrónico que se pide al registrar una nueva cuenta, ¿basta con que haya un string cualquiera a la derecha del "@"? (por ejemplo "user@uc"), ¿o debe incluir el ".dominio" (por ejemplo "user@uc.cl" o user@ing.uc.cl"?

**Comment by jtcaraball** [comment]
No hay restricción en cuanto al dominio del mail al momento de crear una cuenta por lo cual te recomiendo incluirlo.

**Comment by BFFV** [comment]
¿Entonces debo permitir que se registre por ejemplo como user@uc o lo fuerzo a que sea user@uc.”algo”?

**Comment by jtcaraball** [comment]
Fuerza el uso del ".algo".

**Comment by gnacrur** [comment]
Siguiendo con este mismo tema, no se que tanto tengo que restringir en la creación del mail. Por enunciado no veo problema con que haya un mail que sea como a@b.c o a@b..c o $@#.8 que son bastante raros.

**Comment by jtcaraball** [comment]
Es verdad, lo que va a la izquierda del @ puede.ser.muy.raro.com
Aunque doble @ si bien no está especificado en el enunciado me parecería demasiado raro.

Saludos!
