### ISSUE TITLE
Problema actividad 10

### ISSUE THREAD

**Issue by rsnegrin** [IIC2233/syllabus-2018-2#540]
Sin querer hice push a la AC10 en el syllabus en vez de mi repertorio. Que puedo hacer al respecto?  Ya la subí a mi repertorio pero fue pasado la hora limite.

**Comment by naquiroz** [comment]
Hola! Lamento ser yo quien te dice esto, pero lamentablemente tu actividad no podrá ser recolectada :disappointed: . El reglamento es claro en que no se hacen excepciones con respecto a la hora de push. Además, esta es la actividad número 10, por lo que a estas alturas del curso, se espera que un alumno del curso sea capaz de prevenir errores como estos. Mucho cuidado para la próxima! Y ánimo! Hay muchas actividades mas.
