### ISSUE TITLE
actividad 10

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#541]
Hola, por alguna razón durante la actividad no me funcionó nunca la parte de generar las cherries y fue imposible identificar el error durante la actividad porque no se levantaba ningún error. Llegando mi casa me di cuenta que hay un atributo definido en una función pero que nunca recibe y no debí haber puesto. Más aun, borrando esta palabra se arregla todo. Quería saber si hay alguna posibilidad de subir un readme o algo y que le llegue a los correctores para indicar el error para que al menos ellos no tengan que darse vueltas viendo porque el código no funciona ya que a simple vista parece que estuviese bueno. Esto le ahorraría harto tiempo a los correctores y **quizás** me ayude en mi nota.

**Comment by entamburini** [comment]
Hola!,

Desgraciadamente, no podemos hacer ninguna excepción al respecto. Sobretodo en esta actividad, dado que se sabría de antemano la persona que tiene un readme y por ende podría perderse la objetividad de la revisión D:

Perdona pero en este caso no podemos ayudarte u.u
