### ISSUE TITLE
Codigo lento debido a clases

### ISSUE THREAD

**Issue by Coolgatty** [IIC2233/syllabus-2018-2#542]
Hola mi problema es que use clases para representar las casas, generadores etc puesto que no se pueden usar namedtuples. 

Mi problema es que en la base de datos large mientras mas objetos se crean mas se demora mi codigo en ejecutar por lo que me gustaria saber que podria hacer para reducir el tiempo que demora mi codigo (demora como 3 minutos en cargar todo). 

Me da la impresion de que si lo dejo asi mi programa correra muy lento para realizar consultas (que todavia no hago)

**Comment by IriSalazar** [comment]
En la ayudantía dijeron que el programa podía demorarse todo lo que debiese, que no se buscaba que fuera veloz. No se si aplica para este caso

**Comment by Coolgatty** [comment]
Mi base de datos demora 56 minutos en cargar 😬😬😬😬
