### ISSUE TITLE
Calculo de demanda / Resistencia

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#543]
Tengo una pregunta mas de física - eléctrica que de programación, estaba mirando la formula para calcular la demanda con la resistencia y hay algo que no acabo de entender.

La resistencia se calcula como:
R = ρ * L / S que según las unidades que nos dan R quedaría en ohmios.

Pero luego tenemos que usar

M =P / (1−R)

donde P según entiendo estaría en Kw.
Esperaría que M también estuviera en Kw pero queda el ohmio dividiendo, y no se si esta bien dejarlo así o si los ohmios son como los radianes que puede sacar cuando quieras ......
Simplemente lo calculo y me olvido, o hay que hacer alguna conversión?

Saludos!

**Comment by joaquinhernandezg** [comment]
Me surgió la misma duda, el Ohmio es una unidad con dimensiones  y la potencia tiene unidades con dimensiones, al multplicar P*R debería quedar Watt*Ohm, lo cual no es una unidad de potencia. Como puede ser que una perdida de potencia tenga unidades que no son de potencia?
Según tengo entendido, la perdida de potencia se calcula como Pp= R*I^2 o Pp = V^2/R (asumiendo que la electricidad de transporta en un solo cable). Deberíamos ignorar el significado físico de esto?
Si no, deberían darnos los voltajes con los que se trabaja en cada recorrido.

**Comment by arbiocanpion** [comment]
cps

**Comment by Coolgatty** [comment]
Tengo esta misma duda y ademas queria saber si las unidades de esa resistividad estan bien porque sale 0.0172(mm^2)*ohm/km lo cual da 1.72*10^-11 ohms*metro pero en internet sale que la resistividad es 1.72*10^-8. Segun yo la unidad deberia ser (mm^2)*ohm/m

**Comment by ptflores1** [comment]
Hola !
Ignoren el significado físico de las ecuaciones y perdón por las confusiones que esto les pueda causar.
Lo que menciona @Coolgatty es cierto y el cambio que hicimos en las unidades de metro a kilómetro fueron para evitar que el calculo de los consumos diera negativo.
Saludos !
