### ISSUE TITLE
Consumo estaciones elevadoras y subestaciones 

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#544]
Cual es la interpretación del consumo de las estaciones y subestaciones?
Es electricidad que gastan o la electricidad que pasan a sus hijos?
Si es la energía que gastan, no sería demasiada según los datos de las bases de datos?
Si esto es así, no debería llegar nada de electricidad a las casas...

**Comment by haarenas** [comment]
up

**Comment by ptflores1** [comment]
Hola ! #559 creo que eso te responde la pregunta, perdón por la demora

**Comment by cacoos** [comment]
Cómo pasó lo de #592? En mi caso no pasa nada a las casa 😟

**Comment by bgsamilla** [comment]
@cacosandon 
A mi tampoco me levanta la excepción , según yo es porque la casa esa en efecto pide 34000 kw pero con la potencia que tienen las generadoras no le alcanza a llegar mas de 30000 kw, o al menos eso es lo que pasa en mi código, como prueba le puse a todas la generadoras como 100000 mw de potencia y en ese caso si que se levantaba el error ese.
Saludos!

**Comment by cacoos** [comment]
Buena, gracias!

**Comment by jaromero6** [comment]
@cacosandon  y @BSamilla 
se me fue decirlo, al momento de publicar esa issue estaba repartiendo mal la energia lo estaba haciendo mal y por eso me llegaban 33000 kw. La demanda me da 34000 aprox, y al repatir energia les llega mucho menos a las casas. Eso obviamente era con la base de datos antigua, con la nueva ya no ocurre ese error, sorry si causó molestias el no haber arreglado eso
