### ISSUE TITLE
Duda Entregable

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#545]
Hola!
La verdad es que no entiendo que tenemos que hacer en el entregable. Se nos pide "investigar o crear una forma para calcular la demanda de la red". En el punto 3.1. (Cálculo de demanda de la red) nos dan una fórmula explicita para hacerlo. No entiendo entonces que es lo nuevo que tenemos que hacer para el entregable.

Ojalá puedan aclararme esta duda!!
Gracias

**Comment by lily416** [comment]
Hola, 

En el enunciado se te entrega la fórmula para calcular la demanda de una entidad, explícitamente las entidades de consumo.
 
Para el entregarle debes ver como harás este cálculo para una central generadora y de qué forma iras obteniendo las demandas de sus entidades hijos y sabiendo cuanto de esta demanda va a cada entidad padre. A lo que me refiero es que debes ver cómo aplicar la fórmula a un caso más general donde las entidades pueden tener _n_ padres y _m_ hijos. 

Ojalá que con esto te quede más claro, 
Saludos ⚡

**Comment by BFFV** [comment]
¿Y el link del google form será subido al final, o se entrega en el repositorio?

**Comment by lily416** [comment]
El link se les acaba de mandar al mail, pero por si acaso se los dejo [acá](https://goo.gl/forms/gFISQ8C3r3QVUbJh1).

Éxito con la tarea 💡

**Comment by mvgil** [comment]
hasta qué hora se puede subir el entregable? hasta las 23:59?

**Comment by lily416** [comment]
@mvgil Esa misma
