### ISSUE TITLE
Pregunta: error en bases de datos

### ISSUE THREAD

**Issue by IriSalazar** [IIC2233/syllabus-2018-2#546]
Es una posibilidad que las bases de datos van a tirar errores cuando las cargue y yo tengo que lidiar con esos errores y evitarlos??

**Comment by rhanuch** [comment]
#532

**Comment by IriSalazar** [comment]
No me refería a eso. Si no a errores del tipo ASCII

**Comment by rhanuch** [comment]
No. No puedes asumirlo.
