### ISSUE TITLE
Casas colgadas

### ISSUE THREAD

**Issue by haarenas** [IIC2233/syllabus-2018-2#547]
Hola tengo una duda respecto a las casas colgadas. En el enunciado se menciona lo siguiente al conectar las casas:
![casas de una misma comuna](https://user-images.githubusercontent.com/42160913/47237822-98734580-d3b6-11e8-82af-c7fdd01cf07a.png)

Dicho esto, es posible que una casa este conectada a otra casa y a la vez a una distribuidora? (respetando que ambas pertenezcan a una misma comuna)
Por ejemplo en esta imagen, la casa 5 esta conectada a la casa 3 y a la distribuidora 3 (ambas de la misma comuna)
![screenshot from 2018-10-19 16-05-02](https://user-images.githubusercontent.com/42160913/47238497-cc4f6a80-d3b8-11e8-938c-33ce97c1f26a.png)

**Comment by nachocontreras** [comment]
Hola!

Tal como dice el enunciado, NO es posible que una casa este conectada a otra casa y a la vez a una distribuidora.

**Comment by jbartolomev** [comment]
Hola!
¿Y se puede el caso de que hubiera una casa conectada a d3, y c5 estuviera conectada a esta nueva casa en vez de a d3 directamente?
En este caso la casa c5 recibiría energía de 2 subestaciones de distribución distintas. ¿Es ésto posible?
