### ISSUE TITLE
Duda en la hora de leer archivos

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus-2018-2#549]
Hola, gustaria de saber si puedo hacer eso:

def leer_archivo(archivo):
    with open(archivo, "a" , enconding="utf-8") as file:
        for line in file:
            variable1, variable2, variable3 = line.strip().split(",")

o tengo que criar mis proprios methods strip and split?
porque entendo que con with open ocupando for line in file, estoy gerando una lista y eso esta malo para esa tarea cierto? Tengo que ocupar una estructura propria para leer los archivos??

**Comment by agustinkrebs** [comment]
Hola!

Puedes usar strip y split, **pero no puedes usar los resultados sin antes desempaquetarlos en tu propia estructura** .

Saludos!

**Comment by Michelmagna** [comment]
@akrebs2  
Es posible implementar la lista con los resultados (cuando leo los archivos csv con csv.reader por ejemplo) de manera de ir agregando uno por uno? Más claramente, no desempaquetar los resultados directamente (ya que mi lista-propia en si, no recibe argumentos), sino ir agregando uno por uno con el método creado respectivo. Luego posteriormente, usar mi lista creada para el fin que necesito.

Saludos!
