### ISSUE TITLE
Duda Usuario único en Feedback

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#55]
En el feedback sale que el usuario y el mail son únicos, en el caso del mail está bien ya que no se pueden repetir los correos entre usuarios, ¿pero no se supone que el usuario es el nombre a la izquierda del "@" y se puede repetir siempre que el servicio proveedor sea distinto?

**Comment by rhanuch** [comment]
¡Hola @BFFV !

Acabo de actualizar el feedback, ahora debería estar correcto

¡Saludos y éxito! 🍀
