### ISSUE TITLE
Consulta energía total consumida en una comuna

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#550]
En el enunciado de nos pide:
"Energía total consumida en una comuna: dado un string de comuna, se debe retornar el consumo total de esa comuna en kW. Esto es la suma del consumo de energía de cada consumidor dado el id de esa subestación y además deben entregar el porcentaje de ese consumo con respecto al consumo total de la red"

Entiendo que me darán el string de una comuna, pero no me queda claro desde donde comenzar a sumar.
Que quiere decir la parte "dado el id de esa subestación" ¿Cual subestación?, ¿Me darán la id ademas de la comuna? ¿Es una subestación de distribución de transmisión o elevadora?

Saludos!

**Comment by ptflores1** [comment]
Hola !
Comienza a sumar desde la subestación de distribución de la comuna pedida (incluyéndola). Si hubiese más de una subestación de distribución en la comuna, debes considerarlas todas.
Saludos !

**Comment by ariel-m-s** [comment]
Hola!

@ptflores1 a qué se refiere cuando dice "Esto es la suma del consumo de energía de cada consumidor dado el id de esa subestación"? Tenemos que entregar el consumo por cada subestación o de la comuna completa?

**Comment by ptflores1** [comment]
@amartinezsilberstein respondí en #594

**Comment by mericci** [comment]
Hola!

También tengo una duda respecto a esta consulta, cuando dice **Esto es la suma del consumo de energía de cada consumidor**, quiere decir que se debe sumar el consumo tanto de las casas como de las distribuidoras,  o solo las distribuidoras, ya que están incluyen la el consumo de las casas en caso de que haya.

Muchas gracias
