### ISSUE TITLE
AC10, comando exec

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#551]
En mi actividad 10, utilizo app.exec_() para cuando quiero cerrar el programa, con app = QApplication([]). En la guía de corrección de pares leí que si encuentran los comandos eval, exec o pickle que se notifique a un mail, pero yo usé exec_() (que es distinto al exec normal) porque eso estaba en la ayudantía 10. Favor de aclarar si eso está bien o mal y también me gustaría saber el peligro de esas tres keywords.

Gracias de antemano.

**Comment by entamburini** [comment]
Son **diferentes**:

Tu lo que hiciste fue: 
```python
app = QApplication([])
app.exec_()
```
En la guía se especifica que `exec` está prohibido, algo así como hacer 
```python
# Este es un comando cualquiera, es para mostrar la idea
exec('print("holiwi :B")') 
```
El principal problema con estos comandos de python es que pueden inyectar código malicioso a su pc sin que se den cuenta (como puede ser, apagar su pc o borrar archivos sensibles de este) y por eso nunca pueden ser usados en sus actividades o en sus tareas, salvo la honrosa excepción de `pickle` en una de las próximas actividades (podría ser que la usen).
