### ISSUE TITLE
AC10, parte de la interfaz gráfica

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#552]
Abrí las dos actividades y ninguna se abre en la parte de la interfaz gráfica (no se muestra el fondo, ni el packman, etc.), debido a que (al igual que yo) pusimos los sprites e imágenes directamente de la carpeta, y nos pasaron (al parecer) un .zip que tiene a las imágenes en la misma carpeta que el back-end y el front-end. Favor de arreglar esto o informarlo a los demás, ya que no es problema del que lo programó.

Salu2

**Comment by entamburini** [comment]
Hola!,

Debido a lo heterogéneo de la forma en que suben los archivos (algunos con y otros sin los archivos), a las diferentes rutas que usaron y por último a lo poco que deben corregir, es mejor que ustedes arreglen el problema de la ruta (dado que es cambiar sólo una línea o poner las imágenes donde el programa está buscando los archivos).

De todas formas, se subió una actualización de la guía para estos casos :) no se descuenta por estos inconvenientes!

Que estés bien! :D
