### ISSUE TITLE
Feedback T03

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus-2018-2#553]
Hola! Van a publicar el feedback para la tarea 3? 

Saludos!

**Comment by agustinkrebs** [comment]
Hola!

Feedback de los entregables, sí (probablemente el lunes). Tener en cuenta que serán comentarios generales para todos, no específicos por cada entregable.

Saludos!

**Comment by agustinkrebs** [comment]
Interpreté mal lo que pusiste jaja, el feedback lo mandaron por correo hoy.

Disculpa!

**Comment by nhorellana** [comment]
Hola! Perdón, pero no he encontrado el feedback del entregable (el excel ya lo ví, gracias) lo subieron y no lo encuentro no más o todavía no está?

**Comment by agustinkrebs** [comment]
Hola!

Error mío, no había feedback del entregable para esta tarea :(. Esto porque puede haber más de una manera correcta de enfrentar el problema, a diferencia de la tarea anterior en donde se buscaba una forma en particular que modelaran las clases (por eso ahí sí había feedback de entregable).
Perdón por el error.

Saludos!
