### ISSUE TITLE
Energia entregada por centrales

### ISSUE THREAD

**Issue by stmorales** [IIC2233/syllabus-2018-2#554]
Hola, en el ítem 3.2 sobre el flujo de potencia de la red se indica: "Dada una energía generada por las centrales.....". Esto se refiere a la capacidad máxima que produce cada central? Si no es así, no logro entender cómo se dará este parámetro si no existe una cantidad fija de elevadoras? Pueden haber 2 elevadoras conectadas a 2 centrales cada una u otra opción, dentro de las miles que hay, es que haya 1 elevadora con 4 centrales conectadas.

Lo que se me ocurre es hacer un atributo a cada central con una potencia producida, pero darle este parámetro a todas las centrales o es aleatorio o el mismo para todas. Por favor, si pudiesen explicar cómo se dará este valor se los agradecería.

Saludos

**Comment by agustinkrebs** [comment]
Hola!

Las centrales tienen una capacidad máxima a entregar a la red. Sin embargo, la red puede demandarle más (o menos) que ese máximo. Esa demanda de la red es la que debes calcular, y así tienes cuánta energía tiene que entregar cada central.

Saludos!

**Comment by stmorales** [comment]
Entonces no se refiere a que a cada central se le asigna un valor a generar y que este no puede ser mayor al máximo?  En el caso que tu dices el punto 3.1 y 3.2 estarían haciendo referencia a lo mismo. Lo que entiendo del 3.2 es que dado lo que generan las distintas centrales (no la potencia máxima ni la demandada) como se distribuye a lo largo de la red. Mientras que en el 3.1 es la cantidad que debiese producir cada central para satisfacer la demanda.

Ejemplo:
- En el 3.1 me dicen que las centrales 1 y 2 tienen que generar 30 MW y 25 MW respectivamente (por decir un ejemplo) para satisfacer la demanda completa.

- En el 3.2 me dicen si hago que las centrales 1 y 2 generen 25 MW y 15 MW cual es el consumo real de cada identidad de la red.

No se si me explico, que no entendí mucho la diferencia con lo que me explicaste.

Gracias

**Comment by Benjadef** [comment]
Tengo exactamente la misma duda, por favor responder esta issue.

@stmorales según lo que entiendo de @akrebs2, esta energía generada por las centrales, sería la energía que nosotros calculamos teóricamente en el punto 3.1, me imagino que esta energía calculada , a veces podría no satisfacer la demanda de todo el sistema ya que podría suceder que la demanda teórica de las centrales supere la capacidad máxima de ellas, sin embargo, si consideramos que la energía teórica es la "energía dada", esta energía nunca superará a la demanda por lo que la linea del  párrafo del punto 3.2
 "Dada una energia generada por la centrales, la red debe ser capaz de distribuirla. Si la cantidad producida es mayor a la cantidad demandada por la red"
no tendría sentido, a menos que dentro de esta linea se consideren las modificaciones en la red.

igualmente esto es muy confuso, podrían explicitar mejor cual sería esta "energía dada" por favor 
gracias!

**Comment by agustinkrebs** [comment]
En simple, si la demanda es menor que la capacidad máxima, todo bien. Si no, calculen como se explica en 3.2. Son dos casos nomás.

**Comment by stmorales** [comment]
Gracias!

**Comment by Benjadef** [comment]
Gracias !, asumo entonces que esta "energía dada" es la calculada teóricamente?? @akrebs2 , no mencionaste nada sobre esto en tu respuesta 😒

**Comment by agustinkrebs** [comment]
Sí, es eso. Sorry por no responder esa parte.
