### ISSUE TITLE
Energía total consumida en una comuna

### ISSUE THREAD

**Issue by stmorales** [IIC2233/syllabus-2018-2#556]
Hola, debemos entregar la energía total consumida por las casas y las subestaciones? O sólo nos preocupamos de la energía real consumida por las casas de esa comuna?

Gracias

**Comment by agustinkrebs** [comment]
Hola!

¿Te refieres para una consulta en específico, o para calcular la demanda total de la red?

Saludos!

**Comment by stmorales** [comment]
Para la consulta de energía total consumida en una comuna. Perdón, se me fue indicarla en el comentario.

**Comment by ptflores1** [comment]
Hola !
Revisa #550. Debes entregar la cantidad consumida actualmente por la red, no la demanda que viene en las bases de datos.
