### ISSUE TITLE
AC 10, cargar imagenes

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#557]
Buenas, deberá existir algun tipo de descuento si es que no se cargan las imagenes directamente desde la carpeta sprites?, es decir, que importa las imagenes directamente desde la raiz de la carpeta.

**Comment by entamburini** [comment]
Hola!, 

Hace unas horas se subió una actualización de la guía con respecto a este problema. Respondiendo a tu duda, no se descuenta por este problema.

Que estés bien! :D
