### ISSUE TITLE
Duda sobre restricción de estructuras de datos

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#558]
Hola!
en la parte donde se prohíbe el uso de estructuras tales como listas, tuplas, diccionarios, etc. esta prohibición aplica en todas las situaciones? por ejemplo, si quiero crear un grafo y quiero almacenar los nodos del grafo en una lista o un diccionario para iterar sobre el, está permitido eso o debo buscar otra forma?

**Comment by IchottMano** [comment]
Hola!

No está permitido que uses estructuras *built-in* para crear tus propias estructuras. Debes realizar la totalidad de tu tarea con tus propias estructuras.

Saludos!
