### ISSUE TITLE
Valores inconsistentes en potencia total

### ISSUE THREAD

**Issue by Coolgatty** [IIC2233/syllabus-2018-2#559]
En la base de datos small al calcular la suma de las potencias me da que el total generado por las centrales ese de 936.100,47 kW mientras que el total de consumo de las distribuidoras es de 1.843.773,28 kW.

Dijeron en #532 que esto no pasaria. Por favor aclarar si estoy entendiendo algo mal pero me parece que faltara potencia en la red.

**Comment by viantirreau** [comment]
Hola!
Me pasó algo similar. No obstante, me di cuenta de que estaba calculando la demanda o consumo ideal, no el consumo efectivo. Probablemente al calcular lo segundo, como muchas casas se quedan desabastecidas, no dé problemas de ElectricalOverload 😉 

Saludos!

**Comment by Coolgatty** [comment]
> Hola!
> Me pasó algo similar. No obstante, me di cuenta de que estaba calculando la demanda o consumo ideal, no el consumo efectivo. Probablemente al calcular lo segundo, como muchas casas se quedan desabastecidas, no dé problemas de ElectricalOverload 😉
> 
> Saludos!

Si te das cuenta todos los distribuidores tienen un camino que lleva a un generador por lo que si o si se necesita minimo 1.843.773,28 kW y eso es sin contar elevadoras y transmisoras.

De hecho entre transmisoras y elevadoras hay aprox 839.000 kW de consumo

**Comment by ptflores1** [comment]
Hola !
Lo que está en la base de datos corresponde a la demanda de cada entidad y no a consumo real que depende de la cantidad generada. La excepcion `ElectricalOverload` debiese ser levantada cuando el flujo real es mayor a 30.000 kW, como la cantidad generada es menor a la cantidad demandada los flujos reales a nivel de las casas debiesen ser bajos por lo que no habrian `ElectricalOverload`'s
Saludos !

**Comment by Coolgatty** [comment]
Claro entiendo eso pero me confunde mucho porque a nivel de distribuidoras se consume mas potencia de la que se genera en las centrales

**Comment by ptflores1** [comment]
te refieres a nivel de las subestaciones de distribución?

**Comment by Coolgatty** [comment]
Sisi distribucion me equivoque

**Comment by ptflores1** [comment]
Si a nivel de las distribuidoras se consume más de lo que es generado entonces simplemente no pasara energía hacia las casas, el `ElectricalOverload` se produce cuando por una casa pasa mas de lo que se permite, cosa que no sucede en este caso. No se si se entiende, de no ser así repiteme tu duda porfa !

**Comment by Coolgatty** [comment]
Aaah perfecto ahora entiendo. Entonces en las bases de datos no pasara energia hasta que se agreguen mas generadores ?

**Comment by ptflores1** [comment]
@Coolgatty  exacto!
