### ISSUE TITLE
Error en lectura de archivo "distribucion.csv"

### ISSUE THREAD

**Issue by jbartolomev** [IIC2233/syllabus-2018-2#561]
Hola! Al cargar la información del archivo "distribución.csv" en variables, me surgió el siguiente error:

return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 176: ordinal not in range(128)

Me di cuenta que se debe al nombre de una subestación de distribución que es "CERRO DRAGâÃ´N"
¿Que puedo hacer? Muchas gracias de antemano.

**Comment by Arcoirisky** [comment]
Cuando abres el archivo utilizas utf-8? O:
