### ISSUE TITLE
Duda sobre id de entidades

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#562]
Hola!

Quizás la pregunta sea algo obvia, pero la hago de todos modos: Es posible que dos entidades tengan el mismo id pero pertenezcan a clases distintas?

por ejemplo, es posible tener una casa con id = 1234 y una subestación con id = 1234 ?

gracias de antemano

**Comment by joaquinhernandezg** [comment]
Según la issue #524 debería ser posible
