### ISSUE TITLE
Duda desempaquetar datos desde un diccionario

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2233/syllabus-2018-2#563]
Hola!, si estoy usando una funcion que me retorna un diccionario, pero lo recorro y desempaqueto cada elemento de el en mi propia estructura de datos, para despues usar el elemento que me entrego, mi duda esta en que solo uso este diccionario para recorrerlo, con un for y dentro de este for es donde paso cada elemento de el a mi propia estructura (creo que ahi quedo mas claro) , ¿esta correcto aquel uso?

**Comment by lily416** [comment]
Es correcto si lo recorres y desempacas el diccionario dentro del `__init__` de tu estructura de datos.

Saludos ⚡️

**Comment by arbiocanpion** [comment]
Sigo sin resolver mi duda, en mi caso 
```python
reader = DictReader(linea)
 for x in reader:
                for atributo in x.items():
                    ##creo mi estructura de datos, y almaceno la informacion del diccionario
                    
```
¿Eso tambien estaria bien?

**Comment by lily416** [comment]
Es válido lo que estás haciendo siempre y cuando:

1. Una vez obtenidos los datos los guardes altiro en tu estructura de datos,
1. No los uses en otras operaciones antes de guardarlos en la estructura, y
1. El desempaquetado de los datos se haga dentro del `__init__` de la estructura.

Saludos 💡

**Comment by lily416** [comment]
@LucianoAguileraG  Para que lo propones esté correcto, debes entregarle `x` a tu estructura de datos y dentro de la estructura se debe realizar el `for atributo in x.items()`.

Éxito con la tarea 🏡

**Comment by Marialuisaclaro** [comment]
Y puedo en vez de hacer x.items() trabajar con x['id'], x['nombre'] etc?

**Comment by lily416** [comment]
@Marialuisaclaro No, la idea es que eviten utilizar las estructura de datos que no han creado, por lo que al obtener los elementos por medio de sus keys estarías usando la estructura de datos. 

El único caso en el que podrías hacer algo parecido sería:
```Python 
for i in dict:
   atributo = dict[i]
   # Lo agregas a tu estructura de datos
```
Pero eso es practicamente lo mismo que usar `.items()`, ya que te retorna una tupla en la que el primer valor es la key y el segundo el value.

Saludos 🔌👋
