### ISSUE TITLE
Duda desempaquetar listas  

### ISSUE THREAD

**Issue by rsnegrin** [IIC2233/syllabus-2018-2#564]
Hola, cuando yo abro los archivos hago un split(",") para desempaquetarlos en listas. Según la issue #549 no puedo usar estas listas hasta no transformarlas en mi propia estructura de datos. ¿Puedo aplicarle una función a estas listas para transformarlas en mi propia estructura? 
Por ejemplo:
"función_creadora_de_estructura(lista):"

**Comment by lily416** [comment]
El desempaquetado de la lista a tu estructura de datos se debe realizar en el `__init__` de tu estructura, es decir, debe poder recibir la lista como variable y guardarla en la estructura.

Nótese que con guardarla en la estructura me refiero a:
```Python 
def TuEstructura:
   def __init__(self, *args):
      ...
      for i in args:
         # agregar a la estructura
      ...
``` 
y no a:
```Python 
def TuEstructura:
   def __init__(self, *args):
      ...
      lista = args
      ...
``` 

Saludos y éxito con la tarea ⚡️

**Comment by hbkim94** [comment]
Hola! El desempaquetado tiene que ser **estrictamente** en el `__init__` de la estructura? 

Gracias!

**Comment by bgsamilla** [comment]
Sumandone a la pregunta, puede ser al menos que el __init__ llame a un metodo dentro de la clase que desempaquete?

**Comment by lily416** [comment]
@hbkim94 Sí, en el caso de que lo hagas fuera del `__init__` puedes llegar a ser penalizado por ello.
@BSamilla Sí

**Comment by dlcartagena** [comment]
@lily416 En la issue #518 dice que nuestra estructura tiene que recibir la lista desempaquetada, es necesario que sea desempaquetada o puede recibirla como en el ejemplo que pusiste? 

pd: lo hice como dijiste y ahora me entró la duda.

**Comment by lily416** [comment]
@dlcartagena no, debes hacerlo como sale en la issue #518.  Lo siento por el error, altiro corregire el ejemplo.
