### ISSUE TITLE
Agregar o Eliminar Arista

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#565]
Hola! Cuando yo quiero agregar una arista, si lo hiciera como una función, me darán los "ids" los tipos que son ejemplo "casa" y "casa" (Ejemplo de  una arista entre dos casas) y su distancia?
En otras palabras puede ser una función:

def agregar(id_1 id_2, tipo_1, tipo_2, distancia)

Muchas Gracias!

**Comment by ptflores1** [comment]
Hola !
Debes pedir la información que sea necesaria para la conexión al usuario, esto depende de como lo implementes
Saludos !
