### ISSUE TITLE
commit no aparece en github

### ISSUE THREAD

**Issue by johntrombon** [IIC2233/syllabus-2018-2#566]
Hola, hoy hice un commit y un push y salió el mensaje de que funcionó, reviso en github y no aparecen los nuevos archivps.
cloné de nuevo mi repo en otra carpeta, y si se clonaron los archivos que habia pusheado anteriormente pero siguen sin aparecer en github 😰.
Lo que creo que puede ser es que antes de esto, puse "git reset HEAD *" para descartar los cambios que habia hecho en un add anterior, salvo eso no creo haber hecho nada fuera de lo normal. Ayuda por favor :(, aún tengo los mensajes de la consola

**Comment by FJavierOss** [comment]
Como solución parche podrias cortar los archivos afectados, pegarlos en otro lado de tu computador, haces git add, git commit y push. Luego vuelve a meter los archivos afectados a tu carpeta del repositorio, y haz git add, git commit y push. La lógica es decirle a github que se borraron los archivos, github dirá que no existen y lo sacara del repositorio web. Luego al volver a meter los archivos en el local github lo va a detectar y va decir que existen nuevos archivos, por tanto al hacer el nuevo proceso de add, commit  y push el repositorio web lo considerará como nuevos archivos y los subira con los cambios realizados. Es una forma poco ortodoxa pero deberia funcionar.

Saludos

**Comment by johntrombon** [comment]
Gracias, al final sólo había hecho el push mas o menos al mismo tiempo que se cayó github ayer, todo está donde debería estar 👍🏻
