### ISSUE TITLE
Agregar nodo y estaciones elevadoras

### ISSUE THREAD

**Issue by stmorales** [IIC2233/syllabus-2018-2#567]
Hola, al agregar un nodo este debe conectarse inmediatamente? O se debe agregar y luego agregar una arista?

Además, hay algunas partes del enunciado en que dicen que sólo hay una central elevadora por sistema pero en otras partes dice que pueden haber 1 o más. Les agradecería con qué nos quedamos.

Gracias

**Comment by IchottMano** [comment]
Hola!

Cuando agregas un nodo este no esta conectado hasta que le agregas una arista con la función correspondiente.
Lo de las estaciones elevadoras ya fue respondido en otra issue.

Saludos!

**Comment by BFFV** [comment]
Hola, tengo un par de dudas con respecto a la issue de las elevadoras:
1) No me quedó claro si lo que se ignora es el ejemplo de la excepción ForbiddenAction (es decir SÍ pueden haber más de una elevadora por sistema), o se ignora la sección de agregar nodos de estación elevadora completamente (es decir NO puede haber más de una).
2) Según la otra issue no puede NO haber ninguna elevadora en un sistema, pero en el enunciado se indica el caso en el que no hay ninguna (se pierde la energía de las centrales). ¿Entonces es requisito que nunca falte 1?

**Comment by miguelramirezv** [comment]
Hola! Aprovechando el nombre de la issue pregunto aquí. La acción agregar nodos puede agregar cualquier tipo de nodo (central, elevadora, transmisora, distribuidora o casa), no solo los ejemplos que salen el enunciado (central, elevadora y casa). Estoy bien?

**Comment by IchottMano** [comment]
Hola!

@BFFV Se ignora el ejemplo y puede no haber ninguna elevadora.

@miguelramirezv Si, se puede agregar cualquier tipo de nodo, siempre y cuando sea legal hacerlo.

Saludos!

**Comment by Marialuisaclaro** [comment]
Hola!
Si al agregarse un nodo no se conecta automáticamente ¿Como se calcularía si se genera sobre carga eléctrica si no está conectado con nadie?

**Comment by IchottMano** [comment]
@Marialuisaclaro Hola!

Si no está conectado con nadie, no hay manera que le llegue corriente, por lo que es imposible que exista sobrecarga en ese nodo.

Saludos!
