### ISSUE TITLE
Consulta potencia perdida en transmisión

### ISSUE THREAD

**Issue by mvgil** [IIC2233/syllabus-2018-2#568]
Hola!
En el enunciado sale que la potencia perdida en transmisión se calcula con el consumo efectivo del nodo (con lo que efectivamente le llega al nodo). Entonces, si la red tiene exceso de oferta, para calcular la potencia perdida en transmisión usamos el valor total de la potencia que le llega al nodo? o la potencia demandada(que como hay exceso de oferta, la demanda está cubierta )?. 
Si se usa la potencia total que le llega al nodo, cuando haya exceso de oferta, la pérdida de transmisión será mayor. Eso es así?
Gracias !

**Comment by ptflores1** [comment]
Hola !
Cuando hay exceso de oferta el excedente no entra a la red por lo que, lo que llegará a cada nodo sera lo que demande.
Saludos !

**Comment by cacoos** [comment]
Pero en ese caso no habría ElectricalOverload a menos que la demanda de la subestación sea mucho mas grande que la suma de las casas hijas. O no?

**Comment by cacoos** [comment]
No sé si estará correcto, pero me hace mucho mas sentido que la energía pase nomás hasta que haya una sobrecarga o bien, se satisfaga la demanda pero con un gap extra.
Me hace más sentido también pensar que en cada nodo podría haber un poco mas de energía que su demanda, las cuales igual se incluyen en la perdida hacia el traspaso a los hijos, como (creo) pasa en la vida real.
Saludos!
