### ISSUE TITLE
AC10, flechas del teclado

### ISSUE THREAD

**Issue by ghost** [IIC2233/syllabus-2018-2#569]
Hola, deberán haber descuentos en la corrección si es que se usan las teclas WASD en vez de las flechas del teclado para mover al personaje?

Gracias de antemano.

**Comment by bimartinez** [comment]
Hola!

Lamentablemente las instrucciones decían explícitamente  cuales eran las teclas a ocupar para el movimiento del personaje (en este caso las flechas) así que el puntaje asignado en esta ocasión es 0.

Saludos!

**Comment by jncaceres** [comment]
Pero en el momento de realizar la actividad, yo le pregunte a un ayudante si es que se podian usar esas teclas, y dijo que no habia problema :/, igual deberian ponerse de acuerdo para ese tipo de cosas

**Comment by entamburini** [comment]
Lamentamos eso :disappointed:.  Trataremos de corregirlo para que deje de pasar, pero el enunciado era muy claro en ese aspecto de la actividad.

**Comment by jncaceres** [comment]
Si, era claro y no se puede negar, pero tampoco es la idea que los ayudantes de informacion erronea en cuanto a la instruccion.
Muchas gracias por responder y ojala que no vuelva a pasar algo asi :)
