### ISSUE TITLE
Parte 6 de encriptación

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#57]
Hola!

Quiero saber si entiendo bien esta parte del enunciado.

- **Parte 6a**. Acá solamente se está enunciando que hay que aplicar el paso 2 sobre el mensaje ya encriptado por el _Cifrado César_, es decir, transformar cada carácter a _código ASCII_ y eso transformarlo a un número binario de 8 bits.

- **Parte 6b**. Acá nos están diciendo que apliquemos el mismo paso 2 sobre la _lista de números (final)_ que creamos en la **parte 5** de encriptación. El problema es que en el diagrama que le sigue a las instrucciones de la **parte 6** se ve como la _lista de números en binario_ es una transformación directa de la _lista de números (final)_ a números en binario de 8 bits. Es decir, que nunca se hizo el paso de transformarlos a _código ASCII_. Si se hubiese transformado a _código ASCII_ el '1' no iría a caer a '00000001', sino que iría a '00110001', pues ese esa es la representación en binario del _código ASCII_ del carácter '1'.

Gracias,
Ariel

**Comment by lily416** [comment]
Hola, 

La cadena concatenada que se genera en el paso 6b viene de la transformación binaria de 8 dígitos de cada uno de los elementos de la lista obtenida en el paso 5, no de la transformación a binario del orden ASCII de esos elementos. Es decir, hay que transformar la lista de números como se ve en el ejemplo.

Ojalá que con esto quede claro,
Disculpa por la tardanza 🙇
