### ISSUE TITLE
Dudas sobre agregar, remover aristas

### ISSUE THREAD

**Issue by jaromero6** [IIC2233/syllabus-2018-2#571]
Hola, tenía una duda respecto a las funciones que agregan y quitan aristas y nodos. En el feedback de la tarea se da a entender que tanto para agregar como para remover aristas se debe poder hacer de dos formas : Una que genere el cambio en la red (de forma real) y la otra es que no genere el cambio,.
Mii duda es respecto a esta última ¿Que hay que hace al agregar/remover aristas de forma NO real, mostrarle al usuario como quedaría la red con la modificación (mostrar la nueva demanda total que quedaria  por ejemplo) o simplemente comprobar que se puede hacer la modificación solocitada,  y en caso de que se pueda preguntarle al usuario si la desea hacer?

**Comment by ariel-m-s** [comment]
cps

**Comment by joaquinhernandezg** [comment]
wardiola

**Comment by Hernan4444** [comment]
Evitemos los "cps" o "wardiola", suscribanse a las notificaciones de una issue si les interesa. Si les interesa el repo hagan watch (arriba a la derecha):

![image](https://cloud.githubusercontent.com/assets/10425834/14770701/2608a1c2-0a4e-11e6-8378-c58953883176.png)

Tanto en Facebook como aquí, en Github, existen sistemas para evitar las respuestas que no aportan a la discusión y que son solo para marcar seguimiento. Los invitamos a usar Github correctamente :grin:  

ps: Los ayudantes están trajando en responder esta issue.

**Comment by jmndoza** [comment]
Creo que quedo en el olvido, con o sin 'cps' o 'wardiola'

:(
