### ISSUE TITLE
Uso de generadores

### ISSUE THREAD

**Issue by dlcartagena** [IIC2233/syllabus-2018-2#572]
No me queda claro el tema de los generadores. Se dijo en la issue #512  que solo se pueden usar generadores creados por nosotros. Sin embargo está permitida la librería csv. Puedo usar reader e iterarlo?

**Comment by FernandoPieressa** [comment]
Hola!

No exactamente como dices, para poder usar reader tienes que manejarlo tal como sale en #518

Saludos!

**Comment by dlcartagena** [comment]
Sería legal que hiciera esto?

```python
with open('bd/small/casas_casas.csv', newline='') as archivo:
    conexiones_reader = reader(archivo_conexiones)
    next(conexiones_reader) #Este next es para no utilizar la primera línea del archivo csv
    for linea in conexiones_reader:
        lista_legal = MiLista(linea)
````
Después trabajaría con mi propia estructura.
