### ISSUE TITLE
Problema con repr/str de mi lista ligada

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#574]
Hola todos, 

estoy teniendo un problema con mi lista ligada al momento de intentar de imprimir su contenido. 

Esto solo me pasa cuando son listas dentro de mis arboles. 
Ademas si hago len de estas mismas listas me entrega la cantidad correcta. Incluso si itero sobre esta lista y hago prints individuales funciona. 

Por el contrario, cuando creo una lista afuera y la imprimo se imprime sin problema. Como deberia. 

Y tampoco es un problema del arbol, pporque cuando remplazo mi_lista por list si funciona como espero. Espero que alguien sepa cual puede que sea el problema. No es un problema mayor, pero tengo miedo de que esto luego jhaga aparecer otros errores inesperados. 

Imagen de ejemplo:
![image](https://user-images.githubusercontent.com/10112117/47327743-d71e2f80-d644-11e8-8180-1f1f236203e3.png)

Gracias 

(mi lista ligada la llamé list, para asi asegurarme de que no pueda accidentalmente usar la estrucutura prohibida)

**Comment by fringlesinthestreet** [comment]
Hola @Kitaps

Por casualidad estás utilizando el _dunder method_ `__str__`? Si es así, intenta utilizar el `__repr__` y me cuentas cómo te va :smile:.

**Comment by fgbruna** [comment]
No me queda claro, si haces una lista fuera de tu código de la sgte forma:
```python
l = TuLista(*args)
print(l)
```
Se imprime bien?

P.S: Le eché un ojo a tu código y estás usando la clase `str` sobre `self` donde self es una de tus listas, siendo que no tienes definido el metodo `str` para ellas, si no que solo defines `repr`.<sup>de hecho usas `str` dentro de él :o</sup>

**Comment by Kitaps** [comment]
Hola , muchas gracias por la pronta respuesta y por darte el trabajo de mirar mi codigo. 

Respecto a tu pregunta, si, imprime bien, porlomenos cuando hago:
`lista_poblada = list("a", "b", 1, "asd")`
 `print(lista_poblada)`

Respecto a tu PS: te refieres al overwrite del metodo __repr__ ? 
En ese metodo el metodo itera sobre self para hacerle str al valor de cada nodo, y luego unirlo todo por un join. 
`str` por lo tanto se ejecuta sobre los valores de los nodos, no sobre la lista. Igual, cambiando eso sigue pasando lo mismo.

Que más podria ser?

**Comment by Kitaps** [comment]
El problema era iterando:
Tenía definido el init con:
```
self.head = None
self.tail = None
self.iter= self.head

```
pensando que cuando entonces hacía `append `y `head `adquiria un valor, `self.iter` iría a ese mismo valor, pero este se quedo en `None`, 
Luego la primera vez que trataba de iterar no iteraba, pero las otras si, porque al hacer `StopIteration ` hacía a `self.iter = self.head` (que ahora si tenía valor). 

Denuevo muchas gracias por la ayuda
