### ISSUE TITLE
Elevadoras

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#575]
Hola, tengo un par de dudas con respecto a la issue de las elevadoras (#539 ):

1) No me quedó claro si lo que se ignora es el ejemplo de la excepción ForbiddenAction (es decir SÍ pueden haber más de una elevadora por sistema), o se ignora la sección de agregar nodos de estación elevadora completamente (es decir NO puede haber más de una).
2) Según la otra issue no puede NO haber ninguna elevadora en un sistema, pero en el enunciado se indica el caso en el que no hay ninguna (se pierde la energía de las centrales). ¿Entonces es requisito que nunca falte 1?

**Comment by ptflores1** [comment]
Hola !
Puede haber cualquier cantidad de estaciones elevadoras. Lo que se ignora es lo que aparece en el ejemplo de  `ForbiddenAction`. Si no hay estaciones elevadoras, la energía se pierde.
Perdón por la confusión.
Saludos !

**Comment by BFFV** [comment]
Gracias!

**Comment by gnacrur** [comment]
@ptflores1 no entiendo porque podría haber más de una elevadora siendo que el enunciado dice que no se puede. Personalmente use como punto de partida para recorrer el sistema la Estacion elevadora solo porque esta se suponía que era única. Ojala puedan aclarar esto y ojala no perder el avance que llevo hasta ahora.

**Comment by joaquinhernandezg** [comment]
cps

**Comment by stmorales** [comment]
Al no haber estación elevadora no debería ser la demanda 0?? Porque al desconectar una entidad se desconecta de la red todo lo que tiene abajo. No se perdería energía, si no que no se generaría no más. Por favor explicar bien este punto, han habido demasiadas dudas con respecto a esto.

**Comment by Hernan4444** [comment]
Evitemos los "cps" o "wardiola", suscribanse a las notificaciones de una issue si les interesa. Si les interesa el repo hagan watch (arriba a la derecha):

![image](https://cloud.githubusercontent.com/assets/10425834/14770701/2608a1c2-0a4e-11e6-8378-c58953883176.png)

Tanto en Facebook como aquí, en Github, existen sistemas para evitar las respuestas que no aportan a la discusión y que son solo para marcar seguimiento. Los invitamos a usar Github correctamente :grin:  

ps: Los ayudantes están trajando en responder esta issue.

**Comment by ptflores1** [comment]
@gnacrur trabajalo así y no te olvides de aclararlo en tu readme

**Comment by ptflores1** [comment]
@stmorales si se desconectaría toda la red, no entiendo cual es el problema con que se pierda la energía, en la practica es lo mismo que no haya demanda.
