### ISSUE TITLE
Desempaquetar Reader

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#576]
Como el reader del módulo csv es un generador de listas, ¿Se pueden desempaquetar y guardar de esta manera?
```python
    for línea in reader(archivo):
            lista = Mi_lista(*línea)
```

**Comment by lily416** [comment]
Tu duda se responde con lo que sale en la issue #518 .

Saludos 👋⚡️

**Comment by BFFV** [comment]
Mi duda era más que nada si se podía usar ese for para así obtener la lista prohibida y desempaquetarla (ya  que reader no devuelve directamente la lista, sino un generador de ellas). ¿Viendo la issue #518 entonces asumo que está bien hacer eso?

**Comment by lily416** [comment]
Ya que el `reader` retorna una estructura prohibida, debes entregárselo a una estructura válida (digamos `Tu_lista`) en vez de iterar sobre el generador. 

Por lo que sería más correcto que hicieras: 
```Python
def Tu_lista:
   def __init__(self, *args):
      ...
      for linea in args:
         lista = Mi_lista(*linea)
      ...

Tu_lista(*reader(archivo))
```

Ojalá quede todo claro, saludos 💡

**Comment by BFFV** [comment]
Gracias!

**Comment by Benjadef** [comment]
Hola!! esto sería legal ??, 

        with open ("path", "r") as file:
            iter = Iterable(*csv.reader(file))
            for line in iter:
                funcion(*line)

siendo Iterable una estructura creada por mi

me gustaría saber, para cambiarlo, si esque esta prohibido, fue la mejor solución que encontré, el tema es que al parecer al desempaquetar un csv.reader, se desempaqueta en listas, pero luego esas listas las desempaqueto, nunca trabajo con ellas
gracias!

**Comment by lily416** [comment]
@Benjadef Sí, es legal 😊
