### ISSUE TITLE
Lista por comprensión

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2233/syllabus-2018-2#578]
Hola, ¿es legal hacer esto?:
`mi_lista(x for x in mi_otra_lista)`,
donde `mi_lista` y `mi_otra_lista`, serían objetos de la clase lista que implementé.

**Comment by FJavierOss** [comment]
Estimado,

Es legal, siempre y cuando sean listas creadas por ti en todo momento. Que en este caso pareciera que si. Suerte en tu tarea :smile: 

Saludos
