### ISSUE TITLE
Agregar nodos sin aristas

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#579]
Hola!
Se pueden agregar nodos sin estar conectados con otro nodo?
En la issue #567 se especifica que se agrega un nodo y luego las aristas correspondientes, pero me hace mas sentido pedir padres/hijos para el nodo a agregar y si no ingresa, entonces no se puede agregar el nodo.

Saludos!

**Comment by agustinkrebs** [comment]
Hola!

Si te es más fácil hacerlo así, no hay problema. Explicítalo en tu readme.

Saludos!

P.D: Sorry por la demora, ha sido una semana difícil para todos los ayudantes

**Comment by cacoos** [comment]
Muchas gracias!
