### ISSUE TITLE
No puedo crear un archivo con relative path

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#58]
Cuando intento crear un archivo de la forma:
```
with open("datos/archivo.csv", 'w') as archivo:
    archivo.write("algo")
```
Me tira el error: 
`FileNotFoundError: [Errno 2] No such file or directory: 'datos/usuarios.txt'`

Estoy usando atom, y todos los archivos y las carpetas (datos y data) están en la misma carpeta T00. ¿Tal vez es un problema con el package `atom-python-run` que uso para correr mi código?

**Comment by Arcoirisky** [comment]
¿estás seguro que tienes en la carpeta "datos" el archivo "usuarios.txt" ? El error parece ser más por ese archivo que por intentar escribir algo :s

**Comment by Fenho** [comment]
No está el archivo, ¿pero no se supone que debería crearlo si estoy usando 'w' o 'a'?

**Comment by entamburini** [comment]
Hola!

Puedes probar desde el terminal para así ver si es problema del plugin de Atom :)
La única forma en que veo que no podría funcionar eso es que la carpeta no exista (en esos casos te daría otro error) así que te recomiendo que pruebes con el terminal :D 

Avísanos qué onda :)

**Comment by bimartinez** [comment]
Hola @Fenho!

Ojo 👀 que el archivo 📄 que tu estas escribiendo es `"archivo.csv"` y el error habla de un archivo `"usuarios.txt"`. Revisa por ahí si antes o después en tu código haces referencia a este último.

Saludos!

**Comment by Arcoirisky** [comment]
pd: Cuidado que, si no me equivoco, no puedes crear archivos con 'a', sólo agregar información.

**Comment by Fenho** [comment]
@bimartinez el problema es con .csv y .txt
@entamburini Desde el terminal funciona por alguna razón.
Por lo menos ahora tengo una forma de correr el código, gracias!
