### ISSUE TITLE
Consultas Energia total consumida

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#581]
Buenas, cuando se refieren al consumo de energia de cada consumidor se considera el caso de la perdida de energia cuando existe conexion entre las casas, a lo que voy es que si tengo una casa A de la cual se desprende una conexion a B, debo considerar el consumo individual de cada casa, o considero la potencia de B solamente (que contendra el consumo de A, B y la perdida)

**Comment by agustinkrebs** [comment]
Hola!

¿Bajo qué contexto haces esta pregunta (una consulta, una fórmula del enunciado, etc)?

Saludos!

**Comment by SergioZarateG** [comment]
Tengo la misma duda. Es referente a la Consulta: Energía total consumida.

**Comment by agustinkrebs** [comment]
Ocupando el ejemplo de arriba de @NicolasCabello, debes considerar la potencia de B solamente (que contendrá el consumo de A, B y la pérdida)

Saludos

**Comment by NicolasCabello** [comment]
Ya buenaa, muchas graacias 🙌
