### ISSUE TITLE
agregar conexiones

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#582]
Hola, quería saber cual sería el formato de agergar una conexion en el sentido de si debemos pedir los id y tipo de entidades a conectar a través de interacción por consola o debemos simplemente hacer una función que agrega aristas dado dos nodos y que el ayudante al corregir use nuestra función de la forma que este implementada.

**Comment by nachocontreras** [comment]
Hola!

Se tienen que pedir los ids. 
Por ejemplo, quiero conectar el nodo 13 con el nodo 15. No se puede decir de que tipo son los nodos. 
Si el nodo 13 es una casa y el nodo 15 es una generadora, este debería lanzar error.

**Comment by gnacrur** [comment]
@nachocontreras Esto no funcionaría porque los id son unicos solo por tipo de entidad. Existe la casa con id 0 y tambien la generadora con id 0, por ejemplo.

**Comment by alexaptib** [comment]
@nachocontreras Tengo la misma duda, eso es solo posible si los ids son unicos en la totalidad de la base de datos, pero son unicos solo en casa archivo individual.

**Comment by nachocontreras** [comment]
Entonces se debe indicar, además, el tipo de nodo a agregar.
