### ISSUE TITLE
Duda uso funciones built in

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#584]
Hola! Tengo las siguientes dudas:

1. Es válido lo siguiente: `if list(filter(funcion, MI ITERABLE)): print('holo')`. 
2. Es válido, `for i, j in enumerate(MI LISTA): print(i, j)`
3. En general, ¿se pueden usar funciones como map o filter que retornan generadores siempre y cuando se usen según lo que aparece en #518 ?
4. En general, ¿puedo usar cualquier función que retorne una estructura prohibida, pero no la guarde en una variable?

Gracias!
Saludos

**Comment by inveterate-cladocerus** [comment]
up

**Comment by ptflores1** [comment]
Hola !
Perdón por la demora.

1. No, estas usando las listas de `python`.
2. Si, siempre y cuando uses el `enumerate` sobre la **lista que creaste tu**.
3. Puedes usar `map` o `filter` solo sobre **tus propias estructuras**.
4. No.

Saludos !
