### ISSUE TITLE
conexión entre casas y distribuidoras

### ISSUE THREAD

**Issue by MMeisters** [IIC2233/syllabus-2018-2#585]
al crear una nueva conexión, debería ser posible conectar una casa con 2 distribuidoras de manera directa? de ser no la respuesta, se puede conectar una casa a 2 distribuidoras de manera indirecta? (teniendo que subir 2 o mas niveles en el grafo para poder llegar a la distribuidora).

**Comment by ptflores1** [comment]
Hola !
Mientras las dos distribuidoras y la casa estén en la misma comuna si es posible
Saludos !
