### ISSUE TITLE
Nuevas conexiones

### ISSUE THREAD

**Issue by MMeisters** [IIC2233/syllabus-2018-2#586]
En la interacción con el usuario no dice nada sobre crear nuevas conexiones, lo que implica que una nueva conexión solo puede ser entre una entidad recién creada y otra preexistente o también debemos preguntarle al usuario si quiere crear una conexión entre dos entidades preexistentes?

**Comment by IchottMano** [comment]
Hola!
Efectivamente se deben poder crear conexiones entre entidades ya existentes.
Saludos!
