### ISSUE TITLE
Clase "mi_lista" estaría permitida?

### ISSUE THREAD

**Issue by acpopper** [IIC2233/syllabus-2018-2#587]
Duda, creé una clase "mi_lista" (que es una lista ligada), la cual funciona idénticamente a como lo haría una lista (a excepción que los valores de cada casilla son los valores de cada nodo almacenado dentro de ésta), o por lo menos los métodos de interés, esto es: es iterable, se puede buscar/obtener un valor referenciando su posicion (ej: milista[3]) y se puede usar el método append. Todo sin usar listas "built-in", y sobreescribiendo los métodos getitem, etc (por lo dicho en la issue #573). 
Mi duda es: puedo usar esta clase?
Saludos

**Comment by lily416** [comment]
Si, mientras los métodos los hayas implementado tu y no los herede de una estructura prohibida, debería estar bien.

Saludos 👋💡
