### ISSUE TITLE
Strings con tilde en la base de datos

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#588]
¿Es necesario preocuparse por los tildes de los strings en las bases de datos? (el csv reader no es capaz de decodificarlos y se ven raros). ¿Cómo se debe proceder si es que se hace alguna consulta con un string con tilde que estaba en la base de datos, o esto no ocurrirá?

**Comment by agustinkrebs** [comment]
Hola!

Estás segur@ que no se puede? En esta documentación sale que sí (https://docs.python.org/3/library/csv.html).
Avísame si te sirve.

Saludos!
P.D: Sorry la demora!

**Comment by BFFV** [comment]
Al menos la distribuidora de id 222 tiene nombre con tilde y queda como CERRO DRAGâÃ´N en vez de CERRO DRAGÓN. No he encontrado otro tilde entre los nombres. ¿Se asume que en las consultas no se ingresarán strings que podrían contener tilde y causar inconsistencias?

pd: Probé con varios encoding (utf-8, utf-8-sig, latin1, etc...) y en los que no eran utf-8 o utf-8-sig se ve aún peor.

**Comment by agustinkrebs** [comment]
Mmm qué raro.. Igual de todas formas, no es algo que se busca evaluar en esta tarea, así que puedes obviarlo.

Por favor déjalo explícito en tu readme para que el ayudante corrector esté al tanto.

Saludos!

**Comment by BFFV** [comment]
Gracias!
