### ISSUE TITLE
Responder mensajes

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#59]
¿Es necesario añadir la opción para responder mensajes? pregunto porque se nos pide dar la opción de leer el mensaje pero una vez se este leyendo, no hay mas opción que retroceder, cerrar o escribir otro mensaje.

**Comment by IchottMano** [comment]
@PPDZ Hola!

Como no es pedido en el enunciado, no es necesario añadir una opción para responder los mensajes.

Saludos!
