### ISSUE TITLE
Importancia de demora de carga

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#590]
Hola!

Mi programa demora a lo más 40 segundos en abrir y cargar la base de datos _large_ **sin** ordenar la base de datos. Ya que tengo que meter todo a `MiLista` y luego ordenarla, ordenar por columnas es más que trabajo doble, demorándose mucho más.

Es realmente importante que ordenemos las bases de datos?
Saludos

**Comment by agustinkrebs** [comment]
Hola!

Lamentablemente sí es necesario el orden para que así se pueda trabajar correctamente. Si llegas a no poder lograrlo en un tiempo "decente" (un par de minutos), ponlo en tu readme para que el ayudante que corrija lo considere. 

Saludos!

**Comment by Coolgatty** [comment]
> Hola!
> 
> Lamentablemente sí es necesario el orden para que así se pueda trabajar correctamente. Si llegas a no poder lograrlo en un tiempo "decente" (un par de minutos), ponlo en tu readme para que el ayudante que corrija lo considere.
> 
> Saludos!

Con esto se refiere a que podrían haber mas bases de datos ademas de las dadas "small" y "large" ?
No entiendo por que es necesario ordenar
