### ISSUE TITLE
Peer Review AC10

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#591]
Hola!!! Una duda, en el formulario en la parte de creación de cherries, si una persona las hizo pero no las almacena en ningún lado... que puntaje debería poner?? 

Y otra duda, es valido descontar puntos de la parte de modelacion de front end si la persona no implementó cherries? O si las guardó en una variable, pero solo de front end, si no realizó el bonus ? En general, tengo dudas con el tema de las cherries y en donde aplicar o bajar puntos en el formulario 

gracias!!! :cat:

**Comment by fringlesinthestreet** [comment]
Hola @gatochico 

Disculpa la demora! Con respecto al almacenamiento, no guardar las referencias a tus objetos es **muy** mala práctica ⚠️ , ya que complica bastante a la implementación si se desea alterar el estado de esos objetos (como hacer desaparecer a las guindas, o mover al personaje).

Sin embargo, esto **no era evaluado en la actividad** 🎉 . Sólo si realizaban el bonus era necesario guardar la referencia para después poder borrarlas.

---

La parte de puntaje de _frontend_ busca otorgar puntaje por la separación de la lógica y la presentación de su ~~mini~~ aplicación. Está bien sólo guardar la referencia al _label_ en el _frontend_. 

Si realizaron bonus, existe una lógica de colisión de las entidades. Por lo tanto, era necesario tener referencia de guindas (objetos) en el _backend_ para verificar las colisiones. Esto no quita el hecho de que en el _frontend_ se deba seguir teniendo referencia a los _labels_ que representan a esas guindas.

En conclusión, los puntajes del _frontend_ y _backend_ evalúan la correcta separación de las responsabilidades. Si no implementó algo pero el resto está OK, tiene puntaje completo :smile:.

**Comment by marcotroncoso** [comment]
hola!! tengo una duda en relacion con las cherries. Esque la persona hizo todo bien, pero solo le falto mostrarlo con show(), entonces no aparecen las cherries. Deberia colocar 0 ptos?

**Comment by fringlesinthestreet** [comment]
Hola @marcotroncoso 

Si tiene todo el resto bien, se debería asignar mitad de puntaje :smile:, ya que es un error pero tiene gran parte del requerimiento bien implementado.
