### ISSUE TITLE
Potencia máxima de las casas

### ISSUE THREAD

**Issue by jaromero6** [IIC2233/syllabus-2018-2#592]
Hola, respecto a la potencia máxima de las casas a 30.000 kW, se me generan sobrecargas eléctricas en la  base de datos. Por ejemplo en la base de datos small, la casa de id 1538 demanda en total aproximadamente 34.000 kW y le llegan 33.000 kW aprox lo que genera ElectricalOverload. ¿A alguien más le pasa esto? De ser así ¿qué deberíamos hacer?

**Comment by ptflores1** [comment]
Hola !
Acabo de subir una nueva base de datos, avisame si con esa siguen teniendo problemas
Saludos !
