### ISSUE TITLE
consulta consumo de casas y subestación_distribución comuna

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#594]
Hola, no entiendo para que sirve el id de la subestación de distribución para la consulta ` Energía total consumida en una comuna` dado que dijieron en otra issue (#550) que se consideran todas las casas y todas las subestaciones de distribución de la comuna. Por lo tanto, no necesito el id de la subestación. Quería verificar que estoy en lo correcto para así no esperar que prueben que mi programa levante un error si se le entrega un id de subestación que no existe (ya que en mi caso no uso el id).

**Comment by ptflores1** [comment]
Hola!
La consulta pedía el `id` porque se escribió pensando en que solo habría una sola subestación de distribución por comuna pero en realidad pueden haber más distribuidoras. Está bien que no pidas el `id`.
Saludos !
