### ISSUE TITLE
Cliente con mayor y menor consumo

### ISSUE THREAD

**Issue by stmorales** [IIC2233/syllabus-2018-2#595]
Hola en las consultas sobre los clientes con mayor y menor consumo se dice que debemos entregar el con mayor/menor **demanda**. Esta demanda se refiere a la que viene en la base de datos o a la energía consumida realmente?

Gracias

**Comment by agustinkrebs** [comment]
Hola!

Energía consumida realmente.

Saludos!

**Comment by stmorales** [comment]
Gracias!
