### ISSUE TITLE
Duda redondeo de energia electrica

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#596]
Hola !

mi duda es si hay algún problema con que mi programa al tomar los valores de consumo o potencia de energía el valor se redondee, ya que me he dado cuenta que mi programa lo hace automáticamente

por ejemplo: si la potencia de una estación generadora es de 57.619999999999997 MW, mi programa lo redondea a 57.62 MW

gracias de antemano

**Comment by agustinkrebs** [comment]
Hola!

No hay problema con el redondeo siempre y cuando se deje en una cantidad de decimales "decente" (2 a 3 quizás). Lo que importa es que los resultados "prácticos" no sean distintos por considerar menos decimales, por ej: que pase o no pase un ElectricalOverload.

Saludos!
