### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#598]
Si en la actividad el reconocimiento del nombre de usuario no funciona para nada (hay que cambiar un par de señales y unas líneas), pero al cambiarlo por lo correcto se abre bien el mapa y existe movimiento con sprites y todo lo que sigue, cómo asigno el puntaje? Se considera como "error de arrastre"?

Saludos!

**Comment by fringlesinthestreet** [comment]
Hola @cacosandon 

La idea es evitar en lo posible los errores de arrastre. Si la ventana de inicio no funciona para nada, la penalización de puntaje se hace sólo en esa sección. Luego, si la ventana del juego funciona perfectamente, el alumno merece el puntaje en esa sección 😄.

Espero haberte ayudado.

**Comment by cacoos** [comment]
Gracias por la respuesta!
El problema es que para que la ventana de juego se abra, debe funcionar la primera ventana.
Supongo que hizo el código a ciegas para el juego o bien, hizo la verificación de usuario al final, ya que funciona si yo arreglo la primera ventana.

La ventana del juego funciona perfectamente si cambio muchas líneas de código para que funcione **la primera ventana**. Mi pregunta es: ¿Cambio estas líneas y corrijo la segunda ventana?, o qué.

Gracias de nuevo!

**Comment by bgsamilla** [comment]
Tengo a alguien que tiene bien la primera ventana, pero la segunda solo carga el background y al pacman, nada mas.
Mi pregunta es puedo ponerle los 5 puntos por buen uso de backend, frontend y señales, si solo hizo funcionar la primera ventana bien?
Es que como hizo la mitad y en esa mitad están bien usados....... pero por otro lado es solo la mitad (o quizás menos en cuanto a complejidad)
Saludos

**Comment by fringlesinthestreet** [comment]
Hola @cacosandon 

Sí :), ¡siéntete en libertad de modificarlos para poder corregir el resto!

**Comment by fringlesinthestreet** [comment]
Hola @BSamilla 

Tienen todo el puntaje :smile:. Revisa la #591 😉.
