### ISSUE TITLE
Repartir Potencia de Centrales

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#599]
Si hay una central generadora alimentando a más de una elevadora, ¿entonces se puede asumir que la potencia máxima que le puede enviar a cada una se reparte equitativamente? ¿Queda esto al criterio de cada uno?

Ej: Si la central está conectada a 2 elevadoras, entonces puede darle hasta un máximo de (potencia_central/2) a cada una, como si fueran 2 centrales con la mitad de la capacidad.

**Comment by agustinkrebs** [comment]
Hola!

No puedes asumir eso, ya que si (por ejemplo) el grafo de una elevadora está consumiendo muy poco, pero el grafo de otra elevadora (conectada a la misma central que la anterior) consume muchísimo, no tiene sentido restringirle la potencia ya que sí hay energía disponible para entregarle. 

Saludos!

**Comment by BFFV** [comment]
¿Entonces puedo asumir que las centrales siempre generarán su máxima capacidad (potencia) y que si al distribuirlo proporcionalmente supera la demanda en alguna elevadora simplemente se pierde lo que sobra?

**Comment by agustinkrebs** [comment]
Debes asumir que las centrales siempre generarán lo justo para suplir la demanda, ni más ni menos. Hay que darle a cada elevadora lo que demanda su grafo, eso nomás. Si la suma de éstas demandas (considerando también los cables para llegar a ellas) supera la capacidad máxima, ahí comienzas a distribuir proporcionalmente a la demanda de cada elevadora, y luego para abajo se va perdiendo lo que cada nodo pide.

**Comment by BFFV** [comment]
¿En el segundo caso (demanda mayor a oferta), al distribuir proporcionalmente a la demanda de cada elevadora no importa que al hacerlo no se cumplan las demandas de algunas elevadoras que se podrían haber cumplido al no repartir proporcionalmente?

Ej: Una elevadora pide 99 MW y otra 1 MW, la central tiene una potencia de 10 MW. Al hacerlo proporcional se le darían 9.9 MW a la primera elevadora y 0.1 MW a la segunda. La energía se reparte de manera 'justa' pero no se satisface ninguna.

**Comment by agustinkrebs** [comment]
Nop, no importa. Si quieres puedes hacerlo (ya que esa parte queda a criterio de cada uno) y explicitarlo en tu readme.

Saludos!

**Comment by BFFV** [comment]
Gracias!
