### ISSUE TITLE
Receptores de mensaje

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#60]
Al momento de abrir un mensaje en la parte de: "Para: {nombre_del_que_recibe_el_mensaje}" ¿Es necesario poner todas las personas a las que se les envió el mensaje? ¿o solo el nombre del usuario que abrió el mensaje?

**Comment by agustinkrebs** [comment]
Hola!

En la página 4 del enunciado, sección 3.3, dice:

> Finalmente, si el usuario desea revisar un correo específico, este al seleccionarlo deberá desplegar toda la información en la consola.

Dado esto, tu programa debería tener la capacidad de mostrar toda la información, incluyendo los destinatarios. Por simplicidad, puedes mostrarlos todos y listo. Si quieres que se vea más ordenado y limpio, puedes tener la opción (por ej.) de "mostrar destinatarios", y ahí imprimirlos en consola, en vez de que aparezcan de inmediato al abrir el correo.

En definitiva, es decisión tuya **cómo** los muestras, pero el usuario tiene que tener la posibilidad de acceder a la información de alguna manera.

Saludos!
