### ISSUE TITLE
Remover nodos

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#600]
En el enunciado aparecen dos cosas

> Si se quita un nodo de elevación, la energía que le entregaban las centrales generadoras se desvía hacia
otra central elevadora. También **se elimina la conexión** con todos los nodos inferiores.

> Si es que el nodo hijo no tiene otro nodo padre más que el removido, entonces el nodo hijo **es removido también**.

Cuando elimino un nodo que tiene hijos, y estos hijos tienen un único padre que es el nodo que estoy eliminando, estos debieran desaparecer? o bien quedan como nodos "desconectados" que, posteriormente podría conectar?

**Comment by jeschuwirth** [comment]
como dice el enunciado, en la parte 4.3 quinto parrafo:
![image](https://user-images.githubusercontent.com/37160256/47532017-9c570a00-d885-11e8-8b10-3cc63e97991b.png)
por lo tanto son removidos al igual que al padre.

**Comment by cacoos** [comment]
Gracias!
Entonces de cierta forma se responde la issue #579 , dado que no pueden existir nodos sin algun tipo de arista?

**Comment by sopadeoliva** [comment]
No me quedó claro si esto aplica para la eliminación de cualquier nodo o solo los nodos consumidores (casas). Por ejemplo, si elimino la única elevadora de un sistema, se borrarían todos los nodos conectados hacia abajo de ella, quedando el sistema casi vacío? O solo sucede cuando son Casas?

**Comment by ptflores1** [comment]
@sopadeoliva Aplica para todos los nodos. Si, quedaría vacio.
