### ISSUE TITLE
Proporcionalidad al repartir Energía

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#601]
Según el enunciado la proporción de energía que se le entregará a los nodos hijos se saca con la energía que le piden para suplir su demanda, ¿Entonces si hay algún nodo de casa colgada que ya tiene su demanda suplida por otro nodo padre se le envía igual la misma proporción considerando la demanda de la casa colgada aunque esta se perderá? ¿O se debe enviar a los otros nodos hijos cuya demanda no está suplida solamente?

Ej: Una casa suple a 2 casas colgadas, la primera demanda 3 MW y ya los obtiene actualmente de otra casa, mientras que la segunda demanda 3 MW y nadie le está entregando aún. 
¿Entonces se le envía la mitad de la energía disponible en la casa padre a cada una de las colgadas (a pesar de que en una se perderá todo por exceso de oferta), o se le envía todo a la segunda casa colgada?

**Comment by agustinkrebs** [comment]
Hola!

Dependerá del caso.

Si la demanda de la red completa está por debajo de la oferta de las centrales, siempre se calculará de "abajo hacia arriba" (como el ejemplo del enunciado, distribuyendo equitativamente la demanda de las casas colgadas).

En caso contrario, se calcula de "arriba hacia abajo", y la energía máxima que podía ofrecer la central va perdiéndose hacia abajo hasta que eventualmente a algunas casas no le llegará nada :(. Piénsalo así. No es necesario aplicar algunas "medidas de optimización" como la que mencionas.

Saludos!

**Comment by BFFV** [comment]
¿Entonces simplemente no me preocupo de cuanto les falta a los nodos hijos para suplir su demanda y sólo divido proporcionalmente el flujo a entregar considerando las demandas totales de estos?

**Comment by cacoos** [comment]
@akrebs2 en el primer caso 

> Si la demanda de la red está completa por debajo de la oferta de las centrales

Igual debería calcular de arriba hacia abajo no? sería la única forma de detectar si existe `ElectricalOverload`

**Comment by agustinkrebs** [comment]
@BFFV sí (en el segundo caso)

@cacosandon por qué dices eso? Vas subiendo y calculando, y en cada nodo verificas. Si lo que se necesita ya es mayor al máximo de ese nodo, se levanta un ElectricalOverload.

**Comment by cacoos** [comment]
@akrebs2 Me refiero al caso en que alguna casa no tenga hijos y que, por ejemplo, demande 13 kW pero le llegan 35 kW porque sobra. En este caso existe `ElectricalOverload`, y depende de lo que ocurre más arriba del arbol

**Comment by agustinkrebs** [comment]
No entiendo el problema. Si la demanda es **menor** que la oferta, se parte de abajo calculando, por ende, no entiendo como le podrían "llegar" 35kw, si esa casa solo pidió 12kw (siempre se debe satisfacer la demanda exacta, ni más ni menos, no debería sobrar energía en este caso).
Quizás estoy entendiendo mal la duda jaja (perdón si es así).

**Comment by miguelramirezv** [comment]
Hola! Me sumo a la duda de proporcionalidad, en la página 8 del enunciado, en el segundo punto de la sección 3.2 nos explican como calcularla. Nos dicen con Mi,j , esto se refiere a la demanda del nodo más la pérdida de energía de ese nodo al padre, o simplemente se hace la proporcionalidad solo contando la demanda de ese nodo (obviamente con todas las demandas de sus hijos y pérdidas entremedio), pero sin la pérdida de ese nodo a su padre? 

Un ejemplo sería el siguiente:
Opción A) El nodo 1 tiene 2 hijos, el nodo 2 y el nodo 3, estos necesitan 20 mw y 40 mw de energía respectivamente para suplir su energía. Además, el nodo 2 siempre pierde 50% en el camino y el nodo 3 siempre pierde 75% en el camino, por lo que lo que realmente le debiera entregar el nodo 1 debiera ser 40 mw al nodo 2 y 160 mw al nodo 3. Sin embargo el nodo 1 tiene menos de 160 mw (ej: 60 mw). Se debiera sacar la proporcionalidad con:

Opción A) SOLO lo que necesitan los nodos (20 y 40)
Opción B) Lo que necesitan CON sus pérdidas (40 y 160)

Muchas gracias!!!!

**Comment by agustinkrebs** [comment]
Opcion B)
