### ISSUE TITLE
Potencias máximas y requeridas

### ISSUE THREAD

**Issue by baaldana** [IIC2233/syllabus-2018-2#602]
Hola, estoy en proceso de implementar el cálculo de potencias que requiere un nodo, haciéndose cargo de sus nodos hijos según corresponda (considerando a los otros padres de los hijos, etc.). Sin embargo, al calcularlo usando la base de datos ```large``` me encuentro con que lo que pueden entregar todas las centrales generadores y lo que requieren en total los elevadores tiene una gran diferencia. Está pensado que sea de esa forma (y si es así,  ¿cómo debo hacerme cargo?) , o es simplemente un error en mis cálculos?

Muchas gracias!

**Comment by ptflores1** [comment]
Hola !
Las base de datos están hechas de manera tal que la cantidad de energía generada sea menor a la consumida por la red, para manejar este caso debes hacer lo que se indica en la sección 3.2 del enunciado.
Saludos !
