### ISSUE TITLE
Conexiones de las casas

### ISSUE THREAD

**Issue by jaromero6** [IIC2233/syllabus-2018-2#604]
Hola, me surge una duda al momento de recorrer el grafo especifcamente las casas. Si una casa de "primer nivel" por así decirlo es la que está conectada a directamente a una distribución y una de "segundo nivel" es una que está colgada a una de primer nivel y así sucesivamente. Podemos asumir que esto siempre será así o  en el grafo podría una casa estar colgada a una de primer nivel y de cuarto nivel por ejemplo?

**Comment by ptflores1** [comment]
Hola !
Si pueden haber conexiones a diferentes niveles.
Saludos !

**Comment by jaromero6** [comment]
Ok, muchas gracias
