### ISSUE TITLE
Confusion en consulta Potencia perdida

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#605]
Hola, tengo una duda sobre la consulta de la potencia total perdida. Cuando se refiere a la energia total disipada que la llega a la casa, es con respecto a la energia que se "manda" sólo para esa casa o a la energia de toda la red que se ha disipado ? 
Por ejemplo, partiendo desde una casa:
Caso 1 -> A la casa le llegan 10MW. se juntan con 20MW más en la distribuidora, pero en el trayecto distribuidora-transmision solo se cuenta la potencia disipada de los 10MW de la casa
Caso 2 -> Los mismos 10MW se juntan con 20MW más en la distribuidora, y en el trayecto distribuidora-transmision se cuenta la potencia disipada de los 30MW juntos

Aparte de esa duda, también tengo duda sobre lo que pasa si hay más de una elevadora en la red. Como el enunciado fórmula la consulta como DESDE la estación elevadora, debo contar sólo la energía que le llega desde 1 estacion elevadora, o la que le llega entre todas las estaciones elevadoras. Por ej si hay 2 elevadoras que suministran 10 MW c/u , cuento lo disipado de cada una por separado (es decir solo la energia que se disipo de 10MW) o de ambas (de los 20MW). 
En lo personal considero que esta consulta es mucho más logica con una elevadora que con varias D: asi no se presta a confusiones

**Comment by jfacuse** [comment]
Alguien que responda pls ya han pasado 3 diass :((

**Comment by lily416** [comment]
Hola, lo siento por la demora :bow:

En cuanto a la primera pregunta, sería el segundo caso.
La segunda pregunta, queda a tu criterio y la elección que escojas debes justificarla en el readme.  

Éxito con la tarea 💪⚡️
