### ISSUE TITLE
Subestaciones

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#606]
Hola! En el enunciado aparece lo siguiente

> 3. Subestación de transmisión: transporta la electricidad desde las estaciones elevadoras hasta las
subestaciones de distribución. Hay una por provincia.

> 4. Subestaciones de distribución: distribuyen la energía hacia los consumidores. Hay una o más
> por comuna.

Ese  **_Hay una por provincia / Hay una o más_** se refiere a que al menos tiene que haber esa cantidad? porque si elimino una subestación elevadora de acuerdo a la issue #575 puede que no hayan subestaciones elevadoras (y por tanto se eliminan todas las otras subestaciones conectadas, pudiendo ocurrir que no quede ni una).

Gracias!

**Comment by ptflores1** [comment]
Hola !
Esas afirmaciones estaban hechas pensando en como viene la base de datos (se que se explica asi, sorry). Al igual que las estaciones elevadoras puede haber cualquier cantidad de subestaciones de transmisión o distribucion.
Saludos !

**Comment by BFFV** [comment]
¿Y pueden por ejemplo haber más de una de transmisión con la misma provincia?

**Comment by ptflores1** [comment]
@BFFV Si !
