### ISSUE TITLE
Duda con enunciado usuario único

### ISSUE THREAD

**Issue by dlcartagena** [IIC2233/syllabus-2018-2#61]
No me queda claro donde dice "el sistema solo va a permitir que
existan dos usuarios con igual nombre de correo, siempre y cuando el servicio que provee ese correo sea diferente."

Mi pregunta es si pueden existir infinitos mails con el mismo nombre de usuario (nombre_usuario@servidor.com) , siempre y cuando el servidor web sea distinto?

**Comment by jeschuwirth** [comment]
Saludos, 
siempre y cuando lo que este después o antes del @ sea distinto pueden haber infinitas repeticiones del contrario, me explico.

pueden haber muchos correos distintos que todos terminen en @ejemplo.com
como también muchos que empiecen con ejemplo@.......  siempre y cuando lo que venga después del @ sea diferente para cada uno de ellos.

**Comment by Franco1605** [comment]
Entonces el enunciado no limita que solo existan 2 correos con igual usuario y distinta dirección?
Pueden haber entonces correos de la forma: h4@uc.cl - h4@ing.puc.cl - h4@gmail.com ?

**Comment by jeschuwirth** [comment]
exacto, no lo limita

**Comment by RodrigoNazar** [comment]
El servicio que se desea utilizar debe ser consultado a la hora de pedir la dirección de usuario?

**Comment by Mahund** [comment]
Por lo que yo tenia entendido si defines tu usuario como: nombre@serv.icio, hay 2 casos:

1. Para un único @serv.icio tienes infinitos nombres , lo que es válido.

2. Para un único nombre solo puedes tener 2 @serv.icio como máximo.

**Comment by jeschuwirth** [comment]
lo que dijo Mahund pero en el punto 2 no hay límite de servicios, también pueden ser infinitos para un único nombre

**Comment by Mahund** [comment]
Pero el enunciado dice:

> Para asegurar la consistencia y unicidad de cada correo electronico, el sistema solo va a permitir que
existan dos usuarios con igual nombre de correo, siempre y cuando el servicio que provee ese correo sea
diferente. Por ejemplo si se acepta lo siguiente:
h4@uc.cl y h4@ing.puc.cl

¿Ahi no dice que se aceptan solo 2?

**Comment by jeschuwirth** [comment]
Saludos,
Entiendo como esa redacción puede llevar a error, pero se refiere a que pueden existir dos/(o más) usuarios con igual nombre de correo siempre y cuando el servicio sea diferente.
