### ISSUE TITLE
Siglas y nombres en bases de datos

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#610]
En el enunciado se mencionan las siglas de cada sistema eléctrico, pero en la base de datos solo el SIC y SING salen así, mientras que los otros 2 salen como MAGALLANES y AYSEN. ¿Ocuparán estos mismos nombres para corregir la tarea?

**Comment by lily416** [comment]
Considerarán las siglas que se utilizan en la base de datos: SIC, SING, MAGALLANES y AYSEN. 
Por si acaso especificalo en el readme.

Saludos 💡👋

**Comment by BFFV** [comment]
Gracias!
