### ISSUE TITLE
Variable Global para el Tamaño

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#611]
¿Se puede usar una variable global (sin usar los statement global ni globals) para el tamaño de la base de datos a utilizar, así como en la tarea 01?

**Comment by jeschuwirth** [comment]
por lo general ocupar una variable que no este definida dentro de una función esta tirara error por no estar definida localmente, sin embargo si no utilizas global ni globals y no te sale el error, entonces no debería haber problema con lo que estas haciendo.

**Comment by BFFV** [comment]
Gracias!
