### ISSUE TITLE
Cambio en la base de datos

### ISSUE THREAD

**Issue by NachoJuanDev** [IIC2233/syllabus-2018-2#612]
Es posible que expliquen cuales fueron  los cambio en la base de datos y el por qué de estos? Y dar un aviso general, ya que no deben ser muchos los que sepan que la base de datos de la tarea 3 sufrió algunos cambios.

**Comment by marcotroncoso** [comment]
Porfavooor!!!!

**Comment by ptflores1** [comment]
Hola !
No hubo cambios significativos, solo nos preocupamos de que no hubiesen problemas con la excepcion `ElectricalOverload`.
Saludos !
