### ISSUE TITLE
Agregar estación elevadora

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#613]
Hola! En la parte 4.2 del enunciado dice que :

> "cuando se añade una nueva estación elevadora, este debe poder asociarse a alguna(s) generadora(s) para obtener energía eléctrica." 

No entiendo si es que se debe asociar a cualquier generadora o a una perteneciente a su mismo sistema eléctrico; de ser el ultimo caso, al usuario habría que pedirle el nombre del sistema eléctrico?

**Comment by lily416** [comment]
La estaciones elevadores deben pertenecer al mismo sistema eléctrico que sus centrales generadoras.
El usuario debe especificar las centrales generadoras a las que se conectará la estación elevadora. 

Saludos :electric_plug:👋
