### ISSUE TITLE
Agregar casa

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#614]
En la parte 4.2 dice que:

> Finalmente, cuando se añade un nuevo consumidor en la red, la energía que fluya hacia el dependerá de donde se encuentre

No entiendo como debemos saber en que parte "se encuentra" hay que pedirle al usuario estos datos o agregamos el consumidor a una parte aleatoria dentro de donde están los consumidores?
Gracias!

**Comment by lily416** [comment]
Se le debe pedir al usuario la distancia que hay entre la casa y la distribuidora o casa desde donde obtiene la energía.

Saludos 💡👋
