### ISSUE TITLE
Casas Aisladas en la Red

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#615]
Existen varias casas en cada sistema que no están conectadas con la red energética, ¿Se considera su demanda dentro de la demanda del sistema?, ¿Se pueden colgar otras casas de ellas a pesar de que no les llega energía por ningún nodo padre?

Aprovechando la duda, según enunciado al eliminar un nodo cuyos hijos no tienen otros padres entonces se deben eliminar estos nodos por no tener conexión con la red de energía. Aun así están estos casos de nodos aislados en donde tampoco están conectados con la red, pero aun así están 'presentes' en el sistema. ¿Se deben dejar así nomás o se eliminan del sistema?

**Comment by NicolasCabello** [comment]
Me paso exactamente lo mismo, acabo de cachar que existen casas sin padres ni hijos

**Comment by ptflores1** [comment]
Hola !
Queda a su criterio si los guardan como nodos aislados o no, en caso de que los guarden no aportan a la demanda porque están desconectados, si se pueden conectar a otras casas pero nuevamente esto no tendría efecto sobre la red por que no están unidos a ella. Avisen en su readme como manejaran este caso.
Saludos!
