### ISSUE TITLE
Dudas ElectricalOverload

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#616]
Tengo un par de dudas respecto al ElectricalOverload:

1) En el enunciado se menciona que al remover una casa colgada, la energía que le llegaba se devuelve a la casa que le entregaba y podría producirse la sobrecarga, ¿pero no se supone que esa energía en realidad desaparece debido a que se recalcula la demanda de la red y ya no se considera la casa removida? (nunca debería haber más flujo que la demanda de la red)

2) Considerando lo anterior, entonces la única forma de que ocurra la sobrecarga es que se agreguen más casas colgadas, aumentando la demanda de la casa que las provee hasta superar los 30 MW. Si esto ocurre, ¿se debe levantar el error inmediatamente al encontrar que la demanda sobrepasa el límite, o se debe levantar cuando el flujo que le llega REALMENTE (no idealmente) sobrepasa los 30 MW? (no tendría tanto sentido esto último ya que si se intenta satisfacer la demanda de la casa entonces eventualmente ocurriría sobrecarga)

**Comment by johntrombon** [comment]
Tengo las mismas dudas. El enunciado dice de forma explícita que al agregar un nodo hay que recalcular la demanda de la red, sin embargo, no dice si hay que hacerlo al momento de remover nodos. El realizar o no esto último hace una gran diferencia en el comportamiento de la red. +1 a tu issue 🐸
