### ISSUE TITLE
Fecha entrega tarea 3 y Readme

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#618]
Hola !

Estoy algo confundido con la fecha de entrega de la tarea 3, había escuchado que cambiaron la fecha de entrega al martes 30, pero en el pdf del enunciado sigue diciendo que se debe entregar este domingo 28.

Si alguien me lo pudiera aclarar se lo agradecería mucho

saludos

**Comment by lily416** [comment]
Como sale en el mail que se mandó:

>  Se publicó una nueva versión del enunciado de la T03, en esta issue (https://github.com/IIC2233/syllabus/issues/538) pueden encontrar un detalle de los cambios. A raiz de este cambio, la tarea se extendió 2 días. No obstante, el entregable se mantiene en la misma fecha.

Por lo que tienen hasta el martes 30 de octubre para entregar la tarea.

Saludos 👋💡
