### ISSUE TITLE
Consulta potencia perdida

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#619]
Hola ! en el caso de que la casa que se obtiene dado el id de esta, no le llegue energía actualmente por que la red no satisface la demanda de todos sus clientes entonces no entiendo bien como se calcularía la potencia perdida en transmisión ya que en teoría no se le esta transmitiendo nada a esta casa.
Gracias !

**Comment by ptflores1** [comment]
Hola !
Debes calcular las perdidas del camino que lleva hasta la casa hasta donde sea capaz de llegar la energía, es decir si la potencia se hace 0 en la subestación de transmisión, entonces para la consulta solo van a contar las perdidas desde esa subestación de transmisión hacia arriba.
Saludos !
