### ISSUE TITLE
Orden de eventos

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#62]
Dado que se tiene un calendario asumo que los eventos se deben ordenar por fecha, pero mi duda es, ¿hay que "duplicar los eventos en el calendario" (colocando el inicio y el termino)? ¿o hay que colocar inicio y termino juntos y ordenarlos solo por fecha de inicio?

**Comment by agustinkrebs** [comment]
Hola!

A pesar de que no se especifica en el enunciado, debería imitar a los programas "estándar" de calendarización, en donde aparecen como un **único evento**, ordenados por **fecha de inicio**.

Saludos!
