### ISSUE TITLE
Override de simbolos de diccionario

### ISSUE THREAD

**Issue by AndresCalvo** [IIC2233/syllabus-2018-2#621]
Quería saber si existe alguna forma de hacer que cuando escriba los signos {}, python los interprete como un diccionario vacío de mi propia clase de diccionario, en vez del built-in. (lo mismo para [ ] en listas).

**Comment by lily416** [comment]
Hasta lo que tengo conocimiento no se puede 😞 En vez de hacer uso de `{ }` o `[ ]`, podrías llamar a tus estructuras y crear instancias en las que no reciban argumentos, es decir, estén vacíos.

Saludos ⚡️

**Comment by AndresCalvo** [comment]
Eso mismo estaba haciendo. Era solo para que la sintaxis fuera mas universal.
Gracias.

**Comment by fgbruna** [comment]
@AndresCalvo De que puedes, puedes, [pero no es recomendado ;)](https://stackoverflow.com/questions/19083160/can-literals-in-python-be-overridden)
