### ISSUE TITLE
Heredar de una clase que no es una estructura de datos

### ISSUE THREAD

**Issue by MMeisters** [IIC2233/syllabus-2018-2#622]
Hola! Me estaba preguntado si se puede heredar de la clase string para poder modificar métodos para que sean compatiples con los restricciones de la tarea, i. e. modificar el método split para que no use listas. Gracias ❤️

**Comment by Coolgatty** [comment]
pero puedes hacer 
string_nueva = MiLista(*string.split())
?

**Comment by lily416** [comment]
No está permitido heredar de estructuras _built-in_, aunque no sean listas, diccionarios o similares.
Haz lo que dice Coolgatty o algo similar.

Saludos 🔌👋
