### ISSUE TITLE
Unidades_y_columnas_en_base_de_datos

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#623]
Hola, revisando las issues vi algunas cosas que no había visto en el enunciado (o que no están) por lo que lo pregunto para corroborar:
¿Las columnas de las bases de datos podrían estar desordenadas? en cuyo caso tendríamos que revisar en que orden están los datos para poder leer bien la base de datos ¿o estarán ordenadas como para la mayoría de las tareas?

¿Las unidades de las bases de datos podrían cambiar?, por ejemplo, colocar el consumo de las casas en megawatts en lugar de kilo o el consumo de las subestaciones en kilo en lugar de mega. En cuyo caso habría que revisar bien el header.

**Comment by lily416** [comment]
Con respecto al orden de las columnas, se respondió en #531.
Las unidades de las bases de datos se mantendrán.

Saludos 🔌👋
