### ISSUE TITLE
Dudas al Remover Nodos

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#624]
En el enunciado se menciona que al remover un nodo, la energía que le llegaba se redistribuye hacia los otros nodos 'hermanos' conectados al mismo padre. ¿No se supone que al recalcular la demanda de la red esa energía simplemente desaparece ya que la demanda ya no considera al nodo eliminado (es decir no se redistribuye hacia ningún nodo, sino que simplemente se calcula la nueva demanda del nodo padre)?

**Comment by ptflores1** [comment]
Hola !
Si, recalcula la demanda nomas.
Saludos !
