### ISSUE TITLE
Cambios_permanentes_y_no_permanentes

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#625]
Tenía una duda sobre este apartado pues se me ocurrieron distintas formas de como interpretarlo, al decir que un cambio sea permanente o no, se me ocurrieron estas dos ideas:

1) El usuario propone todos los cambios sin que ocurra nada y luego los confirma, al momento de confirmar se levantan errores en caso de haber.

2) El usuario realiza cambios y estos pueden levantar errores a la vez que cambian el sistema de inmediato, pero existe un backup del sistema previo por si quiere retroceder, al momento de confirmar los cambios el backup se elimina y se quedan los cambios de forma permanente.

¿Cual de las dos interpretaciones esta correcta? (y en caso de estar las dos malas, ¿Qué debo hacer cuando se habla de cambios permanentes?)

**Comment by IchottMano** [comment]
@PPDZ Hola!

Puedes hacerlo de cualquiera de esas dos maneras, siempre y cuando lo especifiques en tu README.md

Saludos!
