### ISSUE TITLE
Casa sin Padre ni Hijo

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#627]
Buenas, estuve revisando la base de datos que subieron hace pocos días ( la modificada) y me di cuenta que hay una casa que no tiene ni padre ni hijo (la de id 387), que se hace en esos casos?, la conecto con alguna de las comunas?

**Comment by IchottMano** [comment]
Hola!

No debes conectarla, piensala como una casa recién agragada, simplemente no esta conectada.

Saludos!

**Comment by NicolasCabello** [comment]
yaa buena, muchas gracias!
