### ISSUE TITLE
Leer Archivos

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#628]
Dado que las columnas de la bd pueden modificarse, tenia pensado hacer algo como esto:
with open(path, "r") as archivo:
    archivo = csv.reader(archivo)
   (1) a, b, c, d, e = revisar(next(archivo)) #donde estas letras tendrán la ubicación de cada columna buscada, por ejemplo a (que es id) seria 1.
Y luego desempaquetar el resto de la lista en una funcion mia siguiendo el orden de lo que obtuve arriba, por ejemplo:
    (2) for linea in archivo:
            Casa(ide, *args), donde ide sera linea[1]

Decidí hacer esto, primero porque en (1) no estoy guardando los datos, sino solo leyéndolo (lo que no se si cuente como valido), y por otro lado, en (2), estoy ocupandolo altiro en mi estructura, sería valido? ya que trate de hacerla con csv.dictreader, pero no es valido el ocupar row[x] 😢

**Comment by IchottMano** [comment]
@NicolasCabello Hola!

Lamentablemente no puedes hacer esto, puesto que en (1) estás haciendo uso de tuplas al hacer `a, b, c, d, e` y en (2) estás iterando sobre una estructura prohibida.

Edit: Lo de iterar sobre una estructura prohibida sólo corre si es fuera del init de alguna de tus estructuras, de estar dentro de tu estructura (como para desempaquetar) es válido iterar sobre una estructura prohibida.

Saludos!

**Comment by NicolasCabello** [comment]
Entonces 2) estaria bien? ya que estoy desempaquetando en mi estructura de datos, lo de 1) lo entiendo bien!

**Comment by IchottMano** [comment]
@NicolasCabello Lo que pasa es que en (2) tu iteras sobre la estructura prohibida para luego desempaquetarla, lo cual está prohibido. Lo que está permitido es iterar sobre una estructura prohibida luego de que ya se la entregaste a una estructura para ser desempaquetada.

Saludos!
