### ISSUE TITLE
Calculo de demanda vs consumo en base de datos

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#629]
Hola, ¿el valor de consumo energético de la base de datos de cierta entidad  (por ejemplo, de una subestación distribuidora) es el valor máximo que soporta (lo que posteriormente se usaría para lanzar excepciones) o es la energía que están consumiendo todos los elementos colgados a ella (considerando la resistencia en los cables)?

Gracias de antemano

**Comment by ptflores1** [comment]
#632
