### ISSUE TITLE
Contenido de mails

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#63]
Hola!

Pueden estar los mails "vacíos" (en su descripción o body)?

**Comment by jtcaraball** [comment]
El body del mail tiene como única limitación que no exceda 256 caracteres. Si por descripción te refieres al punto 4. Opciones del correo: este tiene que tener por default "sin clasificación", si te refieres al punto 2. Asunto: este no puede estar vacío. 
Si eliges poner como restricción que el body no este vacío procura informarle al usuario que no se puede.

Saludos!
