### ISSUE TITLE
Crear MiDict

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#631]
Este código encontrado en stackoverflow(https://stackoverflow.com/questions/43627405/understanding-getitem-method):
```
class Building(object):
     def __init__(self, floors):
         self._floors = [None]*floors
     def __setitem__(self, floor_number, data):
          self._floors[floor_number] = data
     def __getitem__(self, floor_number):
          return self._floors[floor_number]
```
¿ Es legal?

**Comment by AndresCalvo** [comment]
Yo pensaría que como hace uso de una lista [None] no puedes, a menos que lo reemplaces con tu propia clase de lista :P.
