### ISSUE TITLE
ElectricOverload

### ISSUE THREAD

**Issue by FloValdes** [IIC2233/syllabus-2018-2#632]
Hola, se lanza un ElectricOverload cuando la demanda ideal de una casa supera los 30 kW o sólo cuando la demanda real los alcanza?

Gracias.

**Comment by miguelramirezv** [comment]
Es necesario implementar esto de ElectricalOverload? Puedo en vez de implementarlo (electrizaloverload) al remover una casa, recalcular la energía que debe llegar a cada nodo y hacer que llega solo lo necesario y no haya sobre carga nunca, excepto si la demanda ideal de la casa es sobre 30kW?

**Comment by IchottMano** [comment]
@FloValdes Hola!

El error debe levantarse cuando la demanda **real** de una casa supera el máximo.

@miguelramirezv Si, es necesario implementarlo, no puedes hacer lo que dices.

Saludos!
