### ISSUE TITLE
Duda leer base de datos

### ISSUE THREAD

**Issue by sacorsi** [IIC2233/syllabus-2018-2#633]
Tengo un problema al leer el archivo "centrales" de la carpeta "large", ya que las columnas estan separadas por comas ( , ) y al leerlo uso .strip( ).split(","). Pero a partir de la fila 87 empiezan a aparecer comas en los nombres de las centrales (ej: LAGUNA VERDE (U1, U2, TG) ) y se me desordena todo a partir de esa fila.
Esto es un error de la base de datos? O estoy haciendo algo mal? 
Gracias de antemano!

**Comment by miguelramirezv** [comment]
Prueba importando csv y usando csv.reader() en vez del Strip()Split(), sale bien como hacerlo en internet!

**Comment by sacorsi** [comment]
@miguelramirezv  Gracias!! Ahi me funciono!
