### ISSUE TITLE
Provincias

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#634]
Hola, estuve revisando y me parece raro que no he leído ninguna restricción ni consulta sobre provincias, solo sobre comunas para distribuidoras y casas, y la restricción mas general de ser parte del mismo sistema, por lo que el dato provincia es simplemente un "adorno" a menos que queramos poner restricciones extras (que dado el tiempo en que pregunto esto no creo probable) ¿Me falto leer algo o es así?

**Comment by BFFV** [comment]
Aprovechando la duda, ¿Es necesario que una Subestación de Transmisión y Distribución sean de la misma provincia para poder conectarse?
