### ISSUE TITLE
Duda agregar Subestacion Generadora

### ISSUE THREAD

**Issue by Michelmagna** [IIC2233/syllabus-2018-2#636]
Hola!

El enunciado en la parte de agregar un nodo de generación señala: "Este incremento de la energía disponible es recibido por la estación elevadora que pertenezca al mismo sistema eléctrico"

Mi duda recae, que ocurre si el sistema eléctrico al que se agrega contiene dos subestaciones elevadoras. Se conecta automaticamente la estación generadora con todas las elevadoras, con una o que? Esto, mi programa debe hacerlo solo o el usuario debe especificar con que conectarlo (Como el caso cuando se agrega una Subestación elevadora)

Gracias!

**Comment by ptflores1** [comment]
Hola !
Debes preguntarle al usuario que quiere hacer, conectarla a una o a varias estaciones elevadoras.
Saludos !
