### ISSUE TITLE
Manejo de excepciones propias

### ISSUE THREAD

**Issue by johntrombon** [IIC2233/syllabus-2018-2#639]
No me queda claro si debemos evitar que el programa se caiga en cualquier circunstancia o sólo con inputs equivocados, me explico:
En el caso de realizar un cambio que levante ElectricalOverlead, por ejemplo, debemos permitir que el programa se caiga o atraparla y revertir los cambios?

De ser así, ¿cual es el punto de hacer una distinción entre hacer un cambio en la red y probar que pasaría se se hace el cambio, si en ambos casos debemos atrapar la excepción y evitar que el programa se caiga? Gracias de antemano.

**Comment by IchottMano** [comment]
Hola!

Tu programa no de sebe caer **bajo ninguna circunstancia**. Debes capturar todas las excepciones que levantes.

La idea de el cambio en la red vs probar que pasaría es que en el cambio tu efectivamente cambias la red mientras que cuando pruebas algo no hay un cambio.

Saludos!
