### ISSUE TITLE
permisos del Calendario del curso

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#64]
Hola, 
estaba intentando integrar el calendario del curso a mi google calendar. Esto no funciona ya que mi calendario personal no está linkeado a mi cuenta uc.

Hay alguna manera de solicitar los permisos para hacerlo?

Gracias :)

**Comment by cilopez** [comment]
Hola Patrick ¿pudiste solucionar tu problema? , la verdad es que no tenemos solución al parecer. Porfavor si lo solucionaste publica lo que hiciste

**Comment by Kitaps** [comment]
Hola Camilo, 

No hay manera de que se de acceso a cuentas de google externas de a la U para poder ver el calendario?

Si es que no se puede buscaría soluciones cuando tenga tiempo.
