### ISSUE TITLE
Retorno funcion tupla

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#640]
Hola!
Puedo hacer una función que tenga un ```return a, b``` si cada vez que la leo, lo hago de la siguiente manera:
```a, b = funcion()```
Se que ese tipo de return retorna una tupla, pero si la leo así desempaquetándola altiro, nunca uso la tupla.
¿Se puede hacer esto?

**Comment by lily416** [comment]
No puedes 😓  En vez de retornar una tupla, retorna una de las estructuras que hayas creado y desempaquétala después.

Ánimo con la tarea 💪
