### ISSUE TITLE
Consulta consumo por comuna

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#641]
Hola!
En esta consulta dice que se debe sumar el consumo de energía de cada consumidor de la comuna. ¿Las subestaciones elevadoras y de transmisión, que también tienen comuna y consumen también cuentan? ¿O se suman solo los consumos de las casas y las subestaciones de distribución como dice en la issue #550?

**Comment by ptflores1** [comment]
Hola !
Solo consumos de casas y subestaciones de distribucion.
Saludos !

**Comment by fabarros** [comment]
La base de datos incluye "consumo" y "comuna" en las estaciones elevadoras y de transmisión por lo tanto lo más lógico es que los consideremos para calcular la demanda total de la red. No entiendo porqué no se considera, no está en el enunciado y la Issue no está etiquetada como importante.
