### ISSUE TITLE
Levantar_errores_pequeños

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#642]
Hola, se que es tarde pero tenía la siguiente duda, que algunos errores muy simples de control de flujo los resolví sin usar try except y levantando errores, por ejemplo, pedir un numero y si entrega un string no numérico, pedirlo de nuevo en un while not string.isnumeric():  ¿Tenemos que aplicar el invalidquery para casos tan pequeños como estos? ¿o podemos dar una solución rápida sin levantar error en estos casos?

**Comment by fernandodediegoavila** [comment]
Hola!
Te recomiendo dejarlo todo en un formato estándar, de manera que cualquier error en las consultas, por pequeño que sea, levante la expeción. De todas formas, si quieres persistir con esa idea te recomiendo revisar los criterios de evaluación y, en caso de que no atente ninguno, destacarlo en tu Readme.
Saludos!
