### ISSUE TITLE
Tuplas y múltiples excepciones

### ISSUE THREAD

**Issue by rafafdz** [IIC2233/syllabus-2018-2#643]
Hola! 
Al parecer, python sólo soporta **tuplas y listas** para poder manejar múltiples excepciones en una sentencia del tipo:
```python
try:
     # Hacer algo
except (Exception1, Exception2, ...):
     # Manejar Excpciones
```
Donde una tupla contiene las distintas ```Exception```.
Hasta el momento no he podido encontrar algún dunder method que le permita a mis propias estructuras funcionar en estos casos, asi que pregunto:

Se pueden usar en estos casos particulares las estructuras prohibidas?
Gracias!

**Comment by jeschuwirth** [comment]
Nunca ocupes nada prohibido en tus tareas !
Luego de una discusión entre ayudantes, porque igual entendemos tu puntos, llegamos a la conclusión que como la tarea es de excepciones preferimos que las manejen por separado, por lo tanto no pueden utilizar tuplas para ver varias excepciones en el mismo except
