### ISSUE TITLE
Envio de formulario

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#644]
Si lleno el formulario, coloco enviar, me aparece que el formulario fue enviado pero no me llega el mail de respaldo, se envio de manera correcta la evaluación o no??

**Comment by entamburini** [comment]
Hola! :)

Estuve revisando y tu usuario sale en ambos formularios c: el de autoevaluación de hecho sale que lo enviaste hace unos 10 o 15 minutos atrás, así que no te preocupes :D 

Igual es raro que no te haya llegado el mail de respaldo, revisando parece estar todo en orden! :o 

Saludos!

**Comment by marcotroncoso** [comment]
Buena excelente, Graciaaas!!!

**Comment by Hernan4444** [comment]
Hola, aunque ya se aclaró que tu respuesta está , te recomiendo revisar la sección de SPAM, a varios le llega el mail de confirmación a esa carpeta e incluso hay otros (como yo) que tenemos configurado que el SPAM se elimina automáticamente 😅, por lo tanto a veces hay mails que llegan directamente a la papelera.

Saludos :v:
