### ISSUE TITLE
uso de range()

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2233/syllabus-2018-2#645]
Se puede ocupar range()? o devuelve una estructura built-in?

**Comment by jeschuwirth** [comment]
la función range devuelve un immutable sequence type, el cual es una especie de estructura de dato built-in. Así que no se puede ocupar, sin embargo es una función generadora muy sencilla de recrear que puedes definir en tu tarea para usarla, al igual que las lista o diccionarios.

**Comment by Gorgola22** [comment]
Y se puede usar entonces un while? El típico i = 0, while i != ...

**Comment by AndresCalvo** [comment]
¿Y puedo usar range() desempaquetado dentro de mi propia lista y usarlo ahí? Es decir, hacer algo del estilo for i in MiLista(*range(n)): etc

**Comment by jeschuwirth** [comment]
@Gorgola22 
Si, no hay problemas con usar loops.

@AndresCalvo 
Evitate problemas y no ocupes builts-in en ambsoluto si puedes hacerlo de otra manera, recomiendo crear la función `rango(n)` que sea análoga a `range(n)`
