### ISSUE TITLE
is vs ==

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#647]
Hola!
Una duda de contenidos, ¿cual es la diferencia de usar is o == ?
En los contenidos o actividades a veces usan por ejemplo if algo is None: ... Porque no usar if algo == None:... ?

Gracias!

**Comment by fdduarte** [comment]
Hola!
En terminos prácticos, utilizar `var == None` y `not var` es lo mismo, pero por **pep8** lo mas correcto es utilizar sentencias de `is` al comparar con un objeto con un booleano.
Si quieres leer mas te dejo esta [issue](https://stackoverflow.com/questions/4050335/strange-pep8-recommandation-on-comparing-boolean-values-to-true-or-false) de stackoverflow.
Saludos!

**Comment by IchottMano** [comment]
Hola!

Para complementar un poco la respuesta anterior, el operador `==` chequea que dos objetos sean **iguales**, es decir que tengan el mismo valor, mientras que el operador `is` chequea que dos variables *apunten* al mismo objeto, es decir por ejemplo:
```python
class Numero:
    def __init__(self, n, a):
        self.num = n
        self.var = a
    def __eq__(self, other):
        return self.num == other.num

if __name__ == "__main__":
    num1 = Numero(1, 2)
    num2 = Numero(1, 3)
    print(num1 == num2)  # Printea True
    print(num1 is num2) # Son objetos distintos, por lo que printea False
```

Si te queda alguna duda, siempre puedes revisar la siguiente [issue](https://stackoverflow.com/questions/132988/is-there-a-difference-between-and-is-in-python)
