### ISSUE TITLE
ElectricalOverload y intento de modificación

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#648]
Hola! En el enunciado no se especifica nada de esta excepción. Entiendo que se levanta cuando se genera sobrecarga eléctrica, pero ¿Cuando se genera una sobrecarga eléctrica? ¿Donde se puede generar? ¿Cuales son los limites?

Por otro lado, cual sería la diferencia de intentar modificar la red y efectivamente modificarla? Son acciones distintas o simplemente antes de modificarla se ve si se puede y si no es así no se hace?

Ojalá puedan aclaralo más porqué no está muy claro en el enunciado!

**Comment by jeschuwirth** [comment]
Saludos, como dice un poco más abajo de esa excepción 
![image](https://user-images.githubusercontent.com/37160256/47660270-724b6380-db75-11e8-973a-e8fb2aaf8c78.png)
Por lo tanto si remover o agregar un nodo la potencia eléctrica de una casa es de 30.000 kW.

No entiendo mucho a que parte del enunciado va la segunda pregunta, pero por ejemplo en la misma excepción, cuando dice:
![image](https://user-images.githubusercontent.com/37160256/47660450-c6eede80-db75-11e8-9bef-9b3f384b142f.png)
Entonces se intenta modificar la red, sin embargo no se modifica realmente ya que cuando se intento esta levanto el error.

Espero que esto haya contestado tus dudas :D
