### ISSUE TITLE
Ciclos al agregar arista entre casas

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#649]
Debo controlar que no se produzca un ciclo al agregar una arista?

Ej:

```
nodo1 -> nodo2
nodo2 -> nodo3
```

Puedo asumir que no se va a intentar agregar una arista en sentido `nodo3 -> nodo1`?

**Comment by jeschuwirth** [comment]
Saludos,
![image](https://user-images.githubusercontent.com/37160256/47670230-784c3f00-db8b-11e8-95ca-6a9fd1e660c9.png)
Como dice esa parte del enunciado, aunque se refiera a cuando se da el grafo y no cuando se agrega, vamos a evitar crear ciclos, por lo tanto si puedes sumir que no se integrarán
