### ISSUE TITLE
No puedo abrir el notebook de Jupyter

### ISSUE THREAD

**Issue by diegomendieta** [IIC2233/syllabus-2018-2#65]
Hola, instalé Jupyter por medio de pip, pero no puedo abrirlo usando el comando jupyter notebook. Qué puedo hacer?

**Comment by IchottMano** [comment]
@diegomendieta Hola!

Cuando intentas abrirlo, te sale algun error?

Saludos

**Comment by diegomendieta** [comment]
Me dice: "jupyter" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by pnheinsohn** [comment]
Hola! Si lo instalaste vía pip debes agregar las librerias de Python al PATH de las variables de entorno... en caso de que ya esté ahí prueba usando:

ipython notebook

Desde el terminal en la carpeta que quieras abrir.
