### ISSUE TITLE
Uso de __getattribute__ y __setattr__

### ISSUE THREAD

**Issue by NachoJuanDev** [IIC2233/syllabus-2018-2#650]
Hola, tengo una duda respecto al posible uso de los atributos `__getattribute__` y `__setattr__`. 
Hace unos días leí una pregunta en la issue #512. Dicha pregunta hecha por @Prochotito es [Pregunta](https://github.com/IIC2233/syllabus/issues/512#issuecomment-431536293): 

> Hola, lamento lo insistente, pero se puede usar setattr y getattr?
> Saludos!

A lo que @rihanuch le respondio esto [respuesta](https://github.com/IIC2233/syllabus/issues/512#issuecomment-431595185): 
> '@'Prochotito , esto viene con las clases, por lo que es un método permitido

Basandome en eso, construí una estructura para mi tarea basadas en esos metodos, sabiendo que los atributos de las clases implementan un dicionario por debajo. Pero, pensandolo bien podría estar incurriendo en una ilegalidad respecto a las prohibiciones de la tarea. Por lo tanto, ¿es legal usar estos metodos?, de ser ilegal ¿Es posible hacera algún tipo de apelación?, esto último porque un ayudante respondió que si es posible usarlos hace 9 días atrás. No creo ser el único que los implemento. 

Saludos

**Comment by rhanuch** [comment]
¡Hola @Nacho111 !

Efectivamente dije eso. Eso si, debes tener en mente que el uso de `__getattr__` y `__setattr__` está condicionado a que por debajo se accede al diccionario interno de la clase que se está implementando, por lo que `__getattr__` y `__setattr__` están permitidos para hacer algo del estilo de

```Python 
class MyClass(object):

    def __init__(self):
        self.data = MiDict()
        self.data["llave1"] = "valor1"
        self.data["llave2"] = "valor2"

    def __getattr__(self, attr):
        return self.data[attr]
```

Es decir, para acceder a los métodos `__getitem__`y `__setitem__`, **NO** para acceder directamente a `Object.__dict__`, que es lo que haría el uso literal de estos métodos.

En estricto rigor, al asignar una variable a una clase se hace lo mismo que con un diccionario, es decir:

```Python
mi_dict = {}
mi_dict['mi_nombre'] = 'un_valor'
```

Por lo que al hacer lo que estás diciendo que hiciste, se estaría haciendo lo siguiente:

```Python
class Hola():

    def __init__(self):
        pass

    def nueva_var(self, nombre, valor):
        setattr(self, nombre,  valor)


h = Hola()
h.nueva_var('arg2', 2)
print(h.arg2)
print(h.__dict__)
# >> {'arg2': 2}

h.nueva_var('arg2', 3)
print(h.__dict__)
# >> {'arg2': 3}
```

Por lo que por debajo se estaría haciendo uso de `Hola.__dict__`, es decir, se estaría usando un método prohibido.

Esto se debe a una materia (metaclases) que ya no se ve en el curso. Te dejo el [link](https://github.com/rihanuch/contenidos/blob/master/semana-07/01-metaclases.ipynb) a continuación. En esencia, en esta se detalla que todo en Python hereda de la clase `type` y que finalmente, uno puede intervenir la creación de las clases antes de que se inicialice (el método `__init__`), pudiendo hacer, por ejemplo, que sólo exista una instancia de una determinada clase. Todo esto hace uso finalmente del diccionario que cada clase tiene implementado por debajo 😬 

Si ya implementaste tu tarea utilizando esto, ¡recuerda la existencia de _DuckTyping_! Puedes crear una clase que **no es eficiente** como un diccionario pero que tiene la misma interfaz. De esta manera, puedes interferir lo menos posible en tu código. 

En otras palabras, puedes simplemente sobreescribir los métodos para acceder a los valores de tus clases 😄

¡Saludos y éxito! 🍀

**Comment by Coolgatty** [comment]
Mi codigo se demora mas de 1 hora en cargar la base de datos large si no uso setattr y getattr y uso mi lista ligada en vez de eso. 
Como se supone que revisen mi tarea en la base de datos large si no se puede implementar un diccionario eficiente ni nos enseñan la materia para hacerlo ?

**Comment by NachoJuanDev** [comment]
Rayos, menos mal pregunte a tiempo. Básicamente estaba operando sobre `__dict__`.

Gracias por la explicación extendida!

**Comment by gnacrur** [comment]
Hola, no entendi muy bien que paso pero para aclarar, si use __setitem__ para mi lista ligada estaría bien?

**Comment by viantirreau** [comment]
Hola! Me surgió una pregunta.
En mi EDD guardo dentro de la ListaLigada los objetos para las distintas entidades en la red. Cada uno de ellos tiene, lógicamente, ciertos atributos por los que sería interesante filtrar, como por ejemplo, todas las casas que tienen el atributo `comuna` seteado con algún valor particular.

Para lograr este filtro, implementé algo de este estilo:
```python
def find_by_attr(self, attr, value):
    # Retorna el primer objeto que tenga el atributo attr == value
    for n in self.nodos_lista():
        # Consulta si tiene el atributo, de lo contrario None
        if getattr(n.valor, attr, None) == value:
            return n.valor  # El contenido del nodo de la lista -> el objeto
```
Cabe recalcar que cada objeto que se almacena dentro de los nodos de la lista -léase Consumidores, Elevadoras, a veces strings o ints- no se utilizan con fines malévolos o para almacenar algún tipo de estructura de datos.
De ser un _approach_ ilegal, ¿hay alguna otra forma de filtrar mi lista sin hacer uso directo del diccionario, considerando que ignoro de antemano si el objeto que almaceno en cada posición de la lista tiene o no el atributo? Conozco la existencia de la función `hasattr`, pero me parece que, de ser ilegal `getattr`, la primera también lo será.
Gracias, saludos!

PD. Supongo que es legal acceder directamente a los atributos de las clases, tal como en la última línea del _snippet_ accedo al atributo `valor` de algún nodo de mi ListaLigada

**Comment by rhanuch** [comment]
¡Hola @gnacrur ! 

Es valido si y solo si implementaste tu mismo tu propio dunder

¡Saludos! 🍀

**Comment by rhanuch** [comment]
@viantirreau, eso sería inválido

**Comment by viantirreau** [comment]
Ok, lo arreglaré entonces.
Muchas gracias!
