### ISSUE TITLE
falta de archivos AC10 peer review

### ISSUE THREAD

**Issue by DCCollao** [IIC2233/syllabus-2018-2#651]
Hola
Una de las personas a la que le tengo que corregir subió su archivo events.py (sin código dentro) en lugar de su backend.py. Al ver el frontend, me doy cuenta de que hizo la actividad, pero dado que no hay backend, no corre absolutamente nada. ¿Debería revisar su frontend adaptando mi backend a él?
Muchas gracias

**Comment by naquiroz** [comment]
Considerando que le estas corrigiendo el frontend, si puedes hacer eso. Se agradece la motivación :smile:

Saludos :v:
