### ISSUE TITLE
AC10: Faltan imagenes en el archivo .zip

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#655]
Buenas
Al momento de abrir el archivo .zip que me fue entregado, éste sólo contiene los archivos .py (frontend.py y backend.py). Agrego los archivos manualmente y descuento en todos los items que tengan relacion con la carga de imagenes? O hay otro protocolo que seguir?

**Comment by entamburini** [comment]
Hola! :) 

Puedes agregarlos manualmente, no hay descuento por ese tipo de problemas porque no había nada explícito en el enunciado al respecto 😄 

Trata de ver en qué carpeta está buscando los archivos (si es en la misma carpeta de estos o en una carpeta diferente) para que no tengas problemas. 😉 

Saludos!
