### ISSUE TITLE
Uso DictReader

### ISSUE THREAD

**Issue by jdiaztoledo** [IIC2233/syllabus-2018-2#657]
Hola, 
Mi duda es si existe algún problema en que diccionarios queden guardados en mi propia estructura de datos, ya que utilicé DictReader de la libreria csv, guardándolo inmediatamente en mi propia estructura (MiLista(*DictReader(x))), y luego, al recorrer esa estructura, paso cada diccionario que queda guardado a mi propia estructura (Diccionario(diccionario_guardado)). 
De antemano gracias.

**Comment by jeschuwirth** [comment]
Saludos,
Puedes hacerlo siempre y cuando lo desempaquetes en tu propia estructura enmediatamente después de leerlos, te puede quedar más claro leyendo esta issue #518 
Suerte!
