### ISSUE TITLE
Uso de Exception

### ISSUE THREAD

**Issue by cpgarrido** [IIC2233/syllabus-2018-2#658]
Hola, en el enunciado dice que no podemos ocupar una excepción genérica, pero podemos hacer que nuestras propias excepciones hereden de ella, algo así:
class InvalidQuery(Exception):
    pass

**Comment by jeschuwirth** [comment]
Claro que pueden, de hecho lo necesitan, a lo que se refiere la excepción generica es que no pueden tener un código como:
```python
try:
    1/0
except Exception:
    print("error")
```
Sino que deben explicitar el error como en el siguiente caso:
```python
try:
    1/0
except ZeroDivisionError:
    print("error")
```
