### ISSUE TITLE
Duda en el Flujo resultante cuando la potencia necesaria es insuficiente

### ISSUE THREAD

**Issue by Faalfaro** [IIC2233/syllabus-2018-2#659]
Hola,
Después de ajustar el flujo de potencia y realizar las consultas me encuentro con que la energía que llega a las casas es en su mayoría cero. Por ejemplo, para una elevadora (los siguientes números no son los reales) la demanda es de 3000 Mw y la energía disponible es de 1000 Mw, después de restarle su consumo propio(100 Mw aprox. para cada estación) reparto proporcionalmente entre las 6 estaciones de transmisión y cada una me queda con aproximadamente 150 Mw, el problema es que al restar nuevamente el consumo propio, me quedo necesariamente con menos de 100 Mw para cada estación de distribución, por lo que toda la energía se va en su consumo y no queda nada para las casas. Lo único que se me ocurre es que la "demanda propia" referida en el enunciado también se calcula proporcionalmente  o simplemente lo que hice esta bien, pero no me hacen sentido las consultas para cliente mayor y menor consumo en ese caso. Saludos y gracias de antemano!

**Comment by viantirreau** [comment]
Hola! Quizás es que la configuración actual de la red no alcanza a abastecer a los consumidores, pero al agregar una central más potente podría suplir esa demanda, y ahí si tendría más sentido preguntar por las casas con mayor/menor consumo 🤔  (a mí me pasó lo mismo)

**Comment by Faalfaro** [comment]
Si, también pensé que para revisar cambian la base de datos, pero igual me interesa saber si efectivamente es al consumo al que se refieren cuando mencionan "demanda propia" en el punto 1 de lo que hay que tener en cuenta para calcular el flujo.
