### ISSUE TITLE
Duda resolución AC01, "entrenador no existente"

### ISSUE THREAD

**Issue by johntrombon** [IIC2233/syllabus-2018-2#66]
De acuerdo al enunciado, en "Lógica del sistema", se debía crear una estructura para almacenar los pokemones ganados por cada entrenador, y esta debía ser capaz de manejar el caso de que se consulten los pokemones ganados por  un entrenador no existente. 
Entiendo que un defaultdict(set) cumplía con el objetivo de asignarle un conjunto a llaves recientemente introducidas (en este caso el entrenador que no existe). ¿Como podría haber logrado que la estructura retornada fuera un diccionario de la forma: `{named_tuple_entrenador : set_de_pokemones}` si el entrenador inexistente no tiene una tupla asociada a su id en el archivo entrenadores.txt? (KeyError '126')
¿Se suponía que creáramos una instancia sin nombre para ese entrenador?

**Comment by Drpinto1** [comment]
Saludos!
Si bien la estructura de datos correcta para esta parte era efectivamente _defaultdict(set)_; las keys a utilizar para este debían ser los _ID_ de cada entrenador, pues si bien las _NamedTuples_ son inmutables y se pueden usar como key para el diccionario, la característica que era única para cada entrenador era su _ID_.
Dicho de otra manera, si existían dos entrenadores con igual nombre y apellido, pero distinto ID, al momento de guardar el primero no tendrías problemas, pero cuando se agregaran los pokémon ganados por el segundo, estos se mezclarían con el _set_ del primero.
El error anterior no es fácil de ver, pues al momento de hacer `diccionario[Entrenador]` si se obtendría un set de pokémon, pero este sería, incorrectamente, el mismo para ambos entrenadores (y de hecho sería la Unión de ambos sets)
Otro motivo, también válido para poner ID como key era el realizar una consulta, pues para consultar los pokemon de un entrenador en particular, esto se haría a través de su ID (nuevamente por ser un la única característica única, valga la redundancia, para cada entrenador) y de no hacerlo de esta manera para responder a esta consulta se haría necesario hacer dos operaciones, buscar en el diccionario `{id: NamedTuple}` al entrenador y luego en el diccionario `{NamedTuple: set}` los pokémon correspondientes al entrenador; si bien esto no es un problema en sí, solamente hace más lenta la búsqueda, es otra razón para seleccionar el _ID_ como _key_

**Comment by johntrombon** [comment]
Muchas gracias! en su momento no se me ocurrió la opción de dejar solo los ids como llave. Saludos
