### ISSUE TITLE
max(), min()

### ISSUE THREAD

**Issue by fperezm12** [IIC2233/syllabus-2018-2#661]
Hola, ¿ está permitido el uso de las funciones max() y min() ?

**Comment by lily416** [comment]
Sólo en las estructuras de datos que hayas implementado. 

Saludos 👋⚡

**Comment by BFFV** [comment]
¿Y si es sobre valores numéricos solamente? ej: max (1, 2)

**Comment by lily416** [comment]
También puedes aplicarlos sobre tus propias listas, diccionarios, etc.
Pero debes implementar los métodos necesarios para esto (<, <= y == o >, >= y ==).

Disculpa la tardanza.
