### ISSUE TITLE
gitignore T03

### ISSUE THREAD

**Issue by tomasmetroy** [IIC2233/syllabus-2018-2#662]
Hola! En esta tarea hay que hacer uso del gitignore para las bases de datos?

Gracias de antemano!
saludos!

**Comment by Arcoirisky** [comment]
Siempre que les entreguemos bases de datos lo mejor es que no lo suban ❤️ Así que usen gitignore :D piensen que son muchos y si todos suben las bases de datos no sería lindo 😰😭
