### ISSUE TITLE
[Peer Review] Reenvío del Form

### ISSUE THREAD

**Issue by AndresFaure** [IIC2233/syllabus-2018-2#663]
Hola,
Al corregir las actividades de mi compañeros y la mía, no me dí cuenta que había que rehacer los archivos con los sprites, por lo que ninguna de las actividades me corrió correctamente y las evalué pensando que estaban malas 😰. Hay alguna posibilidad de que pueda re-enviar el form de Peer Review y de Auto Evaluación para corregir mis paveadas? 
Puedo acceder nuevamente al form pero no estoy seguro que si hago cambios efectivamente se harán definitivos.
Gracias en adelantado

**Comment by fringlesinthestreet** [comment]
Hola @AndresFaure

Reenvía el form tranquilo ya que los cambios sí se guardan. Eso sí, ¡recuerda que tienes hasta mañana nomás!

Mucho ánimo!

**Comment by AndresFaure** [comment]
Gracias!
