### ISSUE TITLE
Duda potencia centrales

### ISSUE THREAD

**Issue by matiasmodinger** [IIC2233/syllabus-2018-2#667]
Buenas,
Al cacular el flujo real que hay en los sistemas me di cuenta que la mayoría de casas terminan con consumo cero, esto porque las centrales tienen muy poca potencia de base. Entonces me preguntaba si es que está bien o yo estoy calculando todo mal.
Gracias de antemano.

**Comment by viantirreau** [comment]
Hola! 
Algo parecido comentábamos en #659, también a algunos nos está dando 0. 
Saludos!
