### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by tamaralues** [IIC2233/syllabus-2018-2#668]
Hola, 
Tengo dos consultas, 

1. Hice envío de los forms de corrección pero no me llego ningún mail de confirmación y quería saber si efectivamente tenía que llegarme un mail.

2. El zip que me llego para mi autoevaluación no tiene la carpeta de sprites si no que las fotos fuera de la carpeta mientras que el de mi entrega si contaba con la carpeta, y me preguntaba si a mi correctores les llegó de la misma manera ya que de ser así mi actividad no funcionaría.

Gracias!

**Comment by fabarros** [comment]
a mi también me llegaron las imágenes fuera de la carpeta sprites

**Comment by Hernan4444** [comment]
Hola,
1. Revisa la sección de SPAM, ese mail muchas veces llega a esa parte.
2. Efectivamente todas las carpetas fueron unificadas porque fue la forma de comprimir los archivos sin que quedara ningún rastro del nombre del usuario. No obstante, tal como se dijo en #655 si faltan las imágenes o en tu caso, están pero leídas de una carpeta, no hay penalización, el corrector agregará la carpeta sprites.

Saludos ✌️
