### ISSUE TITLE
Imágenes no se muestran al abrir interfaz

### ISSUE THREAD

**Issue by ncasassas** [IIC2233/syllabus-2018-2#669]
Hola, tengo una duda con la corrección de actividades. Resulta que llegue a la parte de revisar la interfaz gráfica (posterior al ingreso del usuario) y resulta que la ventana que se me abre en python es completamente blanca y sin contenido, revise los códigos y debería cargar bien el sprite del mapa. Compare también con la actividad que realicé donde lograba hacer aparecer el mapa con el pacman y sus funciones pero me aparece la misma ventana en blanco cuando trato de correr el archivo ahora. Estoy usando el mismo computador y la misma edición de python que utilice para hacer la actividad. Quedo atento a sus respuestas, saludos!

**Comment by bgsamilla** [comment]
A mi tambien me pasó eso, era porque los sprites no estaban donde el programa los estaba buscando. Hecha un vistazo a eso.

**Comment by fringlesinthestreet** [comment]
Hola @nko205 

@BSamilla tiene razón! Podría ser que el _path_ que está utilizando tu compañero tenga un pequeño error y por eso no se visualizan las imágenes. 

Puede ser que haya escrito algún nombre de archivo o carpeta con mayúscula y no esté así en la carpeta que se te entregó. Revisa bien y avisa si puedes resolverlo!
