### ISSUE TITLE
Creación de cuentas de correo

### ISSUE THREAD

**Issue by dberezin** [IIC2233/syllabus-2018-2#67]
Cuando se crea una nueva cuenta de correo, esta se debe escribir dentro del archivo db_users.csv o almacenarse como una estructura de datos en la memoria del computador? O queda a nuestro criterio?

**Comment by ptflores1** [comment]
Hola !
Debes guardar la información en algún archivo, puede ser en `db_users.csv`(te lo recomiendo) o en algún otro que crees tu, pero siempre debes guardarlo, seria una pena que un usuario quiera acceder a **DCCorreos** y no se haya guardado su información 😢 . Ten en cuenta que nosostros al corregir vamos a ejecutar tu tarea solo con los archivos que les dimos o al menos con la misma estructura que tienen.

Saludos !

**Comment by skarlezib** [comment]
Hola!
Para guardar nuevos mails en el archivo db_users.csv se puede importar la libreria csv? En caso de que no como se pueden agregar nuevos usuarios y claves al archivo csv?
Gracias!!!

**Comment by ptflores1** [comment]
@skarlezib revisa la issue #12, los archivos `.csv` los puedes manejar exactamente igual a como se hace con los `.txt`

Saludos !
