### ISSUE TITLE
Duda item correccion frontend

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#671]
En el formulario se nos indica lo siguiente:

Frontend no realiza ninguna operación lógica, solamente cambia la interfaz.Error común: si guarda las referencias a las múltiples Cherries (objeto del backend) en el frontend, medio puntaje.

Esa accion no debería realizarse solo en caso de que la persona quisiese hacer el bonus, ya que de lo contrario no es necesario guardarlas, sino que basta crear las guindas a partir de una  clase QObject en el backend, y luego asignar a un QLineEdit del frontend para poder mostrarlo en una posicion random dentro del mapa.

Gracias de antemano

**Comment by bmorrisc** [comment]
Bajo la misma línea, si la persona modeló las cherries como objetos QLabel sin hacer una clase para éstas, y las guarda en un diccionario en el frontend también se descuenta?
Es realmente necesario guardarlas en el backend si no tienen tanta funcionalidad?

gracias de antemano

**Comment by fringlesinthestreet** [comment]
Hola @pelao97 

Efectivamente la descripción del puntaje iba a aquellos que implementaron el bonus y ya ha sido modificada ✏️ . En el _frontend_ está bien guardar las referencias a los `QLabel` que representan la visualización de la _cherries_ en el _frontend_.  

Te recomiendo igual revisar #591 por si la persona creó y mostró los _labels_ pero no guardó las múltiples referencias de los objetos.

Saludos y disculpas
