### ISSUE TITLE
No utilización de show() en Cherries

### ISSUE THREAD

**Issue by TrinidadVargas** [IIC2233/syllabus-2018-2#672]
Hola perdón por lo tarde, pero tengo una pregunta sobre la parte de las _cherrys_.
Si me faltó solo el `cherry.show()` y con esto aparece **una** guinda en un lugar aleatorio, tengo cero puntaje o puedo asignar un poco.

En específico sale:

```python
g_x, g_y = randint(0, 540), randint(0, 590)

guinda = QLabel(self)

guinda.setPixmap(QPixmap('sprites/cherry.png'))

guinda.move(g_x, g_y)
```

**Comment by fringlesinthestreet** [comment]
Hola @trinivargas 

Si sólo falta el `guinda.show()` para que funciona perfecto, entonces merece mitad de puntaje :smile:. Esto lo puedes verificar fácil agregando la línea en el código de tu compañero.

PS: ¡Recuerda revisar las issues! Esto ya se contestó en la #591.
