### ISSUE TITLE
Cómo evaluar detalles en AC10

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#673]
Hola!!! 
Una duda, tengo una tarea con detalles, como que reviso que tuviera más o igual a 6 letras el usuario, o que no inicializo su pacman en las mismas coordenadas en frontend y backend... ameritan el puntaje completo? Yo lo daría, pero me da miedo que este mal :(

Gracias!

**Comment by fringlesinthestreet** [comment]
Hola @gatochico 

Ambos, aunque sean pequeños, son errores que podrían afectar eventualmente el desempeño del programa. Sin embargo, debido a lo cerca del _deadline_ de la entrega de correcciones y a que creemos que pocos correctores hayan llegado a ese nivel, **se perdonarán para esta actividad**.

Muchas gracias por sacar a luz estos detalles, ya que muchas veces pasan por encima de aquellos que revisan y pueden ocasionar a la larga problemas mayores. 

Saludos y ánimo :smile:

PD: * cough * testing * cough *

**Comment by gatochico** [comment]
Yaya, gracias!
