### ISSUE TITLE
Peer Review QtDesigner

### ISSUE THREAD

**Issue by pgarnham** [IIC2233/syllabus-2018-2#675]
En una de las actividades que debo corregir se usa un signin.ui 😬 
Asumo que se usó QtDesigner, lo cual estaba prohibido.
¿Qué debo hacer en este caso? ¿No asignar puntos a la Ventana de Inicio? ¿O hay otro tipo de descuento?

**Comment by fringlesinthestreet** [comment]
Hola @pgarnham 

Primero, por favor revisa bien si efectivamente utilizó el archivo `*.ui` en su actividad.

Si efectivamente lo utilizó, todo lo que haga con eso tiene 0 de puntaje. Comprueba qué tanto realizó con QtDesigner. Si sólo realizó la visualización de su interfaz, entonces tiene 0 puntos en los primeros 3 subitems de "Ventana de Inicio" (9 puntos).

Si realizó la lógica de la ventana de inicio correctamente **sin la ayuda de QtDesigner**, entonces sí merece ese puntaje (6 puntos).

Por último, **no hay** un descuento de formato "extra" por esto.
