### ISSUE TITLE
Peer Review Archivos

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#676]
Hola! Que hago si al descargar una actividad esta no tiene ninguna imagen. 
Al tratar de incluir imágenes o algo para que funcione no se puede 
debido a que esta bloqueado. Que hago??
Muchas Gracias!

**Comment by Hernan4444** [comment]
@ftrejoc puedes explicitar más a que te refieres con "bloqueado"?

**Comment by ftrejoc** [comment]
Hola! me refería a que no puedo poner ningún archivo dentro de la carpeta. Lo que quería hacer era ingresar las distintas imágenes a la carpeta del pokemón para poder correr bien el programa debido a que no venían incluidas. Saludos!

**Comment by fringlesinthestreet** [comment]
Hola @ftrejoc 

¿Descomprimiste el archivo *.zip antes de intentar insertar los _sprites_?

**Comment by ftrejoc** [comment]
Si lo había hecho! pero me di cuenta que un archivo mio estaba haciendo un problema, pero ya lo solucione. Muchas Gracias!

**Comment by fringlesinthestreet** [comment]
@ftrejoc ¡Buenísima! Ánimo con la corrección 😉.
