### ISSUE TITLE
Autoevaluación AC10

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#677]
Hola!

Para autoevaluarme debo llenar el mismo [form](https://docs.google.com/forms/d/e/1FAIpQLSdzS37NBC2DNWPH95Wu6k795y6ZpxGlIWkQ2KjQrOmO4nzy_g/viewform "Formulario Evaluación peer-review AC10")? En ese caso, qué _pokemon_ sería yo?

Saludos.

**Comment by Hernan4444** [comment]
Hola, en tu repositorio hay otra issue que detalla el proceso de autoevaluación, incluye la actividad, contraseña y formulario.

Saludos ✌️

**Comment by ariel-m-s** [comment]
Oops :grimacing:. Gracias!
