### ISSUE TITLE
Feedback tarea 2 – tipos de clientes

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#678]
Hola!

En la __tarea 2__ se evaluó lo siguiente en la sección de _programación orientada a objetos>relaciones entre clases_:

> Existe herencia entre los distintos tipos de juegos y los distintos tipos de persona (personal, clientes).

En mi caso, me fueron descontados dos puntos porque (cita) _"no hay herencia para las personalidades"_. Me gustaría que me explicaran por qué era necesario utilizar herencia en ese caso en particular. Por lo que yo entiendo, no lo era. :confused:

Recuerdo muy bien que tanto en clases como en ayudantía se recalcó que no abusáramos de la herencia, es decir, que la utilizáramos solamente cuando fuera necesaria. En este caso en particular, los tipos de clientes solamente variaban en la personalidad. De acuerdo con mi implementación esto solo incidía en un atributo de la instancia.

Saludos, :snake:
Ariel

**Comment by santilaguna** [comment]
Estimado,

Te recuerdo que debes seguir las reglas del foro #6 . Si tienes alguna duda con respecto a los criterios de corrección puedes enviarla al mail de ayudantes =D. Pero lamentablemente, este no es el medio.

Saludos
