### ISSUE TITLE
Creación de correo

### ISSUE THREAD

**Issue by chocopiano** [IIC2233/syllabus-2018-2#68]
Cuando se desea crear un usuario... se debe de poder elegir el servidor? o debe venir predeterminado con @uc.cl por ejemplo Gracias!

**Comment by nachocontreras** [comment]
Hola!

Puede ser cualquier servidor. Por ejemplo: nachocontreras@uc.cl, nachocontreras@progra.avanzada.cl, nachocontreras@cualquier.servidor.u.otro

Ten en consideración #54.
