### ISSUE TITLE
Posición guindas en Frontend

### ISSUE THREAD

**Issue by agustinespildora** [IIC2233/syllabus-2018-2#680]
Holaa
En la actividad me tocó alguien que guarda correctamente las guindas en un objeto ``Guinda`` en el backend, pero los atributos correspondientes a la posición de las guindas son definidos en el frontend, es decir, ocupa ``randint`` en el frontend, pero es la única operación lógica realizada ahí. ¿Le asigno medio puntaje en el item de Correcto uso de Frontend o es perdonable?

**Comment by TrinidadVargas** [comment]
Hola, tengo una pregunta muy parecida

Si se define las posiciones de las cherrys en el fronted con `randint`  ,pero no se guardan. Y en el backend no hay nada para las cherrys
¿Se descuenta solo en el fronted por definir las posiciones ahí, o también en el backend?

**Comment by entamburini** [comment]
Para @agustinespildora, dado que es parte de la lógica del programa, debes descontarle la mitad :( 

En el caso de @trinivargas, sólo se descuenta en frontend por definir las posiciones ahí. 

Que estén bien! ✌️
