### ISSUE TITLE
Teclas WASD

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#681]
Leí la otra issue sobre esto pero no me quedó claro cuánto puntaje asignar en cada dirección si es que utilizó WASD en vez de las flechas. Además se indicó dentro del archivo a corregir que el ayudante le dijo que era completamente válido hacerlo así durante la actividad y que lo indicara en un comentario para que el corrector (yo) lo viera.

**Comment by bimartinez** [comment]
Hola! 

Como se dijo en la issue #569:

>Lamentablemente las instrucciones decían explícitamente cuales eran las teclas a ocupar para el movimiento del personaje (en este caso las flechas) así que el puntaje asignado en esta ocasión es 0.

Saludos!
