### ISSUE TITLE
Sprites Peer Review

### ISSUE THREAD

**Issue by TrinidadVargas** [IIC2233/syllabus-2018-2#682]
Si en las sprites todos los movimientos funcionan bien excepto cuando se mueve hacia abajo. La función `keyPressEvent()` esta bien hecha, pero por usar ` keyReleaseEvent()` hay un problema
Ahí cambia el sprite normalmente y justo después cambia al 1 (porque key release event cambia al sprite1 )

Esto se merece todo el puntaje por ser un error por haber implementado una función extra y solo en el caso Down o la mitad del puntaje?

**Comment by entamburini** [comment]
Hola @trinivargas! 

Mitad de puntaje está bien, porque funciona en la mayoría de los casos y en uno específico se cae. Si consideras que es algo muy pequeño puede ser perdonado, para esto mira si cambiando una o dos lineas se puede arreglar :D 

Saludos! ✌️
