### ISSUE TITLE
Método del backend desde el front, peer review

### ISSUE THREAD

**Issue by jmndoza** [IIC2233/syllabus-2018-2#683]
Hola, en el item de 'Modelación del programa: Buen uso de señales' indican:

> Todas las conexiones entre el frontend y backend se realiza a través de señales. Si realiza un llamado directo a un método del backend (desde el frontend) o del frontend (desde el backend), 2.5 puntos. Si realiza más de un llamado a un método de forma directa, 0 puntos.

el problema es que las 3 actividades que estoy revisando (incluida la mía) se basan en solución de la ayudantia  AY10, en la que se utiliza el metodo move() desde el frontend.. y pertenece al backend

cuantos puntos corresponden?

**Comment by jmndoza** [comment]
ah, error mio... confusión entre metodo move del backend y el move de pyqt

(no se como eliminar la issue)

**Comment by entamburini** [comment]
Hola @jerrymendoza! 

**Mucho ojo**, los métodos `move()` que se utilizan en el _backend_ vs en el _frontend_ son **diferentes** en la ayudantía. Una es un método perteneciente a un `QLabel`  en el _frontend_ y la otra es el método `move()` del `backend_character`.

Se aplica el criterio descrito que tu mismo citaste.

Saludos! ✌️

**Comment by entamburini** [comment]
jajajj no te preocupes, yo lo cierro después ;)
