### ISSUE TITLE
Zip mal hecho AC10

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#684]
Hola!!
De curiosidad, baje el zip de mi propia actividad para la autoevaluacion. La cosa es que dentro de este no estaba incluido mi backend :( Busqué el commit a revisar que me publicaron en la issue y el commit si incluia todos mis archivos relevantes. Leí hace poco que alguien subió una issue  sobre que uno de sus zips a revisar no tenían backend y ahora me da miedo que haya pasado algo así con mi actividad... ¿Qué pasó aqui?

Saludos!

**Comment by Hernan4444** [comment]
@gatochico acabo de bajar el zip con tu nombre y descomprimí el archivo con la contraseña que tu tienes en tu issue y como podrás ver en la imagen:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/15641721/47878279-a4bac200-ddfc-11e8-9017-3833c5b3bbc3.png">

El primer archivo que veo es el backend.py, puede ser que accidentalmente eliminaste el archivo cuando descomprimiste o no lo viste, no sé, pero al menos, para tu tranquilidad, los pokemones generados a partir de tu actividad si tienen el backend.py.

Saludos ✌️

**Comment by gatochico** [comment]
Bajé de nuevo el zip y si vi backend está vez, ups 😞 
Gracias!
