### ISSUE TITLE
id repetidas en db

### ISSUE THREAD

**Issue by faandrade** [IIC2233/syllabus-2018-2#685]
Hola! quería preguntar si los id repetidos en la base de datos son un error o se permite que esto ocurra.

**Comment by jeschuwirth** [comment]
Saludos,
si podrías dar un ejemplo del archivo y lineas que están repetidos para poder revisarlos.

**Comment by faandrade** [comment]
En el caso de db small, sólo los id 50 y 51 están repetidos y corresponden tanto a centrales.csv como a transmision.csv.
El caso de db large es mas drástico, de hecho hay ids que se repiten hasta 4 veces, por ejemplo los id 0,1,2 y 3 están en todos los .csv menos en casas, sería muy extenso dar el detalle de todos los id que se repiten y cuantas veces pero un buen resumen es que desde el id 0 hasta el id 234 aparecen, al menos, en dos bases de datos distintas.

**Comment by dgfluxa** [comment]
Según la issue #524 los id son únicos para el tipo de entidad asi que puede existir una casa y una central con el mismo id.
