### ISSUE TITLE
Corrección T01

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#686]
Hola, estoy viendo el feedback de la recorrección de la T01, y todavía no se me responde una duda:
En la parte de consultas de la T01, en las funciones se me coloca "No se explicita retorno de consulta". ¿Cuando se debía explicitar o qué se debía explicitar, aparte de retornar los resultados de la consulta?

Gracias de antemano.

**Comment by santilaguna** [comment]
Estimado,

Te recuerdo que debes seguir las reglas del foro #6  . Si tienes alguna duda con respecto a los criterios de corrección puedes enviarla al mail de ayudantes =D. Pero lamentablemente, este no es el medio.

Saludos
