### ISSUE TITLE
Commit a revisar T03

### ISSUE THREAD

**Issue by johntrombon** [IIC2233/syllabus-2018-2#687]
Hola! Se supone que accedí al beneficio de los dos días extra por el tema del setattr/getattr (recibí un mail de mi profe y todo), sin embargo en mi repositorio sale que el commit a revisar es anterior al último que hice. ¿Lo ignoro o debería preocuparme? Gracias.

**Comment by Hernan4444** [comment]
Hola, debes ignorarlo, ese es el commit para recibir sin ningún beneficio. Durante el día de mañana (mejor dicho hoy después de dormir), a todo aquel que está beneficiado, se le indicará el nuevo commit.

Saludos ✌️
