### ISSUE TITLE
Cuerpo del correo, extensión de 256 caracteres y saltos de línea

### ISSUE THREAD

**Issue by NachoJuanDev** [IIC2233/syllabus-2018-2#69]
Hola buenas,

Para enviar un correo, me gustaría implementar saltos de lineas en los cuerpos para poder separar párrafos y/o no escribir todo el cuerpo en una sola línea. 

Al hacer esto aparecerían los '\n'. ¿Debo considerarlos en los 256 caracteres?

Saludos

**Comment by cilopez** [comment]
Si, ya que son dos carácteres ASCII  \ y n.
