### ISSUE TITLE
Fernando Cervessa - Shame U.U

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2233/syllabus-2018-2#690]
Se señala que con este poder las direcciones se invierten entre izquierda y derecha, pero esto tmbn incluye a arriba y abajo?

**Comment by FernandoPieressa** [comment]
Hola!

Recuerda que el movimiento es siempre derecho, por lo que los botones de arriba y abajo no se usan!

**Comment by felipegarcia98** [comment]
oh my, mejor me voy a acostar
