### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#691]
Para esta tarea ¿nos van a brindar los distintos sprites que se ocupan ?, o ¿solamente las tenemos que hacer o sacar de internet?

**Comment by Arcoirisky** [comment]
busquen en internet si necesitan sprites para avanzar en su tarea. Pueden ser los que quieran ouo)/ 
Pueden crearlos ustedes mismos si quieren pero apoyo la idea del internet xDD

**Comment by FJavierOss** [comment]
Como recomendación los sprites generalmente los obtienen en una spritesheet como un .png con varias imagenes. Para desempaquetar esas imagenes busquen por internet "sprite unpacker", ese tipo de software los ayudara. Suerte en la tarea :smile:
