### ISSUE TITLE
Eliminación simultánea 2.1.1

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#692]
En la parte donde explican la eliminación simultánea, cuando ambos pierden se suma solo 1 punto a Charlie y 1 a Alice. Dado que Charlie ganó, no debería sumar 2 a Charlie?

**Comment by jeschuwirth** [comment]
Saludos, 
efectivamente Charlie debería haber ganado 2 puntos, ya que se eliminaron 2 jugadores. Por lo tanto los puntajes luego del choque serían:
Alice, 4
Bob, 4
Charlie, 7
