### ISSUE TITLE
Poder 'Fernando Cervessa' acumulable

### ISSUE THREAD

**Issue by degutierrez1** [IIC2233/syllabus-2018-2#693]
Hola, quisiera saber si el efecto de este poder es acumulable.

Por ejemplo: si activo el poder una vez y, dentro de su duración, activo otra vez el mismo poder ¿Las teclas se vuelven a invertir (o sea, queda 'normal') o solo se prolonga su duración?

**Comment by Arcoirisky** [comment]
Está a tu criterio :D Igual recuerda comentarlo en el Readme 💕

**Comment by degutierrez1** [comment]
Gracias !

**Comment by nebil** [comment]
Aunque claro, por experiencia personal, cuando me tomo una pinta de cerveza, los efectos no suelen revertirse al beber otra pinta de cerveza. De hecho, si fuera así, la vida sería bastante más fácil. :thinking:
