### ISSUE TITLE
Form de entregable T04

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#694]
Hola, 

tenía una duda de donde subir el entregable de la T04?

Gracias.

**Comment by Arcoirisky** [comment]
Holaaa es en un Google Docs!! Ya se les dirá donde y cómo enviarlo ouo

**Comment by Kitaps** [comment]
?

**Comment by Arcoirisky** [comment]
Al final era Form y se les envió un correo sobre eso hace unas horas
