### ISSUE TITLE
Errores en PyQt5

### ISSUE THREAD

**Issue by jjaguillon** [IIC2233/syllabus-2018-2#695]
A pedido del público:

¿Cansado de caídas de PyQt5 sin saber el error? Evita utilizar mucho de try/except o de print para saber tu error con el siguiente código:

``` python 
if __name__ == '__main__':
    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook

    app = QtWidgets.QApplication([])
    mi_juego = MiJuego(*args)
    mi_juego.show()
    app.exec() 
```

Implementa el siguiente código en tu main antes de instanciar tu backend o frontend y ya no se caerá tu programa.

Código de cortesía de [@MainScientist](https://github.com/MainScientist)

**Comment by naoliden** [comment]
Si se cae, imprimirá el error.
