### ISSUE TITLE
Giro con cambios de velocidad

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#696]
Al momento de generar un cambio de velocidad, el radio con que gira la figura ¿se debe conservar o cambiar respecto al cambio de velocidad?

**Comment by cilopez** [comment]
Hola @fjlopez7 , ante un cambio de velocidad debes conservar el radio 😄 
Edit: En el caso que conservarlo te produzca dificultades, puedes cambiarlo y mencionarlo en tu readme.
