### ISSUE TITLE
Duda Creación de usuarios

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#697]
Hola!!!!

Quería saber si tengo que poner algún tipo de restricción en la creación de usuarios (como no usar :, ;, *, etc.) además de el ver que no este repetido? O puedo asumir que ingresaran usuarios "buenos"?

Saludos! :cat:

**Comment by javierabao** [comment]
Hola! Puedes poner las restricciones que a ti más te acomoden, pero queda a tu criterio. Lo importante es que no haya usuarios repetidos ni claves incorrectas al ingresar. Y sobretodo, que la interfaz avise qué tipo de error se produjo al hacer ingreso o registro.
