### ISSUE TITLE
Cambiar sprites en giros

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#698]
Los sprites de las figuras pueden ser fijos, o deben ir cambiando (cambiando el sprite o girando la figura) con los distintos giros? ¿Puede ser como queramos?

**Comment by fernandodediegoavila** [comment]
Hola! Tus sprites pueden ser fijos (no es necesario que rote), sin embargo no se vería muy bien (como opinión personal). Si tienes este problema podrías usar algún sprite que no requiera de rotación, para que se vea mejor. Sin embargo, esto NO es necesario.
Saludos!

**Comment by Kitaps** [comment]
No tienen que girar entonces?

**Comment by Arcoirisky** [comment]
Si quieres tú Sprite puede ser un punto xD

**Comment by jeschuwirth** [comment]
@Kitaps por si no quedo claro con la explicación de @FernandoDeDiego, no es necesario que rote el sprite
