### ISSUE TITLE
PyQt5 lento

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#699]
Hola!

La interfaz de PyQt5 se pone lenta cuando hay hartos objetos en la interfaz (cuando hay harto dibujado). Investigué y salía que era problema de la librería, no encontrando solución.

Supongo que esto afecta al juego, ya que la “velocidad” va disminuyendo gradualmente.

Qué puedo hacer en este caso? 
Gracias!

**Comment by Arcoirisky** [comment]
Más que la librerías es que no utilizas señales para mover tus objetos. 

Señales 4TW
