### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by fabarros** [IIC2233/syllabus-2018-2#7]
Hola! es muy terrible si uso Python 3.7 en vez de Python 3.6.x? Me di cuenta recién que instalé Python 3.7 y ya instalé numpy, simpy, PyQt5 blablá :(
Saludos!

**Comment by Drpinto1** [comment]
Hola!
Generalmente no es _muy terrible_ usar python 3.7 en lugar de 3.6.x, pero puede llegar a serlo y si bien puedes quedarte con esta versión  __NO es recomendable__ que lo hagas, principalmente por dos razones: 

-  Todas las correcciones, de actividades y tareas, se harán utilizando python 3.6.x, por lo que si algún programa no corre debido a diferencias entre las versiones, esta no será una justificación válida para optar a la recorrección de dicha evaluación. 

- A medida que el curso avanza, se utilizan más, y más complejas, librerías y es ahí cuando los problemas de compatibilidad empiezan a aparecer y tener que reinstalar python (y las librerías necesarias) a mitad de semestre es un gasto innecesario de valioso tiempo de ~sueño~ estudio.

En resumen, puedes utilizar la versión que tienes instalada de python, pero será bajo tu propio riesgo, por lo que la opción más segura es que cambies a 3.6 lo antes posible. Para esto, la mejor manera sería desinstalar la versión de python que instalaste y seguir los pasos de la [wiki](https://github.com/IIC2233/syllabus/wiki/Software-Obligatorio) para instalar la versión correcta.
Saludos :smile:

**Comment by fabarros** [comment]
Perfecto! Gracias por la información y tu consejo. Yo creo que voy a
instalar Python 3.6.
