### ISSUE TITLE
Error al hacer push

### ISSUE THREAD

**Issue by bgsamilla** [IIC2233/syllabus-2018-2#70]
Hola tengo un error al intentar subir unos cambios en la tarea que deje pendientes en mi ordenador de escritorio.
Supongo que se deben a los push que hice con el notebook hoy en la actividad.

Si hago pull perderé los avances que no he subido?
Como hago para evitarlo?

**Comment by naquiroz** [comment]
Hola!
### **Respuesta corta a tu pregunta**
No, hacer pull en **tu respositorio personal** (lo destaco porque puede ser que tu error se deba a que estas intentando subir cosas a otro repositorio) no hace que pierdas los avances que no haz subido, pero tampoco se usa para actualizar tu repositorio.
 
### **Respuesta larga a tu pregunta**
Cuando haces pull en un repostiro, estas descargando los _commits_ que no tienes en tu repositorio local. Sin embargo, cuando los "descargas" con `git pull`, lo que va a intentar hacer git es "unir" tus _commits_ con los _commits_ del _repositorio online_  a traves de lo que se conoce como _merge_. Un merge es al final un _commit_ que une dos _commits_ de distintas fuentes. En general esto no trae problemas, a menos que  los commits que se están uniendo, hayan trabajado el/los mismo/s archivo/s.

Dicho esto, mi opinion personal es no intentar resolverlo con un `git pull`. Primero fijate en las siguientes opciones y trata solucionarlo de esta manera.

1. 100% Seguro que hiciste al menos un nuevo commit?.
2. Estás en tu repositorio personal? o en Syllabus? Procura esta un repositorio personal .
3. Que error te tira al intentar subir los cambios a la tarea? Lo googleaste?

Si aún tienes problemas con subir los cambios, no dudes en commentar esta issue!

:v:
