### ISSUE TITLE
movimiento por Ticks

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#700]
Hola, 

tenía una duda respecto a si recomiendan hacer el juego con ticks o como, 
porque queremos que todos los jugadores se muevan igual de harto, entonces si son simplemente 2-4 threads corriendo libremente, independiente uno del otro puede que derrepente uno avance más que el otro. 

Me estoy complicando solo o deberíamos considerar eso y hacer que cada thread avance lo mismo en cada tick?

**Comment by jeschuwirth** [comment]
Hola!

Eso queda a tu criterio, es cierto que si lo haces con threads puede que uno avance más que otro, pero eso no va a significar descuento la hora de la corrección y es más sencillo que lo otro. Cualquiera sea el caso recuerda ponerlo en el readme por si el ayudante tiene problemas con tu código.

En general, por simplicidad recomendaría usar threads.
Suerte en la tarea :D

**Comment by cilopez** [comment]
Para profundizar, en los juegos en general existe un _delta time_, que permite que los desplazamientos sean homogéneos y no depende demasiado en lo que tu computador está haciendo (aún así los juegos se pegan). 

En el caso de la tarea mediante _Networking_ podrías crear un _delta time_ del servidor que de el "_visto bueno_" de que efectivamente los jugadores se muevan, es decir si se aprieta W ,se envía una señal que el jugador 1 apretó W al servidor, este  ve a que tiempo delta pertenece esta señal y finalmente envía esa información a todos los jugadores y actualiza el mapa ,**incluyendo la del jugador que apretó la tecla** (es decir este no se mueve hasta que el servidor lo diga).  

Si bien podrías hacer que cada jugador se mueva inmediatamente en su interfaz eso puede causar que las pantallas de juego se vean distintas. Puedes aplicar esto en la tarea (sería una modelación más correcta), pero podría sumar mayor dificultad y **no es obligatorio**.


PD: Para los que quieran saber más del tema pueden leer el siguiente link que se explica el delta time pero no desde una perspectiva multijugador https://www.parallelcube.com/es/2017/10/25/por-que-necesitamos-utilizar-delta-time/
