### ISSUE TITLE
[Interfaz Gráfica] Dudas generales

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#701]
Buenas, tengo unas dudas generales sobre la interfaz gráfica:
1. ¿Que tanta libertad podemos tener al momento de implementar la interfaz? Por ejemplo no habría problema si (aparte de cumplir con lo propuesto en el enunciado) agregamos otras funcionalidades a nuestra interfaz, ej: agregar mas botones, etc.
2. ¿Todas las ventanas que diseñemos tienen que poseer un Grid? ¿O podemos asumir que al momento de corregir la tarea, la modificación de las dimensiones de las ventanas no será un concepto de descuento?
De antemano muchas gracias
PD: Encuentro que sería bueno que se deje esta issue para este tipo de preguntas (preguntas que no son tan directas respecto a funciones que debe seguir nuestro programa según el enunciado, sino preguntas sobre las cosas extras que nosotros podríamos implementar)

**Comment by FJavierOss** [comment]
Saludos,

1. No hay problema, el enunciado es para las cosas mínimas, si se desea agregar más cosas no se genera descuento, eso si no es recomendable que se distraigan de cumplir las cosas que se piden en el enunciado por incluir funcionalidades que no se les requirio.

2. No deberian de preocuparse por lo de un Grid, pueden asumir que la modificación de las dimensiones de las ventanas no serán concepto de descuento.

Mucha suerte en la tarea :smile:

**Comment by FJavierOss** [comment]
Eso si, no es recomendable que la interfaz sea más grande que la pantalla común de un notebook, porque eso implicaria que el juego no se podria desempeñar correctamente en todos los computadores. Por lo que algo sobre 1080x720 pixeles es excesivo. Idealmente más chica. 

PD: Por otro lado, si quieren avanzar más rapido entre hacer código y probar varios clientes al mismo tiempo, les conviene hace una interfaz de tal tamaño que puedan haber abiertas dos interfaces de dos clientes distintos en la misma pantalla de computador. De esa manera podrán ver instantaneamente el funcionamiento de su codigo y como funcionan sus dos clientes sin tener que recurrir a otro computador necesariamente.
