### ISSUE TITLE
PyQt5 problemas con señales para abrir otra ventana

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#703]
Tengo definida un clase para un ventana que hice en Qt Designer y hago todo lo que sale en los contenidos y funciona, pero al momentos de hacer que con un botón se cierre la ventana actual y se abra otra, mi programa se termina, que puedo estar haciendo mal?
Para iniciar la ventana hago esto:
```python
if __name__ == "__main__":
    app = QApplication([])
    form = VentanaBienvenida()
    form.show()
    sys.exit(app.exec_())
```

y hago esto en la función del evento:

```python
self.hide()
ventana_registro = VentanaRegistro()
ventana_registro.show()
```

**Comment by jeschuwirth** [comment]
Saludos,
Lo comentamos un par de ayudantes y no logramos encontrar el posible problema con la información que hay, mándame un mail con el código completo para ver si puedo ayudarte. Mi correo es mi usuario de github @uc.cl

Espero una respuesta :)

**Comment by joaquinhernandezg** [comment]
Graciaaaas ya encontré el problema, era poner esto:
```python
self.hide()
self.ventana_registro = VentanaRegistro()
self.ventana_registro.show()
```

**Comment by Arcoirisky** [comment]
No la cierres aún ouo) puede que alguien tenga el mismo problema :O
