### ISSUE TITLE
Eleccion de controles y sala de espera

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#704]
Luego de ingresar un usuario correcto, es posible  redireccionar al usuario a una ventana donde este puede solamente escoger las teclas que usara para moverse **y luego** introducirlo a una sala de espera? O la elección de estas teclas debe ser realizada mientras se espera una partida? o da lo mismo?

**Comment by Arcoirisky** [comment]
La verdad queda a tu decisión cómo lo haces, mientras cumpla con el enunciado estará bien :D
