### ISSUE TITLE
Única ventana de inicio

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#706]
Hola!

En la tarea 04, puedo hacer que mi programa tenga una única ventana de inicio? Es decir, que esta sirva tanto para iniciar sesión como para registrarse? Obviamente dejando clara la funcionalidad.

Saludos.

**Comment by FJavierOss** [comment]
Estimado, espero poder aclarar tu duda, el enunciado entrega la posibilidad de elegir entre abrir dos ventanas o modificar la ventana de inicio inicial, que es lo que aparece entre paréntesis en el primer párrafo de la sección 4.1

> Dependiendo del botón presionado, se abren dos ventanas (o se modifica la ventana de inicio) para que ...

Si es que crees que no comprendí correctamente la duda que tenías, házmelo saber.

Saludos y suerte en tu tarea :smile:
