### ISSUE TITLE
Problema abrir archivos .ui

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#708]
Hola! Tengo problemas al intentar abrir la ventana que hice en QtDesigner con Python, me aparece esto:
`Traceback (most recent call last):
  File "C:\Users\rleiv\Documents\U\2018\S2\IIC2233-1\Prochotito-iic2233-2018-2\Tareas\T04\cliente\front_end\front_end.py", line 9, in <module>
    window_name, base_class = uic.loadUiType('hola.ui')
  File "C:\Users\rleiv\AppData\Local\Programs\Python\Python36\lib\site-packages\PyQt5\uic\__init__.py", line 198, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
  File "C:\Users\rleiv\AppData\Local\Programs\Python\Python36\lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 110, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "C:\Users\rleiv\AppData\Local\Programs\Python\Python36\lib\site-packages\PyQt5\uic\uiparser.py", line 1013, in parse
    document = parse(filename)
  File "C:\Users\rleiv\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "C:\Users\rleiv\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'hola.ui'
`

He revisado hartas veces el código y no es un problema de tipeo :/, probé con el ejemplo de los contenidos. 
Saludos!

**Comment by bimartinez** [comment]
Hola @Prochotito,

Lo que te señala ese error es que el archivo que intentas abrir `hola.ui` no se encuentra en la carpeta, en este caso dentro de `C:\Users\rleiv\Documents\U\2018\S2\IIC2233-1\Prochotito-iic2233-2018-2\Tareas\T04\cliente\front_end\`. Revisa bien eso y dime como te va.

Saludos!

**Comment by Prochotito** [comment]
si está ahí :((((( 
![imagen](https://user-images.githubusercontent.com/39094323/48286704-3fdb1980-e445-11e8-938e-51ab4cd611bf.png)

**Comment by inveterate-cladocerus** [comment]
si está en la carpeta :(

**Comment by bimartinez** [comment]
Ojo! :eyes: 

Que según la imagen que muestras no existe ningun archivo `hola.ui` en la carpeta :file_folder:

**Comment by inveterate-cladocerus** [comment]
jajaja si es que le había cambiado el nombre a "qt-designer-mainwindow.ui", pero igual no funciona

**Comment by bimartinez** [comment]
Vuelve a cambiar el nombre a `hola.ui` y vuelve a ejecutar tu programa y dime que pasa.

**Comment by inveterate-cladocerus** [comment]
lo volví a intentar y me sigue tirando error, así que saqué todo el código que tenía y solo dejé 
`from PyQt5 import uic
window_name, base_class = uic.loadUiType("hola.ui")`
y la carpeta en la que tengo los archivos es esta
![imagen](https://user-images.githubusercontent.com/39094323/48287099-75cccd80-e446-11e8-86d0-51b751c8c33e.png)
y aún así me sigue tirando el mismo error.

**Comment by bimartinez** [comment]
Intenta probar con el *path* absoluto hacia el archivo (`C:\Users\rleiv\Documents\U\2018\S2\IIC2233-1\Prochotito-iic2233-2018-2\Tareas\T04\cliente\front_end\hola.ui`). Si no te funciona pushea tu código a tu repo para echarle una mirada.

Saludos!

**Comment by inveterate-cladocerus** [comment]
Ahí me funciono!!!! Pero @bimartinez, por qué no funciona con el path reativo?

**Comment by bimartinez** [comment]
**Probablemente** PyQt al momento que le entregaste el path relativo no tomó como carpeta raíz desde donde ejecutaste tu código. El hecho de poner el *path* absoluto obliga a PyQt a dirigirse al directorio específico que le señalas.

Saludos!

**Comment by inveterate-cladocerus** [comment]
Gracias, te pasaste!

**Comment by IchottMano** [comment]
@Prochotito Hola! 
Se que la duda ya está resuelta, sin embargo recomiendo fuertemente que no **hardcodees** el path absoluto. Para hacer esto sin que se rompa tu tarea porfavor lee la documentación de la librería [os](https://docs.python.org/3/library/os.html). Con esto podrás seguir entregandole el path absoluto a tus funciones, pero adecuándolo al path del computador de la persona que está corriendo tu código.
Saludos!
