### ISSUE TITLE
Problema con sprites y color de fondo

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#709]
Hola, estoy intentando hacer un área negra de juego en mi interfaz. Para eso decidí hacer un Qlabel para así poder ir cambiando el tamaño. Puse el fondo de otro color para que así se vieran los limites de esta área claramente. El problema es que los sprites usan el color del fondo como se muestra en la imagen:

![image](https://user-images.githubusercontent.com/42191903/48293912-15e32080-e460-11e8-8f89-ae496d60d7d6.png)

Quería saber si hay alguna forma de evitar esto o mejor aun si hay alguna forma de "pintar" una sección del fondo de pantalla o ciertos pixeles de un color (algo que igual necesitaré más adelante). No quiero usar una imagen de fondo porque después sería más difícil cambiar el tamaño. Estoy usando Qt designer para todo esto.  No se si lo que busco hacer se puede o no ni si tiene sentido o no de hacer. 
Gracias!

**Comment by camichavez** [comment]
Te recomiendo buscar otras sprites, en internet podrás encontrar varías páginas ya sea para editar las tuyas o unas de pacman ya hechas, que tienen el fondo transparente y el tamaño apropiado. Te recomiendo esto porque luego te podría afectar que el tamaño de tu imagen sea mayor a lo visible, espero se entienda a lo que me refiero, cualquier cosa puedes decirme :)

**Comment by gnacrur** [comment]
@Cschavez  gracias por tu respuesta. Se entiende perfecto. El sprite de pacman solo lo use para probar que funcionara bien. Este lo dieron en una actividad y no tiene fondo. Creo que el rectángulo gris se genera porque mi fondo es de ese color. El fondo no es negro, esa parte es negra porque hay un label negro que pretendía que sirviese para delimitar el área de juego. En esta imagen quizas se entienda mejor:

![image](https://user-images.githubusercontent.com/42191903/48294887-239ba480-e466-11e8-889d-48769220cd2c.png)

Aquí el sprite esta sobre el fondo real.

**Comment by camichavez** [comment]
Ah ya entiendo, intenta poniendole esto a tu Qlabel 
pacman = QLabel(...)
pacman. setStyleSheet("background-color: color que quieras;")

**Comment by gnacrur** [comment]
Ahí funcionó. Muchas gracias!!
