### ISSUE TITLE
Networking-Sockets

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#710]
Al trabajar con un servidor que haga varias cosas, por ejemplo, estar a la espera de que alguien pida validar usuarios, enviar información, etc. Como se implementa esto? Creando varios Threads, y que cada Thread inicie un socket en puertos diferentes y destinar cada puerto a una funcionalidad o se hace en un mismo socket y envio un diccionario (codificado), por ejemplo, con la solicitud que se quiere hacer y los datos a procesar.

**Comment by jeschuwirth** [comment]
Saludos,
Como aún no ven la materia de networking, te recomendaría hacer el resto de la tarea y empezar con esta parte luego de la ayudantía y actividad, pero te respondo tus dudas de todos modos.

Personalmente lo que encuentro más cómodo al trabajar con servidores es utilizar un thread se preocupe de escuchar nuevas conexiones de usuarios, y cuando un cliente se conecte se le asigna su propio thread a ese socket, de ese modo el servidor queda constantemente escuchando a todos los usuarios y esperando la llegada de nuevos.

En cuanto al envío de datos, el modo más legible es utilizar json para transportar diccionarios con toda la información importante.

Espero que eso te encamine en general, recuerda que la materia aún no la ven así que cualquier duda se puede preguntar en la siguiente clase. 

Animo con la Tarea :)
