### ISSUE TITLE
Lag excesivo en los giros

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#711]
Hola!
Encuentro que se tarda mucho en emitir la señal del `keyPressedEvent` hacia la función que hace rotar la trayectoria de mis personajes. ¿Es esto algo común, evitable, a alguien más le pasa?
Una vez que ya registra el `AutoRepeat` gira normalmente, pero es en cada "inicio" del giro que se demora aproximadamente un segundo en responder.
Agradezco si alguien me puede orientar con su experiencia.
Saludos!

**Comment by cacoos** [comment]
Yo usé la señal de _dejar de presionar_ también, así determino cuando empieza y termina de girar. 
Ojalá te ayude!

**Comment by viantirreau** [comment]
Funciona perfecto! Muchas gracias @cacosandon 💪

**Comment by jcechavarri** [comment]
> Funciona perfecto! Muchas gracias @cacosandon 💪
@viantirreau 

Por casualidad al utilizar ambas señales no se te demora también una fracción de segundo en empezar a girar? (Nada excesivo pero un poco molesto)
