### ISSUE TITLE
Qt Designer

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#712]
Hola!

Cuando intento crear un nuevo proyecto en Qt Designer, me da estas opciones:
![captura de pantalla 2018-11-10 a la s 10 41 24](https://user-images.githubusercontent.com/42193915/48302005-47e29a00-e4d5-11e8-8173-d6e38628c81e.png)
Elijo la opción Qt Widgets Application y al crearlo, se me crea una carpeta con muchos archivos y no solo el archivo .ui que es lo que quiero
![captura de pantalla 2018-11-10 a la s 10 41 40](https://user-images.githubusercontent.com/42193915/48302010-60eb4b00-e4d5-11e8-9a37-d2c3cffd8865.png)
Como puedo cambiar esto? Estoy creando muchos archivos innecesarios

Gracias!

**Comment by naoliden** [comment]
Me parece que estas usando el programa equivocado. Busca el que se llama solo "Designer", el que tienes ahí si no me equivoco es para hacer cosas en C. 
El que necesitas se ve así en mac:

<img width="885" alt="screenshot 2018-11-10 at 11 28 31" src="https://user-images.githubusercontent.com/8712696/48302443-cd694880-e4db-11e8-87e8-1ee31c81a01d.png">

**Comment by Marialuisaclaro** [comment]
Ya me di cuenta que estaba haciedndo mal. Tenia que crear un new file y no new project.
En todo caso, descargué Qt Creator, eso está mal?

**Comment by naquiroz** [comment]
@Marialuisaclaro técnicamente sí. Pero en la práctica, si entiendes como usarlo, Qt Creator es casi lo mismo que Qt Designer

**Comment by chocopiano** [comment]
@Marialuisaclaro como lo hiciste? A mi solo me sale la opcion de crear new project

**Comment by Marialuisaclaro** [comment]
@chocopiano pon en el menú de arriba File-> New file or project
