### ISSUE TITLE
archivos, bytes y strings

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#714]
Hola!
Como se puede hacer para escribir y leer archivos que tienen bytes y strings?
Tengo un archivo que tiene los nombres de los usuarios como string y la contraseña codificada (bytes), al escribir la contraseña en el archivo esta queda guardada como string.
Al leer el archivo la contraseña queda como string y no puedo trabajar con ella como bytes, me queda un string de la forma "b'\x...\x...".
Como puedo convertir ese string a bytes?
O es recomendable escribir todo el archivo con wb? En ese caso no se como leer por lineas y usar un split() para separar entre nombre y contraseña. ¿Como se haría?

Gracias!

**Comment by Arcoirisky** [comment]
Si es que entendí bien tu problema.
Debes decodificar ese pedazo que quieres como bytes o:
Mira este [link](https://stackoverflow.com/questions/7585435/best-way-to-convert-string-to-bytes-in-python-3) <-- a ver si te ayuda con tu problema.
