### ISSUE TITLE
Threads, Qthreads y signals

### ISSUE THREAD

**Issue by johntrombon** [IIC2233/syllabus-2018-2#715]
Hola!
- ¿Que diferencias tienen, en la práctica, las Qthreads de pyqt con las Threads importadas desde el módulo threading?
- Al estar realizando dos procesos dentro de una gui, comunicándose por signals, ¿Corren de forma paralela, es decir, hay algún tipo de threading ocurriendo por debajo, o es secuencial? 🤔

**Comment by bimartinez** [comment]
Hola @jtescobar1,

1.- Básicamente sus objetivos son los mismos, poder realizar tareas de manera paralela. Pero los *QThreads* están creados y optimizados para trabajar de manera conjunta con la librería `PyQt`, ya que tienen funcionalidades específicas para interactuar con elementos de este módulo. Para mas información puedes visitar [este link](https://stackoverflow.com/questions/1595649/threading-in-a-pyqt-application-use-qt-threads-or-python-threads).

2.- Técnicamente depende de tu modelación, pero te pregunto, ¿cómo sería la vida si cada vez que ocupamos una aplicación o un juego (incluso nuestro propio computador) tuviéramos que esperar a que cada proceso que se ejecuta terminara?, básicamente sería insoportable dada la cantidad de operaciones que realiza un computador. Lo más natural es ejecutar tareas en paralelo para que estas no afecten nuestro uso de la GUI a menos que sea estrictamente necesario. Ahora respecto a las *signals*, el objetivo de estas es comunicar elementos entre ellos, no necesariamente tienen que ser procesos (por ejemplo, si yo envío una señal desde un *QThread* hacia un *QLabel* para actualizar su contenido, estoy comunicando un proceso con un objeto que no hace nada mas de mostrar información). Pero en el caso de estar comunicando procesos, necesitas que estos estén corriendo en paralelo porque si fueran secuenciales ¿cómo voy a comunicar un proceso con algo que aún no existe?.

Saludos!

**Comment by johntrombon** [comment]
Gracias! 💯

**Comment by fgbruna** [comment]
Como anexo a la respuesta de @bimartinez, @jtescobar1 si bien no deberías preocuparte de esto para tu tarea, es bueno saber que tanto los `QThreads` como los threads de python están limitados por el [GIL](https://stackoverflow.com/a/1645666) cuando ejecutan código de python.En simples palabras este es un lock global para el **intérprete de python**, es decir, solo un thread puede ser interpretado (ejecutado) en un cierto intervalo de tiempo(mientras no lo libere).Es por esto que, no puedes obtener "concurrencia real" para el código que tú escribes.
Dicho esto, aun así es preferible que uses `QThreads` cada vez que interactúas de una manera u otra con `Qt` ya que están hechos para trabajar con la librería(Especialmente por el sistema de señales y slots de c++).
Por último, [esta pregunta de stackoverflow](https://stackoverflow.com/questions/1595649/threading-in-a-pyqt-application-use-qt-threads-or-python-threads) tiene muchas respuestas que te pueden dar una idea de sus diferencias y las limitaciones de los threads de python.
