### ISSUE TITLE
Uso de QBasicTimer

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#716]
Hola! Estaría bien usar QBasicTimer en lugar de QTimer? Si bien en la documentación de qt se recomienda usar QTimer, QBasicTimer ha sido más fácil de entender y ha funcionado bien en el código que tengo.

**Comment by jeschuwirth** [comment]
Hola!,

No hay problema con utilizar QBasicTimer en vez de QTimer, si te hace más cómoda la tarea trabaja con ese. 

Suerte :)

**Comment by hbkim94** [comment]
Gracias!!
