### ISSUE TITLE
Descarga Qt Designer

### ISSUE THREAD

**Issue by chocopiano** [IIC2233/syllabus-2018-2#718]
Hola! Como puedo descargar de forma facil Qt designer para mac? Esto es debido a que a la hora de descargarlo me pide que tenga Xcode y este a la vez me pide OS X 10.13.6 o una versión posterior cosa que no he podido actualizar. Gracias

**Comment by ariel-m-s** [comment]
Hola!

Yo tuve que instalar Xcode. Lo más probable es que tengas que hacerlo tú también, además de actualizar el sistema operativo.

Salu391

**Comment by chocopiano** [comment]
Que sistema operativo tienes? Que estoy con OS x el capitan 10.11.6 y no me deja actualizarlo más, jajaja llevo todo el día tratando de actualizarlo a la versión que me pide y no puedo...

**Comment by fgbruna** [comment]
Hola @chocopiano , puedes intentar instalando [qt a través de homebrew](https://formulae.brew.sh/formula/qt).
Si te funciona, designer deberia estar en `/usr/local/Cellar/qt/<qtversion>/libexec/Designer.app`

**Comment by chocopiano** [comment]
@fgbruna no tengo idea porque pero no me funciona, @amartinezsilberstein Xcode tambien se te descargaba con .xip?, ya que al descargarlo aparece verificando y no se descomprime el archivo. Le esta ocurriendo exactamente lo mismo a un amigo.

**Comment by fgbruna** [comment]
y qué mensaje te aparece cuando intentas instalarlo con brew?

**Comment by chocopiano** [comment]
@fgbruna la verdad no sé si te estoy entendiendo mucho, pero me metí al link de homebrew y luego descargue Qt en el link https://www.qt.io/... pude descargarlo pero a la hora de instalación me pide Xcode.

**Comment by fgbruna** [comment]
Lo que te recomiendo es que instales brew en tu computador e instales qt a **través de homebrew**, no con el instalador de la página oficial.
Pero independiente de como quieras instalar qt, si buscas tu problema, uno de los resultados de google es [este](https://stackoverflow.com/questions/31554125/attempt-to-install-qt-on-os-x-gives-you-need-to-install-xcode-5-0-0-but-this).Ahí se menciona que el conflicto no es necesariamente por no tener xcode si no por no tener las xcode cmd tools(lo cual no requiere instalar xcode exactamente.).
Te recomiendo correr lo sgte:
```bash
xcode-select --install
```
y luego intentar instalar qt.
Si no te funciona, comenta el output que te entrega.

**Comment by chocopiano** [comment]
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by fgbruna** [comment]
y tienes instalado [`homebrew`](https://brew.sh/index_es) ?

**Comment by chocopiano** [comment]
@ Sí lo tengo instalado. Ahora pude descargar Qt pero era Qt Creator. Hay algun link especial para el Designer. jajaja la verdad es estoy desde el jueves tratando

**Comment by fgbruna** [comment]
Si puedes usar QtCreator genial, tiene hartas más cosas que designer que no vas a necesitar, pero lo incluye, así que te basta con buscarlo dentro de él.Esta issue está relacionada #712

**Comment by chocopiano** [comment]
No he podido lograr nada aún, me aparecen puras opciones de crear proyectos y todo relacionado a c++. Me podrías señalar como se instala Qt Designer por homebrew porfa

**Comment by chocopiano** [comment]
listo, se resolvio!! Gracias!!...carrete en mi casa

**Comment by fgbruna** [comment]
Encontraste la opción en creator o instalaste qt a través de homebrew?

**Comment by chocopiano** [comment]
encontre la opción en creator finalmente

**Comment by ariel-m-s** [comment]
@chocopiano @fgbruna Al menos cuando yo instalé ```Qt``` se me instalaron dos aplicaciones: ```Qt Creator``` y ```Designer```. Esta última se instala en secreto ajajaja así que intenta buscarla en la barra de búsqueda para encontrarla.
