### ISSUE TITLE
Tamaño fondo y Pintar rastro

### ISSUE THREAD

**Issue by isavega** [IIC2233/syllabus-2018-2#719]
Hola! Tengo 2 preguntas:

1. Cree una imagen para el fondo de mi juego, pero solo aparece una parte de ella (lo negro en la foto).
Estoy usando: setPixmap y resize(self.pixmap.width(), self.pixmap.height()). Lo que me funcionó para la actividad pero no ahora. 

2. En la imagen aparece como mi rastro atraviesa el "fondo" pero lo hace por debajo, como invierno la situación?

Gracias!

![pantallazo](https://user-images.githubusercontent.com/42187168/48448648-7a62f000-e77e-11e8-88d9-a895f34cd208.png)

**Comment by lily416** [comment]
Hola :)

1. Revisa si le estas dando la imagen a la ventana o a un label, en el caso de que sea lo último para agrandar el tamaño de la imagen también debes agrandar el label, aunque es más recomendable que el entreges la imagen al widget.

2. Asumiendo que la imagen del fondo esté guardada en un label o algún objeto de la clase QWidget, prueba utilizando las funciones `lower()` y `raise()`, sirven para llevar un objeto hasta el fondo o el frente respectivamente. 

Ojala te sirva 😄 
Saludos 👋🐍

PD: A veces es útil echarle un ojo a la documentación de [Qt](http://doc.qt.io/) tiene mucha información sobre los objetos que utilizan y funciones útiles 😉
