### ISSUE TITLE
ast.literal_eval

### ISSUE THREAD

**Issue by ftrejoc** [IIC2233/syllabus-2018-2#721]
Hola! quería saber si este comando (ast.literal_eval) se puede usar en la tarea. Seria ocupado para cuando tengo un byte en forma de string poder cambiarlo al tiro al formato byte. Esto lo digo para cuando guardo la "sal" y luego la necesito para verificar los registros.

**Comment by bimartinez** [comment]
Hola @ftrejoc 

Por favor este tipo de preguntas hazlas en #689.

Saludos!
