### ISSUE TITLE
Error al cambiar de ventana

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#722]
Hola!

estoy teniendo problemas a la hora de desplazarme de ventana en ventana en la interfaz. Lo que hice fué crear 3 QWidgets que serían mes ventanas de inicio, para registrarse y para iniciar sesion, los cuales estan ccontenidos en una QMainWindow, y lo que hice para cambiar de una ventana a otra es que cada vez que se quiera cambiar aplicaba el codigo

`self.setCentralWidget(self.ventana)`

y al principio funciona, pero cuando quiero volver a una ventana anterior arroja el siguiente error:

`RuntimeError: wrapped C/C++ object of type [...] has been deleted`

A que se debe este error?

**Comment by Arcoirisky** [comment]
Por lo que me da a entender, es que estas borrando la ventana que dejas atrás al cambiar a una nueva en vez de esconderla para usarla de nuevo o algo similar. 

Fíjate si no estas matando la referencia de self.ventana al pasar de ventana o: Según san Google y stackoverflow este link te puede explicar qué sucede (a pesar de ser para Pyqt4)

http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html

Aunque voto por que estas perdiendo referencia uwu)/
