### ISSUE TITLE
Thread vs QTimer 

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#723]
Hola!
Todavía estoy en el juego donde existe un usuario nomas (sin networking) y estoy complicada si usar threads o qTimer.

En primer lugar hice que mi personaje del backend fuera un thread, y en su método run puse un while True con todo lo que debe pasar en una iteración (moverse, revisar cosas, etc). El problema de esto es que el while avanza demasiado rápido entonces no se alcanza a percibir nada y no se si es buena idea poner un sleep o algo así.
Lo cambié entonces y empecé a utilizar Qtimer, donde se corre la función tic (que es la misma que el run del thread sin el while True)  con un Delay. De esta forma el juego se logra ver bien. 

Supongo que cuando existan más jugadores deberé implantar Threads para que se muevan al mismo tiempo y esas cosas, entonces, es mejor que vuelva a la primera forma? En ese caso, como hago que no corra tan rápido con el while True o como hago que corra la función indefinidamente?

Gracias!

**Comment by nachocontreras** [comment]
Hola!

Te dejo esta issue creada el semestre anterior que aclara el uso y diferencias de los QThreads y QTimers (cortesía de @fgvenegas).

## QTimers y QThreads:
### QThreads:
Los Qthreads siguen el mismo comportamiento que los Threads que fueron enseñados en el ramo, por lo que no debería presentarles mayor complicación aplicarlos en su tarea. Pero qué pasa si queremos utilizarlos para una acción que sabemos que se va a repetir constantemente ? Podríamos implementar algo así en el Qthread
```Python
def run(self):
    while True:
        # Lo que quiero que el QThread haga en cada iteración
        time.sleep(0.1) # Muy importante para que su interfaz no se quede pegada, el valor es ajustable
```
- ¿Con esto que tenemos ?: Un QThread que repite una acción una y otra vez.
- ¿Problemas?: Si.
- ¿Cuáles? ¿Cómo detenemos este Qthread?
En general detener (matar) un thread es una [mala practica](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread), la idea es que un Thread se inicie, cumpla su objetivo y muera al terminarlo, no que lo tengamos que detener por nuestra cuenta (mas detalles en el link, es interesante y útil)
Entonces siguiendo esta misma lógica estamos abusando del run del Qthread con un vacío legal.
- ¿Puedo detenerlo con break ? Si, hay casos donde alumnos usan Qthreads en toda su tarea y no tienen problemas, como experiencia propia, empezar a matar Qthreads a diestra y siniestra con este método no escalo bien.
### Qtimers
Otra forma de realizar lo que hacíamos con Qthreads es con Qtimers.

- ¿Cuál es la ventaja que tienen estos sobre Qthreads?:
Qtimers está pensado para que se repita una y otra vez lo que contiene su run sin necesidad de utilizar un while, recibe como parámetro al inicializarlo el tiempo cada cuanto se debe ejecutar y además posee un método stop para poder detenerlo "legalmente". Si, se ve más limpio en general que usar Qthreads, pero no asegura que su programa vaya a ser perfecto ni vaya a sufrir problemas de lag o caídas de interfaz, eso ya va en la programación de cada uno.
## Recomendación final
Son libres de usar ambos en sus tareas, los 2 son útiles y pueden tener una tarea 100% funcional ya sea con uno, el otro o ambos. Por ejemplo para objetos que existan en muchas cantidades y sea difícil controlar cuando interrumpirlos puede ser más útil utilizar un Qtimer con ellos, pero para objetos que permanecen constantes en el escenario o que son más fáciles de controlar un Qthread es una buena opción.
Experimenten ! Vean con cual les anda mejor, con cual es mas eficiente su tarea y averigüen mas por su cuenta, siempre es útil leer un poco antes de lanzarse a usarlo algo, y no olviden siempre comentar en el README este tipo de decisiones y porque escogieron lo que escogieron.

**Comment by jeschuwirth** [comment]
Saludos!
El problema que tienes puede ser solucionado de varias formas, te dejo un par por si alguna te gusta para agregarla a tu programa:

- **utilizar sleep():** como dijiste en el enunciado no es el mejor modo, pero te permite cambiar la velocidad de cada linea de manera muy sencilla y no vamos a descontar por su uso.

- **utilizar wait:** otra forma es dejar un wait en cada thread de modo que cada flecha sólo avance una vez que todas las demas hayan avanzado, y que esto ocurra cada cierto tiempo, tiempo el cual puedes cambiar para adaptar la velocidad del juego.

QTimer lo puede ver como una funcion dentro de un `while True` pero que la última línea del while es un `sleep()`.

Ojalá la respuesta te haya ayudado y guiado un poco para que puedas terminar tu tarea 

PD: Otro ayudante acaba de responder esto 10 seg antes que enviara lo mio, dejo la mia de todos modos por si te ayuda

**Comment by Marialuisaclaro** [comment]
Gracias!!
Una última pregunta, podría ser útil (o buena práctica) que el run del Thread ejecute lo que ocurre en **una** iteración (sin el While) y qué con Qtimer se ejecute "infinitamente" thread.start()??. De esta forma ya no tendré el problema de que el while funcione muy rápido, el thread se podrá detener solo y podré controlar el tiempo con Qtimer. 
Pensé que esto podría ser útil para manejar el movimiento de los personajes con Threads (y que sean independientes) y que el manejo del juego general se maneje con Qtimer, así el juego correrá infinitas iteraciones con qtimer, y en cada una de estas iteraciones se ejecutará el Start de cada personaje, haciendo lo que debe hacer en cada iteración. 
Mi duda es si está bien y/o es eficiente llamar al Start de un thread hartas veces, en vez de meter un while dentro del run y ejecutar el Start  una sola veces.


Gracias!

**Comment by Cadagan** [comment]
Se puede usar a QBasicTimer() en lugar de QTimer ??

**Comment by fgbruna** [comment]
@Cadagan #716

**Comment by jeschuwirth** [comment]
@Marialuisaclaro no puedes utilizar el método start() de un thread múltiples veces, una vez que un thread termina debes crear uno nuevo para hacer lo mismo, por este motivo te diría que te quedaras con un while dentro del thread que lo mantenga 'vivo' y que no termine hasta que se acabe la partida.

Espero que eso te ayude y suerte con la tarea :D
