### ISSUE TITLE
json Error 

### ISSUE THREAD

**Issue by lucasvsj** [IIC2233/syllabus-2018-2#725]
Tratando de "decodificar" un string con json.loads(), me salio el siguiente error:
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Estuve buscando salia que la causa es que json decodifica solo diccionarios con "" y no con '' en sus keys, pero ningún diccionario mio posee '' en sus keys.
Cualquier ayuda serviría.
De antemano muchas gracias.

**Comment by cilopez** [comment]
Hola @lucasvsj , ¿puede ser que los strings que estes enviando esten en single quotes?
me dices que tal

**Comment by lucasvsj** [comment]
Hola @cilopez , ese es mi problema (como dije, "" en los keys), pero no se porque ocurre, ya que me preocupe de poner " " en los keys y values del diccionario que estoy mandando. Es como si el programa los cambiase a ' ' solo, ya que al printearlos aparecen con ' ' en vez de " "

**Comment by cilopez** [comment]
Ah, perdon me refería a los strings en los values, puedes ver lo que comentaron el semestre pasado con la misma duda: https://github.com/IIC2233/Syllabus-2018-1/issues/756

**Comment by lucasvsj** [comment]
@cilopez  hay algun comando de json para ver lo siguiente:
line 1 column 2 (char 1)
?

**Comment by cilopez** [comment]
@lucasvsj mm, la verdad es que no estoy seguro pero creería que sería el primer caracter del json. sigues con problemas?

**Comment by lucasvsj** [comment]
@cilopez ya lo pude solucionar, gracias

**Comment by cilopez** [comment]
@lucasvsj me puedes decir cual era el problema alfinal, por si le sirve a otros alumnos

**Comment by lucasvsj** [comment]
@cilopez el problema es el que estabamos hablando (mi diccionario aparecia con '' en vez de "" aunque yo especificamente utilizaba solo ""). Por lo que utilice el comando .replace("\'", "\"") y se soluciono el problema
