### ISSUE TITLE
sprite jugador y Qt Designer

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#726]
Hola, por algún motivo, al trabajar con Qt designer, al hacer ventanas se ven de forma distinta en el designer a cuando se ejecuta en python. Además, a los sprites se les genera una especie de contorno rectangular. Este no se ve, pero al ponerle fondo de cierto color se logra ver. Me di cuenta de esto porque por alguna razón el rastro del jugador se pintaba harto más lejos que la ubicación del sprite. A fin de cuentas Qt Designer me esta generando muchos problemas visuales ya que no se están configurando bien las coordenadas de las cosas. 
Ante esta situación me interesaría saber si implicaría algún descuento no usar ningún sprite para los jugadores y que simplemente sea una linea que se va moviendo. No me refiero a usar un círculo o algo por el estilo, me refiero a no poner nada. Además, quería saber si saben de alguna solución para lo que me sucede con la geometría de mis ventanas al pasarlas de Qt Designer a python o si recomiendan hacer la ventana de juego de otra forma para evitar el problema?

**Comment by Arcoirisky** [comment]
Sobre los Sprites ¿te refieres a que solo se vea un rastro en la pantalla que cumple con las peticiones del enunciado? Si es así no hay problema!! No se necesitan sprites para esta tarea xD 

Sobre Qt no sabría decirte pero veré si algún otro ayudante te puede responder eso!
