### ISSUE TITLE
Problemas al conectarse al server

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#727]
Holaa:

He estado teniendo problemas al intentar conectarme a un server que está corriendo en un pc distinto, cuando un cliente trata de conectarse me lanza el siguiente error:

`ConnectionRefusedError: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión`

el host que se utiliza en ambos es 'localhost' y utilizan el mismo puerto, pero no se a que se deba el error

**Comment by bimartinez** [comment]
Hola @jlperez6 

Recuerda que en el caso del cliente tienes que brindarle la `ip` del computador en donde se está ejecutando el servidor. Revisa este [link](https://stackoverflow.com/questions/41294848/python-sockets-how-to-connect-between-two-computers-on-the-same-wifi) donde explican mejor como hacerlo.

Saludos!

**Comment by Arcoirisky** [comment]
Si eso no funciona, cierra toda ventana de internet (seguridad primero) y desactiva por unos minutos el antivirus. Mi windows 7 me daba ese problema y con eso se conectaron mis servers. 

Lo qué pasa es que windows se protege pero como que no cacha que se protege de sí mismo skndksdndk 

Oh! Cambiar el puerto también funciona a veces! 8080 o 8000 (si no me equivoco) dicen algunos que funciona

**Comment by csolguin** [comment]
Qué otra solución existe si  aun después de desactivar el cortafuego y el antivirus,  en el servidor de TCP me aparece el error "503 Service Unavailable" y en el servidor UDP ni siquiera se termina de ejecutar (en el caso de los jupyter en contenidos) ?

**Comment by Arcoirisky** [comment]
Hmmmm ese error es distinto ¿puedes mostrar el error completo?

**Comment by fjlopez7** [comment]
como se colocan los host entre servidor y cliente, entre dos computadores respectivamente?

**Comment by bimartinez** [comment]
Hola @fjlopez7 

El *host* en el caso del servidor es el computador en el que está alojado, en este caso con `localhost` basta.  Para el caso del cliente, como lo comenté mas arriba :arrow_up:, debes poner la dirección `ip` local del computador al cual quieres conectarte. (Te dejo [aquí](https://stackoverflow.com/questions/11352855/communication-between-two-computers-using-python-socket) mas información). Fíjate que el puerto siempre sea el mismo en ambos (cliente y servidor).

Saludos!

**Comment by gatochico** [comment]
Hola,

Estoy en lo mismo, entré a los links y todavia no tengo claro cual poner en host del cliente? La dirección IPV4 del server? Por que hemos intentado con ese valor y no logra conectarse.

Aiuda

**Comment by bimartinez** [comment]
Hola @gatochico,

Exactamente, en el cliente debes poner la dirección IPv4 del computador donde está corriendo el servidor. En caso que no funcione, ve si *Python* no esta bloqueado por el *firewall* en los dos computadores. Luego, recuerda que el servidor siempre tiene que estar corriendo antes de conectar algun cliente. Si esto no llega a funcionar, puede que sean problemas con eduroam:cry:, aunque es muy poco probable.

Saludos!
