### ISSUE TITLE
JSON Extra Data error

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#728]
Hola!

En mi programa envío múltiples mensajes que codifico/decodigico en JSON. El error que puse en el asunto se lanza cuando intento hacer algo del estilo

```python
self.send(data1)
self.send(data2)
```
Específicamente ocurre cuando cargo las curvas a jugar y a la vez envío el mensaje al server para iniciar el contador. ¿Cómo puedo solucionar esto?

Gracias!

**Comment by cacoos** [comment]
Ya lo resolví

**Comment by Banfanci** [comment]
@cacosandon  hola mira yo tengo el mismo problema pero cuando envio la informacion cada muy poco tiempo, basicamente cuando estoy haciendo que todos se muevan en el juego... encontraste alguna manera de resolver el problema, o simplemente dejaste de enviar multiples mensajes???
