### ISSUE TITLE
Error json (?)

### ISSUE THREAD

**Issue by chocopiano** [IIC2233/syllabus-2018-2#729]
Hola! Alguien me podría ayudar porfa con el siguiente error, de verdad he buscado y no encuentro nada que me ayude

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/benjamindelpiano/Desktop/T04/cliente/Servidor.py", line 74, in escuchar_cliente_thread
    decoded = json.loads(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jeschuwirth** [comment]
Hola!
Parece que estas tratando de decodificar con json el `None` de python, revisa si estas enviando data de manera correcta entre tu servidor y cliente, revisa el string que quieres mandar antes de codificarlo en json y por parte del servidor, asegurate de recibir una secuencia de bytes con sentido antes de decodificarla. Ojalá con eso logres encontrar la solución a tu problema, sino vuelve a escribir en esta issue para intentar solucionarlo.

Suerte y espero que te ayude :)

**Comment by chocopiano** [comment]
Hola! me esta ocurriendo algo super raro, cuando le envío data a servidor, este me lo lee de buena forma y se lo responde al cliente, pero luego el servidor me trata de leer otro mensaje que en teoría es None o esta vacío y no tengo la menor idea de donde se esta enviando ese mensaje. De verdad no cacho que hacer, llevo mucho tiempo pegado y he vuelto a escribir el codigo de nuevo una y otra vez, he probado con pickles y me tira lo mismo y eso que tengo un codigo similar al de la ayudantía.

**Comment by chocopiano** [comment]
De verdad que puedo hacer?, llevo demaciado tiempo parado y no puedo avanzar con otra cosa, he tratado por todas partes, he preguntado, googleado y nada de nada

**Comment by lily416** [comment]
Te diría que **por ahora**:

-  Imprimas todos los mensajes que se están mandando entre el servidor y el cliente para ver qué es lo que puede estar causando el error, y 
- Que antes de enviar el mensaje revises su largo, y si es 0 entonces no lo envíes.

Saludos 👋🐍

**Comment by chocopiano** [comment]
ahora me salen otros errores que son:
QObject::killTimer: Timers cannot be stopped from another thread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
y en ningun momento he usado QBasicTimer, ni si quiera lo he importado

**Comment by Mahund** [comment]
Me salio el mismo error.

Me pasa que al cerrar el cliente, este le envia al servidor un string vacio y el servidor al tratar de hacer json.load colapsa.

Lo solucione a la mala en el servidor para que reaccionara antes si llegaba esta señal desconocida
