### ISSUE TITLE
Duda guardar en base de datos

### ISSUE THREAD

**Issue by Fenho** [IIC2233/syllabus-2018-2#73]
¿Cuando dice que se deben guardar los datos en una carpeta "datos", no se refiere a "data"? ¿No se guardan los datos nuevos junto a los datos antiguos (los archivos ya dados)?

**Comment by cilopez** [comment]
Puedes o no hacerlo. _datos_ podría referirse a la carpeta _data_ si es que guardas todo en los mismos archivos `.csv`
