### ISSUE TITLE
Duda networking con interfaces y comunicacion

### ISSUE THREAD

**Issue by gnacrur** [IIC2233/syllabus-2018-2#730]
Hola, he tenido algunos problemas para mezclar networking con interfaces graficas. Me interesaba saber si esta bien abordar el problema haciendo que mi cliente (de networking) sea como una especie de backend y que herede de QObject (para poder enviarle señales a mis interfaces). Para hacer esto hay que hacer varias cosas que no se si son muy aceptables desde el punto de vista de la programación;  dejar como parámetro de mi cliente la instancia de mi ventana de inicio e ir guardando en esta instancia como parámetro, las ventanas que voy abriendo (registro, ingreso) algo que tampoco se si debiese hacer. Esto último con el fin de que mi cliente tenga acceso a la instancia de mi ventana de registro, por ejemplo, para poder conectar la señal. Revisé en la ayudantía del chat y lo que hacían es conectarse directamente con las funciones del frontend sin enviar señales y creo que eso es ilegal en la tarea.  Me serviría cualquier tipo de feedback!

**Comment by lily416** [comment]
Echale un ojo a la [Ayudantía 13 - Networking](https://github.com/IIC2233/syllabus/tree/master/Ayudantias/S13%20-%20Networking) del semestre 2018-1, siento que en ella se explica bien como separar la interfaz, del usuario y el servidor y además responde varias de tus dudas.

Trata de dividir bien la interfaz y el cliente, si quieres pueden pensar en él como el _back_end_ de tu progra (pero considera que no es **todo** el _back_end_ ya que tambíen se encuentra el servidor), relacionar las ventanas con una ventana principal o con otras ventanas y realizar la comunicación entre _back_end_ y _front_end_ mediante señales (considera que la ayudantía es una simplificación de networking).

Ojalá que ahora todo este más claro :)
Saludos 👋🐍

**Comment by VicenteVicente** [comment]
@lily416 en la función `manejar_comando` mi programa se cae al tratar de abrir ventanas, como te mencioné en #731 :(, ¿de qué otra forma podría hacer `show()` dentro de esa función?

**Comment by lily416** [comment]
@VicenteVicenteVicenteVicenteVicente prueba que en vez de llamar directamente al `show()` y el `hide()`, llama a funciones que se encargue de realizar las acciones.

Y reitero trata de hacer una buena separación entre interfaz, usuario y servidor.
<img width="907" alt="captura" src="https://user-images.githubusercontent.com/26393515/48655870-164d5f80-e9fc-11e8-9e37-a28253e81194.PNG">

- Deja en la interfaz todo lo relacionado con las ventanas.
- En clientes los aspectos básicos del back-end, como la comunicación con el servidor. Por ejempo, cuando el servidor envíe un mensaje que indique se que debe abrir una ventana X, el cliente le avisa por una señal a la interfaz que se debe abrir la ventana X y cerrar la ventana que se encuentra actualmente abierta.
- En el servidor la comunicación entre clientes y la validación de datos o almacenamiento de estos.

Fijate que en la ayudantía, el cliente es una variable de la ventana y que además es un QObject.

Ojala que ahora quede todo más claro 🙏

**Comment by VicenteVicente** [comment]
@lily416 aaah, todo me queda mucho más claro ahora, no tenía en consideración que cliente era un QObject, ¡muchísimas gracias!
