### ISSUE TITLE
[PyQt] - hide/show para mostrar una ventana nueva

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2233/syllabus-2018-2#731]
Cuando quiero mostrar una nueva ventana al cliente, la única forma de que funcione es añadiendo al `init` algo como:
```python
self.ventana_nueva= ventana_nueva(self)
self.ventana_nueva.show()
self.ventana_nueva.hide()
```
Si quito el `show()` o el `hide()`, la ventana queda en blanco y se cierra instantáneamente, o en otros casos, se queda pegada y el programa se cierra. ¿Hay alguna otra forma para que esto no suceda? y en caso de no haberla ¿Hay algún problema en que realice esto para que funcione correctamente?

**Comment by AlexGV7** [comment]
X2

**Comment by innerprospective** [comment]
X3

**Comment by lily416** [comment]
@VicenteVicenteVicenteVicenteVicente @thealexga98 y @innerprospective si entiendo bien ¿quieren ver si existe una forma de cambiar o mostrar una nueva ventana sin hacer uso de `hide()` y `show()`?

PD: Por favor eviten comentar _x2_, _cps_ o similares, utilicen el botón **Suscribirse**.

**Comment by VicenteVicente** [comment]
@lily416 no, lo que pasa es que en el `init` del cliente, debo poner `hide()` y `show()` de todas las ventanas que más tarde serán mostradas, es decir, al inicio todas las ventanas que serán utilizadas por el cliente se abrirán y cerrarán, ya que si no hago esa serie de pasos, al intentar abrirla más adelante, la ventana queda en blanco y el programa se cae

**Comment by santilaguna** [comment]
@VicenteVicenteVicenteVicenteVicente Hola! 

¿Intentaste con crear la ventana después? 
Si entendí bien lo que mencionas, defines instancias de todas las ventanas que quieres usar  en el init, por la forma en que funciona pyqt, te recomiendo crear la "ventana hija" al momento de que el usuario lo solicite. De esta forma, no tendrías la necesidad de crear muchas ventanas al mismo tiempo. =D

Saludos

**Comment by VicenteVicente** [comment]
Efectivamente fue lo primero que intenté y no funciona, si creo la instancia de la ventana cuando el usuario quiera, pasa el mismo error:(

**Comment by lily416** [comment]
@VicenteVicenteVicenteVicenteVicente 
¿Podrías enviar una foto del error que sale cuando tratas de crear y mostrar la ventana? 
Sí es que no lo puedes ver el error, utiliza lo que sale en #695 para que se imprima.

Saludos 👋🐍

**Comment by VicenteVicente** [comment]
Disculpa el mal concepto por decir "error", ya que no muestra un error, si no que simplemente la ventana queda pegada. El problema que sucede es que no me permite utilizar la función `show()` por primera vez fuera del init, necesariamente tuvo que haber sido ejecutado una vez en el init, si no, no puedo hacerlo en las ocasiones futuras, y no le encuentro el sentido de por qué se soluciona al hacerle un `show()`+`hide()` previamente en el init, no le encuentro mucho sentido 😢

**Comment by lily416** [comment]
@VicenteVicenteVicenteVicenteVicente ¿Tienes la última versión de tu código en tu repositorio para echarle un ojo?

**Comment by VicenteVicente** [comment]
@lily416 claro, la función `manejar_comando`, de `cliente.py` está todo lo que he comentado, además del init, que es donde hago el `show()`+`hide()`

**Comment by lily416** [comment]
Probablemente tu error se debe a que no estás separando bien el _front_end_ y el cliente. Trata de pensar en el cliente como el _back_end_ de tu programa y que se comunica con la interfaz mediante señales.

Échale un ojo a la issue #730 y revisa la [Ayudantía 13 - Networking](https://github.com/IIC2233/Syllabus-2018-1/tree/master/Ayudantias/Ayudantia%2013) del semestre 2018-1, ahí se explica bien como separar la interfaz y el cliente.

Ojala te sirva 
Suerte 🍀

**Comment by VicenteVicente** [comment]
Dale, le echaré un ojo a eso, ¡muchas gracias!
