### ISSUE TITLE
Poderes - Nebcoins

### ISSUE THREAD

**Issue by mericci** [IIC2233/syllabus-2018-2#732]
Hola! En la sala de espera, cuando el jefe de partida elige los poderes, se le debe dar la opción de elegir si hay o no nebcoins?, o siempre habrán (pensando en que siempre pueden haber choques frontales.

Muchas gracias!

**Comment by FJavierOss** [comment]
Hola,

Se debe dar la opción de elegir si hay nebcoins, pero no logre entender a que te refieres con choques frontales, si pudieras explicarmelo mejor seria ideal. :smile: 

Saludos

**Comment by jeschuwirth** [comment]
@FJavierOss se refiere a cuando hay empates, dos lineas chocan de frente
@mericci Es bastante especifica la consulta pero tiene sentido, el jefe de partida SI puede eliminar las nebcoins, en el caso de que no las agregue y ocurra un empate especifica en el readme que hace tu programa.
