### ISSUE TITLE
Error agregar sprite.png

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#733]
Hola!
Al intentar agregar un sprite (formato .png) que no tiene fondo sobre mi ventana, el fondo del sprite se rellena con el color del fondo de mi ventana. Esto pasa solamente si utilizo una ventana cargada de QtDesigner, si creo una ventana en python (que hereda de QWidget en vez de los archivos del .ui) funciona perfectamente.

Alguna idea de como solucionar esto? 

Adjunto imagen de lo que me pasa ( el sprite es un círculo rojo sin fondo, pero de alguna forma se le rellena un fondo negro)

![image](https://user-images.githubusercontent.com/42159312/48649470-71b62800-e9d1-11e8-8427-0764af2f5a2b.png)

Y creando la ventana en python en vez del Designer:

![image](https://user-images.githubusercontent.com/42159312/48649533-ac1fc500-e9d1-11e8-9f49-ab98f9725cad.png)

**Comment by lily416** [comment]
No se me ocurre la razón, tal vez pueda tener relación con el fondo negro, aunque es poco probable pero por si acaso prueba la imagen en un widget creado en Python con fodo negro.

Podrías tratar de hacer que tu ventana creada en QtDesigner reciba un widget y que ese widget lo crees en Python:
<img width="687" alt="captura" src="https://user-images.githubusercontent.com/26393515/48656159-ed2ece00-e9ff-11e8-9a86-cdf8cb38a2cc.PNG">
Las interfaces creadas a partir de QtDesigner pueden modificarse en Python y agregarle o quitarle cosas, por lo que después de cargar el .ui puedes asignarle el widget.

Ojala te sirva,
Saludos 👋🐍

**Comment by jcechavarri** [comment]
> No se me ocurre la razón, tal vez pueda tener relación con el fondo negro, aunque es poco probable pero por si acaso prueba la imagen en un widget creado en Python con fodo negro.
> 
> Podrías tratar de hacer que tu ventana creada en QtDesigner reciba un widget y que ese widget lo crees en Python:
> <img alt="captura" width="687" src="https://user-images.githubusercontent.com/26393515/48656159-ed2ece00-e9ff-11e8-9a86-cdf8cb38a2cc.PNG">
> Las interfaces creadas a partir de QtDesigner pueden modificarse en Python y agregarle o quitarle cosas, por lo que después de cargar el .ui puedes asignarle el widget.
> 
> Ojala te sirva,
> Saludos 👋🐍

Gracias!
