### ISSUE TITLE
Mantener un server corriendo

### ISSUE THREAD

**Issue by johntrombon** [IIC2233/syllabus-2018-2#734]
Hola, en la AY-13, mantienen corriendo el server con un while True: pass,
mi pregunta es, ¿es esta la mejor manera de hacerlo?. Lo otro que se me ocurre es haciendo dejando uno de los threads como no-daemon pero siento que eso podría traer problemas para cuando decida cerrarlo.
Busqué en internet otra alternativa pero me salen puras cosas de django :(

**Comment by jeschuwirth** [comment]
Hola @jtescobar1 !
lo que más te recomiendo para dejar un servidor corriendo es tener en el thread principal un `while True`, el cual esta constantemente esperando nuevas conexiones y cuando reciba una le haga todas las interacciones necesarias, un vez la haya trabajado y asignado a un lugar correcto, el servidor vuelve a su estado normal de escuchar nuevas conexiones.
