### ISSUE TITLE
Botones Sala de Juego

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#735]
¿Los botones para salir del juego o iniciar una nueva partida sólo deben aparecer cuando la partida actual haya finalizado?

**Comment by lily416** [comment]
@BFFV Los botones deben aparecer durante toda la partida.

Lo siento por el enredo, 
Saludos 👋🐍

**Comment by BFFV** [comment]
Gracias!

**Comment by BFFV** [comment]
Entonces ahora que es en toda la partida, ¿se muestran sólo al final de cada ronda?

**Comment by lily416** [comment]
Se muestra durante toda la partida, entre rondas y al final de la partida.

Saludos 👋🌈

**Comment by BFFV** [comment]
¿Pero no mientras se está jugando y moviendo?

**Comment by lily416** [comment]
También se deben mostrar mientras se está jugando, moviendo y deben estar funcionando.
