### ISSUE TITLE
Duda señales unidireccionales

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#736]
Hola ! En el feedback de la tarea 4 hay un punto que dice que las señales deben ser unidireccionales, y que no pueden haber referencia circular. No entiendo muy bien que significa esto, alguien me podría explicar y dar un ejemplo de referencias unidireccionales y otra circular ? De antemano muchas gracias!

**Comment by jeschuwirth** [comment]
Hola!
Todo esto esta en la carpeta contenidos de la semana de Networking, te explico un poco cada concepto para ver si te queda más claro. 
Una referencia, en este caso, es cuando tienes una clase que como atributo posee otra, o llama a otra dentro de ella misma. Por ejemplo, por lo general se guarda el BackEnd  como atributo dentro del FrontEnd o viceversa, esto no es malo, sin embargo cuando luego agregas un atributo en el BackEnd que sea el FrontEnd, entonces entras en cadenas donde se busca información constantemente entre las 2 clases. Esto es una mala práctica y por eso se descuenta su uso.

Para evitar estos problemas, lo que uno puede hacer es  utilizar señales, esto es que el FrontEnd tenga al BackEnd y que cada vez que el BackEnd necesite información del FrontEnd le mande una señal que utilice un atributo o lo que sea que necesite.

En resúmen:
una referencia unidireccional es aquella que llama de una clase a otra pero no de vuelta (BackEnd a FrontEnd)
una referencia circular es aquella que llama de una clase a otra y también hacia el otro lado (BackEnd a FrontEnd y FrontEnd a BackEnd)

Ojalá te ayude est y suerte en la Tarea :)

**Comment by gnacrur** [comment]
Hola @jeschuwirth, aun no logro entender como se puede hacer esto. En la ayudantía de networking de este semestre si no me equivoco se hace de la forma en que descuentan para la tarea. En otra issue me recomendaron ver la del semestre pasado. Revisandola me di cuenta que solo usaban como atributo al cliente en el frontend y no al frontend en el cliente (lo que es bueno). Luego me di cuenta que de todos modos en el frontend se conectan señales hacia el cliente y aprovechando que tienen al cliente como atributo le conectan desde el frontend una señal que se conecta con una función del frontend. No se si esto último también se considera referencia circular o no habría problema en hacer esto. 
Así se ve la conexión de señales en el frontend de esa ayudantía:

` self.trigger_boton.connect(self.client.enviar_jugada)
      self.client.trigger_resultados.connect(self.desplegar_resultado)`
Agradecería si me pudieran aclarar si esto es lo que se busca o se supone que lo hagamos de otra forma.

**Comment by hbkim94** [comment]
Hola! Agregando a la duda anterior, ¿estaría incorrecto hacer esto (en base a la ayudantía de networking)?
- En el init de client (backend) instanciar al frontend como atributo (ie. `self.frontend = Frontend()` )
- Llamar a una función del frontend directamente desde el backend (ie. `self.frontend.foo(bar)` )

Según entendí, estaría bien hacer esto con tal que en el frontend no llame a atributos/métodos del backend. ¿Es esto correcto o incorrecto?

Gracias!
