### ISSUE TITLE
Duda aplicación con python

### ISSUE THREAD

**Issue by fjtobar** [IIC2233/syllabus-2018-2#737]
Hola, 

creo que esta duda va un poco más allá del curso, sin embargo no sé donde más preguntarlo. 

Se pueden crear aplicaciones "reales" con python? es decir, crear un icono en mi PC al cual le haga click y se abra mi interfaz programada? esto es para evitar que el usuario deba abrir python y ejecutar el código manualmente para interactuar con la interfaz. 

He intentado buscar en internet pero no sé como realizar la búsqueda. Agradecería infinito si me dijeran que tan posible es realizar esto, y como averiguar más sobre el tema.

Gracias de antemano!! :D

**Comment by fgbruna** [comment]
Hola, crear ejecutables de python es relativamente simple, te recomiendo echarle un ojo a la documentacion de [cx_freeze](https://anthony-tuininga.github.io/cx_Freeze/) y las librerias que mencionan ahi mismo.
Si quieres buscar otras opciones deberías buscar cosas como:
+ How to compile python apps
+ How to freeze python apps
+ How to create python executables
