### ISSUE TITLE
Problema con setText()

### ISSUE THREAD

**Issue by mhrobles** [IIC2233/syllabus-2018-2#738]
![duda](https://user-images.githubusercontent.com/37165583/48667699-d7caaa00-eaba-11e8-8a56-736f75ee5cdd.PNG)

tengo un problema en mi codigo al momento de actualizar los mensajes en el chat de la sala de espera, lo que pasa es que pareciese como si se saltara el codigo de setText, porque incluso los prints que puse antes y despues de este se ejecutan, incluso el como deberia verse el mensaje tambien aparece en el print de la consola, pero no de la interfaz

**Comment by camichavez** [comment]
Hola! No debieses pasarle el socket del cliente al que mandas el mensaje?

**Comment by mhrobles** [comment]
No, es que esa funcion es parte del frontend, lo que pasa es que tengo una funcion Enviar en donde está una señal que conecta con cliente.send() ahi es donde se procesa el mensaje que se escribe, luego se envia del cliente al servidor y luego del servidor al cliente y este se conecta con la funcion actualizar_chat() del frontend, incluso tengo un setText() en la funcion Enviar que deja en blanco el LineEdit donde se escribe el mensaje a enviar y funciona como debería, lo que no entiendo es por que no funciona en esta funcion. Perdon por no especificarlo antes

**Comment by camichavez** [comment]
Estuve viendo que podría ser y creo que lo que puedes probar es en vez de utilizar un setText() (para actualizar el **chat**) debieses utilizar un addItem(), sin embargo, sigue usando el setText para dejar en blanco el LineEdit. Creo que eso debiese servir :)

**Comment by camichavez** [comment]
Por si acaso, eso significa que probablemente tienes que cambiar el tipo de objeto que estás utilizando!

**Comment by mhrobles** [comment]
No me funcionó, pero creo que debe haber un error con mi codigo del servidor o cliente

**Comment by camichavez** [comment]
Pero cambiaste el tipo de objeto de la interfaz donde quieres que aparezca el mensaje del chat? Si es que ya lo intentaste, puedes actualizar tu tarea en tu repositorio por favor:)?

**Comment by mhrobles** [comment]
ahi acabo de actualizarlo, y si cambié el tipo de objeto tambien

**Comment by camichavez** [comment]
Estuve bien tu código un buen rato y me costó pillarlo pero lo logré:D Lo que hice fue añadir en la función Enviar que está en la línea 185 de frontend.py lo siguiente: self.msg.addItem(self.Writer.text())
Perdón la demora!

**Comment by mhrobles** [comment]
si funcionó! muchas gracias :D

**Comment by AndresFaure** [comment]
Hola! Me pasa el mismo problema, y no me quedó claro como solucionarlo. Tengo exactamente la misma función del screenshot que subió @migueliic1005 (estaba en la ayudantía). No entendí, ¿por qué está mal si el tipo de objeto en donde escribimos los chats es QLabel? ¿Hay que hacer que sea QListWidget?
