### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#739]
Hola! 
Me pasa a menudo que al mandar la respuesta del server al cliente se genera este error:
BrokenPipeError: [Errno 32] Broken pipe
Específicamente luego de la linea:   self.send(msj, skt)  , el código es bastante parecido al de la ayudantía, no he cambiado nada de señales o bytes que podría generar un error de este tipo y no he podido solucionarlo :(

**Comment by camichavez** [comment]
Hola! podrías subir a tu repositorio tu código por favor!?

**Comment by NickCastillo** [comment]
Subido! Cliente.py es el main, el error se genera de vez en cuando y evita la llega de mas mensajes/senales, al chat o a la lista de jugadores en la sala de espera.

**Comment by camichavez** [comment]
Intenta con cambiar esto: msg_bytes = msg_json.encode()
por: msg_bytes = msg_json.encode(enconding = "utf-8")
En Server.py
