### ISSUE TITLE
Agregar elementos dentro de un valor de diccionario que sea una tupla

### ISSUE THREAD

**Issue by ncasassus** [IIC2233/syllabus-2018-2#74]
Hola! Tengo una duda si existe alguna forma de hacer esto. Tengo un diccionario que al darle una llave me da como valor una tupla. Qué tengo que hacer si quiero agregar elementos dentro de la tupla sin eliminar los elementos anteriores? Obviamente manteniendo la estructura del diccionario. Muchas gracias!

**Comment by ncasassus** [comment]
Me di cuenta que la tupla al ser inmutable, no solo no puede cambiar o mover sus elementos, si no que tampoco puede agregar. Pero mi duda sigue en caso de que, en vez de una tupla sea una lista. Muchas gracias!

**Comment by rhanuch** [comment]
¡Hola @ncasassus !

Recuerda que un diccionario es una estructura de dato, lo cual no impide que uno de los elementos de esta estructura sea otra estructura del mismo (o diferente) tipo. En tu caso particular supongamos lo siguiente

```Python
my_edd = { '1': ['my', 'list']}
```

Para agregar un elemento a la lista de ```my_edd``` simplemente debes hacer referencia al valor que tiene asociado el `keyword` `'1'`, es decir, podrías hacer:

```Python
my_edd['1'].append('is expandable')

my_edd
>> { '1': ['my', 'list', 'is expandable']}
```

**Comment by ncasassus** [comment]
Buenísima, me quedó claro! Gracias!
