### ISSUE TITLE
Comprobar contraseña inicio sesión

### ISSUE THREAD

**Issue by aljara97** [IIC2233/syllabus-2018-2#740]
Para comprobar que el hash guardado al registrar un usuario con el hash creado con la contraseña ingresada, es válido aplicar hexdigest() a cada uno y luego verificar si son iguales?

**Comment by jeschuwirth** [comment]
Hola!

Debido a que hexdigest() no traduce el string a la contraseña en si, si esta correcto utilizarlo

Suerte en la tarea :)
