### ISSUE TITLE
Problema al usar QPainter

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#741]
Hola, estoy teniendo poblemas para animar el movimiento del jugador, para dibujar el rastro estoy usando QPainter y al momento de crear una instancia de este utilizando el comando:

`painter = QPainter()`
`painter.begin(self)`

me aparece el siguiente error:

`QWidget::paintEngine: Should no longer be called`
`QPainter::begin: Paint device returned engine == 0, type: 1`

no se me cae programa, solo aparece en la consola y no dibuja nada en la interfaz, a que se debe este error?

**Comment by jeschuwirth** [comment]
Hola!
al llamar QPainter este inicia inmediatamente, te recomiendo leer la documentación en el siguiente link:
http://doc.qt.io/archives/qt-4.8/qpainter.html#QPainter

Te dejo un pantallazo de la parte que necesitabas:
![image](https://user-images.githubusercontent.com/37160256/48674932-bd331800-eb30-11e8-9e19-6b12fd795773.png)

**Comment by jlperez6** [comment]
trato de hacer lo que aparece en el documento pero el error sigue apareciendo y no dibuja nada

**Comment by jeschuwirth** [comment]
No estoy seguro cual puede ser tu problema, te recomiendo revisar ejemplos de códigos de QPainter en internet y analizar cómo están escritos, probablemente el problema sea que a tú código le falte guardar el objeto QPainter en un self.------ o algún error de sintaxis más que de concepto.
