### ISSUE TITLE
Dudas partidas y rondas

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#742]
Hola!

Tengo un par de dudas con respecto al enunciado.
Si por ejemplo yo defino 10 puntos para ganar,
-Cómo inicio **cada ronda**? con _space_ o con un botón?
-Es legal que alguien se salga al final de una ronda (por ejemplo van en la segunda ronda) y no al final de una partida? (a legal me refiero a si debe estar activado el botón Volver). Si es así, qué pasa si solo queda uno jugando?
-El contador es únicamente para iniciar la partida? o también cada ronda?

Gracias!

**Comment by camichavez** [comment]
Hola!
1. Puedes utilizar _space_
2. Lo que dices si es legal y si queda uno solo jugando este debe ganar automáticamente. 
3. Solo al inicio de la partida, para las demás rondas no es necesario :)

**Comment by cacoos** [comment]
Gracias Cami! Otra duda
Para pausar el juego puede ser con _space_ o con el botón de pausar que especifica el enunciado? O puedo elegir una de las dos?
