### ISSUE TITLE
Problema con threads y QLabel()

### ISSUE THREAD

**Issue by rsnegrin** [IIC2233/syllabus-2018-2#744]
Tengo un problema al hacer .show() a un QLabel() dentro de un thread. Por alguna razón, cuando trato de mostrar los labels en mi interfaz usando un thread, mi programa se queda parado. Ya traté usando un lock en esa parte del código, pero igual se pega. Solo pasa con el método .show()

**Comment by entamburini** [comment]
Hola! :)

Estas usando `Thread` o `QThread`? Si es la primera, cambiala por la segunda, esta ha sido una advertencia que siempre se hace en ayudantías porque la librería de `PyQT` no se lleva muy bien con los threads que no sean `QThread`. Si es la segunda, te recomiendo que veas el tema de eventos para hacer la sincronización y el llamado de cosas en el frontend con el backend ;)

Saludos! :D
