### ISSUE TITLE
Problema con Qthread

### ISSUE THREAD

**Issue by jlperez6** [IIC2233/syllabus-2018-2#745]
Holaa, estoy teniendo problemas al usar Qthreads, pasa que creo una instancia y al ejecutar

`thread.start()`

me aparece el siguiente error:

`QThread: Destroyed while thread is still running`

**Comment by IchottMano** [comment]
@jlperez6 Hola!
Lo mas probable es que no estés guardando una referencia del thread, lo cual causa que python crea que no se usará mas y lo destruye a través de su garbage collection.
Lo que puedes intentar hacer es guardar tu thread en alguna parte (como un atributo de una clase o algo por el estilo).
Dime si esto resuelve tu problema.
Saludos!

**Comment by roberto009** [comment]
Intenté lo que me dijiste y sigue sin funcionar. Cuando uso  QTimer en vez de un threading.Thread funciona perfecto, el problema es que el "delay" que le quiero aplicar al QTimer es variable, por lo que pensaba hacerlo con un Thread y un time.sleep(). Sin embargo, si agrego un time.sleep() al QTimer se detiene la ejecución de todo el programa.

**Comment by IchottMano** [comment]
@roberto009 Hola!
Tienes el mismo error que la otra persona? Es decir que obtienes el error

```
QThread: Destroyed while thread is still running
```

Si no es así, has otra issue explicando a mas detalle tu error, pero de ser el caso, me gustarías si puedieras explicar a mas detalle aquí que errores lanza tu programa.

Saludos!
