### ISSUE TITLE
Json error Extra Data error 2.0

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#747]
Hola!! me sucede que cuando envio informacion desde un mismo thread cada muy poco tiempo, me salta el error Extra Data error y esto me tiene muy atado de las manos por que cada 25 milisegundos cada jugador envia su nueva posicion entre otras cosas, y por si esto no fuera poco, dije bueno probemos subiendolo a 50 milisegundos donde no se caia con un jugador, pero ya al agregar un segundo pasaba lo mismo.

Como puedo resolver este problema?
Muchas gracias de ante mano.

**Comment by jeschuwirth** [comment]
No estoy muy seguro del error, pero se me ocurren un par de ideas que podrían ayudarte:

1. el cliente envia la información más rápido de lo que el servidor la procesa, por lo que algunos bytes de un segundo mensaje se leen al mismo tiempo que el primero, lo que podría lanzar tu error. Para arreglar esto podrías hacer que el número de bytes que se manden se siempre el mismo, y por lo tanto el servidor siempre debe leer la misma cantidad.

1. Otro problema podría ser el explicado en el siguiente StackOverflow: https://stackoverflow.com/questions/21058935/python-json-loads-shows-valueerror-extra-data

Ojalá alguno de esos te ayude, sino sigue escribiendo en la issue para intentar solucionar el problema.

**Comment by cacoos** [comment]
Hola!

Lo que está pasando (o lo que me pasaba a mí) es que el algoritmo que nos pasaron en clases y ayudantía para decodificar los mensajes enviados no funcionaban para este tipo de casos (donde se envían múltiples cosas a la vez).
En la ayudantía se manda por _packs_ de ciertos _bytes_, con algo de la forma
```python
while len(contenido_mensaje_bytes) < tamano_mensaje:
                    contenido_mensaje_bytes += self.socket_cliente.recv(256)
contenido_mensaje = contenido_mensaje_bytes.decode("utf-8")
```
Ahora, imagina mandas dos mensajes seguidos (tan seguidos que no alcanza a recorrer el _while_ y _decode_ de forma completa) que en la cola de recepción de mensajes tienes algo del estilo
```python
cola = "bytes1bytes2"
```
con `bytes1` de largo 5, y `bytes2` de largo 1000 con la información del tamaño incluida en los bytes.
Si lee ese mensaje, entonces el algoritmo hace;
```python
tamano_mensaje = 5
while len(contenido_mensaje_bytes) < tamano_mensaje:
                    contenido_mensaje_bytes += self.socket_cliente.recv(256)
contenido_mensaje = contenido_mensaje_bytes.decode("utf-8")
```
Y entonces lee todo `bytes1`, junto con una parte de `bytes2` (porque leyó 256 y no 5), decodificando _bytes_ que no tienen sentido.

Ojalá te sirva!

**Comment by Marialuisaclaro** [comment]
@cacosandon y como lo solucionaste?

**Comment by Banfanci** [comment]
@cacosandon  Gracias con eso lo pude solucionar... y @Marialuisaclaro aqui explicitamente no creo que sea legal por decirlo de alguna manera decir paso a paso como solucionarlo, pero no es muy dificil si entiendes el problema en si, hay que entender que el recv no discrimina si los bytes son del primer mensaje enviado o del segundo, entonces hay que cambiar el protocolo de tal manera de poder solucionar este problema, que lea los bytes justos del primer mensaje y luego lea los del segundo. Para visualizarlo mejor piensa que cada vez que se envian mensajes al servidor se van formando los bytes unos tras otros y el recv(256) lo que hace es tomar el minimo entre 256 y los bytes que quedan en esta cola.

Saludos, espero que con esto puedas solucionar el problema.
