### ISSUE TITLE
Varios widgets en la misma ventana

### ISSUE THREAD

**Issue by firulais33** [IIC2233/syllabus-2018-2#749]
Hola,

No he podido encontrar una manera para tener varios widgets en la misma ventana. Por ejemplo, tengo un QWidget para el chat, otro para la ventana del juego, etc. Quiero mezclar todos ellos en la misma ventana, pero no se como... alguna idea? Gracias!

**Comment by naoliden** [comment]
Si lo que quieres hacer es ir mostrandolos al mismo tiempo se me ocurre que puedes usar Qthreads para el chat dentro de tu widget principal. O threads normales que vayan actualizando las conversaciones.
