### ISSUE TITLE
Loop, forma mas optima dentro de una función

### ISSUE THREAD

**Issue by dhvasquez** [IIC2233/syllabus-2018-2#75]
Si tengo que realizar un loop, ¿cuál sería la manera más óptima? De acuerdo a estos 2 ejemplos

Ejemplo 1, función recursiva:
```
def loop():
    opcion = input()
    if opcion == 1:
        loop()
    else:
        exit()
```
Ejemplo 2, función iterativa:
```
def loop():
    opcion = 1
    while opcion == 1
         opcion = input()
    exit()
```
** Asumiendo que para cada opción tendrá que haber un loop `while` hasta obtener una respuesta coherente.

**Comment by NachoJuanDev** [comment]
A mi parecer, el ejemplo 2 es más óptimo.

En el ejemplo 1 estarás haciendo una recursión, por lo cual, según la cantidad de respuestas no coherentes que recibas, tendrás un número de funciones en espera y cuando logres una respuesta coherente tendrás que retornarla una vez por cada vez que la función se llamó a si mismo. 

En el ejemplo 2, aunque recibas muchas respuestas incoherentes estarás siempre en la misma función, por lo tanto, tendrás que retornar una sola vez la respuesta coherente, y el while no te ocupará espacio extra en la memoria (eso creo) cada vez que recibas una respuesta no coherente.

Espero haberte ayudado.
