### ISSUE TITLE
Error al abrir interfaz desde el codigo de cliente.

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#750]
Hola, cuando intento correr mi codigo de cliente, abro la interfaz de adentro de este al igual que la ayudantia, pero al hacerlo esta nunca abre ya que me tira esto que nisiquiera se si es un error. 

libpng warning: iCCP: known incorrect sRGB profile

De antemano muchas gracias.

**Comment by marcotroncoso** [comment]
Cuando lo hago desde el frotend, se abre sin ningun problema.

**Comment by naoliden** [comment]
Estas cargando fotos?

**Comment by marcotroncoso** [comment]
Nose porque me tiraba el error, pero coloque este comando y se soluciono, ni idea porque jajajaj.

sys.exit(app.exec_())

**Comment by marcotroncoso** [comment]
volvio a tirarme el error, sigo sin entender porque aparece eso  :(
