### ISSUE TITLE
Peer Review #12 Errores de arrastre

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#751]
Hola!

Estaba revisando las actividades del peer review, y tenía una duda respecto a errores de arrastre:
Si no está implementada una función (por ejemplo, el cargar recetas), pero está escrito el crear comida de tal forma que funcionaria si es que la función de cargar estuviera implementada.... ¿Puedo ponerle todo el puntaje, o cuenta como error de arrastre?

Gracias!!!! 🌵

**Comment by fringlesinthestreet** [comment]
Hola @gatochico

La idea es evitar en lo posible descontar por errores de arrastre. Asume que las funciones necesarias están bien implementadas :smile:.
