### ISSUE TITLE
Peer review 12, PyKitchen.cocinar()

### ISSUE THREAD

**Issue by catorres8** [IIC2233/syllabus-2018-2#752]
En el formulario de evaluación hay una parte que dice `Funciones del Backend - cocinar: Se guardan las recetas dentro de la carpeta horno. `.
Luego en el código que estoy revisando, en ese método se itera sobre cada receta en `self.recetas` y se abre un context manager en 'horno/nombre_receta.json" para guardar la comida preparada con el modo "ab".
Debería asignar el puntaje?? porque si bien se está guardando la comida en el horno, todo el tiempo se añaden al mismo archivo en lugar de tener un archivo por receta/comida.

**Comment by entamburini** [comment]
Hola!

Gran pregunta! Revisando el archivo, tu compañero hizo **literal** `horno/nombre_receta.json`, por eso guarda todo en un archivo, esto podría ser perdonable con medio punto, **pero** también está utilizando pickle en vez de json, por lo que no entendió lo que debía hacer y le corresponde 0 puntos :c 

Saludos! :)

**Comment by catorres8** [comment]
Gracias!! c:
