### ISSUE TITLE
Contraseña y confirmación de contraseña

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#753]
Es valido comprobar en el frontend  que la contraseña y la confirmación de contraseña son iguales,  y otras relaciones si es que los edit están vacios, y luego arrojar un mensaje en la interfaz?

**Comment by naoliden** [comment]
Preguntas por hacer las validaciones en el frontend?
En general puedes revisar la completitud de los datos o que los tipos de datos sean los correctos en el fronted, pero validaciones de usuario como logins, etc deben ser con conexión al servidor.
