### ISSUE TITLE
Sala de Espera

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#754]
Hola!
En el enunciado se dice lo siguiente:
"...y puedes permitir que los jugadores que no son jefes de partida, vean las opciones que este ingres ́o, pero no modificarlas."
Se dice **y puedes**, es decir, no es obligación que los demás jugadores puedan ver las opciones?

Gracias!

**Comment by Arcoirisky** [comment]
Hola~~
Como bien dices, no es obligación que los demás jugadores puedan ver todas las opciones del jefe. Pero recuerda que si hay cosas que comparten xD como el cronómetro 👀
