### ISSUE TITLE
Problema al recibir datos servidor

### ISSUE THREAD

**Issue by jaromero6** [IIC2233/syllabus-2018-2#755]
Hola
Tengo un problema con el envio de datos con el servidor. Si bien este recibe la mayor parte de las veces de forma correcta de parte del cliente hay veces que empieza a acumular mensajes por parte de este y tira error al hacerle loads con json, por ejemplo, si Jugador 1 envia su posicion desde su funcion tick para moverse le llega al server algo así:
       {"posisicion":(0,0),"jugador":1} -> Aqui lo recibe bien no ocurre errores
       {"posicion":(1,1),"jugador":1}Un numero en bytes{"posicion":(2,2), "jugador":1} -> Aqui ocurre el error
Los mensajes del servidor se acumularon, hice un try: y except en el servidor al hacer loads para ver si ocurria siempre y me di cuenta que ocurre a veces solamente. Mi duda es como solucionar esto, ya que si bien con posiciones no es tan complicado de solucionar (Se usa el try y except solamente y se ignoran los que se acumulan), pero me ocurre tambien con otras cosas, como por ejemplo al cambiar al hacer cambios muy rapidos en la sala de espera (si el lider aumenta muy rapido el puntaje o la velocidad ocurre el mismo error).
Quedo atento a su respuesta

**Comment by fgbruna** [comment]
#747 te podría servir, 
Tip: debes preocuparte de cuántos bytes espera el recv(no siempre debería ser la misma cantidad).
