### ISSUE TITLE
Ventanas de sala de espera

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#756]
¿Es absolutamente necesario que hayan dos ventanas separadas para el líder de la partida y los demás participantes?

Es decir, en lugar de eso, ¿se podría simplemente tener una ventana, y habilitar las opciones de líder solo para el que está en la posición de líder?

¡De antemano gracias!

**Comment by naoliden** [comment]
El hecho de que hayan ventanas distintas se refiere a que se realicen funcionalidades distintas, no necesariamente tienen que ser widgets distintos.

**Comment by hbkim94** [comment]
Gracias!
