### ISSUE TITLE
Notas T3

### ISSUE THREAD

**Issue by sicalderon1210** [IIC2233/syllabus-2018-2#758]
La nota de la Tarea 3 la subirán antes de la entrega de la tarea 4? Para tener una idea de como nos fue en esa tarea.

**Comment by ararojas** [comment]
Y la recorreccion de la T02? :)

**Comment by Hernan4444** [comment]
Estimados, los ayudantes están haciendo todo lo posible para tener ambas cosas para el lunes.

Saludos ✌️
