### ISSUE TITLE
Distribución Uniforme cortar rastro

### ISSUE THREAD

**Issue by diegovaras97** [IIC2233/syllabus-2018-2#759]
Hola, en la tarea no me queda claro parte del enunciado:

> "...cada cierto tiempo aleatorio T segundos, donde T distribuye uniforme continua U(a = 0,b = τ), se corta el rastro durante S segundos y S distribuye uniforme continua U(a = 0,b = δ). Debes deﬁnir δ y τ de manera que permita una buena jugabilidad..."

   La pregunta es, ¿estas distribuciones se calculan una vez por juego y siempre se usa el mismo numero obtenido por la distribución?, o ¿Cada vez que corte el rastro debo re-obtener un numero nuevo de la distribución?

De antemano Gracias! :computer:

**Comment by Arcoirisky** [comment]
El espacio que deja el camino no tiene porqué ser el mismo para cada jugador en una partida ni ser constante por juego o: Entonces, debes re-obtenerla cada vez que sucede ouo
