### ISSUE TITLE
Formato de mails

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#76]
Puedo restringir los caracteres de las direcciones de correo a los que yo quiera?
**Por ejemplo**: No se pueden usar mayúsculas, _#, $, %_, etc.

**Comment by cilopez** [comment]
La verdad es que cualquiera que sea tu decisión probablemente no afecte a tu nota, pero recuerda tu consola debe ser a prueba de inputs por rúbrica. Puedes señalar en tu _readme_ como lo hiciste para evitar ambiguedades.
