### ISSUE TITLE
Lag excesivo movimiento networking

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#760]
Hola!

Estoy intentando implementar el movimiento del jugador a través del servidor de la siguiente manera:

Implemente el tiempo mediante timers ( induviduales para cada jugador pero coordinados ). Por cada "tick" se le manda al servidor el movimiento que quiere hacer ese cliente, y el servidor lo devuelve a todos los jugadores para que estos lo hagan y se actualice la interfaz de cada uno.

Resulta que al hacer esto, incluso jugando 1 jugador solo, se laguea y se ve con saltos.

Alguna sugerencia?

**Comment by Arcoirisky** [comment]
Usas señales? 🤔

**Comment by jcechavarri** [comment]
@Arcoirisky 
Si, para enviar y recibir los mensajes con los datos de movimientos
Esto solo pasa si le pongo un delay bajo, si dejo el movimiento lento, funciona bien.

**Comment by Arcoirisky** [comment]
Entre varios se nos ocurrió distintas situaciones o:

Puede que estés sobrecargando el servidor con los cálculos del movimiento, puntaje, etc. Algunos de estos cálculos deben hacerse por personaje, si tienes 4 jugadores entonces debes calcular todo 4 veces D:!! 

También, puede que entre los cálculos y el envío de los mensajes exista un desfase considerable, lo cuál explicaría que si dejas el movimiento lento todo funcione bien.

¿Por qué no le echas un ojo a todo lo que debe hacer tu servidor y si de alguna forma le reduces un poco la carga? O:

**Comment by jcechavarri** [comment]
@Arcoirisky 

Por ahora, lo único que hace el server es retransmitir la señal de un usuario hasta todos, cada cliente calcula sus colisiones. Podrá ser otra cosa?

**Comment by jcechavarri** [comment]
@Arcoirisky 
Fijándome más en detalle, al parecer con movimiento también se producen saltos, solo que casi no se notan.

**Comment by Arcoirisky** [comment]
¿Se notan demasiado? Si es lo que te preocupa y no se notan tanto, puedes dejarlo así xD No importa tanto mientras funcione y no vaya a 1pixel por hora xDD 

De todas formas estamos pensando en qué es lo que sucede uwu Si nos enteramos de algo te respondemos aquí mismo

**Comment by jcechavarri** [comment]
@Arcoirisky 
Si, es bastante molesto el movimiento de hecho. El tema es que debe ser algo con el server o las señales, porque al implementar exactamente el mismo método de movimiento sin networking funciona perfecto.

Tengo mi cliente, frontend y servidor subidos en mi repositorio, la parte que hace los movimientos corresponde a las últimas dos funciones del frontend ( menos de 40 lineas ), te podría pedir que le echaras una ojeada rápida? A lo mejor pillas mi error fácil 😬 🙏 

Edit: Me di cuenta que estaba utilizando pickle en vez de json, al cambiarlo se laguea menos pero el problema persiste y es muy molesto.
