### ISSUE TITLE
arrow keys

### ISSUE THREAD

**Issue by Banfanci** [IIC2233/syllabus-2018-2#761]
cuando estoy seteando las teclas el key press event no me reconoce las flechitas pero si todos las demas teclas... que puede estar pasando?

**Comment by lily416** [comment]
¿Cómo estás llamando a las flechas? 
De paso, prueba imprimiendo el evento que recibes en el _key press event_, si no recuerdo mal los eventos de las teclas tienen un número asociado, con eso puedes ver que teclas son las que corresponden a las flechas de tu computador.

Ojalá te sirva, 
Saludos 👋🐍

**Comment by Banfanci** [comment]
Hola! Estoy usando keypressevent, y si, probe imprimiendo el evento, lo que entiendo que está pasando es que no entra en el keypressevent cuando presiono las flechas, no printea nada, pero si con todas las demás teclas... 
Saludos!!!

**Comment by lily416** [comment]
¿Qué sistema operativo usas? ¿Tuviste estos problemas con la actividad de PyQt?

**Comment by Banfanci** [comment]
Tengo windows y no, no lo tuve, incluso en el juego en sí cuando yo ponia las teclas a usar, en ese keypressevent me funciona, pero en el keypressevent de la otra clase donde estoy seleccionando que teclas usare para el movimiento, ahi no me las toma.

**Comment by jcechavarri** [comment]
Tuve el mismo problema, lo que pasaba era que al apretar las flechas, en vez de tomarlo como un `keyPressEvent` te lo toma como un comando para cambiar la selección al siguiente botón (*parecido a cuando aprietas tab para ir al siguiente cuadro de texto*).

Para solucionarlo, si tienes pocos qPushButtons en esa ventana, puedes deshabilitar los botones con `button.setEnabled(False)` y luego apretar la flecha.

**Comment by lily416** [comment]
Estaba probando tu código y parece que el problema está en el focus del widget, por lo que cuando se aprietan las flechas estas se utilizan para moverse entre los botones, el lineEdit, las check boxs y demases, pero después de apretar tab una veces se tiene acceso a las flechas en el keyPressEvent. 

Arreglando el foco debería funcionar bien,
Éxito 💪🐍

**Comment by bgsamilla** [comment]
Tengo el mismo problema pero con el espacio: @lily416 Seria valido dejar en el readme  "Debes apretar tab antes de usar el espacio" o algo por el estilo?

Hay alguna manera de hacer que sea automático?

**Comment by lily416** [comment]
@BSamilla si es que no puedes solucionar el problema, anota en el readme que se debe apretar `tab` para usar el `espacio`, pero ten en cuenta que dificulta mucho la corrección puedes tener descuentos.

Para tratar de arreglarlo averigua un poco sobre el método `setFocusPolicy` y cómo asociarlo a la venta que recibe el `espacio` como input.

Saludos y éxtico con la tarea 👋🌈
