### ISSUE TITLE
Leer bytes de csv

### ISSUE THREAD

**Issue by AndresCalvo** [IIC2233/syllabus-2018-2#762]
En #714 preguntaron (me parece que) lo mismo, pero la respuesta de ahí no me fue muy satisfactoria.
Tengo una base de datos en formato csv, donde guardé la información (con csv.writer) de los usuarios en formato byte, pero al momento de leerla (con csv.reader) recupero strings, no bytes (aunque sí comienzan con b'...'. Es como si el string entero representara la representación de un byte).
Leí por ahí que los csv no se pueden leer con 'rb' (y efectivamente no pude lograr que funcionara), por lo que abro el archivo en modo 'r'. El método string.encode() no me sirve para pasar string a byte pues me quedan de la forma b'b'...'', lo que modifica ciertos resultados, como el método hash aplicado a la contraseña.
¿Debería rehacer mi base de datos en formato .txt para no tener mas problemas, o existe algún método para recuperar bytes de mis strings?

**Comment by viantirreau** [comment]
Hola!
Te sugiero no utilizar `csv.writer` para guardar tu base de datos, puesto que internamente, lo más probable es que utilice algo del estilo de ```with open(file, "w") as file_name:```, es decir, los escribe como strings con cierto encoding.

Como en el output del _salt_ y del _hash_ habrá de seguro caracteres no imprimibles, o que no se encuentran en el _encoding_, lo ideal es guardarlo con la opción **`"wb"`** (o `"ab"` si quieres hacer _append_). Luego, debes leer el mismo archivo (que puede tener la extensión que quieras, ya que no afecta al contenido del archivo) con la opción **`"rb"`**. Recuerda que, al escribir estos archivos con el método `write`, debes pasar una cadena de bytes o un `bytearray`, no la representación "imprimible" de tus bytes (esa que es b"algo"), es decir, no debes pasarlo a `str`.

Saludos!
