### ISSUE TITLE
Peer review "recetas.book"

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#763]
La situación es que se trabaja con otro archivo que no tiene el mismo nombre que ***recetas.book***, pero tiene el mismo contenido que este. Para cargar y guardar recetas ocupa ese otro archivo y no directamente ***recetas.book***. Entonces debería asignar todo el puntaje o debería colocar 0 por ocupar otro archivo?

**Comment by fringlesinthestreet** [comment]
Hola @fjlopez7 

Si las funciones están bien hechas, **merece puntaje completo** en esos requerimientos. Puedes probar esto cambiando manualmente el nombre del archivo.

Sin embargo, debido a que salía explícito en el enunciado que debía trabajarse con el archivo llamado `recetas.book`, se aplica un **descuento de formato de 2 décimas.** Se agregó al cuestionario una sección para aplicar el descuento por formato.
