### ISSUE TITLE
Duda al abrir SalaEspera con Networking

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#764]
Hola!

Al utilizar networking, y abrir todo desde el cliente, tengo el problema que cuando quiero ingresar desde la VentanaIngreso (donde uno ingreso su usuario y contraseña) a la SalaEspera, mi programa tira a abrir la MainWindow de la SalaESpera, pero se queda en blanco, y luego se corta. Esto lo realizo actualizando un parametro, self.frontend en el cliente, una vez que ingreso un usuario y una contraseña correcta.

Ejemplo:
Antes:
Cliente: tiene un self.frontend = VentanaIngreso

Una vez que ingreso d emanera correcta, emito una señal al cliente, que lo odifica y queda de la siguiente manera:

Despues:

Cliente: tiene un self.frontend = SalaEspera

pero en eso momento como comente anteriormente, intenta de abrirse, pero se queda en blanco y desaparece a los 3 segundos, sin tira un error ni en el cliente ni en el servidor

Gracias a cualquiera de antemano!!

**Comment by trinigomez** [comment]
@pelao97 me pasa lo mismo, lo pudiste arreglar?
