### ISSUE TITLE
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2233/syllabus-2018-2#765]
Tengo un copy-paste de la ayudantia del chat. Al intentar abrir mi sala de espera, el programa me imprime el siguiente error y no me muestra la ventana. No se por que. No encuentro en que parte se utiliza QBasicTimer en la ayudantia y por lo tanto nose cual es mi error.

QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

**Comment by tsgonzalez** [comment]
Me pasa lo mismo :/

**Comment by Arcoirisky** [comment]
Solo dice eso o es solo el final del error que te aparece? ¿Puedes mostrar el resto del error?

**Comment by tsgonzalez** [comment]
Solo decía eso, pero al parecer era por intentar ejecutar una función del frontend con el cliente, en vez de mandar una señal cliente - frontend para que el frontend ejecutara la función.

**Comment by ebrzovic** [comment]
me pasa lo mismo, pudieron solucionarlo?

**Comment by tsgonzalez** [comment]
@ebrzovic  Si, lo que dije arriba. Yo con el cliente intentaba ejecutar funciones de alguna ventana (como por ejemplo, self.frontend.ventana_chat.funcion(), o algo por el estilo) y en vez de eso había que mandar una señal hacia la función del frontend para que se ejecutara directo en el frontend. Entonces haces onda, funcion_signal = pyqtSignal() , y luego en vez de hacer self.frontend.ventana_chat.funcion(), haces funcion_signal.connect(self.frontend.ventana_chat.funcion), y luego le emites algo para que se ejecute, y a la funcion le das como parametro la señal funcion_signal en el frontend (y bueno, para que el cliente pueda mandar señales debe heredar de QObject). 
Ojalá te sirva pq no sé explicarlo mejor xdxd.
