### ISSUE TITLE
Overload mensajes servidor

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#766]
Hola!

Al implementar el movimiento con el servidor, lo que hago es mover al cliente, calcular si hay alguna colisión con ese movimiento y luego mandar su nueva posición al server para retransmitirla. Esto causa que después de varios segundos de juego, el rastro del cliente1 se atrase en el cliente2. Me imagino que esto se debe a que son muchos mensajes y que el pc no puede procesarlos tan rápido, por lo que se va atrasando.

El único trabajo del server es retransmitir la posición, no calcula nada. 

Si envío la posición antes de hacer el movimiento, al querer doblar el personaje demora mucho en comenzar a hacerlo ya que se atrasa la señal de girar. Si disminuyo mucho el delay mejora un poco la situación pero no 100%

Alguna sugerencia para solucionar esto? Es válido dejarlo funcionando así?

Gracias!

**Comment by jaromero6** [comment]
Hola, tenia el mismo  problema que tú y lo solucioné disminuyendo la cantidad de mensajes que se le envía al server. Para esto lo que hice fue correr el juego "completo" en cada cliente ( Es decir en cada cliente se ejecutan los ticks de todos los jugadores) y lo unico que le mando al server es cuando un jugador apreta una tecla de direccion y la suelta para hacer que empiece o termine de girar. Esto mejoró considerablemente el retraso que se producia con el envío de señales, pero me genera cierto desfase al momento de girar que me causa problemas como se puede ver en esta imagen:
![image](https://user-images.githubusercontent.com/37157122/48969433-33c29080-efdd-11e8-8933-2954bccea8b6.png)
Donde en la primera el azul chocó pero en la segunda no.
Espero te ayude en algo esa idea, y aprovecho de preguntar lo mismo que tú, si hay alguna forma de disminuir el lag (Porque al menos al mandarle todas las posiciones al server en mi caso se hacia injugable, probé también corriendo el juego en el server y que este se las mandara a los clientes y tambien ocurría un lag que lo hacía injugable) .
