### ISSUE TITLE
Poder Fernando Atraviessa

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#767]
¿Para este poder existe un límite de tiempo, o dura el resto de la ronda?, en caso de que sí tenga un límite, ¿que se debería hacer en caso de que un jugador justo este cruzando un borde cuando se acabe el tiempo (con su sprite de jugador a medio camino de 'aparecer' al lado contrario) , cuenta como chocar con el borde o simplemente se deja que aparezca al otro lado antes de desactivar la inmunidad del poder?

**Comment by fernandodediegoavila** [comment]
Hola,
Como no está señalado en enunciado, quedan a tu criterio tanto el tiempo del poder, como la decisión de lo que ocurre cuando se acaba el tiempo.
Saludos!
