### ISSUE TITLE
Peer Review Act 12, falta de un modulo

### ISSUE THREAD

**Issue by mathiasvaldebenito** [IIC2233/syllabus-2018-2#768]
En una de las actividades que me tocó revisar no está contenido en el archivo .zip uno de los módulos necesarios en la actividad y con aspectos que se pide que se evalúen, ¿Qué se debe hacer en este caso?.

**Comment by fringlesinthestreet** [comment]
Hola @mathiasvaldebenito 

Debes asignarle 0 puntos en esos ítems del cuestionario.

¿Qué módulo falta? Si es posible, utiliza el (mismo) módulo tuyo o del otro alumno que debes corregir para poder corregirle el resto. La idea es evitar bajarle por errores de arrastre.

**Comment by mathiasvaldebenito** [comment]
Falta el modulo backend.py, por eso estaba con la duda de qué hacer.

**Comment by fringlesinthestreet** [comment]
@mathiasvaldebenito 

Subí en el [syllabus](https://github.com/IIC2233/syllabus/blob/master/Actividades/AC12/Soluci%C3%B3n%20Pair%20Review/backend.py) el `backend.py` de la solución para facilitar la corrección.

¡Ánimo! :smile:

**Comment by pablovejar** [comment]
a pesar de que este en el syllabus igual debemos aplicar puntaje 0, cierto?

**Comment by agustinespildora** [comment]
Tengo la misma duda que @pablovejar , en las dos actividades que me tocaron no hay ``backend.py``, esto fue un error de los alumnos o de los ayudantes?

**Comment by fringlesinthestreet** [comment]
@pablovejar Efectivamente. Debes asignar 0 puntos en los ítemes correspondientes. Se subió el módulo con el único propósito de facilitar la corrección.

@agustinespildora comprobamos que ambos alumnos **no subieron** el archivo. No fue un error en la recolección 

Ánimo en la corrección!
