### ISSUE TITLE
Tiempos Sala de espera

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#769]
Hola ! En el Feedback de la tarea dice que todos los tiempos del juego deben ser QThreads, QTimer o Threads. Mi pregunta es si el tiempo que pasa en la cuenta regresiva de la sala de espera se puede hacer simplemente con time.sleep() o hay que hacerlo con lo de arriba (Como la sala de espera no es el juego en si me imagino que si se puede, pero preguntar no esta demás)

**Comment by FernandoPieressa** [comment]
time.sleep() no deberia ser usado para la cuenta regresiva, porque eso va a parar toda la aplicacion y se tiene que poder visualizar la cuenta regresiva en la sala de espera. 

Saludos!

**Comment by NachoJuanDev** [comment]
Si el problema es la visualización de la cuenta regresiva en la sala de espera, se podría usar un time.sleep() en conjunto con un while, algo así:

```
i = 0
while i < 4:
    time.sleep(1)
    # actualizar label con el contador
    i += 1
# Lanzar juego
```
¿Esto tampoco puede utilizarse?

**Comment by BenjaPrograma** [comment]
me uno a la pregunta, y también con el detalle si se puede realizar en una venta al estilo pop up, o es necesario que se vea en la misma ventana de sala de espera? Esto suponiendo que el "pop up" le aparece a todos los players al mismo tiempo.
