### ISSUE TITLE
Invitados a eventos

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#77]
Cuando se invita a alguien a un evento, ¿a esa persona se le agrega el evento automaticamente al calendario? ¿no tiene la opción de elegir si quiere aceptar el evento o no?
Además, ¿un usuario no puede eliminar un evento al que fue invitado (solo de su calendario personal)?

**Comment by nachocontreras** [comment]
Hola!

Queda a tu criterio lo de agregar automáticamente el evento. 
No se puede eliminar un evento al que fue invitado (en el feedback está detallado que se pedirá).

Saludos! :smile:
