### ISSUE TITLE
Duda networking para conectarse a otro pc

### ISSUE THREAD

**Issue by Faalfaro** [IIC2233/syllabus-2018-2#770]
Hola,
Hasta ahora solo programe para conectarse al "localhost" y abrir varios clientes desde mi computador, mi pregunta es si se evalúa que la tarea se pueda jugar desde otros computadores y en si ese es el caso ¿que host debo ocupar? Ya intente con mi IP y con la de python.org, lo cual me tira este error:

OSError: [WinError 10049] La dirección solicitada no es válida en este contexto

Gracias!

**Comment by Faalfaro** [comment]
PD: Aunque no se evalué igual me gustaría saber como, ya que es difícil probar el juego con varias ventanas abiertas en el mismo pc.

**Comment by Conjo1** [comment]
No sé si se evalúa en la tarea, pero dentro de una misma red, creo que debería bastar con usar la IP local del computador que corra el server. O algo así probé recién. Buscando encontré [en stackoverflow](https://stackoverflow.com/a/166520) que ```socket.gethostbyname(socket.gethostname())``` te da la IP local (gran parte de las veces, al menos me funciona en Windows). Luego debería bastar con usar la IP local del servidor en los clientes. Al menos funcionó cuando lo probé conectándome desde mi teléfono (no tengo otro PC a mano), [el server detectó la conexión al menos](https://i.imgur.com/E3RKiDh.png)  

Tienen que estar en una misma red, y quizás también AP Isolation/Client Isolation estar desactivado en los ajustes del router (Tengo entendido que esa opción hace que dispositivos dentro de una misma red no puedan comunicarse entre ellos)

**Comment by johntrombon** [comment]
Hola! y de conectarme en otra red, sería igual o más fácil/difícil ? O el networking que sabemos solo sirve para redes locales?
