### ISSUE TITLE
Label de resultado de juego

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#771]
En el enunciado aparece

> Cuando alguno de los jugadores gane, para el jugador campeón debe aparecer un mensaje que señale que ganó el juego. Para el resto de los jugadores, debe aparecer un mensaje avisando que perdieron la partida.

Puedo hacer aparecer un mensaje a todos de quién ganó? 

Gracias!

**Comment by Arcoirisky** [comment]
El enunciado es bastante explícito al respecto 🤔

**Comment by cacoos** [comment]
Sí, pero igual me parece razonable entregar el mismo mensaje, únicamente porque así es en el juego real. Por eso preguntaba.
Seguiré el enunciado entonces

Gracias
