### ISSUE TITLE
cargar_recetas AC12 Peer Review

### ISSUE THREAD

**Issue by dgfluxa** [IIC2233/syllabus-2018-2#772]
Hola, quería saber si es válido volver a definir self.recetas como una nueva lista obtenida desde recetas.book, en el método de PyKitchen, en vez de realizar extend o appends.

Gracias

**Comment by fringlesinthestreet** [comment]
Hola @dgfluxa 

Mientras funcione está bien :smile:, debiese tener puntaje completo.

Saludos
