### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#773]
En el feedback aparece que se evalúa el uso de .gitignore, pero no se entregó ningún archivo como en las otras tareas, por lo que no le encuentro mayor uso excepto para no subir el caché de PyCharm. 
¿Es necesario usarlo?

**Comment by Arcoirisky** [comment]
¿Lo dices por la parte de descuentos? 
En este caso, como bien dices, no les dimos nada. Así que no hay necesidad de usar gitignore uwu)/
