### ISSUE TITLE
Error al abrir interfaz desde Cliente

### ISSUE THREAD

**Issue by pbyoma** [IIC2233/syllabus-2018-2#774]
Hola, al correr mi código de cliente, abro la interfaz de adentro de este al igual que la ayudantía, pero al hacerlo querer abrir otra ventana, esta nunca abre y la ventana que se encuentra abierta para abrir la siguiente ventana se queda pegada. De hecho si llamo un método de la clase que quiero que se abra, funciona perfecto, solo se me presenta problemas cuando pongo show().
Si la abro directamente desde el fronted, no presenta ningún problema. 
No ocupo imágenes.

**Comment by lily416** [comment]
¿Revisaste está issue #731? ¿Se te levanta algún error cuando tratas de abrir la ventana?

**Comment by pbyoma** [comment]
Si la revisé, pero a mi no me tira ningún error (solo se queda pegada la ventana actual y no se abre la siguiente), el programa nunca deja de correr y si tengo en mi código lo que sale en esa issue.

**Comment by lily416** [comment]
Intenta mandando una señal desde el cliente hacia el frontend, y que la señal llame una función que realice el show de la nueva ventana.

**Comment by pbyoma** [comment]
Si lo intente y tampoco funciona

**Comment by lily416** [comment]
@pbyoma trate de correr tu código para ver que estaba fallando, pero no tienes subido el archivo `mapa.ui`. Avisame cuando lo subas para poder comprobar lo que está pasando 😄

**Comment by pbyoma** [comment]
listo

**Comment by lily416** [comment]
Puede que tu problema se deba a errores que se levantan en el código 😨 

- Cuando trato de crear un usario se levanta: 
   ``` Python
   Exception in thread Thread-2:
   Traceback (most recent call last):
     File "...\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
       self.run()
     File "...\Python\Python36-32\lib\threading.py", line 864, in run
       self._target(*self._args, **self._kwargs)
     File ".../Tareas/T04/servidor/servidor.py", line 122, in listen_client_thread
       for linea in file:
     File "....\Python\Python36-32\lib\codecs.py", line 321, in decode
       (result, consumed) = self._buffer_decode(data, self.errors, final)
   UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 92: invalid start byte 
   ```

- Y cuando se inicia el servidor: 
   ``` Python
   Traceback (most recent call last):
   Servidor escuchando en ...
     File ".../Tareas/T04/servidor/servidor.py", line 234, in <module>
   Servidor aceptando conexiones...
       server = Server(DEFAULT_HOST, DEFAULT_PORT)
     File ".../Tareas/T04/servidor/servidor.py", line 44, in __init__
       user, password, sal, separador = linea.strip().split(b"separador")
   ValueError: not enough values to unpack (expected 4, got 3)
   ```

Entonces, debido a los errores se envían mal las señales y no por lo tanto no se abren las ventas que corresponden.

Ánimo corrigiendo los errores y éxito con la tarea,
Saludos 👋🌈 

PD: Hardcodeando un poco tu código (niños no hagan esto en casa) logré abrir el menú de espera, por lo que las señales parecen estar funcionando bien 👍

**Comment by jmsilvas** [comment]
Hola, llevó más de un día con el mismo problema. Realmente no sé como arreglarlo. Me quedan todas las ventanas así al abrirlas desde una venta "madre" (Si las abro por si solas no presentan ningún problema):
![image](https://user-images.githubusercontent.com/42247208/48980068-1e179e80-f0a3-11e8-9d6b-eae27b7a52bd.png)

Cualquier ayuda es bienvenida!

**Comment by lily416** [comment]
@jmsilvas ¿puedes subir lo que tienes hasta ahora a tu repositorio? para echarle un ojo 👀

**Comment by jmsilvas** [comment]
> Lo acabo de subir!



> @jmsilvas ¿puedes subir lo que tienes hasta ahora a tu repositorio? para echarle un ojo 👀

Perdón, me habia equivocado. Ahora lo subí bien.

**Comment by lily416** [comment]
@jmsilvas Tu error se debe a que la comunicación entre el cliente y el front-end **no** la estas realizando con señales. Una vez que incluyes señales para enviar los `show_error_message` se abre correctamente la ventana.

Es importante hacer una buena separación y comunicar correctamente las distintas partes
<img width="907" alt="captura" src="https://user-images.githubusercontent.com/26393515/48655870-164d5f80-e9fc-11e8-9e37-a28253e81194.PNG">
Entre la interfaz y los clientes debes usar señales, mientras que entre el cliente y el servidor usas los sockets.

Saludos y éxito con la tarea 👋🐍

**Comment by jmsilvas** [comment]
Ahí lo pude arreglar!! Muchiiiisimas gracias! Con respecto a lo de la foto, es mala práctica mantener un backend que solo interactua con la interfaz como el que tengo?? Es que en verdad sólo lo utiliza el frontend para manejar el juego propio por lo que eso no requiere intervenir en el Networking.

**Comment by lily416** [comment]
Personalmente, encuentro que es mejor práctica dejar el back-end junto al cliente para centrar las señales hacia un mismo lugar 🤔  pero en honor al tiempo te recomendaría dejarlo como está ⏳
