### ISSUE TITLE
Botón de Pausa

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#775]
1) Como se debe usar space para comenzar cada ronda, ¿igual se debe utilizar space para pausar el juego una vez que ya se estén moviendo, o se puede hacer sólo con el botón de pausa?

2) Si un jugador pausa el juego y luego otro también lo pausa, ¿el juego se resume (es decir se 'cancela' la pausa) o no se deja que continúe hasta que el mismo jugador que apretó pausa lo vuelva a hacer?

**Comment by Arcoirisky** [comment]
1) Queda a tu criterio si quieres usarlo para pausa o no. La idea de la barra espaciadora es iniciar el movimiento de forma que se puedan sincronizar los clientes de forma más simple o: 

2) Queda a tu criterio lo que desees hacer pero escríbelo en el Readme ouo)/
