### ISSUE TITLE
Concatenador/separador de paths universal

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2233/syllabus-2018-2#776]
Hola!

Acerca del _peer-review_ de la AC12.  Debería descontar puntaje si se abre un archivo usando un _path_ con el carácter ```'/'``` en vez de utilizar la librería ```os.path```?

Saludos,
Ariel

**Comment by naquiroz** [comment]
Hola! Si bien lo correcto es que debiera usar `os.path.join` o `os.sep`, no es lo que se está evaluando en la actividad por lo que no hay descuento.

Salu2 :v:
