### ISSUE TITLE
Poder "Felipe del Trio"

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#779]
¡Hola! ¿Es correcto asumir que los 3 poderes al azar que se generarán por este poder solo corresponden a los que el líder eligió al inicio de partida? ¿Y es obligatorio que aparezcan los 3 al mismo tiempo? ¿O es válido utilizar una función similar a la sgte.? (Aparecen con milisegundos de diferencia)

`for i in range(3):`
 &nbsp;&nbsp;&nbsp;&nbsp;`create(power)`

¡De antemano gracias!

**Comment by cilopez** [comment]
Hola @hbkim94 , si es correcto y también puedes usar la función que señalas 👍
