### ISSUE TITLE
Enviar correo a destinatarios no registrados

### ISSUE THREAD

**Issue by baaldana** [IIC2233/syllabus-2018-2#78]
Hola! ¿Se permite que usuarios que no se encuentren en db_users "reciban" correos? En otras palabras,¿hay que encargarse de que los destinatarios pertenezcan a la base de datos, o da igual?

**Comment by nachocontreras** [comment]
Hola! 

En la issue #50 se habló sobre la existencia de los correos.

Saludos! :smile:
