### ISSUE TITLE
Error extraño

### ISSUE THREAD

**Issue by marcotroncoso** [IIC2233/syllabus-2018-2#780]
Hola, tengo un mac y al correr mi codigo de repente funciona y derrepente no, ya que a veces me aparece este error "Segmentation fault: 11". A que se podria deber?

**Comment by marcotroncoso** [comment]
Tambien si saben a que se debe este otro error "QBasicTimer::start: QBasicTimer can only be used with threads started with QThread"

**Comment by marcotroncoso** [comment]
El segundo error ocurre cuando pasan los 10 segundos luego de apretar start en la sala de espera, se terminan se esconde la sala y deberia mostrarse la ventana del juego, pero ahi es cuando aparece el error.

**Comment by fgbruna** [comment]
@marcotroncoso 
> Hola, tengo un mac y al correr mi codigo de repente funciona y derrepente no, ya que a veces me aparece este error "Segmentation fault: 11". A que se podria deber?

#789
