### ISSUE TITLE
URGENTE: "Error" muy raro cuando corro el cliente

### ISSUE THREAD

**Issue by firulais33** [IIC2233/syllabus-2018-2#781]
Me pasa algo muy raro cuando corro el cliente. Ayer funcionaba perfecto, pero cuando me meto hoy y corro el cliente desde el terminal (no le hice ningún cambio entre ayer y hoy) no pasa nada. No me tira niun error ni nada por el estilo, solo queda corriendo y no puedo hacer nada para pararlo (no responde a KeyboardInterrupt, etc). Lo raro es que comenté lo que había después de if __name__ == "__main__" y lo cambié por un print y tampoco lo hace. Alguien sabe porque puede ser??

Gracias!

**Comment by jeschuwirth** [comment]
El if name te es un if name == "__main__": con guiones bajo al lado del main.

Si eso no te soluciona comenta en esta issue :) 

EDIT: note que si tenías los guiones bajo pero el foro lo cambia por palabras en negrita

**Comment by jeschuwirth** [comment]
No estoy seguro cual puede ser el error, abriste el servidor antes de correr el cliente ?

**Comment by firulais33** [comment]
Si lo abrí, en todo caso no hay problema en correr el cliente sin abrirlo... Nosé cual es el problema, y es muy raro siendo que hace un rato me funcionaba todo sin problemas, ya además la consola no tira ningún error
