### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#782]
Hola, 

no me fijé en las instrucciones y hice mi protocolo de networking en UDP, pero me acaban de decir que tiene q ser en TCP, revisé el enunciado y efectivamente tiene que ser TCP. 

Que tanto descuento recibo si entrego en UDP? 
Consideren por factor que en el material de clases sale:

> Ejemplos de uso incluyen aplicaciones donde es preferible que se pierdan algunos mensajes en vez de retrasar la comunicación, como el streaming de audio o video, ciertos juegos en línea, etcétera

Entonces me quede con esa idea al ponerme a programar.

**Comment by Arcoirisky** [comment]
Hola~ Estamos evaluando TCP :( Si utilizas UDP estaría completamente malo u-u Te sugiero cambiarlo lo más pronto posible

**Comment by Kitaps** [comment]
Oka, 
me temía eso jajaj
gg nomas
Gracias
quiero cometer sudoku

**Comment by Arcoirisky** [comment]
@Kitaps me notifican por interno que se a cambiado de opinión! Si te funciona bien el UDP  puedes usarlo O:!!!!
 (Si ya cambiaste la mayoría perdonad ;—;)

**Comment by Kitaps** [comment]
Gracias
