### ISSUE TITLE
Error Server

### ISSUE THREAD

**Issue by juanfcolopez** [IIC2233/syllabus-2018-2#784]
hola, una consulta, estoy interactuando server-cliente y me aparece el siguiente error, a veces me sale al comienzo de la conexión y en otras me sale como a la mitad de un proceso. ¿Qué lo puede estar provocando?
![duda](https://user-images.githubusercontent.com/42149950/48972655-a3507400-f00d-11e8-84bb-5b6f21454976.jpg)

**Comment by jeschuwirth** [comment]
Puede que tengas un problema de que se te acumulen mensajes en el servidor, básicamente tu cliente envía un mensaje y luego otro antes que el servidor terminara de leer el primero, lo que causa que se acumulen. Imprime todos los byted que le lleguen al server, luego el string traducido y luego después de hacer el cambio en json, así deberías poder encontrar el problema.

Suerte en la entrega :)

**Comment by juanfcolopez** [comment]
lo revisé y el error se me produce cuando presiono las teclas para moverme hacía los lados, en si el problema está con el keyPressEvent, que no sé por qué, cuando recibe el evento de esas teclas me cierra automáticamente a cliente y por eso me lanza el error en pantalla, porque no lee bien los mensajes entre servidor y cliente. Pero cómo se podría solucionar este problema? como que hay interferencia o se me ocurre asociarlo a lo de una issue anterior, en la cual no leía el evento de las flechas de dirección porque en ese momento tenían una función de estar seleccionando los botones que se encontraban en la interfaz.

**Comment by jeschuwirth** [comment]
Por lo menos sabes más o menos dónde está tu problema, no es de threading, sino que de interfaz, por algún motivo se te cierra y manda un último mensaje que el server no sabe traducir y se cae.

Te queda revisar en el frontend que el keypressevent funcione bien. Por lo que escribiste al final te diría que hagas que el programa no acepte inputs por teclado o que no hagan nada hasta que comience la partida, eso por lo menos te va a dejar trabajar sin que se levante el error
