### ISSUE TITLE
Velocidad del juego

### ISSUE THREAD

**Issue by cacoos** [IIC2233/syllabus-2018-2#785]
Hola!

En el Enunciado aparece que el líder puede seleccionar la velocidad del juego. A qué se refiere esto? A la velocidad con la que avanzan las curvas?

Gracias!

**Comment by lily416** [comment]
Puede referirse al radio de giro o cuántos radianes se mueve cuando se aprieta una tecla.
Queda a tu elección cuál de los dos eliges, mientras se **note claramente** que al aumentar el parámetro aumenta la velocidad de la partida.

Saludos y éxito con la tarea 👋🌈

**Comment by BFFV** [comment]
Y también se debe mover más rápido cuando no está girando?

**Comment by lily416** [comment]
Personalmente encuentro más normal que se mueva a la misma velocidad si es que está girando o se mueve recto, pero si sientes que es más lógico que se mueva más rápido cuando va recto puedes dejarlo así.
