### ISSUE TITLE
Duda programación circular

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#786]
Hola! Leí la issue #736 existente respecto a que podría definirse como programacion circular y que no, pero tengo dudas en un caso muy específico: 

Por temas de número de líneas, mi tarea quedó con 2 archivos de frontend... para poder hacer los saltos de ventana entre etapas, podría importar f1 en f2 y viceversa? O esto también se consideraría incorrecto?

Saludos!!!!!

**Comment by Arcoirisky** [comment]
Son parte de un mismo fronted pero moduralizado. Esta bien que trabajen entre ellos xD 
Es peligroso cuando se comunican con el backend y este de vuelta sin hacer uso de señales ni cosas así. 
Insisto que, como lo estoy entendiendo, están separados por modularización y si los necesitas juntos puedes importar uno en otro tranquilo ouo)/

**Comment by gatochico** [comment]
Si, me referia a eso ❤️ gracias!
