### ISSUE TITLE
Problema al intentar volver a iniciar los QTimers()

### ISSUE THREAD

**Issue by rsnegrin** [IIC2233/syllabus-2018-2#787]
Cuando trato de empezar una nueva ronda, tengo que volver a iniciar todos mis QTimer() que había hecho para el manejo de los movimientos de los personajes y que había parado cuando estos personajes mueren. Sin embargo, cuando trato de volver a hacerle timer.start() estos nunca vuelven a entrar a la función a la que estaban conectados. El programa no tira ningún error, simplemente no vuelven a iniciar los timers()

**Comment by lily416** [comment]
¿Intentaste reasigna el `QTimer` y después hacer `.start()`?

Saludos 👋🐍

**Comment by roberto009** [comment]
Si, intenté reasignando el QTimer, volviéndolo a crear. He intentado casi todo :(

**Comment by rsnegrin** [comment]
Probé usando señales para llamar a mi función y ahí parte el QTimer! Gracias
