### ISSUE TITLE
Problema JSON desde Frameworks mandando una señal

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#788]
Hola! Estoy mandando una señal al server para que este le entregue al cliente una lista con los poderes habilitados por el jefe pero cuando el mensaje le llega al "escuchar_cliente_thread" (mismo nombre de la ayudantía) me sale el siguiente error con respecto a JSON. Estoy mandando un dict con una lista como una de sus values(), ya he mandado mensajes como este sin tener problemas :(

<img width="828" alt="screen shot 2018-11-25 at 01 28 39" src="https://user-images.githubusercontent.com/37150130/48975541-89388500-f051-11e8-836d-d9950f794459.png">

**Comment by viantirreau** [comment]
Hola!
Mira el #747 😉
