### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by BenjaminRubio** [IIC2233/syllabus-2018-2#789]
Al intentar correr mi programa con más de un computador todo funciona perfecto excepto
al empezar el juego, después de unos segundos tira el error

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

creo que se produce en el socket.recv(4) del cliente pues rastreando la comunicación el servidor alcanza a mandar algo pero el cliente no a recibirlo, pero es raro pues alcanza a hacer muchas comunicaciones antes de fallar.

Si se les ocurre por que podria ser se los agradecería.

**Comment by IchottMano** [comment]
Hola!

Una SIGSEGV (o segmentation fault) puede tener muchas causas, este error se debe a que tu programa intenta acceder a memoria que no se suya.

Mi recomendación es que intentes ver si hay algun objeto (lo mas probable que sea de PyQt) que no estés guardando en memoria como atributo de tu frontend o backend.

Suele suceder que python detecta que un objeto no tieneas referencias y lo elimina, liberando su memoria. Al intentar acceder al objeto, se levanta la segmentation fault.

Espero que esto resuelva tu problema, de no hacerlo o tener mas dudas por favor no dudes en preguntar.

Saludos!
