### ISSUE TITLE
¿Se pueden usar defaultdicts en la tarea?

### ISSUE THREAD

**Issue by inveterate-cladocerus** [IIC2233/syllabus-2018-2#79]
Hola!
Básicamente eso, quiero saber si se pueden usar, porque se deben importan datos y existen restricciones en la tarea respecto a eso.
Saludos.

**Comment by IchottMano** [comment]
@Prochotito Hola!
Dado que se permite la librería collections, si se pueden usar.
Para preguntas de este tipo por favor usar la issue #12 

Saludos
