### ISSUE TITLE
Error al Abrir Pestaña del Chat

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#790]
Hola!, llevo casi un dia pegado en tratar de abrir el chat (hasta ayer me funcionaba, pero al implementar el registro de usuarios ya no me abre y me tira el siguiente error : QBasicTimer::start: QBasicTimer can only be used with threads started with QThread). Ni siquiera estoy usando QBasicTimer, y no entiendo tampoco de donde podría venir el error, aunque tengo mis sospechas de que es donde estoy definiendo el servidor_signal :c 

Para abrir la pestaña del chat necesito una señal enviada desde el servidor, donde efectivamente se ingresa al usuario, pero cuando trato de hacer chat.show() me tira ese error

**Comment by Arcoirisky** [comment]
Estas enviando señales a medida que llegan nuevas? Puede que estén chocando señales y por dentro el programa te dice que algo no está bien. 

Puede que parezca que los computadores hacen las cosas en paralelo pero la verdad es que es mentira :’( A nuestra velocidad lo creen así pero cuando hay interferencia se caen u-u

Es una idea ¿por qué no revisas qué pasa antes de intentar abrir la nueva ventana?
