### ISSUE TITLE
setText en Mac

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#791]
Hola! 
En Mac a veces pasa que cuando se sete el texto de un Label no se cambia automáticamente, sino que uno debe cambiarse de pestaña y volver y se ve el cambio. En una ayudantía de hecho al ayudante le pasó lo mismo. Importa esto? Porque pareciera muchas veces que no estoy informando de los errores en el registro e inicio por ejemplo.

Gracias!

**Comment by Arcoirisky** [comment]
Podrias anotarlo en el readme si lo crees necesario. No todos los ayudantes tienen Mac pero si llegara a ocurrir un error, nos serviría esa información para tenerlo presente en la corrección.
