### ISSUE TITLE
Necesidad de networking para elegir las teclas de movimiento

### ISSUE THREAD

**Issue by jfacuse** [IIC2233/syllabus-2018-2#792]
Hola! Tengo una duda con el feedback de la tarea. En el item de logica del juego, la parte de se pueden elegir las teclas de movimiento esta marcada en rojo para que sea con networking. Por qué es esto ? Desde mi punto de vista tanto al servidor como a los demas jugadores les da lo mismo cuales teclas se esten utilizando para moverse, por lo que no veo la necesidad de que se haga esta parte con networking. de hecho en cualquier videojuego en linea la eleccion de los controles se hace de manera local, es decir cada jugador elige sus controles y no necesita avisarle al servidor de este cambio.

**Comment by Arcoirisky** [comment]
Cuando lo pruebes todo en un solo computador si importarán las teclas que elijas xD Pomte tu que dos o todos los jugadores elijan ASDW ¡piensa en el caos! 😱
