### ISSUE TITLE
Comprobar Regex y forma correo

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#795]
Las secuencias de regex para comprobar que un correo o una clave cumple con lo que se pide, debería ser solamente una secuencia para cada una o pueden ser varias que comparen distintas cosas, como si tiene bien el largo, están bien las mayúsculas, tiene un solo punto, etc...?
El punto en el correo es válido de las siguientes formas?
1- juanito@uc.cl
2- juanito@.uccl
3- juanito@uccl.
o solamente como en la forma 1?

**Comment by hbkim94** [comment]
No es difícil lograr que acepte solo la forma 1 con regex, que en mi opinión debería ser la forma correcta :o Quizás sea bueno poner en el Readme qué criterio usaste también!

p.d. No soy ayudante, solo opino jaja

**Comment by ncasassas** [comment]
Tengo la misma la misma duda y también sobre si después del último "." puede haber tantos caracteres como el rango de 4-12 lo permita, por ejemplo si se puede tener un correo del tipo:
loquesea@u.estelargo
Tambien tengo la duda si es posible tener correos con el formato:
loquesea@correo.123
loquesea@123.123
etc.

Saludos!

**Comment by Arcoirisky** [comment]
El punto en los correos deben ser válidos de la forma convencional. Al menos yo no he visto ninguno que sea de la forma 2 y 3 que muestras xD 

@nko205 yo te diría que si sobre los caracteres y el formato de 123.123 aunque déjame confirmarlo antes. Cualquier cosa os digo en esta misma issue

Y como dice @hbkim94 No es difícil hacerlo en una sola instrucción  y es lo que se esperaría

Ánimo y suerte!!

**Comment by haarenas** [comment]
Aprovechando esta issue, después del arroba pueden ir guiones bajos?

**Comment by Arcoirisky** [comment]
@haarenas El enunciado sólo especifica que después del arroba solo debe haber un punto y el largo debe ser entre 4 y 12. Si puede o no tener guion bajo después del arroba queda a tu criterio :D

**Comment by ariel-m-s** [comment]
Según lo que entiendo del enunciado, el correo __abcde@abcde.__  sería válido. Es así?

**Comment by Arcoirisky** [comment]
@amartinezsilberstein Sip.
