### ISSUE TITLE
URL Foursquare

### ISSUE THREAD

**Issue by danustilovsky** [IIC2233/syllabus-2018-2#796]
Hola, para crear la API en Foursquare me pide ingresar un URL. ¿tiene que existir o puede ser cualquier cosa?

gracias

**Comment by lily416** [comment]
Puede ser cualquier cosa.

Éxito con la tarea 👋🚐

**Comment by lily416** [comment]
Puede ser cualquier cosa.

Éxito con la tarea 👋🚗

**Comment by danustilovsky** [comment]
Gracias!!
