### ISSUE TITLE
Busqueda de lugares

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/syllabus-2018-2#797]
Al principio donde nos piden ubicar los lugares cercanos, necesitamos poner como parametro tanto la posicion y el radio. En el caso de la posicion poner la pos actual del usuario no? y en cuanto al radio de busqueda, lo dejamos como input al usuario (al igual que cuantos resultados quiere ver)?

**Comment by Arcoirisky** [comment]
Holasssss~

La posición lo obtienes de la API al buscar el lugar que un usuario quiera según sus preferencias. El radio que debes utilizar está en el enunciado. Punto 2.2 pasó 7 del primer párrafo. Con ese radio buscas todos los paraderos de la posición que desees y entre todos esos te quedas con el más cercano.  Con eso tienes la posición del lugar y el paradero objetivo que debe alcanzar tu usuario. 

Así se obtiene el lugar más cercano. ¿Se entiende mejor? 

2) a que te refieres con cantidad de resultados? A los lugares cercanos a cierta posición o a las preferencias que eligió el usuario para decidir a dónde ir? Porque el usuario al inicio buscará una ubicación objetivo y después se trabaja con esa misma (a menos que el usuario decida cambiar su elección pero eso es aparte)

**Comment by cdlanas** [comment]
Holaa, no sé si entendí bien, al principio del programa cuando se le ofrece al usuario elegir un lugar de destino también hay que ocupar la ubicación del usuario? o hay que pedirle al usuario que ingrese una ubicación? ya que puede que la ubicación de destino se encuentre lejos (más allá del radio) del usuario.

**Comment by NicolasCabello** [comment]
Esa era la pregunta que tenia!, porque lo que respondieron fue para buscar el paradero (en el 2.2 y yo pregunte por la 2.1), tambien el radio es para buscar paraderos, entonces no se 🤷‍♂️.

En cuanto a la cantidad de resultados me referia a que por defecto en el 2.1 se ocupa 10, se le debe preguntar al usuario o dejamos 10?

**Comment by Prochotito** [comment]
cps

**Comment by Arcoirisky** [comment]
Dejen 10 ouo No es necesario preguntar por otro radio uwu

**Comment by NickCastillo** [comment]
Aun no me queda bien claro, según la documentación el radio esta en metros entonces poner radio = 10 en la primera parte, al buscar lugares, nos entregaría solo los lugares cercanos que no es la idea. Los paraderos deben estar cerca de la ubicación del cliente pero este puede querer ir a un lugar lejos o me equivoco? Entonces, estaria bien buscar los lugares, por ejemplo, a una distancia máxima de 10.000 metros y si no hay nada, entonces mató ?

**Comment by haarenas** [comment]
Según yo el radio que sale en el ejemplo de Foursquare no hay que pescarlo, se debería usar 10k de radio en ambas APIs (la de Foursquare y Transantiago), por que no tiene sentido buscar 100 metros en la API de Foursquare y 10k en la del Transantiago.

**Comment by BlancaMunizaga** [comment]
pero entonces la latitud y longitud que se usa para encontrar el lugar al que se desea ir (2.1) es la actual??

**Comment by Arcoirisky** [comment]
Primero, disculpad la demora ;--; El semestre nos ataca a todos

Ahora, Entiendo la confusión que existe al buscar los lugares. Como bien dice @NicolasCastillo24 el usuario puede ir a donde él quiera. Su trabajo es buscar lugares según descripción o categoría con la API foursquare pero, esta requiere de una ubicación y un radio ¿no? Nuestra idea es que DCConnect sea para todo santiago. 

No necesariamente será buscar el lugar más cercano al usuario. Eso depende de lo que seleccione el usuario. Hay varias formas de solucionar esto, sean creativos y escribanlo en su readme! Igual, la API debería de darles la ubicación de estos lugares para que puedan hacer los siguientes puntos del flujo.

@haarenas, se utilizan 10km para la api del transantiago porque necesitan el paradero más cercano al usuario y al destino. Pedirles más que eso darían muchísimos más resultados de los que ya les deben de aparecer D: 

@BlancaMunizaga La posición actual sólo se utiliza para encontrar los paraderos y micros más cercanos al usuario con la API del transantiago :D El usuario quizás quiera llegar a la otra punta de santiago con sus elecciones porque puede u-u)

**Comment by juanfcolopez** [comment]
Entonces el radio que se debe usar para Foursquare también es de 10k? o tiene que ser uno mayor? para que pueda ser usada en todo Santiago

**Comment by Arcoirisky** [comment]
Hay muchas issues que hablan de ese tema ¿por qué no les echas un vistazo? @juanfcolopez
