### ISSUE TITLE
Flujo de informacio.2

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/syllabus-2018-2#798]
En el punto 2 de flujo de informacion, dice:
'Encontrar un lugar al que se desea ir. Para esto, se debe permitir al usuario buscar por categor ́ıas o descripci ́on y que luego pueda elegir alguno dentro de una lista entregada por el programa'

Mi duda es que categorias se deben mostrar? porque todas es una lista practicamente infinita, la cual obtuve de: https://developer.foursquare.com/docs/resources/categories

Seria valido solo tomar las mas 'tipicas' como por ejemplo: Arts & Entertainment, College & University, Food, Nightlife Spot, Outdoors & Recreation, Shop & Service?

**Comment by Arcoirisky** [comment]
Debes considerarlas todas al momento de validar la consulta.
No necesitas mostrarlas todas uwu) pero que quede claro que cualquiera la de la lista infinita funcione :D

**Comment by alexaptib** [comment]
@Arcoirisky gracias por la respuesta pero sigo con la duda ya que el enunciado dice:
'Por cada uno de estos lugares se debe mostrar la informaci ́on relacionada. Estos pueden ser comentarios, ubicaci ́on, horario u otra informaci ́on relevante al contexto que entregue la API de Foursquare.'

de ahi entiendo que debo ofrecerle al usuario una lista de categorias, con una descripcion relevante, y luego pedir al usuario que eliga una. no es asi? si es asi, entonces como ofrezco toda la lista?

**Comment by Arcoirisky** [comment]
Como bien dices el enunciado menciona que el usuario puede buscar por categorías o descripción un lugar al cual ir. Luego, puede seleccionar alguno de estos lugares. Entonces, por cada uno de estos lugares, los seleccionados, se debe mostrar su información. Esta información son los comentarios, ubicación, horarios y cualquier otra información relevante que te pueda entregar la api.

Se entiende mejor o igual la lectura del párrafo? O:

**Comment by alexaptib** [comment]
@Arcoirisky mi duda es esta: el usuario debe ingresar una categoria/descripcion y luego el programa ver con cuales calza, o si yo debe primero mostrar las opciones posibles y que de esa lista el usuario eliga

**Comment by Arcoirisky** [comment]
Lo primero. Por eso no es necesario que muestres todas las opciones. Sólo validarlas o:

**Comment by alexaptib** [comment]
@Arcoirisky Perfecto, ahora si entiendo, gracias por la ayuda! Asumo entonces que si no se entrega uno valido simplemente se dice que no se encontró nada con ese criterio

**Comment by Arcoirisky** [comment]
Sip, aunque nunca está de más dar ejemplos de inputs válidos al momento de decirle que no se encontró nada al usuario uwu)/ 

Piensa en tus correctores y ellos pensarán en ti <3

**Comment by fjlopez7** [comment]
Para ingresar una consulta con categoría (category_id), nosotros debemos relacionar como con un diccionario cada categoría al id de la categoría o se debe pedir al usuario directamente el id de la categoría?

**Comment by alexaptib** [comment]
@Arcoirisky En relacion a buscar por categoria, hay dos maneras de hacerlo a mi parecer:
con 'https://api.foursquare.com/v2/venues/search' 
- usar el parametro query
- usar el parametro categoryId

Se puede usar el primero? o debemos hacer el segundo obligatoriamente?

**Comment by NicolasCastillo24** [comment]
Si yo cree una lista con las palabras de "shortTerm", "pluralTerm" y "name" dentro de la llave de category (por ejemplo Pizza Place y Pizza Places) de los lugares y luego compare esta lista con la(s) categoria(s) seleccionada(s) por el usuario, estaría bien? o buscan que trabajemos con los parámetro query y categoryId?

**Comment by Arcoirisky** [comment]
@alexaptib Puedes usar el primero. No encontré en el enunciado que sea obligatorio utilizar el categoryId 
\(owo)/

@fjlopez7 El usuario pide lugares por categorias o descripción. No tiene como ni porqué saber los Ids de las categorías que maneja la API. Eso ya es parte de cómo hacen ustedes las consultas o:

Perdón la demora ;--;

**Comment by isavega** [comment]
Pero supuestamente usando el parámetro query='algo' me entrega los nombres de todo lo que tenga 'algo' en su nombre (independiente de la categoría). En ese caso, se tomaría como descripción cierto?

**Comment by Arcoirisky** [comment]
Sip. Porque buscas según palabras clave o generales que entrega el usuario :D

**Comment by JavierNarvaez** [comment]
> Pero supuestamente usando el parámetro query='algo' me entrega los nombres de todo lo que tenga 'algo' en su nombre (independiente de la categoría). En ese caso, se tomaría como descripción cierto?

En ese caso contaría como categoría o como descripción? Entiendo que uno puede usar query="algo", pero como el enunciado dice que se deben ofrecer esas 2 opciones, query estaría filtrando según las 2 opciones al mismo tiempo o no? Por ejemplo, si busco por la palabra clave "banco" al mismo tiempo filtraría los elementos que estén en la categoría Banco y los elementos que en su descripción tengan la palabra banco.

**Comment by Arcoirisky** [comment]
Query contaría como descripción ya que si bien te busca categorías de bancos, es más que nada porque los nombres de los bancos generalmente tienen banco en ellos. Pero no necesariamente me retornará todo lo que la categoría me pueda dar. 

Por ejemplo, si busco lapiz me puede aparecer lápiz López con query pero no por eso me aparecerá la nacional a pesar de que ambas venden lápices. (Esto es un ejemplo bien hipotético). Aunque, si existiera una categoría tipo “librería técnicas” ahí me podrían aparecer ambas dos. (Para esto me guió por la descripción de query del enunciado. Que busca palabras concretas)

**Comment by JavierNarvaez** [comment]
Ah ya, esa era mi pregunta. Más arriba leí que se podía usar query para filtrar por categoría, pero te entiendo. Gracias!
