### ISSUE TITLE
Duda git

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#8]
Es posible seguir practicando git y seguir subiendo archivos al repositorio para practicar?

Gracias

**Comment by FernandoPieressa** [comment]
No hay ningún problema, igual puedes generar tu propio repositorio personal por si quieres ser mas ordenado con el repositorio donde entregaras todas tus tareas/actividades del semestre.

Saludos!

**Comment by pablovejar** [comment]
y como creamos un repositorio personal?

**Comment by kaminetzky** [comment]
Es muy fácil crear un repositorio en Github. Tienes que apretar el “+” que aparece arriba a la derecha en la página. Ahí podrás crear un nuevo repositorio fácilmente! También puedes crear uno desde la página principal, apretando el botón “New Repository” que aparece a la izquierda. :)
