### ISSUE TITLE
Requisitos entrada usuario

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#80]
Hola! Cada vez que en el enunciado sale "la contraseña ni nombre de usuario pueden contener ',' o ';' " o "Si hay más de un destinatario, las direcciones de correo deben ser escritas separadas por comas", etc. Debemos preocuparnos de que el usuario lo haga así? o asumimos que así lo hará? Gracias!

**Comment by cilopez** [comment]
Debes preocuparte que así lo hará, tu programa debe ser a prueba de inputs. Pero en caso de que no lo puedas implementar o no quieras (perderas puntaje) puedes señalarlo en tu _readme_.
