### ISSUE TITLE
Duda informacion de Foursquare

### ISSUE THREAD

**Issue by Michelmagna** [IIC2233/syllabus-2018-2#801]
Hola!

Tenía duda respecto a que se refieren realmente con "comentarios" de un lugar. 

Además, he notado que por defecto todos los lugares tienen nombre, pero no todos una dirección "entendible" (Ej: Avenida Vicuña Mackenna 1234). Así mismo con sus categorías, que algunos no tienen y en este caso no sería posible filtrarlos por estos parámetros. Ante esto, es realmente importante mostrar mucha información del lugar, o basta con el nombre y que el usuario seleccione este?

Gracias!

**Comment by lily416** [comment]
Tienes razón, la información que entrega la API no incluye comentario, ni descripción, la idea es que muestres suficiente información relacionada al evento como para poder elegir entre dos de ellos.

¿Para qué quiere utilizar la dirección? Si es para calcular el paradero más cercano o distancia la API te entrega las coordenadas del evento, por lo que con eso debería ser suficiente 🤔

Saludos 👋🚐
