### ISSUE TITLE
Error al realizar consulta

### ISSUE THREAD

**Issue by pelao97** [IIC2233/syllabus-2018-2#802]
Al hacer una consulta con el formato del ejemplo:
url = 'https://api.foursquare.com/v2/venues/search'
    CLIENT_ID = 'UZH5QZUA3KZBPDGMXFNOYMLPR335MZX0ZT53QFLJDCX1ZJO5'
    CLIENT_SECRET = 'PJBMY14HLS1MUNNFVYU11GJWTXAK0IGXKSVPTLR4SO1FEXGV'
    params = dict(cliente_id=CLIENT_ID,
                  client_secret=CLIENT_SECRET,
                  intent='browse',
                  v='20180323',
                  ll='-33.390428.-70.594271',
                  radius=100,
                  limit=10)
    resp = requests.get(url=url, params=params)
    data = resp.json()
    print(data)

recibo el siguiente error:

{'meta': {'code': 400, 'errorType': 'invalid_auth', 'errorDetail': 'Missing access credentials. See https://developer.foursquare.com/docs/api/configuration/authentication for details.', 'requestId': '5bfd52189fb6b752ad75d340'}, 'response': {}}

Lei en internet que puede ser porque uno de los parametros esta mal ingresado, pero no se cual de  ellos es

Gracias de antemano!!

**Comment by javalenzuela3** [comment]
Creo que puede ser el ll que tiene un . en vez de una , separando latitud y longitud

**Comment by pelao97** [comment]
gracias!!
