### ISSUE TITLE
Buscar por descripción

### ISSUE THREAD

**Issue by pablosteinmetz** [IIC2233/syllabus-2018-2#803]
En el flujo de infomación punto 2 se hace alusión a poder buscar un lugar por categoría o descripción, ¿la descripción en que consiste? No he visto ninguna request que entrega descripciones cerca de latitudes y longitudes en Chile.

**Comment by Michelmagna** [comment]
Tengo la misma duda, los parámetros que entregan los lugares son su nombre, dirección y categorías, pero estos dos últimos a veces están vacíos incluso.

**Comment by Prochotito** [comment]
cps

**Comment by fabarros** [comment]
Same duda

**Comment by Arcoirisky** [comment]
Se me ocurre un ejemplo simple. Categoría podría ser bebestibles o alimento mientras que la descripción podría ser café, hamburguesas, sopaipillas, su buen choripan, etc. Más que descripciones extensas piensen en cómo buscan algo en el buscador, usando palabras claves. (Es una forma de verlo, ojalá se les haga una idea de lo que podría buscar un usuario) 

Los parámetros que entregan los lugares son la información de estos. La cual puede contener parte de la descripción :eyes:
