### ISSUE TITLE
Buscar paradero cercano

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#804]
En la parte 2.2 del enunciado en el punto dice que:
7. Dados los paraderos de los recorridos de las micros, obtener con la API de Transantiago, las
coordenadas de cada uno de esos paraderos y ver si se está un radio de 10 kilómetros desde donde
uno se encuentra.

Se puede realizar de forma inversa, o sea ver cuales paraderos (donde pasan esos microbuses) coinciden que estén en un radio de 10 kilómetros desde donde uno se encuentra. De esta forma evitar hacer varios llamados, ya que son varios los paraderos que se arroja en el recorrido de las micros.

**Comment by lily416** [comment]
Queda a tu criterio como lo implementes mientras funcione y de los resultados esperados.

Saludos 👋 🚌

**Comment by acpopper** [comment]
Respecto a esto mismo, podría (alterando el flujo de información del enunciado) por ejemplo, obtener los paraderos mas cercanos al lugar como al usuario, ver si comparten una misma ruta y si no, ir revisando de la misma forma paraderos más alejados de cada uno, hasta encontrar un par de paraderos que si compartan una ruta? Porque conseguir todos los paraderos de todas las rutas que pasan por algunos paraderos específico pueden llegar a ser demasiados y lo encuentro poco eficiente. En un caso por ejemplo conseguí todos los paraderos de una ruta, una sola, en un radio de 10km (que a mi parecer también es mucho), y obtuve cerca de 40 paraderos, de los cuales igual terminaría descartando casi todos (además, por el paradero analizado pasaban unas 12 rutas). 
Gracias de antemano.

**Comment by lily416** [comment]
@acpopper como se dice en las respuesta de la issue #830 
> Igual si descubriste una mejor forma puedes hacerla mientras no hagas uso de otras APIs ni librerias prohibidas ouo)

Saludos 👋🚗
