### ISSUE TITLE
Exactitud de api ipstack

### ISSUE THREAD

**Issue by pbyoma** [IIC2233/syllabus-2018-2#805]
Hola quisiera saber que tan exacta es esta ubicación que nos entrega, dado que la ejecuto y me arroja que estoy en el centro De Santiago siendo que estoy en las condes. Saludos

**Comment by danustilovsky** [comment]
Hola, creo que en el enunciado sale que se puede deber a que la busqueda se realiza por tu IP, y podria dar la del provedor y que por eso puede fallar.

**Comment by hbkim94** [comment]
A mi me sale que estoy en Chiguayante en la región del Bío Bío  T_T

**Comment by Kitaps** [comment]
Trabajamos con la del proveedor entonces? O tenemos que buscar una manera de conseguir nuestra ip?

**Comment by marcotroncoso** [comment]
tengo la misma duda, lo dejamos asi nomas?

**Comment by cristianhdez** [comment]
bump

**Comment by Arcoirisky** [comment]
Pueden dejarlo así y tratar de encontrar una forma que el transantiago los deje en una ubicación destino 
ó
señalar en el README y probandolo con el programa mismo que la API no los quiere y los exilia de esta hermosa región (?). Así el ayudante tendrá en cuenta que si su programa no funciona por esto es que estamos siendo enviados a otra parte del mundo ;--; 

Por mientras pueden usar coordenadas de prueba (ojalá fáciles de localizar y modificar) para que puedan probar su programa xD No se calienten tanto la cabeza con un problema de la API uwu <3
