### ISSUE TITLE
Flujo del programa

### ISSUE THREAD

**Issue by danustilovsky** [IIC2233/syllabus-2018-2#806]
Hola, si al momento de ingresar el usuario y la contraseña, en caso de que al validarlos estos no lo sean, se deben pedir nuevamente o se debe cerrar el programa.

En general, se deben manejar excepciones en los inputs o se puede asumir que seran ingresados correctamente?

gracias

**Comment by nachocontreras** [comment]
Hola!

De ser incorrectos se deben pedir nuevamente.
No, no se puede asumir que serán ingresados correctamente.

Saludos 😄
