### ISSUE TITLE
Descoordinacion de micros

### ISSUE THREAD

**Issue by AndresCalvo** [IIC2233/syllabus-2018-2#808]
Me pasa a veces que las micros que pasan por el paradero de destino y pasan por mi paradero más cercano no se encuentran activas, por lo que no tengo micros para mostrarle al usuario. ¿Debería manejar estas situaciones para encontrar otro paradero donde pasen micros que sí estén activas? ¿O simplemente lo dejo así, con un mensaje donde diga que no hay micros disponibles?

**Comment by nachocontreras** [comment]
Hola!

Trata de buscar paraderos más cercanos, pero si no hay o están muy lejos, muestra el mensaje.

Saludos :smile:
