### ISSUE TITLE
Limite requests Foursquare

### ISSUE THREAD

**Issue by joaquinhernandezg** [IIC2233/syllabus-2018-2#809]
Al hacer requests la api me devuelve esto:
{'meta': {'code': 429, 'errorType': 'quota_exceeded', 'errorDetail': 'Quota exceeded', 'requestId': '5bfeaa4e4c1f676746ca2bd7'}, 'response': {}}
Que debo hacer? :(

**Comment by naoliden** [comment]
La API de Foursquare permite hacer 
950 Regular Calls por día y 50 Premium Calls por día. Tal vez estas pidiendo parametros premium en tu llamada a la API y por eso esta contandolas como llamadas premium.

**Comment by Mahund** [comment]
A mi me dio: Max retries exceeded with url: etc...

**Comment by sacorsi** [comment]
A mi me paso eso, y me cree una nueva cuenta en foursquare, con otro mail y me funciona

**Comment by joaquinhernandezg** [comment]
Pucha, entonces los requests para pedir la información de un venue son considerados como premium? Como podemos obtener entonces la información de contacto, comentarios, y esas cosas para dar información relevante como sale en el enunciado?

**Comment by Arcoirisky** [comment]
Pueden seguir haciéndolo de la misma forma pero, sugiero que mientras prueben no lo hagan para que no les lancen errores por requests premiums D: 

Incluso podrían ser creativos y agregar una opción premium para que no sea necesario modificar tanto y así no gastarse el límite de requests solo probando el programa o:

Si se encuentran en esta situación agregenlo en el README para que tengamos cuidado con el límite owo)/

**Comment by acpopper** [comment]
A mi me sale lo mismo de Max retries with url...
Y lo raro es que esperé más de 24 horas, incluso me hice otra cuenta y aún me sigue tirando el error D:
Lo omitiré por ahora pero si alguien tiene una solución lo agradecería

**Comment by sacorsi** [comment]
A mi me pasaba lo mismo, y al final me di cuenta que estaba usando premmium calls y se me acababan al tiro. Ahora hice toda la tarea sin premium calls y no he vuelto a tener problemas.

Al usar un url como: "https://api.foursquare.com/v2/venues/id_lugar" estas usando una premmium call.

Yo ahora solo uso estas 2 url que son calls "normales".        
"https://api.foursquare.com/v2/venues/categories"
"https://api.foursquare.com/v2/venues/search"

Eso si, con las calls normales no puedes obtener comentarios, ni rating, ni "tips", ni nada de eso, solo puedes obtener datos como el nombre del lugar, las coordenadas, ubicacion y algo mas.
