### ISSUE TITLE
Datetime (uso y error de importación)

### ISSUE THREAD

**Issue by isiguelfand** [IIC2233/syllabus-2018-2#81]
Hola! No muy inteligentemente le puse a un archivo datetime.py para probar algo, y ahora no puedo usar date time. Obviamente traté cambiándole en nombre y borrándolo pero sigo teniendo el mismo problema. Traté de borrar el archivo .pyc  con `find . -name '*.pyc' -delete` pero no funcionó.

**Comment by fgbruna** [comment]
Hola @isiguelfand !
Podrías mostrarme que aparece si ejecutas `ls -a` en la terminal desde la carpeta donde creaste ese archivo?

**Comment by isiguelfand** [comment]
```
MacBook-Pro-de-Isidora-4:probar isidoraguelfand$ ls -a
.		.idea		db_users.csv	dt2.py		probar.csv
..		__pycache__	dt.py		probando.py
```

`dt2.py` es el archivo que antes se llamaba date time
En pycharm todavía me aparece run date time

**Comment by fringlesinthestreet** [comment]
Hola @isiguelfand 

Prueba abriendo el archivo que quieres ejecutar en PyCharm. Luego, haz click derecho en cualquier parte del código. Ahí se debiese ver la opción `run nombre_archivo.py`. Haz click en eso y avisa si continúa ocurriendo tu error.

![captura de pantalla 2018-08-17 a la s 20 10 26](https://user-images.githubusercontent.com/20802067/44292207-a9d68f00-a259-11e8-9358-962f51d599a2.png)

**Comment by isiguelfand** [comment]
Sí me sigue pasando, el problema es que todavía me parece la opción de run date time, entonces no lo puedo importar bien 
<img width="1023" alt="captura de pantalla 2018-08-17 a la s 20 53 42" src="https://user-images.githubusercontent.com/42189248/44293128-a7773380-a25f-11e8-9ecf-1b27aea169ae.png">

**Comment by fgbruna** [comment]
Prueba borrando la carpeta `__pycache__` cuéntanos cómo te va!

**Comment by rhanuch** [comment]
¡Hola @isiguelfand !

El problema que tienes no es que hayas destruido (o matado) al módulo `datetime` luego de haber cambiado el nombre del archivo (por suerte) :sweat_smile:, sino que estas haciendo mal el llamado de la variable en tu código:

```Python3
from datetime import datetime

a = datetime.datetime("2017-02-01", "%Y-%m-%d %H: %M:%S") 
```

Siendo que tu código debería ser algo como lo que sigue

```Python3
from datetime import datetime

a = datetime.strptime("2017-02-01", "%Y-%m-%d")
```

En resumen tus problemas radican en 3 cosas:

1. Al hacer el llamado `from datetime import datetime` estas diciéndole a Python que importe `datetime` del módulo `datetime`, es decir, al hacer lo original tu estarías haciendo el equivalente de `datetime.datetime.datetime("2017-02-01", "%Y-%m-%d %H: %M:%S")` :alarm_clock: 

2. Estas dándole un `string` a la función `datetime`, siendo que esta recibe `ints`, provocando un error, por lo que debes utilizar `strptime` como sale en la [documentación :scroll:](https://docs.python.org/3.6/library/datetime.html#strftime-and-strptime-behavior)

3. Estás diciéndole a `datetime` que le vas a entregar una hora, minutos y segundos explícitos, pero no se  encuentran dentro del string, provocando un error, por lo que debes o remover `%H: %M:%S` o agregarle la información declarada para tener un objeto del tipo `datetime` con la hora, minutos y segundos que quieras :clock1: 

En teoría, esto sumado a lo que dijo @fringlesinthestreet , debería solucionar tu problema.

¡Ánimo y suerte en la tarea! :four_leaf_clover: 

----

P.S.: Recuerda leer bien la documentación y buscar en Google cómo se utilizan los módulos de Python, ya que a mucha gente le ocurren cosas similares con las librerías :smiley:
