### ISSUE TITLE
Uso de APIs

### ISSUE THREAD

**Issue by Mahund** [IIC2233/syllabus-2018-2#810]
El enunciado menciona en punto 2.2 que al seleccionar un lugar para ir, se debe:

1. Buscar el paradero más cercano a este lugar
2. Buscar todos los microbuses que se detengan en este paradero
3. Buscar todos los paraderos de todos estos microbuses

Mi consulta es: 

Pese a que el enunciado menciona solamente a la API de Foursquare en estos puntos, ¿es legal utilizar la API de Transantiago para esto?

**Comment by Arcoirisky** [comment]
Es legal usar transantiago ouo)/ 

se salvo con tu semestre~ ✨
