### ISSUE TITLE
Consola o GUI

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#811]
Hola, 

para esta tarea la interacción del usuario con el programa puede ser a través de la consola o tiene que ser con una GUI de pyqt?

**Comment by fabarros** [comment]
tengo la misma duda

**Comment by Michelmagna** [comment]
En la issue de las librerías preguntaron si esque se podia usar PyQt5 y dijeron que si. Pero no es obligación por lo que se.

**Comment by Arcoirisky** [comment]
Consola ouo) Si quieren meterle interfaz están libres de hacerlo pero no hay nada extra más que más trabajo para ustedes y problemas si es que no funciona bien :(
