### ISSUE TITLE
Carácteres alfanuméricos en la contraseña

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#812]
¡Hola! 

Con carácteres alfanuméricos, ¿se refieren a que solo acepta `a-z`, `A-Z` y `0-9`, o puede incluir `_` y `-`también? 

¡De antemano muchas gracias!

**Comment by naoliden** [comment]
Letras y numeros normales

**Comment by hbkim94** [comment]
Gracias!
