### ISSUE TITLE
Aviso de utilidad

### ISSUE THREAD

**Issue by naoliden** [IIC2233/syllabus-2018-2#813]
Así se ve una consulta a la API de foursquare, entrega harta info pero para lo que se necesita sólo deben buscar en ['response']['venues'] tal como se muestra en la foto. Luego dejé ordenado a el diccionario que retorna la consulta para que vean con claridad cómo es y los datos que les pueden servir.

<img width="757" alt="screenshot 2018-11-28 at 13 05 16" src="https://user-images.githubusercontent.com/8712696/49164664-55d64e80-f30e-11e8-9225-169f7e201c1c.png">

Así es como se ve un solo venue, si hay más vendría otro diccionario como elemento dentro de esa lista.

**Comment by faandrade** [comment]
Hola!, cuando hago un request de la misma forma que en el ejemplo, si trato de imprimir 
data["response"]["venues"] me tira KeyError en venues. Es posible llegar a la lista de venues pero es un poco mas engorroso. Quería preguntar si efectivamente debería existir data["response"]["venues"] o simplemente era para ejemplificar la información que nos será util.
Muchas gracias!

**Comment by Arcoirisky** [comment]
Te sugiero llegar a la lista de "venues" por muy engorroso que sea. Contiene información que necesitas mostrar según enunciado :o

**Comment by faandrade** [comment]
Sii pero la pregunta iba por si yo tenia algun error al momento de hacer la request

**Comment by ariel-m-s** [comment]
@faandrade quizá no lo has cargado con ```JSON```?

**Comment by ncasassas** [comment]
Quizás es por que la llave "venues" existe solo cuando es más de un resultado ?
Lo menciono ya que en la documentación la llave es "venue" y se esta accediendo a un solo resultado. (aún no he comprobado el tema de si va o no con s cuando es más de un resultado pero puede ser por eso que te tire error).
Acá esta lo que menciono https://developer.foursquare.com/docs/api

**Comment by Cadagan** [comment]
@nko205 Cambia el final de tu url de "explore" a "search". 

"Y notaras la diferencia" :wink:
