### ISSUE TITLE
Lugar destino

### ISSUE THREAD

**Issue by Franco1605** [IIC2233/syllabus-2018-2#814]
Hola. Para obtener el lugar de destino, utilizo esta url :https://api.foursquare.com/v2/venues/search.
Luego, para poder hacer el get, me pide una latitud y una longitud.¿ Esta corresponde a la longitud y latitud del usuario ?, si es así, entonces solo con el radio podría variar el alcance de la búsqueda.
¿Estoy en lo correcto?

**Comment by Arcoirisky** [comment]
Para qué parte lo estás haciendo? Si es sobre flujo se a respondido antes en otra issue O:

**Comment by Franco1605** [comment]
He leído las otras issues y no he visto una respuesta a esta pregunta. O quizás no lo he entendido. Por ello, lo pregunté aparte :o

**Comment by Arcoirisky** [comment]
Quizás soy yo la que no entiende bien tu pregunta. Se supone que para buscar el lugar de destino el usuario debe de haber elegido uno en particular. La api que usas para eso ya te entrega long y lat para que busques el paradero a los 10km de distancia O:

**Comment by Franco1605** [comment]
M... mi pregunta va más por el siguiente lado: el usuario elige una categoría. Supongamos la categoría "Food". Luego, busco lugares que estén dentro de un radio determinado que cumplan con la categoría dicha anteriormente. Para buscar lugares con id's de categorías específicas, necesito una longitud y una latitud. Y yo supongo que se utiliza las coordenadas de la posición del usuario, no es así?
Por lo menos así me calza a mí, pues https://api.foursquare.com/v2/venues/search exige una latitud y una longitud... :o

**Comment by Benjadef** [comment]
[no soy ayudante] Yo tengo la misma duda, yo creo que no tendría mucho sentido usar la longitud y latitud del usuario a menos que se use un radio bien grande, sino que sentido tendría buscar solo lugares que estén muy cerca del usuario, para eso no usa el transantiago jaja, creo que seria razonable que el área de búsqueda sea por los lugares donde llega el transantiago, ósea santiago, y al parecer esta opción existe como parámetro, eso salu2

**Comment by BlancaMunizaga** [comment]
pero entonces de donde sacamos los parámetros longitud y latitud? se los pedimos al usuario?

**Comment by Arcoirisky** [comment]
Como dice @Benjadef no tiene sentido buscar lugares cerca del usuario porque sino el transantiago no tiene trabajo. Tampoco se le debe de pedir la latitud y longitud al usuario @BlancaMunizaga :( Yo al menos no conozco la latitud ni longitud de los lugares que quiero visitar ;--; 

Lo que deben de hacer es encontrar lugares **alrededor de santiago** que cumpla con las características o descripciones del usurario. El cómo hacerlo es parte de su trabajo :O Estoy segura que hay otra issue en la que se toca el mismo tema y llegaron a una idea de lo que podrían hacer. Hay otra que entrega el cómo hacer una consulta a la API para que te entregue la información de un lugar, entre esa información la ubicación con latitud y longitud.

Lo único que sabe el usuario es qué quiere buscar y que quiere llegar allá con el transantiago :O!!

**Comment by Franco1605** [comment]
Ok. ¡Muchas gracias !
