### ISSUE TITLE
Paraderos Validos

### ISSUE THREAD

**Issue by Mahund** [IIC2233/syllabus-2018-2#815]
Si más de 1 paradero (que permite tomar un microbus y llegar al destino) cumple en estar a menos de 10km del usuario, debo entregar los tiempos de cada paradero o solo del primero.

Esto ya que al solo validar todos los paraderos de las rutas validas mi programa tarda mas de 1 minuto.

**Comment by Arcoirisky** [comment]
Se supone que debes usar el más cercano dentro de un radio de 10km No podría existir más de un paradero 🤔 al menos no con una alta probabilidad xD

**Comment by Mahund** [comment]
@Arcoirisky a mi me aparecen bastantes, no se si se deba a la logica de mi programa.

1) Al seleccionar un lugar obtengo el paradero más cercano.
2) Con el paradero obtengo las rutas que llegan a él
3) Con las rutas veo todos los paraderos desde los cuales llego al del lugar elegido en mi paso 1.
4) Y de los paraderos del paso 3 bastantes calzan con la parte final (cercania de 10km a mi posicion).

Otro problema es que si quisiera buscar el mas cercano, la demora de ejecucion es de más de 5min.

Podria simplemente asumir que el primer paradero que cumpla con los requisitos baste?

**Comment by Arcoirisky** [comment]
Buscas el más cercano entre los resultados de los 10km te tarda 5minutos? 

No puedes asumir que el primer paradero cumple con los requisitos porque puede ser uno que este justo a los 10km y eso no es nada cercano :( 

Revisa bien cómo estás haciendo la filtración. En cómo guardas todos estos paraderos y luego cómo buscas sobre estos el más cercano. Hay varias formas en las que se me ocurre cómo puedes disminuir ese tiempo pero no puedo decírtelas por claras razones :((
