### ISSUE TITLE
Problema con los recorridos (La F24 esta en todo santiago)

### ISSUE THREAD

**Issue by rodrigofelipe11** [IIC2233/syllabus-2018-2#816]
Al buscar los recorridos de cada paradero todos me devuelven la F24, pasa por todos los paraderos de santiago. 
```
buscar_paradero(stop_code):
    url=f"https://api.scltrans.it/v2/stops/{stop_code}/next_arrivals"
    resp=requests.get(url=url)
    data=resp.json()
    print(data)
```

al usar esta funcion con cualquier codigo de paradero (llamados "stop_code") me retorna que la F24  

tambien intente usar como url : f"https://api.scltrans.it/v3/stops/{stop_code}/stop_routes" y tambien me devuelve la F24

**Comment by lily416** [comment]
Estuve probando y con estos paraderos (PD112, PG996 y PI38) no me retorna la F24 🤔 ¿Puedes probarlo y decirme si te la retorna o no?

Saludos 👋🚌

**Comment by rodrigofelipe11** [comment]
El error estaba en funciones anteriores, que tenia mal puesta la latitud y longitud,  😂😂😂
