### ISSUE TITLE
Duda uso apropiado regex

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#817]
Se considera mala práctica ir intercalando funciones de match de regex y funciones de string de python?
Por ejemplo, hacer un:

If re.match(algo, palabra):
...**una funcion que modifica la palabra**
...if re.match(algo, palabramodificada):
......**otrafuncion**

O la idea es hacer todo el filtrado de regex en una sola funcion match? Gracias! 🌵

**Comment by FernandoPieressa** [comment]
Hola! No es mala practica, por lo que no hay problema en separarlos.

Saludos!

**Comment by csolguin** [comment]
Considerando que las funciones de string son validas, entonces es legal algo como:
```
def funcion(email):
    if email.count('@') == 1:
            pattern = "expresion_regex"
            return bool(re.fullmatch(pattern, email))
    else:
        return False 
```

Saludos!
