### ISSUE TITLE
Búsqueda de venues/establecimientos

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#818]
¡Hola!

¿Sería suficiente que el usuario pueda buscar los venues por todas las categorías y subcategorías? En mi programa, los usuarios pueden ir buscando/actualizando la lista de establecimientos en tiempo real según dichos parámetros a través de una GUI.

¿O es necesario también implementar la búsqueda por query (ie. que escriban la palabra "bar" y aparezcan todos los lugares que tengan la palabra "bar")?

Y otra pregunta, ¿cuál es el radio de búsqueda de establecimientos? ¿Los mismos 10km del radio de búsqueda de paraderos?

¡Muchas gracias!

**Comment by Arcoirisky** [comment]
1) Necesitas implementar la búsqueda por query como la llamas. Porque también hay que buscar según la descripción o:
2) La idea es que los establecimientos puedan estar más lejos que los 10km. Pero mientras sea un radio considerable estaría bien :D recuerda que la idea era buscar por todo santiago ouo)

Aunque, ya teniendo el establecimiento seleccionado por categoría o descripción, basta con que llegue a este destino o:

**Comment by hbkim94** [comment]
Gracias, te pasaste.
