### ISSUE TITLE
Busqueda Categoria query/categoryId

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/syllabus-2018-2#819]
En relacion a buscar por categoria, hay dos maneras de hacerlo a mi parecer:
con 'https://api.foursquare.com/v2/venues/search'

-usar el parametro query
-usar el parametro categoryId
Se puede usar el primero? o debemos hacer el segundo obligatoriamente?

**Comment by NickCastillo** [comment]
Misma pregunta, si cree una lista con las palabras de "shortTerm", "pluralTerm" y "name" dentro de la llave de category (por ejemplo Pizza Place y Pizza Places) de los lugares y luego compare esta lista con la(s) categoria(s) seleccionada(s) por el usuario, estaría bien? o buscan que trabajemos con los parámetro query y categoryId?

**Comment by bmorrisc** [comment]
@alexaptib según lo que entendí, query es para buscar por palabras claves que pueden estar en el nombre del lugar que buscas, no por nombre de categoría. En ese caso, creo que lo más correcto sería usar categoryId
Aquí salen los parámetros explicados https://developer.foursquare.com/docs/api/venues/search
(no soy ayudante)

**Comment by alexaptib** [comment]
@bmorrisc gracias por la respuesta, si, eso es lo que entiendo por querry, pero no veo una manera muy directa de obtener los ids con una 'palabra de busqueda' y en varios casos, los nombres si estan relacionados con la categoria. Entiendo que no es lo optimo pero quiero saber si es suficiente para la tarea :/

**Comment by bmorrisc** [comment]
@alexaptib revisa https://developer.foursquare.com/docs/api/venues/categories
Básicamente haces una request especificando los parámetros básicos (url, client_id, client_secret, v) y te entrega todas la categorías posibles con sus id
Espero que eso te sirva :)

**Comment by lucasvsj** [comment]
@bmorrisc  no te pasa que al hacer [variable].json() o json.loads([variable]) de tu respuesta, sale un error tipo UnicodeEncodeError: 'charmap' codec can't encode - character maps to <undefined>?

**Comment by bmorrisc** [comment]
@lucasvsj  no tengo problemas para usar json... Usaste lo de la issue #813 ? En vez de buscar en  ['response']['venues'] tienes que buscar en  ['response']['categories']

**Comment by lucasvsj** [comment]
@bmorrisc  yo me referia al usar este https://developer.foursquare.com/docs/api/venues/categories

**Comment by Arcoirisky** [comment]
@alexaptib  
Pueden usar ambos parámetros. Mientras les den los resultados esperados estará bien (Te había contestado lo mismo en la otra issue dónde preguntaste lo mismo :'C)

y gracias @bmorrisc por ayudarnos <3 sos grande y lo que dices está perfecto ouo)/
