### ISSUE TITLE
Docstrings en funciones pequeñas

### ISSUE THREAD

**Issue by viantirreau** [IIC2233/syllabus-2018-2#82]
Hola!
¿Hasta qué punto es necesario comentar/documentar el código?
En general comento todas las clases y funciones más grandes o complejas, pero ¿es necesario hacerlo para todas?
En la misma línea, ¿existe algún requisito particular del curso para los docstrings? Normalmente, intento describir la función/clase, con qué estructuras trabaja y qué retorna, pero para las más chicas o simples terminaría siendo más documentación que función 😆 

Saludos!

**Comment by cilopez** [comment]
Hola @viantirreau, documentar es una muy buena práctica y es genial que la estes aplicando desde la Tarea 0, respondiendo a tus preguntas:
- Hasta que te parezca prudente, en particular si es un código que volveras a utilizar mucho ojalá documentar la mayoría de las cosas, si es un código más fugaz, intenta documentar sólo lo complejo.  Como es una tarea yo opino que solo documentes lo complejo.
- Más adelante en el curso les pediremos documentar cierto % de funciones, pero no determinamos requisitos de largo.

**Comment by viantirreau** [comment]
Perfecto, muchas gracias!
