### ISSUE TITLE
Encoding del .json() en utf-8

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#820]
Hola 

cuando hago un get de requests y luego hago .json() me entrega un diccionario de la respuesta.
El problema es que hay caracteres que no se expresan bien. 
Pero reviso el encoding de la request y me dice q es utf-8.
Como puedo hacer que cuando haga el .json() el encoding sea en utf-8 ?

gracias

**Comment by Arcoirisky** [comment]
por qué no intentas lo de este [link](https://stackoverflow.com/questions/18337407/saving-utf-8-texts-in-json-dumps-as-utf8-not-as-u-escape-sequence) pero cargando jsons?

**Comment by Kitaps** [comment]
Ya, es decir igual hay q hacer el dumps. Igual raro que no haya una manera de hacerlo directo pero bueno. Gracias !! :D
