### ISSUE TITLE
IP para ipstack

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/syllabus-2018-2#822]
Hola!
Para hacer requests usando ipstack hay que conocer nuestra ip. Mi pregunta es, puedo asumir que el corrector va a saber su ip y ponerla o tengo que buscar alguna forma de automatizar esto?
De antemano gracias!

**Comment by Kitaps** [comment]
Si pones /check en vez de /{IP_QUE_QUIERAS_METER} lo hace automatico con la Ip de la maquina. (creo)

**Comment by bmorrisc** [comment]
uuh gracias! lo había intentado antes pero no sé por qué no me funcionó jajaj

**Comment by Arcoirisky** [comment]
He llegado 7 horas tarde ;--;
Pero al menos lo solucionaste! Gracias @Kitaps por la ayuda :D
