### ISSUE TITLE
búsqueda por categoria/descripción

### ISSUE THREAD

**Issue by Benjadef** [IIC2233/syllabus-2018-2#823]
En la búsqueda por categoría estoy implementando que de despliegue una lista con las categorías posibles y que le usuario elija la que quiera, el problema es que foursquare me entrega las categorías en ingles, no hay problema con eso ?
respecto a la descripción, no me queda muy claro como sería esta búsqueda, el usuario podría ingresar, calles, nombres. Podrían aclarar más respecto a este punto pls, gracias !

**Comment by Arcoirisky** [comment]
No hay problema con el idioma uwu)/ mientras el usuario pueda buscar estará bien. Señala lo que pasa en el README.

Sobre la descripción, pueden ser palabras claves que describan lo que desea el usuario O:! coffe, hamburguesa, piscina, lo que sea válido O:

**Comment by Benjadef** [comment]
oka muchas gracias  !

**Comment by Faalfaro** [comment]
¿Es necesario poner una lista con las categorías? también pensé en ponerla pero queda muy largo en la consola si lo hago. ¿Es suficiente que el usuario tenga que solo ingresar y se devuelva un mensaje si es que no esta lo que ingreso o tengo que desplegar la lista no importa como se vea?

**Comment by Arcoirisky** [comment]
No es necesario poner una lista de categorías. Es suficiente con lo que dices @Faalfaro

**Comment by castrillini** [comment]
El enunciado dice claramente, en el paso 2 del punto 2.2. Flujo de la información:
"...Para esto, se debe permitir al usuario buscar por categorías o descripción y que luego..."
Lo que uno entiende es que se debe usar una de dos (por categoría, descripción, o incluso ambas) pero no es obligatorio usar las dos. Yo lo que estoy haciendo es desplegar una lista con las categorias (obviamente de forma entendible y ordenada) para que el usuario vaya marcando cuáles desee. Luego realizar la búsqueda.
@Arcoirisky Esto debiera estar correcto, cierto? ✌️

**Comment by Arcoirisky** [comment]
Te faltaría la búsqueda por descripción y eso no te dará todo el puntaje. Lo de las categorías está bien pero incompleto :0

La “o” del enunciado es un “o” inclusivo uwu)

**Comment by Cadagan** [comment]
Para la descripcion, tambien tenemos que desplegar una lista de opciones? o podemos dejar que el usuario ingrese lo que quiera y que se busque segun lo que ingreso?

**Comment by Arcoirisky** [comment]
Siempre a sido cosa del usuario lo que ingresa. La opción de búsqueda es distinta o: (categoría o descripción)
