### ISSUE TITLE
Buses paradero

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#825]
Hola, 

en el enunciado se dice que necesitamos sacar todas las micros de un paradero. 
Entonces mi duda es: Todos todos o todos los "next arrivals"

La otra duda es: Queremos los buses o los recorridos? Porque segun mi los recorrido son lo que importa, más que los buses.

**Comment by alexaptib** [comment]
@Kitaps sumandome al issue, a mi parecer lo mas logico es que se vea los 'next arrivals' ya que es lo mas practico para ver el recorrido mas eficiente que debe tomar el usuario. Seria correcto hacerlo asi?

**Comment by BenjaCastillo** [comment]
Una pregunta, ustedes están recibiendo algo del next arrivals?, es que yo he puesto varios paraderos y siempre me entrega una respuesta vacía

**Comment by danustilovsky** [comment]
Segun yo se podria ocupar next arrivals, pero sale en la documentacion que el webservice no es estable, por lo tanto de ocupar eso se esta obligado a manejar ciertos timeouts. Ademas, en todo caso seria importante saber los next arrivals de las micros en el paradero de salida de la persona, por lo que segun yo hay que ocupar los recorridos simplemente.

**Comment by Arcoirisky** [comment]
Holaaaa~
Mientras puedan obtener la información del tiempo de llegada de cierta micro, la duración estimada del viaje y la distancia entre le partida y la llegada al punto de destino pueden usar la opción que más les acomode ouo)

**Comment by Kitaps** [comment]
@alexaptib el problema que veo con el next arrivals es que solo te muestra las micros que están proximas a llegar. Y si por ejemplo es un paradero donde inicia un recorrido no te va a lanzar resultado excepto cuando la micro está justo en el paradero (lo se xq uso una app que hace eso). 
Para que lo tengas en consideración.
