### ISSUE TITLE
Uso de r" Regex 

### ISSUE THREAD

**Issue by isavega** [IIC2233/syllabus-2018-2#826]
Hola!
Hay alguna diferencia entre usar re.sub(r'mi expresión regular') con re.sub('mi expresión regular')? En stackoverflow leí que la 'r' cambia el '\' por '/' y no sé si esto afecta mi expresion regular. O es lo mismo?

Muchas gracias 😄

**Comment by Arcoirisky** [comment]
¿Por qué no miras la documentación en este [link](https://docs.python.org/2/library/re.html)? Por lo que entendí es para poder identificar los "/" como parte de la cadena de strings que intentas revisar O:!
