### ISSUE TITLE
Limite de results

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/syllabus-2018-2#827]
al momento de hacer un request de paraderos en radio de 10km, puede ocurrir que el limite sea mayor a 100 (el limite por default). debemos incrementar el limite para este caso? Hice eso y me entrega un error de 'Endpoint request timed out' asumo que porque hay demasiados resultados. Que se debe hacer?

**Comment by Arcoirisky** [comment]
puedes dejarlo con ese límite o el por default. Recuerda que necesitamos el más cercano y seguro que en 10km deben de contener cientos de paraderos D:!

**Comment by alexaptib** [comment]
@Arcoirisky gracia de por la respuesta, pero que pasa si se toma el límite default de 100, y el mas cercano no parece en los 100? O necesariamente el límite entrega los más cercanos?

**Comment by Arcoirisky** [comment]
Ojalá la API pudiera encontrar los más cercanos, te mentiría si te respondo un Sí o un No pero, puedes asumir entre estas respuestas que encontrarás uno entre estos que sea el más cercano al usuario. Al menos cumplirá con estar a menos de 10km :D Y eso es mejor que nada ;--;

Ya si la consulta no entrega ningún resultado como para señalar un paradero, puedes mostrar un mensaje que no se encontró nada a menos de 10km de esta pobre persona que tendrá que buscar otra forma de entretenerse ;-;

**Comment by BFFV** [comment]
Tengo una duda, al momento de usar la API con la latitud y longitud del usuario ésta entrega los paraderos comenzando desde los que están cerca, pero al incluir el radio de 10 km como parámetro, extrañamente deja de hacer esto y muestra otros paraderos al comienzo que están mucho más lejos que  los originales (cuando no se especificó el radio). ¿En este caso no convendrá más no utilizar el radio, y si en caso de que el paradero más cercano esté a más de 10 km, entonces se le indica que no hay rutas posibles?

**Comment by Arcoirisky** [comment]
El requisito de un paradero es que sea el más cercano a un punto y que esa distancia sea menor a 10km :eyes:

Ya si el más cercano está sobre los 10km sip, indicas que no existe ruta que le lleve a su destino :’(

**Comment by BFFV** [comment]
Y si entre los 100 paraderos cercanos al usuario ninguno sirve para llegar al destino (aunque ni siquiera esté tan lejos) entonces también le decimos que no se pudo encontrar ruta al paradero de destino? (Lo digo porque con un destino me ocurrió que no había ningún paradero entre los 100 más cercanos al usuario que tuviera la ruta del destino, y si aumento ese límite de 100 resultados se vuelve muy lento ya que debe consultar a la API por cada uno para obtener sus rutas)

**Comment by Arcoirisky** [comment]
Sip. No somos los mejores en recomendar rutas pero al menos buscamos que sea la más cómoda (?) xDD
