### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by cristianhdez** [IIC2233/syllabus-2018-2#828]
Con respecto al formato  PEP8, que sucede si hay urls con más de 80 caracteres? se puede tomar como excepción al formato?

Saludos

**Comment by cristianoberpaur** [comment]
Si estas usando pycharm, si apretas enter en medio del string antes de llegar a los 80 caracteres, te continuará el string en la siguiente linea. (manteniendote dentro del pep8 y queda más ordenado) Asumo que con otros editores de texto es igual ? pd: no soy ayudante

**Comment by ncasassas** [comment]
Tengo la misma duda, estoy usando Atom y en internet solo he encontrado respuestas del tipo: "no rompas la url" por el momento.
Intente hacer lo que usualmente hago que es usar triple comilla al inicio y al final del string pero no funciona al usar el metodo .get 
Saludos!

**Comment by Arcoirisky** [comment]
Encontré respuestas creativas para los que tienen ese problema en este [link](https://stackoverflow.com/questions/18685184/pep8-e501-line-too-long-error)

**Comment by ncasassas** [comment]
Ahí funcionó muchas gracias !
