### ISSUE TITLE
Nombres cortos categorías

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/syllabus-2018-2#829]
Hola!
Si no me equivoco hay categorías que tienen el mismo nombre corto. En caso de que el usuario quiera buscar por nombre corto, debería agregar a la búsqueda por categorías todas las que tengan el mismo nombre corto? Está bien que hayan categorías con el mismo nombre corto o estoy haciendo algo mal? :(

**Comment by Arcoirisky** [comment]
Quizás el error de gestión fue por parte de quienes permitieron estos nombres cortos >:O!
¿haz visto la información que entregan estas categorías? si son exactamente las mismas mejor filtrarlas y mostrar una sola. Caso contrario podrías señalar con un comentario o similar que en el fondo son diferentes.

**Comment by bmorrisc** [comment]
Al parecer hay subcategorías que repiten nombres cortos. Me pasa por ejemplo que Travel Lounge y Airport Lounge tienen de nombre corto Lounge. Hasta ahora estaba considerando ambas categorías en caso de que el usuario ingresara un nombre corto que se repita, es decir, hago el request de venues con todos los id de categorías que coincidan. Está bien que lo deje así o tengo que hacer algo más?

**Comment by Arcoirisky** [comment]
Aaah, está bien así. Eso es cosa de la búsqueda del usurario :D
