### ISSUE TITLE
Búsqueda posición paraderos

### ISSUE THREAD

**Issue by cristianoberpaur** [IIC2233/syllabus-2018-2#830]
En el punto 7 de la sección 2.2 del enunciado, una vez obtenidos los paraderos de cada recorrido, se debe obtener la ubicación de cada uno de estos. Pero dada la cantidad de paraderos, el tiempo hasta que se realicen todas las consultas es muy largo. Encontre otra forma de calcular el paradero más cercano que es de utilidad para el usuario. Esta mucho más rápida que preguntar la ubicación de cada paradero de todas las rutas. Mi pregunta es, ¿es válido hacerlo de otra manera o se debe seguir el enunciado al pie de la letra ?

**Comment by fjlopez7** [comment]
Ve la issue #804

**Comment by cristianoberpaur** [comment]
Gracias, busque si habia alguna issue similar, pero no la pille.

**Comment by Arcoirisky** [comment]
¿Te quedó clara la respuesta? o:
Igual si descubriste una mejor forma puedes hacerla mientras no hagas uso de otras APIs ni librerias prohibidas ouo)

**Comment by cristianoberpaur** [comment]
Si quedo claro con la issue 804, gracias 👍 .
