### ISSUE TITLE
Uso de stops/{ . . . } /next_arrivals

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#832]
El principal uso de esta búsqueda ***v2/stops/PB8/next_arrivals*** es encontrar los tiempos de viajes entre los paraderos, por lo que seria valido ocupar [/v2/routes/102/directions](http://scltrans.it/#/api?id=direcciones-detalles-recorrido) (Ejemplo del uso de esta api) en donde unos de los parámetros que devuelve es el tiempo que se demora en llegar al paradero en el formato hora-minuto-segundo (más facil de manejar al pasar a datetime), mientras que el otro solo da una aproximación de este tiempo de arribo.
Entonces es válido ocupar cualquiera de los dos, al cumplir la misma función?

**Comment by Arcoirisky** [comment]
Voy a preguntar pero en principio es válido. Cualquier cambio te comento aquí´mismo o: 

Aunque por lo que dices el primero te da el tiempo de viaje entre dos paraderos mientras el segundo solo el de arribo a uno en particular. Pero si crees que te sería más útil. Dale ouo)
