### ISSUE TITLE
Envío de credenciales a github

### ISSUE THREAD

**Issue by cmescobar** [IIC2233/syllabus-2018-2#833]
Dado que en la tarea hay plataformas que entregan credenciales de usuario, ¿es necesario subirlas para la corrección de la tarea?, ¿o utilizarán credenciales distintas y verán el funcionamiento del programa al igual que en la actividad 14?

Saludos!

**Comment by lily416** [comment]
No deben subir las credenciales. Pero idealmente señala en el readme el archivo donde deben ponerse y el nombre de las variables, para así hacer más fácil la corrección.

Saludos 👋🚐
