### ISSUE TITLE
Radio de busqueda para destino

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/syllabus-2018-2#834]
Lei varias veces el enunciado, pero sigo con una duda. Que 'll' se le debe entregar a foursquare para buscar destinos en santiago? ademas que radio? ya que asumo que puede ir a donde quisiera en santiago, pero no el mundo no?

De hacer una issue que no corresponda a lo anterior, simplemente se cerrará y se hará referencia a lo establecido en otras issues o en el feedback.

Si consideras que las preguntas no aplican a tu duda, entonces borra lo todo esto y haz la issue. De no borrarlo debes repetir: "no se leer las instrucciones, no borré las instrucciones y estoy haciendo preguntas ya resueltas 🙃🐥"

**Comment by Arcoirisky** [comment]
Ya revisaste entre las otras issues? Hay varias dónde se hace referencia al tema. ¿Por qué no les echas un vistazo?

**Comment by alexaptib** [comment]
@Arcoirisky revisaré nuevamamente, gracias :)
