### ISSUE TITLE
Correr una sola vez o hasta cerra el programa

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#835]
Hola, 

tenía una duda respecto a que si es suficiente con que el programa, una vez que entregó lo que se le pide termine de ejecutarse o tiene que volver al menú principal y dar la posibilidad de hacer otra consulta hasta que se elija la opción salir ?

**Comment by Arcoirisky** [comment]
Es preferible lo último. Facilita la corrección muchísimo o:
