### ISSUE TITLE
Comparación entre paraderos posibles

### ISSUE THREAD

**Issue by ncasassas** [IIC2233/syllabus-2018-2#836]
Hola, tengo una duda respecto a la elección de paradero del usuario. Debo considerar las distancias de por ejemplo los 3 paraderos más cercanos al lugar que se quiera ir y lo mismo para el usuario? Me refiero exactamente a que por ejemplo si encuentro un paradero que esta al lado de donde quiero ir pero las micros que pasan por ahí quedan en el paradero a 9km del usuario v/s un paradero que puede estar a 1km del lugar y a 2 km del usuario.

**Comment by Arcoirisky** [comment]
Prefiere la segunda opción. Recuerda que los paraderos deben intentar ser lo más cercanos posibles al usuario y al lugar.

Ya si solo hay una micro que te sirva de entre todas las posibilidades y se da que el usuario debe caminar 9km pero está al lado del destino. Dale a ese camino. No hay otra opción xD Pero intenta siempre ir por la mejor opción.
