### ISSUE TITLE
Problemas con Git

### ISSUE THREAD

**Issue by isavega** [IIC2233/syllabus-2018-2#837]
Hola, como siempre, quería subir un respaldo de mi tarea pero me sale el siguiente error.

![image](https://user-images.githubusercontent.com/42187168/49317989-84eaec80-f4d5-11e8-8c68-969def3a2ec3.png)

Espero puedan ayudarme (antes del domingo...) Jajajajajaj Muchas gracias! :

**Comment by ncasassas** [comment]
Hola, no soy ayudante pero cuando me ocurre eso a mi (que es siempre que subo algo desde la página y no desde la consola), lo que hago es crear de nuevo el repositorio en mi pc, ojo con guardar todo lo que no haz subido antes en otra carpeta por si borras tu repositorio anterior.

**Comment by Arcoirisky** [comment]
Esta bloqueado por ese index.lock seguramente por un commit sin pushear de antes o por como dice @nko205, por modificar en la página en vez de la consola. 

Sugiero hacer lo que dice tu compañero xD pero cuando me pasaba a mi, habilitaba los archivos ocultos y eliminaba el que me bloqueaba todo. Por suerte nada malo me pasaba pero mejor prevenir que lamentar xD

**Comment by isavega** [comment]
Copie de nuevo mi repositorio y todo bien! Gracias a ambos 😄
