### ISSUE TITLE
ubicacion por ip

### ISSUE THREAD

**Issue by acpopper** [IIC2233/syllabus-2018-2#838]
Hola, me pasa que al usar ipstack me tira la latitud y longitud de las que supongo son las oficinas de VTR en santiago centro. Probé con varios ip de amigos que tienen VTR y tira la misma ubicación en cada caso. Hay manera de resolver esto para obtener unas coordenadas por lo menos más cercanas a uno? O me quedo usando las coordenadas que me da ipstack?
Saludos de antemano.

**Comment by Arcoirisky** [comment]
Ya hay una issue donde se trata el tema o: ¿por qué no les echas un vistazo?
