### ISSUE TITLE
Límite de Places

### ISSUE THREAD

**Issue by fabarros** [IIC2233/syllabus-2018-2#839]
Hola, cuando un usuario hace una consulta con su determinada categoría y descripción le pueden aparecer muchos resultados. Mi pregunta es, le muestro todos ellos al usuario? o sólo... no sé... 10?
**EDIT:** Puse la coordenada del metro Franklin porque está más o menos en el centro geográfico de Santiago y un radio suficiente. Sin embargo, me tira sólo 50 resultados a pesar de que le pongo 100 de límite, eso está bien? no son muy pocos? onda, hay solo 50 lugares de Santiago registrados en FourSquare?

**Comment by Arcoirisky** [comment]
Agranda el radio de la búsqueda y mira si te sigue lanzando los 50 resultados aún cuando tienes el límite 100. No creo que eso sea normal.

Ojalá puedas mostrar los resultados lo mejor que puedas. Igual mostrar solo 10 fijos pierdes muchas otras opciones, pero si lo modelas como "hojas de resultados" o algo parecido para no perder los otros resultados.

**Comment by adpolanco** [comment]
Es porque en la descripción del parámetro limit de la documentación de Foursquare sale "Number of results to return, up to 50.". Asique no creo que sea posible que salgan más resultados que esos.

**Comment by fabarros** [comment]
@Arcoirisky Agrandé el radio y me siguen saliendo 50 resultados, debe ser lo que dijo @adpolanco, Gracias!
@adpolanco Entiendo, eso era entonces. Gracias!
