### ISSUE TITLE
Creación Evento/Correo, cliente se equivoca

### ISSUE THREAD

**Issue by Gorgola22** [IIC2233/syllabus-2018-2#84]
Hola!

Tengo una duda: ¿debo dar la opción de volver atrás cuando se esté creando un correo, es decir, quiero escribir otra dirección más cuando se está escribiendo el cuerpo, o lo puedo hacer normal (creación lineal y si se equivoca, descartarlo todo)?

Gracias!

**Comment by cilopez** [comment]
Como no sale explicito en el enunciado, puedes hacerlo como te acomode. Obviamente hay una solución que requiere más tiempo, pero sería más real, depende de ti.

**Comment by Gorgola22** [comment]
¡Ok, gracias!
