### ISSUE TITLE
Optimizacion busqueda paradero mas cercano al cliente

### ISSUE THREAD

**Issue by danustilovsky** [IIC2233/syllabus-2018-2#840]
Hola, al buscar el paradero que se encuentra mas cercano al usuario, ocurre que el hecho de tener que calcular la distancias de todos los paraderos de todos los recorridos toma mucho tiempo sobre todo cuando el paradero de destino contiene a muchos recorridos. Dado lo anterior se podria asumir que el primer paradero que cumpla con los 10 km de radio es el que se utilizara? o hay alguna manera de ordenar los resultados de la API por distancia?

muchas gracias

**Comment by ncasassas** [comment]
Aprovechando esta issue, existe algún tiempo límite razonable a la hora de querer realizar la búsqueda ? sobre todo la consultada acá, al menos como lo estoy haciendo se demora bastante en encontrar primero todos los paraderos de los recorridos que sirven y sus respectivas ubicaciones ya que consulto a la api al menos dos veces por recorrido ( para saber si es inbound o otbound y luego por cada paradero consulto nuevamente por su información en cuanto a ubicación.

**Comment by Arcoirisky** [comment]
Hay una issue donde se dieron cuenta de una particularidad a la hora de buscar paraderos. Quizás les ayude a reducir el tiempo.

@nko205 define límite de tiempo razonable :eyes:

**Comment by ncasassas** [comment]
@Arcoirisky tardo alrededor de 4-5 minutos en: encontrar todos los paraderos para todos mis recorridos cercanos a donde quiero llegar y elegir el más cercano que me sirva.
Ese tiempo es en todo caso en el "peor" de los casos ya que estoy probando con direcciones cerca de donde vivo y paraderos que conozco (como llegada) y coinciden todos los recorridos para paradero de llegada y de inicio. Si pruebo otras distancias se reduce el tiempo y se encuentra lo pedido.

**Comment by Faalfaro** [comment]
Hola, tengo un problema con la API transantiago en relación a esto. Según la documentación, cuando se aplica el filtro 'center_lat' y 'center_lon' en listar paraderos, esta request devuelve los paraderos ordenados según distancia, lo cual quizá no es extremadamente exacto pero entrega un orden. El problema es que cuando busco los paraderos cercanos al usuario y aplico el filtro 'radius' para revisar solo los que estén a 10 km, esto causa que se pierda el orden de la lista que entrega. ¿Hay alguna solución para esto o tendré que utilizar sin el filtro de radio y al revisar si el paradero me sirve también tendré que revisar si esta dentro de los 10 km de radio?

**Comment by ncasassas** [comment]
Hola, según pude probar con el parametro radius se pierde lo de los más cercanos. Yo lo hice como indicas al final.

**Comment by fabarros** [comment]
@Faalfaro _[No soy Ayudante]_ Según enunciado, no es necesario que busquemos en un radio el paradero que está cerca del lugar al que queremos ir, la búsqueda en el radio de 10km no es en la API de Transantiago, sólo se hace para comprobar que el paradero está "suficientemente cerca" de nuestra ubicación actual (casi al final del flujo del programa).
En ese sentido, no veo por qué habría problema en buscar **sin radio** un paradero cercano al lugar donde queremos ir, de manera de obtener los datos ordenados desde la API de Transantiago.
Saludos.

**Comment by Faalfaro** [comment]
@fabarros los paraderos que yo quería buscar era con respecto al usuario para ver si podía realizar el flujo del programa de forma inversa, esto ultimo por que al hacerlo de la forma que dice el enunciado el programa se demora mucho.
