### ISSUE TITLE
Duda búsqueda por descripción

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#841]
Hola! Al momento de buscar por descripción, podemos permitir que el usuario ingrese múltiples parametros? (Ej: "comida, completos, barato") Si es así, los resultados deben ser los que cumplan TODOS estos filtros, o basta con que cumplan por lo menos 1 de ellos?

Saludines!

**Comment by Arcoirisky** [comment]
Eres libre de decidir cómo hacerlo :D Recuerda agregarlo al Readme
