### ISSUE TITLE
Duración estimada 

### ISSUE THREAD

**Issue by JavierNarvaez** [IIC2233/syllabus-2018-2#842]
Para el último punto del flujo de información, calcular cuánto tiempo le falta a la micro es fácil (lo provee la API), calcular la distancia es directo tomando en cuenta las coordenadas de cada paradero, pero la duración estimada requiere cálculos no tan sencillos. ¿Podemos hacer los supuestos que queramos para esto? 

Gracias de antemano

**Comment by Arcoirisky** [comment]
¿supuestos como cuales? o:

**Comment by alexaptib** [comment]
@Arcoirisky @JavierNarvaez Me parece que se refiere a supuestos como velocidad promedio de la micro, para calcular junto con la distancia el tiempo. Eso es valido?

**Comment by Arcoirisky** [comment]
Estoy segura que la API del transantiago da la información que necesita o: (la del tiempo entre paraderos) 🤔

**Comment by JavierNarvaez** [comment]
@Arcoirisky Es verdad, después de hacer la issue encontré eso

**Comment by bmorrisc** [comment]
@JavierNarvaez cómo obtuviste esa información? He buscado mucho rato y no la encuentro :(

**Comment by JavierNarvaez** [comment]
@bmorrisc https://api.scltrans.it/v2/routes/411/directions, te tira hartos datos
