### ISSUE TITLE
búsqueda más de una categoría

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#843]
Al hacer la request con dos categorías usando ***categoryId*** , siendo estas dos superiores en el árbol de categorías, por ejemplo ocupe la de artes y cultura, con la de comida, pero solo se obtiene la búsqueda de una de las categoría superior. Por lo que, ¿seria valido enviar varias request por cada categoría por separado (no es lo más optimo), de esta forma nos aseguramos que tenemos la información de cada categoría?

pd: Si comprobé que con la forma que ingreso las id's en categoryId funciona con más de un categoría pero estas eran subcategorias del mismo nivel.

**Comment by Faalfaro** [comment]
¿Es necesario hacer esto? la verdad es que yo lo tengo para que filtre con una sola categoría y que se pueda filtrar al mismo tiempo por descripción y categoría, pero eso seria todo. ¿Se evalúa que se pueda con mas o esta bien así? y para cualquier caso ¿Cuantos resultados se deben mostrar al filtrar?, ya que no logro subir la cantidad de resultados de 50 al cambiar el parámetro 'limite' y ,ya que estoy buscando en todo santiago, casi siempre obtengo mas que esto.
Saludos.

**Comment by fjlopez7** [comment]
En varias issues de este tema dijeron que la búsqueda debe permitir más de una categoría a la vez, (en general la api de foursquare no muestra descripción), y parece que esta bien dejar como 50 el parámetro

**Comment by Faalfaro** [comment]
Me refiero al filtro de query cuando dije por descripción, que es lo que te piden en el enunciado , y si entrega descripción, revisa la sección 'Get Details of a Venue'. Ademas, según lo que leí en otra issue, no esta realmente bien que te limite los resultados. Por otra parte, respecto a lo de mas de una categoría a la vez en el filtro, me gustaría de todas maneras que algún ayudante lo confirme o si me puedes dar el link de la issue donde lo dijeron pls.
Saludos.

**Comment by viantirreau** [comment]
Mira el #821 😉

**Comment by Faalfaro** [comment]
Gracias @viantirreau

**Comment by csolguin** [comment]
Me sumo a la pregunta inicial de @fjlopez7 
Saludos!
