### ISSUE TITLE
Supuestos

### ISSUE THREAD

**Issue by ncasassas** [IIC2233/syllabus-2018-2#844]
Hola, tengo un problema a la hora de considerar los recorridos "ida" y "vuelta". Se que la API entrega la información de si el paradero es inbound o outbound, pero en la mayoría de los casos para una calle hay por lo menos 2 paraderos ( uno de ida y otro de vuelta) entonces a la hora de decidir cual usar, puede que el de ida este más cerca del usuario siendo que para llegar al evento tenia que usar el paradero que va en la otra dirección. Por lo que estoy obteniendo el paradero más cercano que necesito pero dependiendo de como la API me entregue los datos retorno un paradero que puede mandar al usuario al lado contrario de donde quiero ir.
Por esto, puedo suponer que el usuario "sabe" en que dirección cardinal queda el evento para así si retorno el paradero incorrecto "sepa" que tiene que tomar el que esta cruzando la calle?? Los tiempos y distancias de viaje son practicamente los mismos con estos datos.

**Comment by ptflores1** [comment]
Hola !
Si pueden asumir que el usuario sabe que dirección tomar.
Saludos !
