### ISSUE TITLE
Calcular distancia

### ISSUE THREAD

**Issue by fabarros** [IIC2233/syllabus-2018-2#845]
Hola, tengo dos preguntas sobre el cálculo de distancia.
1) Una vez que tenemos el paradero más cercano al usuario (su latitud y longitud) y las coordenadas del usuario (su latitud y longitud), ¿debemos googlear una fórmula para calcular distancia entre dos coordenadas lat, lon?
2) Sobre el final del flujo del programa, se señala que debemos indicarle al usuario la distancia a la que está del lugar de destino, mi duda es: ¿esa distancia es en línea recta al lugar de destino (tal como lo que pregunté arriba) o es la distancia que va a recorrer la micro?
Gracias!

**Comment by ptflores1** [comment]
Hola !
1.  Revisa #793 
2. La distancia recta

Saludos !

**Comment by castrillini** [comment]
No se responde la duda...
@ptflores1
