### ISSUE TITLE
Manejo de errores en get

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#846]
debemos manejar los casos en que al hacer get se produce algún error por x motivo?
en el caso que sea cierto cuales serían?

**Comment by ncasassas** [comment]
Hola, no soy ayudante, pero a mi los errores que me daban era por ejemplo cuando ocurría lo del enunciado al buscar /next_arrivals,  cuando una categoría no existe o cuando no hay coincidencias entre lo que escribe el usuario para buscar por palabras clave y lo que entrega la api, no se si a eso te referías,
Saludos!
