### ISSUE TITLE
Sentido de recorridos

### ISSUE THREAD

**Issue by bmorrisc** [IIC2233/syllabus-2018-2#847]
Hola!
Hasta ahora estoy asumiendo que el usuario sabe si tiene que tomar una micro que esté describiendo un recorrido inbound o outbound, es decir, recorrido de ida o vuelta de acuerdo a su propio punto de partida, y entrego los resultados para ambos recorridos dejando que el usuario elija. Es esto válido o hay alguna forma de saber si me tengo que quedar con micros que vayan en cierta dirección?

**Comment by ptflores1** [comment]
#844
