### ISSUE TITLE
Mostrar información establecimiento

### ISSUE THREAD

**Issue by fjlopez7** [IIC2233/syllabus-2018-2#848]
Se realiza muy difícil mostrar información de los distintos establecimientos en la api de foursquare.
En su mayoría no muestran información o no la presentan.
Ejemplos de esto es que el número de contacto esta vació, el número de visita es 0, no posen descripción, alguno no poseen las calles del lugar. Por lo que uno se queda con poca y casi nula información que mostrar.
Entonces que seria lo que debemos mostrar ?

Por ahora solo muestro nombre, la verificación y si es que tiene la calle, la muestro.

**Comment by ptflores1** [comment]
Hola !
Si no presentan alguna información, debes indicar que no tienen.
Saludos !

**Comment by Faalfaro** [comment]
La API también tiene una forma de obtener los detalles de cada venue en la sección 'Get Details of a Venue', pero cuando lo intento ocupar me dice que VENUE_ID no es un parámetro valido, ¿estaré haciendo algo mal o simplemente esta operación no esta habilitada en la API?

**Comment by Faalfaro** [comment]
Ya lo resolví, hay que poner el id de la venue en el url directamente y no como parámetro, con esto te entregan información detallada de la venue, como descripciones, comentarios, horarios, etc...
