### ISSUE TITLE
Orden de Ruta

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#849]
Al revisar las rutas de las micros me di cuenta que en algunos casos el paradero de destino es recorrido antes que el de origen, por lo que la micro que va a parar en el origen va a seguir en el sentido contrario del destino. ¿En estos casos esa micro no sirve? (además al calcular el tiempo de viaje se tendrían que considerar todos los paraderos que quedan hasta dar la 'vuelta')

**Comment by jeschuwirth** [comment]
Saludos,
Por como esta escrito en orden de los pasos en el enunciado:
![image](https://user-images.githubusercontent.com/37160256/49340974-b1ae1980-f625-11e8-8a28-acc5c527dfd3.png)

Entonces deberás utilizar esa micro y 'dar la vuelta' a todo el recorrido

Suerte :)

**Comment by topkaj** [comment]
@jeschuwirth Quizá es algo rebuscado, pero en este caso, ¿es posible asumir que se puede *'dar la vuelta'*?, lo menciono porque en la práctica, la micro podría pasar por uno o dos *terminales*, y habría que ir a tomar otra micro al primer paradero de la ruta.
