### ISSUE TITLE
Eventos repetidos

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#85]
El enunciado dice que no pueden haber eventos con el mismo nombre y fecha, sin embargo me entro la duda de si acaso se puede hacer que dos usuarios distintos puedan tener eventos de igual nombre y fechas si no se invitan entre si ni comparten invitados (no me complica hacer la primera restricción pero me parece extraño que el que uno haga un evento le impida a otro hacer un evento semejante a pesar que ni se conozcan ni tengan conocidos comunes)

**Comment by ptflores1** [comment]
Hola !
Debes hacer lo que se indica en el enunciado, se hizo así para simplificar el editar, eliminar y agregar invitados a los eventos.
Saludos !
