### ISSUE TITLE
Duda radio paradero inicio

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#850]
Hola!
Por temas de la ubicación que me entrega ipstack, no existe ningún paradero que este a 10k de radio (Revisado a mano en la app de transantiago)... ¿Podría aumentar el radio, o simplemente asumo que esto no pasará a la hora de revisar y lo dejo en 10?

Saludos!

**Comment by jeschuwirth** [comment]
Hola!
Eso queda a tu criterio, mientras lo escribas en readme todo bien :)
