### ISSUE TITLE
Cantidad de resultados a desplegar

### ISSUE THREAD

**Issue by mihenriquez** [IIC2233/syllabus-2018-2#851]
En el Feedback se refiere a que se debe entregar la información de más de una ruta posible. Sin embargo en el enunciado dice que se debe desplegar la del paradero más cercano al usuario, habla siempre en singular ¿Qué es lo correcto?

**Comment by FernandoPieressa** [comment]
Hola! 

Ninguno de los dos esta en lo incorrecto. Tienes que mostrar todos los paraderos a menos de 10km de radio (los posibles), sin embargo la informacion especifica como los tiempos y distancias es solo para el mas cercano.

Saludos!

**Comment by bmorrisc** [comment]
Es necesario mostrar  todas las rutas posibles que cumplen con el radio de 10 km? Pensé que solo se calculaban (ni en el enunciado ni en el feedback piden que se impriman las rutas, solo que se calculen). Considero que sería demasiado imprimirlas todas en la consola y no se entendería el flujo del programa

**Comment by hbkim94** [comment]
@FernandoPieressa  En mi caso, estoy usando interfaz gráfica. Estará bien con sólo mostrar los nombres de los paraderos que cumplan con la condición de estar dentro de los 10 km, pero sólo mostrar los buses (incluyendo tiempo, distancia, etcetc) que se usan para el paradero que está más cerca?

Gracias!

**Comment by FernandoPieressa** [comment]
@hbkim94 Esta bien

@bmorrisc De alguna forma tienes que mostrarnos que obtuviste las rutas que cumplen con un radio de 10km, si sientes que imprimirlas todas es muy desordenado, puedes imprimir un numero que diga cuantas cumplen, necesitamos un valor o algo que diga que obtuviste los paraderos en el radio de 10km

**Comment by bmorrisc** [comment]
ok, muchas gracias!
