### ISSUE TITLE
Error (?) Feedback

### ISSUE THREAD

**Issue by NickCastillo** [IIC2233/syllabus-2018-2#852]
En el feedback sale "Ubicar con precisión el paradero mas cercano al usuario dentro del radio indicado" pero en el enunciado, Flujo de la información parte 3 se dice que se debe "Buscar el paradero mas cercano a la ubicación del lugar (destino) que se desea ir". Asumo que es un error del feedback?

**Comment by FernandoPieressa** [comment]
Tal como dijiste, "Buscar el paradero mas cercano a la ubicación del lugar (destino) que se desea ir". El destino es el evento, no el usuario. El usuario se rige por "Ubicar con precisión el paradero mas cercano al usuario dentro del radio indicado" , que técnicamente es el punto 7 del flujo de la información en el enunciado

Saludos!

**Comment by bmorrisc** [comment]
En mi caso, asumí que lo más parecido a  la realidad era buscar un recorrido con sus respectivos paraderos que minimizara la distancia total caminada, es decir, que los paraderos estén lo más cercano posible tanto al punto de partida como al destino. Está bien si lo indico en el readme como un supuesto o debería cambiarlo?
