### ISSUE TITLE
Interfaz no responde cuando busca el recorrido

### ISSUE THREAD

**Issue by Faalfaro** [IIC2233/syllabus-2018-2#853]
Hola,
Después de que el usuario ingresa su destino, mi programa comienza a buscar la información necesaria, lo cual demora poco mas de 40 seg, el problema es que en ese intervalo la interfaz gráfica muestra el mensaje de "no responde", ¿esto es normal?

**Comment by lily416** [comment]
Dependiendo de cómo hayas hecho la interacción _frontend-backend_ puede darse la situación de que no responde la interfaz. También puede deberse a que se están calculando muchas cosas.

De paso, como se dice en #811 para está tarea no era necesario realizar una interfaz 😅 basta com la interacción por consola. 

Saludos y éxito con la tarea 💪👋

**Comment by Arcoirisky** [comment]
1) ¿interfaz gráfica? ¿Why?

2) debe de estar procesando y entre tanto la interfaz se niega a hacer otra cosa hasta no tener la información que necesita. Por eso mismo té deja el mensaje “no responde” si esperas el tiempo suficiente para que tenga sus resultados está volverá a la vida con tu respuesta. 

3) ¿interfaz? ¿Why? Ten cuidado con agregarle interfaz. Es solo trabajo extra y si tu tarea no funciona por la interfaz es un GG :(

**Comment by lucasvsj** [comment]
@Faalfaro  a mi me pasaba eso, al final lo solucione usando Qthreads

**Comment by Faalfaro** [comment]
@Arcoirisky  como dices la interfaz vuelve a la vida cuando se terminan los cálculos, supongo que explicaré en el readme que puede suceder. En cuanto a, por qué interfaz, creo que se ve mas limpio (tanto el código como en la interacción), es mas fácil de mantener (Qt-designer) y es mas fácil hacer que el programa sea mas robusto contra inputs erróneos, no creo que sea trabajo extra.
Gracias y saludos!
