### ISSUE TITLE
Duración del programa

### ISSUE THREAD

**Issue by RodrigoNazar** [IIC2233/syllabus-2018-2#854]
Actualmente mi programa se demora al rededor de 5 minutos en realizar todas las consultas que necesita para dar una respuesta. Incluso en algunos casos puede ser más tiempo. Por lo que me pregunto, ¿Es demasiado o debo buscar optimizar mi programa?

Vale la pena comentar que mi programa sigue los pasos detallados en el flujo del programa. 
Muchas gracias!

**Comment by sacorsi** [comment]
+1

**Comment by RodrigoNazar** [comment]
El principal causante de la demora es el paso 7, hay que realizar muchas consultas al tener que buscar las coordenadas de cada uno de los paraderos.

**Comment by Arcoirisky** [comment]
Hay muchas formas de solucionar eso y están entre las issues ;—; De todas formas, agregarlo al readme es una opción para que al revisarlo no se tache como incompleto. Sin embargo, no recomiendo que se demore tanto.

**Comment by RodrigoNazar** [comment]
Gracias @Arcoirisky

**Comment by csolguin** [comment]
Es posible reemplazar el paso 7, por buscar los paraderos cercanos y hacer match con los obtenidos del paso 5?
Es mucho más rapido que ir de paradero en paradero por cada micro , para calcular su distancia y ver que sea menor a 10 km
