### ISSUE TITLE
Error API Transantiago ( https://api.scltrans.it/v1/stops)

### ISSUE THREAD

**Issue by fjtobar** [IIC2233/syllabus-2018-2#855]
Hola, 

acabo de descubrir que hay un error en la API del Transantiago.

Tal como dice acá, supuestamente la API nos entrega en orden (de más cercano a más lejano) los paraderos dada una ubicación:

![captura de pantalla 2018-12-02 a la s 5 27 16 p m](https://user-images.githubusercontent.com/42159875/49344773-767a0d80-f65a-11e8-897d-b7f7f28628a0.png)

Ahora que tengo casi terminada la tarea, corroboré los paraderos que me entrega esta consulta y me percaté que la API no los entrega ordenados.

En esta imagen calculé las distancias de los paraderos que me entrega la API vs la distancias calculada con una función externa:

![whatsapp image 2018-12-02 at 17 53 41](https://user-images.githubusercontent.com/42159875/49344861-6878bc80-f65b-11e8-8ebf-4fc1c2f47fbf.jpeg)

También es cosa de corroborar en google maps que el primer paradero que entrega la API no es el más cercano.

Qué hago? Debería guiarme por lo que debería entregar la API pero no entrega? O debería intentar solucionar este problema por mis medios?

Gracias

**Comment by chris-carstens** [comment]
Me pasó lo mismo! :(

**Comment by hbkim94** [comment]
Estoy en las mismas!

**Comment by lily416** [comment]
Aparentemente solo el primer paradero que entregan es el más cercano a la ubicación actual 🤔 
Traten de reordenar los datos que les entrega la api, aprovechen Haversine si es que ya implementaron el calculo.

Saludos y ánimo con la tarea 💪🚌

**Comment by haarenas** [comment]
Aca hablan de eso :eyes:
https://github.com/IIC2233/syllabus/issues/840

**Comment by hbkim94** [comment]
@lily416 nones, lo comprobé con varios venues y el primer paradero que entregaba no siempre calzaba con el que está más cerca

**Comment by lily416** [comment]
Puchis 😞 Entonces cada vez que reciban los paraderos deberán ordenarlos

**Comment by topkaj** [comment]
No se cómo calculará la distancia la API de Transantiago, pero deben tener en cuenta que al usar haversine se asume que la Tierra es una esfera perfecta, por lo que podrían haber variaciones importantes en los cálculos. En mi caso cuando listé las distancias con haversine de menor a mayor, efectivamente habían algunas que estaban más lejos y aparecían en primer orden. Pero, *en general* considero que estaban *más o menos* ordenadas. Dado esto, @lily416, si se explicita en el Readme, ¿se puede asumir que si están ordenadas según la API?. Porque reordenar la lista de paraderos que es bastante grande, haría que el programa tarde aún más :crying_cat_face:

**Comment by lily416** [comment]
@topkaj Cambio de último minuto ⏳ pueden ordenar los paraderos de la forma que más lo estimen conveniente (ej. distancia euclidiana, haversine, etc. 👀), pero independiente de la forma que escojan deben escribir en el readme cual escogieron.

Saludos y éxito con la tarea 👋🚗
