### ISSUE TITLE
Subir o no Credenciales

### ISSUE THREAD

**Issue by BFFV** [IIC2233/syllabus-2018-2#856]
¿Debemos evitar subir las credenciales propias de las API?, en caso de no subirlas, ¿las dejamos en un módulo aparte, de manera que el corrector agregue esos parámetros el mismo (con las suyas)?

**Comment by FernandoPieressa** [comment]
Es su eleccion si quieren darnos sus credenciales, pues es información privada de ustedes, sin embargo si no  las entregan tienen que explicar claramente en el readme donde hay que colocarlas, ya sea en un módulo aparte o una línea específica.

Como buena práctica, en general todas esas variables de deben colocar en un .env que son leídas por su programa y se encuentra en el .gitignore de su repositorio para que no sean subidas
