### ISSUE TITLE
Posibilidad de reducir el radio de 10KM alrededor del usuario

### ISSUE THREAD

**Issue by hbkim94** [IIC2233/syllabus-2018-2#857]
Hola! No hay forma de que puedan cambiar la rúbrica de buscar todos los paraderos que estén dentro de los 10km de radio para el cliente? 

Lo digo porque tomando en cuenta los tiempos de cálculo dentro del programa y que además vamos a terminar eligiendo el paradero más cercano, no le encuentro sentido buscar en un diámetro tan grande, sobretodo porque no se esperará que el cliente de verdad quiera caminar 10 KM para llegar a un paradero. Además, cuando corrijan nuestras tareas se van a demorar muchísimo en probar distintas combinaciones :( 

De antemano gracias!

**Comment by Arcoirisky** [comment]
Está explícito en el enunciado y es ley :c 

Hay muchas soluciones entre las issues para ayudar con el problema del tiempo ¿por qué no pruebas alguna?

**Comment by hbkim94** [comment]
@Arcoirisky Gracias por la respuesta! Igual no es que se demore taaaanto, max 1-2 minutos, pero me desesperaba un poco que se demorara jaja

**Comment by Arcoirisky** [comment]
Oooh 1-2 minutos está bien skndskkd Con que nos dejes un mensaje en plan “procesando, no se vaya que en promedio demoro 2min” estarás bien uwu

**Comment by juanfcolopez** [comment]
ese mensaje es conveniente dejarlo en el readme y que aparezca en la consola también? o basta con dejarlo en el readme?

**Comment by Arcoirisky** [comment]
Por consola siempre es bienvenido <3
O muy marcado en el readme skndksnd
