### ISSUE TITLE
consulta a v2/map

### ISSUE THREAD

**Issue by jmndoza** [IIC2233/syllabus-2018-2#859]
esta consulta, según la documentación (http://scltrans.it/#/api?id=map) permite ocupar radius, sin embargo al querer ocupar los 10 km, me da mensaje Internal server error,
si le saco este parámetro me muestra los resultados sin problemas..

podría dejarlo sin definir los 10 km? y si entregar el mas cercano
de todas formas la api me entrega todos los necesarios...(y mas)

ejemplo : https://api.scltrans.it/v2/map?include_stop_routes=1&center_lon=-70.6667&center_lat=-33.45&radius=10000

**Comment by lily416** [comment]
Evita reducir el radio de búsqueda, ya que se especifica en el enunciado que deben ser 10 km.

En vez de utilizar `map`, te recomendaria usar `stops` ya que también permite buscar por medio de un centro de coordenadas y un radio, y cómo esa función se especializa en buscar paraderos es más eficiente que `map`. En la [guía de uso](http://scltrans.it/#/user_guide) sale un ejemplo de cómo utilizarlo.

Saludos y éxito con la tarea 👋🗺
