### ISSUE TITLE
Informacion_de_eventos

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#86]
En el enunciado se muestra que debemos dar la oportunidad a un usuario el acceder a la información completa de los eventos, sin embargo, esto asume que no mostramos toda la información desde un principio en el calendario, si esto es así, ¿Qué información debemos ocultar en el calendario y mostrar solo una vez se acceda a este evento?

**Comment by ptflores1** [comment]
Hola !
Como dice en el enunciado en el segundo párrafo de 3.4.2:

> Como resultado se debe mostrar una lista con los nombres de los eventos...

Debes mostrar solo los nombres de los eventos y luego al seleccionar un evento debes mostrar **toda** la información
Saludos !

**Comment by ararojas** [comment]
Se puede mostrar el nombre y la fecha de inicio (para que sea mas como un calendario)?

**Comment by nachocontreras** [comment]
@ararojas Sí, puedes mostrar también la fecha de inicio, recuerda escribirlo en el Readme.
