### ISSUE TITLE
F

### ISSUE THREAD

**Issue by csolguin** [IIC2233/syllabus-2018-2#860]
GIT NO ME FUNCIONA

**Comment by Arcoirisky** [comment]
DAMN

**Comment by lily416** [comment]
Que error te sale?!!

**Comment by Arcoirisky** [comment]
Clona tu repo de nuevo si crees que es un pull o push a medias

**Comment by IchottMano** [comment]
D:

**Comment by csolguin** [comment]
Pueden dar 40 seg más?

clone todo denuevo :( pero me dio las 00:36

**Comment by Arcoirisky** [comment]
GUARDA LO QUE TIENES DE LA TAREA A PARTE PARA NO PERDERLO D:!!

**Comment by csolguin** [comment]
! [rejected]        master -> master (fetch first)

**Comment by Arcoirisky** [comment]
Aaah pero lo subiste?

**Comment by csolguin** [comment]
sipi pero a las 00:00: algo, 
:/

**Comment by Arcoirisky** [comment]
120 segundos de colchón. Eres salvo :’D

**Comment by csolguin** [comment]
Dios te escuche @Arcoirisky

**Comment by DCCollao** [comment]
F

**Comment by gatochico** [comment]
F
