### ISSUE TITLE
Paso 3 Encriptación

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2233/syllabus-2018-2#87]
Hola! En el paso 3 de la encriptación no entiendo a que se refiere con "Para descifrar el mensaje esta cadena aleatoria es obtenida de los primeros 10 elementos del mensaje a descifrar". No entiendo si la cadena aleatoria son 10 dígitos al azar, o tiene que ver con los 10 elementos del mensaje original, o con 10 elementos de la cadena de numero binarios obtenida en el paso 2. Gracias!!

**Comment by ridiazcampos** [comment]
¡Hola! También me confundió esta parte :o Me parece que hace referencia al paso 7, donde indican que la estructura del mensaje encriptado consistirá en una cadena aleatoria unida al mensaje codificado. De esta forma al querer descifrar un mensaje ya encriptado, se tendrán que tomar los primeros 10 digitos para obtener la cadena aleatoria de ese caso.
Básicamente al codificar el mensaje, la cadena aleatoria será al azar, mientras que al descifrarlo, esta se tendrá que obtener a partir de los diez primeros dígitos :D

**Comment by nachocontreras** [comment]
Hola!

Se respondió en la issue #23. Es tal como dice @ridiaz2

Saludos! :smile:
