### ISSUE TITLE
Validacion de fechas (años bisiestos)

### ISSUE THREAD

**Issue by ararojas** [IIC2233/syllabus-2018-2#89]
Hola!
Para poder ingresar una fecha en datetime sin que tire un error, esta tiene que ser una fecha valida.
Se deben considerar los 29s de febrero de los años bisiesto? o podemos asumir que febrero siempre tiene 28 dias?
Gracias!

**Comment by IchottMano** [comment]
@ararojas Hola!

No te preocupes por los años bisiestos, la libraría datetime maneja todo eso.

Saludos!

**Comment by ararojas** [comment]
@IchottMano Hola!
Si se que la libreria maneja eso, pero si yo le pido a un usuario que ingrese la fecha que quiere, tengo que validar que esa fecha exista antes de pasarla a datetime porque sino cuando la intente pasar datetime me va a tirar un error.

**Comment by IchottMano** [comment]
@ararojas Simplemente no te preocupes por los años bisiestos
