### ISSUE TITLE
Duda actualizar archivo ya subido a github

### ISSUE THREAD

**Issue by carajila** [IIC2233/syllabus-2018-2#9]
Me resultó subir el archivo de la actividad, pero cuando lo subo de nuevo con el código mejorado no me lo cambia a la ultima versión. 
En mis archivos locales está guardada la última versión, pero no me cambia la del repositorio remoto al agregarla de nuevo, solo cuando la subo con otro nombre.
¿Cómo puedo actualizar un código en github sin cambiarle el nombre?

**Comment by jecastro1** [comment]
Hola,

No estoy muy seguro si entendí tu pregunta, pero responderé con lo que se debería hacer para modificar un archivo en git.

1. Modificar el archivo ✓.
2. Llevarlo al _staging area_, con `git add nombre_archivo`. Notar que si el archivo está dentro de una carpeta y tu consola está en la "raíz" del repo, entonces tendrás que "decir" cómo encontrar el archivo. Por ejemplo, si la consola está en la raíz del repo y el archivo `bienvenida.py` está dentro de `Actividades/AC00` entonces el comando sería `git add Actividades/AC00/bienvenida.py`.
3. Hacer un _commit_ ¿Recuerdas como se hacía?
4. Hacer _push_.

Luego de esos pasos, el archivo debería cambiar en GitHub. Comenta acá si te resultó (y qué parte no estabas haciendo bien), o comenta si no te resultó con algun screenshot que nos permita ayudarte.

Saludos

**Comment by carajila** [comment]
Ahí me funcionó, gracias!
