### ISSUE TITLE
Usar datetime

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#91]
Hola, usa consulta, tengo terminado todo respecto a eventos y me funciona bien pero no he usado datetime, ¿es necesario usarla? o si me las arregle para que funcionara no hay problema (si es obligatorio usarla para algo entonces ¿que me podría estar faltando por no usarla?)

**Comment by jtcaraball** [comment]
Datetime te permite comparar las fechas y horas de los eventos pero no es una obligación usarlo, si te funciona bien esta perfecto :)

Saludos!
