### ISSUE TITLE
Guardar eventos

### ISSUE THREAD

**Issue by PPDZ** [IIC2233/syllabus-2018-2#92]
Sobre la base de datos que hay que crear, por como hice mi programa me sería muy fácil guardar todos los eventos existentes en un solo "espacio", ¿puedo hacer eso? ¿o es necesario colocar n lineas de: nombre de usuario; correos recibidos;eventos que puede ver el usuario? (de no ser así también tendría n lineas pero solo una con los eventos)

**Comment by FernandoPieressa** [comment]
Hola!

Tienes que considerar que nosotros probaremos su tarea solamente con archivos con una estructura similar a la que les fue entregada. Si quieren hacer otras bases de datos editadas con distinta información/otra estructura, su programa debe encargarse de poder manejar las bases de datos iniciales que nosotros entregamos, modificaras internamente en código, y luego poder leerlas con su programa con normalidad.

**No** pueden decirnos que su programa solo correrá si es que tenemos sus nuevas bases de datos, cualquier base de dato nueva tiene que ser generada por su programa.

Saludos!
