### ISSUE TITLE
Comas dentro de descripciones, nombres, títulos y/o cuerpo

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2233/syllabus-2018-2#93]
Hola! 
Noté que en el enunciado dice que las descripciones, nombres, títulos y cuerpo pueden contener comas, por lo tanto quería saber si puedo usar el modulo csv y sus métodos para enfrentar este problema.
Gracias

**Comment by IchottMano** [comment]
@kelseyfranken Hola,

Lamentablemente, la librería está prohibida, por lo que no puedes usarla.
Por favor, en el fututo hacer todas las preguntas sobre módulos hacerlas en la issue correspondiente.
#12 

Saludos
