### ISSUE TITLE
Enunciado bases de datos emails

### ISSUE THREAD

**Issue by BenjaminRubio** [IIC2233/syllabus-2018-2#95]
Hola!. No me queda claro en el enunciado si los mails nuevos que sean creados usando el programa ,deben ser guardados encriptados, no encriptados o de ambas formas en las bases de datos?

**Comment by lily416** [comment]
Hola :)

La idea es que los mails nuevos se guarden con el mismo formato del archivo `db_emails.csv`, es decir, sólo el cuerpo del mail debe estar encriptado.

Saludos 👋

**Comment by BenjaminRubio** [comment]
Entonces nunca guardamos los mensajes sin encriptar. cierto?

**Comment by sicalderon1210** [comment]
Entonces en la base "db_emails" el mensaje si está encriptado?
Porque en el enunciado dice en db_emails.csv "el cuerpo no encriptado"

**Comment by lily416** [comment]
@BenjaminRubio  Exacto!

@sicalderon1210  Como se dice en [esta issue](https://github.com/IIC2233/syllabus/issues/25)  en `db_emails.csv` se encuentran los mensajes encriptados y en `old_db_emails.csv` se encuentran los mismos mensajes pero sin encriptar.

Saludos y ánimo con la tarea 👋
