### ISSUE TITLE
input usuario de fecha y hora

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/syllabus-2018-2#97]
Hola, 

los usuarios al momento de introducir fecha  y hora que tan maliciosos son para que se caiga el programa?

Hay que revisar que el input que metan no tengo mas de 24 horas o 12 meses etc... ?

Respecto a esto, estoy pensando que lo mas facil como programador es hacer que el usuario ingrese el input de a 1 (es decir primero año, luego fecha etc...) y ir revisando cada uno por separado. 
Pero para un usuario eso sería mucho mas tedioso, entonces como debería ser eso?

**Comment by IchottMano** [comment]
@Kitaps Hola!

Efectivamente, tienes que revisar que los inputs sean válidos, y que la persona que usará tu programa puede poner lo que sea

Saludos!

**Comment by fjtobar** [comment]
Hola, puedo asumir que me pondrán fechas REALES? es decir, no pondrán como fecha un 31 de febrero por ejemplo

Saludos

**Comment by IchottMano** [comment]
@ftobar22 Hola!

Lamentablemente, no puedes asumir eso, tienes que controlar que el usuario no ponga fechas falsas. Sin embargo, no debes preocuparte de los años bisiestos

Saludos!
