### ISSUE TITLE
try/except en datetime

### ISSUE THREAD

**Issue by MMeisters** [IIC2233/syllabus-2018-2#98]
Quería saber si existe la posibilidad de reconsiderar  el uso de la función "try" solo en datetime. El control de flujo de los inputs de las fechas sin "try" se hace extremadamente  tedioso y además, datetime pierde casi toda su funcionalidad. 
También, me gustaría mencionar que el uso de "try" solo en datetime no rompe con ninguno de los objetivos de la tarea, ni nos impide cumplir alguno de ellos. 
Saludos @rihanuch .

**Comment by Coolgatty** [comment]
No

**Comment by rhanuch** [comment]
¡Hola @MMeisters !

Acabo de tocar este tema en la issue #104 

¡Saludos! 🍀
