### ISSUE TITLE
Eventos duplicados

### ISSUE THREAD

**Issue by gatochico** [IIC2233/syllabus-2018-2#99]
En el enunciado de la tarea se explicita que no deben haber 2 eventos con el mismo nombre y fechas, lo que asumo es para evitar que hayan eventos duplicados. Sin embargo, esto es una regla por usuario o global? 

Por ejemplo, si usuario 1 tiene el evento con nombre y fecha "a", el usuario 2 podrá hacer un evento en ese mismo datetime con el mismo nombre ? O en verdad es una regla para que un usuario no ingrese el mismo evento 2 veces en su calendario?

Gracias! 🐈

**Comment by fernandodediegoavila** [comment]
La issue #85 responde la misma duda.
Éxito en la tarea!
